<section class="section-header has-tabs">
    <div class="container">
        <div class="row">
            <div class="col-sm-8">
                <h1><?=$this->translate('Email');?></h1>
            </div>
            <div class="col-sm-4">
                <a href="<?=$this->url(array('controller' => 'mail-send', 'action' => 'index'));?>" class="btn btn-primary cta"><span class="glyphicon glyphicon-pencil"></span> <?=$this->translate('New Email');?></a>
            </div>
        </div>
        <?=$this->emailTabs('emailing');?>
    </div>
</section>
<section class="section-content">
    <div class="container">
        <div class="row">
            <div class="sidebar">

                <?=$this->emailNavigation('queued');?>

            </div>
            <div class="content">
                <a
                    href="<?=$this->url(['action' => 'send-all']); ?>"
                    class="btn btn-default pull-right<?=!count($this->emails) ? ' disabled' : '';?>"
                >
                    <span class="glyphicon glyphicon-send"></span>
                    <?=$this->translate('Send all emails');?>
                </a>
                <h2><?=$this->translate('Queued Emails');?></h2>

                <?php if (!count($this->emails)): ?>
                    <p class="alert alert-info">
                        <span class="glyphicon glyphicon-info-sign"></span>
                        <?=$this->translate('There are no emails in the queue to be sent.');?>
                    </p>
                <?php else: ?>

                    <table class="table">
                        <thead>
                            <tr>
                                <th class="col-xs-3 sorting-desc" data-toggle="sort" tabindex="0"><?=$this->translate('Time Queued');?></th>
                                <th data-toggle="sort" tabindex="0"><?=$this->translate('Subject');?></th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($this->emails as $email): ?>
                                <tr>
                                    <td data-sort-value="<?=$this->escape($email->time_queued);?>">
                                        <?=$this->formatDate($email->time_queued);?>
                                    </td>
                                    <td><?=$this->escape($email->subject);?></td>
                                </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>

                <?php endif; ?>

            </div>
        </div>
    </div>
</section>
