<?php foreach ($this->consultations as $consultation): ?>
    <?php
        $bubbles = array();
        $disabled = array(
            'input' => (Zend_Date::now()->isEarlier($consultation->inp_fr) || $consultation->inp_fr == '0000-00-00 00:00:00'),
            'voting' => (Zend_Date::now()->isEarlier($consultation->vot_fr) || $consultation->vot_fr == '0000-00-00 00:00:00'),
            'follow-up' => (!Zend_Date::now()->isLater(new Zend_Date($consultation->vot_to, Zend_Date::ISO_8601)) || $consultation->vot_to == '0000-00-00 00:00:00' || $consultation->follup_show == 'n'),
        );

        // Voting disable result
        if ($consultation->vot_to != '0000-00-00 00:00:00'
            && Zend_Date::now()->isLater(new Zend_Date($consultation->vot_to, Zend_Date::ISO_8601))
            && $consultation->vot_res_show == 'n'
        ) {
            $disabled['voting'] = true;
        }

        if (Zend_Date::now()->isLater(new Zend_Date($consultation->inp_fr, Zend_Date::ISO_8601))
            && Zend_Date::now()->isEarlier(new Zend_Date($consultation->inp_to, Zend_Date::ISO_8601))
        ) {
            if ($consultation->inp_show == 'y') {
                $bubbles['input'] = '<div class="bubble bubble-large">'
                    . '<h3>' . $this->translate('Participate now!') . '</h3>'
                    . '<span>' . $this->translate('from') . ' '
                    . $this->formatDate($consultation->inp_fr, Zend_Date::DATE_MEDIUM) . '<br />'
                    . $this->translate('until') . ' '
                    . $this->formatDate($consultation->inp_to, Zend_Date::DATE_MEDIUM) . '</span>'
                    . '</div>';
            }
        }
        if (Zend_Date::now()->isLater(new Zend_Date($consultation->vot_fr, Zend_Date::ISO_8601))
            && Zend_Date::now()->isEarlier(new Zend_Date($consultation->vot_to, Zend_Date::ISO_8601))
        ) {
            if ($consultation->vot_show == 'y') {
                $bubbles['voting'] = '<div class="bubble bubble-large">'
                    . '<h3>' . $this->translate('Vote now!') . '</h3>'
                    . '<span>' . $this->translate('from') . ' '
                    . $this->formatDate($consultation->vot_fr, Zend_Date::DATE_MEDIUM) . '<br />'
                    . $this->translate('until') . ' '
                    . $this->formatDate($consultation->vot_to, Zend_Date::DATE_MEDIUM) . '</span>'
                    . '</div>';
            }
        }
    ?>

    <!-- Consultation box -->
    <div class="consultation">

        <!-- Heading -->
        <a href="<?=$this->url(['controller' => 'article', 'action' => 'show', 'kid' => $consultation->kid]);?>" class="consultation-heading">
            <h2 class="consultation-heading-title">
                <?=$this->escape($consultation->titl);?>
            </h2>
            <h3 class="consultation-heading-subtitle">
                <?=$this->escape($consultation->titl_sub);?>
            </h3>
        </a>

        <?php //=$this->ribbonImage($consultation);?>

        <!-- Phases navigation -->
        <ul class="consultation-phases consultation-phases-preview">

            <!-- Title image with explanation -->
            <li>
                <a href="<?=$this->url(['controller' => 'article', 'action' => 'show', 'kid' => $consultation->kid]);?>" class="consultation-phases-preview-image">
                    <img
                        src="<?=$this->baseUrl('media/' . Service_Media::MEDIA_DIR_CONSULTATIONS . '/' . $consultation->kid . '/' . $consultation->img_file);?>"
                        alt="<?=$this->escape($consultation->img_expl);?>"
                    />
                    <div class="consultation-phases-preview-image-description">
                        <p><?=nl2br($this->escape(strip_tags(htmlspecialchars_decode($consultation->expl_short))));?></p>
                    </div>
                </a>
            </li>

            <!-- Info -->
            <li>
                <a href="<?=$this->url(['controller' => 'article', 'action' => 'show', 'kid' => $consultation->kid]);?>" class="consultation-phases-item">
                    <h3 class="consultation-phases-item-title"><?=$consultation->phase_info ? $this->escape($consultation->phase_info) : $this->translate('Info');?></h3>
                </a>
            </li>

            <!-- Questions -->
            <li>
                <a href="<?=$this->url(['controller' => 'question', 'action' => 'index', 'kid' => $consultation->kid]);?>" class="consultation-phases-item">
                    <h3 class="consultation-phases-item-title"><?=$consultation->phase_support ? $this->escape($consultation->phase_support) : $this->translate('Questions');?></h3>
                </a>
            </li>

            <!-- Contributions -->
            <?php if (!$disabled['input']): ?>
                <li>
                    <a href="<?=$this->url(['controller' => 'input', 'action' => 'index', 'kid' => $consultation->kid]);?>" class="consultation-phases-item">
                        <h3 class="consultation-phases-item-title"><?=$consultation->phase_input ? $this->escape($consultation->phase_input) : $this->translate('Contributions');?></h3>
                        <?php if (isset($bubbles['input'])): ?>
                            <?=$bubbles['input'];?>
                        <?php else: ?>
                            <?php if ($consultation->inp_show == 'y'): ?>
                                <div class="consultation-phases-item-info">
                                    <?=$this->translate('from');?>
                                    <?=$this->formatDate($consultation->inp_fr, Zend_Date::DATE_MEDIUM);?><br />
                                    <?=$this->translate('until');?>
                                    <?=$this->formatDate($consultation->inp_to, Zend_Date::DATE_MEDIUM);?>
                                </div>
                            <?php endif; ?>
                        <?php endif; ?>
                    </a>
                </li>
            <?php else: ?>
                <li>
                    <div class="consultation-phases-item disabled">
                        <h3 class="consultation-phases-item-title"><?=$consultation->phase_input ? $this->escape($consultation->phase_input) : $this->translate('Contributions');?></h3>
                        <?php if (isset($bubbles['input'])): ?>
                            <?=$bubbles['input'];?>
                        <?php else: ?>
                            <?php if ($consultation->inp_show == 'y'): ?>
                                <div class="consultation-phases-item-info">
                                    <?=$this->translate('from');?>
                                    <?=$this->formatDate($consultation->inp_fr, Zend_Date::DATE_MEDIUM);?><br />
                                    <?=$this->translate('until');?>
                                    <?=$this->formatDate($consultation->inp_to, Zend_Date::DATE_MEDIUM);?>
                                </div>
                            <?php endif; ?>
                        <?php endif; ?>
                    </div>
                </li>
            <?php endif; ?>

            <!-- Voting -->
            <?php if (!$disabled['voting']): ?>
                <li>
                    <a href="<?=$this->url(['controller' => 'voting', 'action' => 'index', 'kid' => $consultation->kid]);?>" class="consultation-phases-item">
                        <h3 class="consultation-phases-item-title"><?=$consultation->phase_voting ? $this->escape($consultation->phase_voting) : $this->translate('Voting');?></h3>
                        <?php if (isset($bubbles['voting'])): ?>
                            <?=$bubbles['voting'];?>
                        <?php else: ?>
                            <?php if ($consultation->vot_show == 'y'): ?>
                                <div class="consultation-phases-item-info">
                                    <?=$this->translate('from');?>
                                    <?=$this->formatDate($consultation->vot_fr, Zend_Date::DATE_MEDIUM);?><br />
                                    <?=$this->translate('until');?>
                                    <?=$this->formatDate($consultation->vot_to, Zend_Date::DATE_MEDIUM);?>
                                </div>
                            <?php endif; ?>
                        <?php endif; ?>
                    </a>
                </li>
            <?php else: ?>
                <li>
                    <div class="consultation-phases-item disabled">
                        <h3 class="consultation-phases-item-title"><?=$consultation->phase_voting ? $this->escape($consultation->phase_voting) : $this->translate('Voting');?></h3>
                        <?php if (isset($bubbles['voting'])): ?>
                            <?=$bubbles['voting'];?>
                        <?php else: ?>
                            <?php if ($consultation->vot_show == 'y'): ?>
                                <div class="consultation-phases-item-info">
                                    <?=$this->translate('from');?>
                                    <?=$this->formatDate($consultation->vot_fr, Zend_Date::DATE_MEDIUM);?><br />
                                    <?=$this->translate('until');?>
                                    <?=$this->formatDate($consultation->vot_to, Zend_Date::DATE_MEDIUM);?>
                                </div>
                            <?php endif; ?>
                        <?php endif; ?>
                    </div>
                </li>
            <?php endif; ?>

            <!-- Follow Up -->
            <?php if (!$disabled['follow-up']): ?>
                <li>
                    <a href="<?=$this->url(['controller' => 'followup', 'action' => 'index', 'kid' => $consultation->kid]);?>" class="consultation-phases-item">
                        <h3 class="consultation-phases-item-title"><?=$consultation->phase_followup ? $this->escape($consultation->phase_followup) : $this->translate('Reactions & Impact');?></h3>
                    </a>
                </li>
            <?php else: ?>
                <li>
                    <div class="consultation-phases-item disabled">
                        <h3 class="consultation-phases-item-title"><?=$consultation->phase_followup ? $this->escape($consultation->phase_followup) : $this->translate('Reactions & Impact');?></h3>
                    </div>
                </li>
            <?php endif; ?>

        </ul><!-- .consultation-phases -->
    </div><!-- .consultation -->

<?php endforeach; ?>
