<?php if (!empty($this->layout()->messages)): ?>
    <?php foreach ($this->layout()->messages as $level => $messages): ?>
        <?php if (!empty($messages)): ?>
            <?php foreach ($messages as $message): ?>
                <?=$this->partial(
                    '_partials/flashMessage.phtml',
                    ['message' => $message, 'level' => $level]
                );?>
            <?php endforeach; ?>
        <?php endif; ?>
    <?php endforeach; ?>
<?php endif; ?>
