<div class="alert alert-<?=$this->level;?> fade in">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <?php if ($this->level == 'success'): ?>
        <span class="glyphicon glyphicon-ok-sign"></span>
    <?php elseif ($this->level == 'error'): ?>
        <span class="glyphicon glyphicon-warning-sign"></span>
    <?php else: ?>
        <span class="glyphicon glyphicon-info-sign"></span>
    <?php endif; ?>
    <?=$this->translate($this->message);?>
</div>
