<div
    class="followup-timeline-box js-openoverlay js-timeline-box"
    data-href="<?=$this->url(['action' => 'json', 'ffid' => (int) $this->snippet['ffid'], 'fid' => null, 'tid' => null, 'page' => null]);?>"
    data-fid="<?=$this->snippet['fid'];?>"
>
    <div class="well well-bordered followup-well followup-well-link<?=$this->snippet['typ'] !== 'g' ? ' has-typ-overlay' : '';?>">

        <?php if ($this->snippet['typ'] !== 'g'): ?>
            <div class="followup-typ edge-left followup-typ-<?=$this->snippet['typ'];?>"></div>
            <div class="followup-typ gfx-who-overlay followup-typ-<?=$this->snippet['typ'];?>"></div>
        <?php endif; ?>

        <img src="<?=$this->snippet['gfx_who'];?>" width="80" class="followup-timeline-box-image" alt="" />

        <?=$this->escape($this->snippet['expl']);?>

        <!-- Voting -->
        <div class="offset-bottom-small">
            <span class="badge js-amount js-like"><?=$this->snippet['lkyea'];?></span>
            <a href="<?=$this->url(['action' => 'like', 'fid' => (int) $this->snippet['fid'], 'page' => null]);?>" class="link-alt link-unstyled js-voting js-like">
                <span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span>
            </a>
            <span class="badge js-amount js-dislike"><?=$this->snippet['lknay'];?></span>
            <a href="<?=$this->url(['action' => 'unlike', 'fid' => (int) $this->snippet['fid'], 'page' => null]);?>" class="link-alt link-unstyled js-voting js-dislike">
                <span class="glyphicon glyphicon-thumbs-down" aria-hidden="true"></span>
            </a>
        </div>

        <!-- Follow path -->
        <?php if ($this->followPathLink): ?>
            <a
                href="<?=$this->url(['action' => 'show-by-snippet', 'controller' => 'followup', 'kid' => $this->kid, 'fid' => $this->snippet['fid']], null, true);?>"
                class="btn btn-default js-follow-path"
            >
                <?=$this->translate('Follow this path');?>
            </a>
        <?php endif; ?>

    </div><!-- .well -->

    <?php if ($this->snippet['relFowupCount'] != 0 && $this->relFollowupCount): ?>
        <a
            href="<?=$this->url(['action' => 'json', 'fid' => $this->snippet['fid'], 'ffid' => null, 'tid' => null, 'page' => null]);?>"
            class="link-unstyled followup-link followup-timeline-count followup-sprite followup-sprite-timeline-count js-ajaxclick"
        >
            <?=$this->snippet['relFowupCount'];?>
        </a>
    <?php endif; ?>

</div><!-- .followup-timeline-box -->
