<footer>

	<!-- Footer navigation -->
	<nav role="navigation" class="footer-navigation navbar navbar-static hidden-print">
		<div class="navbar-inner">
			<div class="container">

				<ul class="nav">
					<?php echo $this->footerLinks(); ?>
					<li class="licence">
						<a rel="license" href="<?=Zend_Registry::get('systemconfig')->license->creative_commons->link?>" class="logo" rel="license" target="_blank" title="Creative Commons Namensnennung-Nicht-kommerziell 3.0 Unported Lizenz">
							<img alt="Creative Commons Lizenzvertrag" style="border-width:0" src="http://i.creativecommons.org/l/by-nc/3.0/88x31.png" alt="CC-BY-NC 3.0" />
						</a>
					</li>
				</ul>

			</div><!-- .container -->
		</div><!-- .navbar-inner -->
	</nav><!-- .footer-navigation -->

	<!-- About -->
	<section role="contentinfo" class="footer-about">
		<div class="container">
			<div class="row-fluid">
				<div class="span9">
					<div class="row-fluid">

						<?php $footerLogos = Zend_Registry::get('projectConfig')->footerLogo->toArray(); ?>
						<?php for ($i = 1, $size = count($footerLogos); $i <= $size; ++$i): ?>
							<div class="span4">
								<h3><?php echo $footerLogos[$i]['name']?></h3>
								<p>
									<a href="<?php echo $footerLogos[$i]['link']?>" class="logo" rel="external" target="_blank" title="<?php echo $footerLogos[$i]['title']?>">
										<img
											src="<?php echo $this->baseUrl(); ?>/projects/<?php echo Zend_Registry::get('systemconfig')->project?>/images/<?php echo $footerLogos[$i]['image']['name']?>"
											alt="<?php echo $footerLogos[$i]['image']['alt']?>"
											/>
									</a>
								</p>
							</div>
							<?php if ($i % 3 == 0): ?>
								</div>
								<div class="row-fluid">
							<?php endif; ?>
						<?php endfor; ?>

					</div><!-- .row-fluid -->
				</div>
				<div class="span3 contact">
					<p>
						<?php echo Zend_Registry::get('projectConfig')->contact->name?>
					</p>
					<p>
						Mühlendamm 3<br />
						10178 Berlin<br />
						<a href="mailto:<?php echo Zend_Registry::get('projectConfig')->contact->email?>">
							<?php echo Zend_Registry::get('projectConfig')->contact->email?>
						</a>
						<br />
						<a href="<?php echo Zend_Registry::get('projectConfig')->contact->www?>" rel="external" target="_blank">
							<?php echo Zend_Registry::get('projectConfig')->contact->www?>
						</a>
					</p>
				</div>
			</div><!-- .row-fluid -->
		</div><!-- .container -->
	</section><!-- .footer-about -->

</footer>
