<footer>

	<!-- Footer navigation -->
	<nav role="navigation" class="footer-navigation navbar navbar-static hidden-print">
		<div class="navbar-inner">
			<div class="container">

				<ul class="nav">
					<?php echo $this->footerLinks(); ?>
					<li class="licence">
						<a rel="license" href="<?=Zend_Registry::get('systemconfig')->license->creative_commons->link?>" class="logo" rel="license" target="_blank" title="Creative-Commons-Lizenz 4.0: Namensnennung, nicht-kommerziell">
							<img alt="Creative-Commons-Lizenz 4.0: Namensnennung, nicht-kommerziell" style="border-width:0" src="http://i.creativecommons.org/l/by-nc/4.0/88x31.png" alt="CC-BY-NC 4.0" />
						</a>
					</li>
				</ul>

			</div><!-- .container -->
		</div><!-- .navbar-inner -->
	</nav><!-- .footer-navigation -->

	<!-- About -->
	<section role="contentinfo" class="footer-about">
		<div class="container">
			<div class="row-fluid">

				<div class="span3">
					<h3>Projektträger</h3>
					<a href="http://www.dbjr.de" class="logo" rel="external" target="_blank" title="Deutscher Bundesjugendring">
						<img src="<?php echo $this->baseUrl(); ?>/images/logo/dbjr.png" alt="Deutscher Bundesjugendring" />
					</a>
				</div>
				<div class="span3">
					<h3>Gefördert vom</h3>
					<a href="http://www.bmfsfj.de" class="logo" rel="external" target="_blank" title="Bundesministerium für Familie, Senioren, Frauen und Jugend">
						<img src="<?php echo $this->baseUrl(); ?>/images/logo/bmfsfj.png" alt="Bundesministerium für Familie, Senioren, Frauen und Jugend" />
					</a>
				</div>
				<div class="span3">
					<h3>Das Tool für ePartizipation</h3>
					<a href="" class="logo" rel="external" target="_blank" title="ePartool">
						<img src="<?php echo $this->baseUrl(); ?>/images/logo/epartool.png" alt="ePartool" />
					</a>
					<?php if (Zend_Registry::get('systemconfig')->project == 'sd'): ?>
						<br /><br />Im Rahmen der
						<a href="http://strukturierter-dialog.de/einfuehrung/eu-jugendstrategie/" class="logo" rel="external" target="_blank" title="EU-Jugendstrategie">
							<img src="<?php echo $this->baseUrl(); ?>/images/logo/js.png" alt="EU-Jugendstrategie" />
						</a>
					<?php endif; ?>
				</div>
				<div class="span3 contact">
					<p><strong>Projektbüro Ichmache&gt;Politik</strong><br />
						Jugendbeteiligung an der Entwicklung<br />
						einer Eigenständigen Jugendpolitik</p>
					<p>Mühlendamm 3<br />
						10178 Berlin<br />
						<a href="mailto:ichmache-politik@dbjr.de">ichmache-politik@dbjr.de</a><br />
						<a href="http://www.ichmache-politik.de" rel="external" target="_blank">www.ichmache-politik.de</a></p>
				</div>

			</div><!-- .row -->
		</div><!-- .container -->
	</section><!-- .footer-about -->

</footer>
