<footer>

	<!-- Footer navigation -->
	<nav role="navigation" class="footer-navigation navbar navbar-static">
		<div class="navbar-inner">
			<div class="container">

				<ul class="nav">
					<li<?php if (stristr($this->url(), 'imprint')) echo ' class="active"'; ?>>
						<a href="<?php echo $this->url(array(), 'imprint', true); ?>">Impressum</a>
					</li>
					<li<?php if (stristr($this->url(), 'about')) echo ' class="active"'; ?>>
						<a href="<?php echo $this->url(array(), 'about', true); ?>">Über uns</a>
					</li>
					<li<?php if (stristr($this->url(), 'faq')) echo ' class="active"'; ?>>
						<a href="<?php echo $this->url(array(), 'faq', true); ?>">Häufige Fragen</a>
					</li>
					<li<?php if (stristr($this->url(), 'privacy')) echo ' class="active"'; ?>>
						<a href="<?php echo $this->url(array(), 'privacy', true); ?>">Datenschutz</a>
					</li>
					<li<?php if (stristr($this->url(), 'contact')) echo ' class="active"'; ?>>
						<a href="<?php echo $this->url(array(), 'contact', true); ?>">Kontakt</a>
					</li>
					<li class="licence"><img src="<?php echo $this->baseUrl(); ?>/images/licence.png" alt="Lizenz" /></li>
				</ul>

			</div><!-- .container -->
		</div><!-- .navbar-inner -->
	</nav><!-- .footer-navigation -->

	<!-- About -->
	<section role="contentinfo" class="footer-about">
		<div class="container">
			<div class="row">

				<div class="span3">
					<h3>Projektträger</h3>
					<a href="http://www.dbjr.de" class="logo" rel="external" target="_blank" title="Deutscher Bundesjugendring">
						<img src="<?php echo $this->baseUrl(); ?>/images/logo/dbjr.png" alt="Deutscher Bundesjugendring" />
					</a>
				</div>
				<div class="span3">
					<h3>Gefördert vom</h3>
					<a href="http://www.bmfsfj.de" class="logo" rel="external" target="_blank" title="Bundesministerium für Familie, Senioren, Frauen und Jugend">
						<img src="<?php echo $this->baseUrl(); ?>/images/logo/bmfsfj.png" alt="Bundesministerium für Familie, Senioren, Frauen und Jugend" />
					</a>
				</div>
				<div class="span3">
					<h3>Das Tool für ePartizipation</h3>
					<a href="" class="logo" rel="external" target="_blank" title="ePartool">
						<img src="<?php echo $this->baseUrl(); ?>/images/logo/epartool.png" alt="ePartool" />
					</a>
					<?php if(Zend_Registry::get('systemconfig')->project == 'sd'): ?>
					<br /><br />Im Rahmen der
					<a href="http://strukturierter-dialog.de/einfuehrung/eu-jugendstrategie/" class="logo" rel="external" target="_blank" title="EU-Jugendstrategie">
						<img src="<?php echo $this->baseUrl(); ?>/images/logo/js.png" alt="EU-Jugendstrategie" />
					</a>
					<?php endif; ?>
				</div>
				<div class="span3 contact">
					<p><strong>Projektbüro Ichmache&gt;Politik</strong><br />
						Jugendbeteiligung an der Entwicklung<br />
						einer Eigenständigen Jugendpolitik</p>
					<p>Mühlendamm 3<br />
						10178 Berlin<br />
						<a href="mailto:ichmache-politik@dbjr.de">ichmache-politik@dbjr.de</a><br />
						<a href="http://www.ichmache-politik.de" rel="external" target="_blank">www.ichmache-politik.de</a></p>
				</div>

			</div><!-- .row -->
		</div><!-- .container -->
	</section><!-- .footer-about -->

</footer>
