<header>

    <!-- Header region -->
    <div role="banner" class="header-region">
        <div class="row">
            <div class="span4">

                <!-- Brand -->
                <a href="<?php echo $this->url(array('controller' => 'index'), 'default', true); ?>"
                    rel="home"
                    class="brand"
                    title="<?=$this->translate('Home')?>"
                >
                    <img
                        src="<?php echo $this->baseUrl(); ?>/project/images/logo.png"
                        itemprop="image"
                        width="177"
                        height="50"
                        alt="Strukturierter Dialog"
                    />
                </a>

            </div>
            <div class="span5">

                <!-- Main navigation -->
                <nav role="navigation" class="main-navigation hidden-print">
                    <h2 class="hide">Hauptmenü</h2>

                    <!-- Menu -->
                    <ul class="nav nav-pills">
                            <li><a href="<?php echo $this->url(array(), 'about'); ?>#what"><?=$this->translate('What')?></a></li>
                            <li><a href="<?php echo $this->url(array(), 'about'); ?>#us"><?=$this->translate('We')?></a></li>
                        <?php if (Zend_Registry::get('Zend_Translate')->getAdapter()->getLocale() === 'de'): ?>
                            <li><a href="<?php echo $this->url(array(), 'about'); ?>#you"><?=$this->translate('With You')?></a></li>
                            <li><a href="<?php echo $this->url(array(), 'about'); ?>#vision"><?=$this->translate('Do')?></a></li>
                        <?php elseif (Zend_Registry::get('Zend_Translate')->getAdapter()->getLocale() === 'en'): ?>
                            <li><a href="<?php echo $this->url(array(), 'about'); ?>#vision"><?=$this->translate('Do')?></a></li>
                            <li><a href="<?php echo $this->url(array(), 'about'); ?>#you"><?=$this->translate('With You')?></a></li>
                        <?php endif?>
                    </ul>
                </nav><!-- .main-navigation -->

            </div>
            <div class="span3">

                <!-- Search -->
                <form method="get" action="<?php echo $this->baseUrl(); ?>/index/search" class="form-search hidden-print">
                    <div class="input-append">
                        <input type="text" name="q" placeholder="<?=$this->translate('Search…')?>" class="input-medium search-query" value="" />
                        <button type="submit" class="btn btn-primary btn-icon"><i class="icon-search icon-white"></i></button>
                    </div>
                </form>

                <!-- Login -->
                <?php echo $this->login(); ?>

                <!-- User box (user is logged in) -->
                <?php echo $this->userBox(); ?>
                <!-- .user-box -->

            </div><!-- .span3 -->
        </div><!-- .row -->

        <!-- Hero unit -->
        <?php echo $this->partial('_partials/heroUnit.phtml', $this) ?>

    </div><!-- .header-region -->
</header>
<hr class="hide" />
