<!-- Print -->
<div class="main-page-tools">
    <a href="javascript:print();" class="link-alt has-icon main-print">
        <?=$this->translate('Print page');?>
        <span class="glyphicon glyphicon-print" aria-hidden="true"></span>
    </a>
</div>

<!-- Top link -->
<div class="top-link">
    <a href="#top" class="has-icon js-scroll">
        <span class="glyphicon glyphicon-menu-up" aria-hidden="true"></span>
        <?=$this->translate('up');?>
    </a>
</div>
