<!-- Print -->
<div class="main-page-tools">
    <?php if (!empty($this->help)): ?>
        <a
            href="<?=$this->url(['controller' => 'help', 'action' => 'index', 'name' => $this->help]);?>"
            class="link-alt has-icon js-toggle-help"
        >
            <?=$this->translate('Help');?>
            <span class="glyphicon glyphicon-question-sign" aria-hidden="true"></span>
        </a>
        <br class="visible-xs visible-sm" />
    <?php endif; ?>
    <a href="javascript:print();" class="link-alt has-icon">
        <?=$this->translate('Print page');?>
        <span class="glyphicon glyphicon-print" aria-hidden="true"></span>
    </a>
</div>

<!-- Top link -->
<div class="top-link">
    <a href="#top" class="has-icon js-scroll">
        <span class="glyphicon glyphicon-menu-up" aria-hidden="true"></span>
        <?=$this->translate('up');?>
    </a>
</div>
