<section class="section-header has-tabs">
    <div class="container">
        <div class="row">
            <div class="col-sm-8">
                <h1><?=$this->translate('Email');?></h1>
            </div>
            <div class="col-sm-4">
                <a href="<?=$this->url(array('controller' => 'mail-send', 'action' => 'index'));?>" class="btn btn-primary cta"><span class="glyphicon glyphicon-pencil"></span> <?=$this->translate('New Email');?></a>
            </div>
        </div>
        <?=$this->emailTabs('settings');?>
    </div>
</section>
<section class="section-content">
    <div class="container">
        <div class="row">
            <div class="sidebar">

                <?=$this->emailSettingsNavigation('components');?>

            </div>
            <div class="content">

                <a href="<?=$this->url(array('action' => 'index'));?>" class="back"><?=$this->translate('Back to Email Components');?></a>

                <h2><?php echo !$this->templateId ? 'New' : 'Edit'?> <?=$this->translate('Email Component');?></h2>
                <?=$this->form;?>

                <div class="well">
                    <h4><?=$this->translate('Placeholders');?></h4>
                    <table class="table table-striped">
                        <?php foreach ($this->placeholders as $placeholder): ?>
                            <tr>
                                <th class="col-sm-3"><?php echo Dbjr_Mail::TOKEN_OPEN . $placeholder->name . Dbjr_Mail::TOKEN_CLOSE?></th>
                                <td><?php echo $placeholder->description?></td>
                            </tr>
                        <?php endforeach?>
                    </table>
                </div>

            </div>
        </div>
    </div>
</section>

