<tr
    data-admin-confirmation="<?=$this->escape($this->adminConfirmationFlags[$this->input['is_confirmed']]);?>"
    data-user-confirmation="<?=$this->escape($this->userConfirmationFlags[$this->input['is_confirmed_by_user']]);?>"
    data-voting="<?=$this->escape($this->votableFlags[$this->input['is_votable']]);?>"
    data-tags='<?=json_encode(array_map(function($el) {return $el['tg_nr'];}, $this->input['tags']));?>'
>
    <td class="table-cell-id table-cell-top">
        <div class="checkbox">
            <label>
                <input type="checkbox" value="<?=$this->escape($this->input['tid']);?>" name="inp_list[]" />
                <span class="muted"><?=$this->escape($this->input['tid']);?>
            </label>
        </div>
    </td>
    <td class="table-cell-top">
        <p class="overflow-horizontal"><?=$this->escape($this->input['thes']);?></p>
        <p class="overflow-horizontal"><?=$this->escape($this->input['expl']);?></p>

        <p>
            <small>
                <?php if (!empty($this->input['uid'])): ?>
                    <a href="<?=$this->url(['controller' => 'user', 'action' => 'edit', 'uid' => $this->input['uid']]);?>">
                        <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                        <?php if ($this->input['name']): ?>
                            <?=$this->escape($this->input['name']);?>,
                        <?php endif;?>
                    </a>
                <?php endif; ?>
                <?=$this->formatDate($this->input['when']);?>
                <span
                    class="glyphicon glyphicon-thumbs-up"
                    data-toggle="tooltip"
                    data-placement="bottom"
                    title="<?=$this->translate('Supported by %d users.', $this->input['spprts']);?>"
                ></span>
                <?=$this->input['spprts'];?>
            </small>
        </p>
        <p>
            <?php foreach ($this->input['tags'] as $tag): ?>
                <span class="label label-primary"><?=$this->escape($tag['tg_de']);?></span>
            <?php endforeach; ?>
        </p>
        <?php if (!empty($this->input['notiz'])): ?>
            <p class="overflow-horizontal">
                <?=$this->escape($this->input['notiz']);?>
            </p>
        <?php endif; ?>
        <?php if ($this->input['input_discussion_contrib']): ?>
            <p>
                <span class="label label-warning">
                    <span class="glyphicon glyphicon-comment" aria-hidden="true"></span>
                    <?=$this->translate('Created from discussion post.');?>
                </span>
            </p>
        <?php endif; ?>
    </td>
    <td class="col-xs-3 table-cell-top">
        <p>
            <?=$this->translate('Admin Confirmation');?><br />
            <span
                class="js-contribution-change-status"
                data-kid="<?=$this->kid;?>"
                data-tid="<?=$this->input['tid'];?>"
                data-property="blocking"
            >
                <?php if ($this->input['is_confirmed'] === null): ?>
                    <span class="label label-default">
                        <span class="glyphicon glyphicon-question-sign" aria-hidden="true"></span>
                        <?=$this->translate('Unknown');?>
                    </span>
                <?php elseif (!$this->input['is_confirmed']): ?>
                    <span class="label label-danger">
                        <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                        <?=$this->translate('Blocked'); // Yes no is switched as in db the actual column is 'blocked', thus negative?>
                    </span>
                <?php elseif ($this->input['is_confirmed']): ?>
                    <span class="label label-success">
                        <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
                        <?=$this->translate('Confirmed'); // Yes no is switched as in db the actual column is 'blocked', thus negative?>
                    </span>
                <?php endif; ?>
            </span>
        </p>
        <p>
            <?=$this->translate('User Confirmation');?><br />
            <?php if ($this->input['is_confirmed_by_user'] === null): ?>
                <span class="label label-default label-disabled">
                    <span class="glyphicon glyphicon-question-sign" aria-hidden="true"></span>
                    <?=$this->translate('Unknown');?>
                </span>
            <?php elseif (!$this->input['is_confirmed_by_user']): ?>
                <span class="label label-danger label-disabled">
                    <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                    <?=$this->translate('Rejected');?>
                </span>
            <?php elseif ($this->input['is_confirmed_by_user']): ?>
                <span class="label label-success label-disabled">
                    <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
                    <?=$this->translate('Confirmed');?>
                </span>
            <?php endif; ?>
        </p>
        <p>
            <?=$this->translate('Voting');?><br />
            <span
                class="js-contribution-change-status"
                data-kid="<?=$this->kid;?>"
                data-tid="<?=$this->input['tid'];?>"
                data-property="voting"
            >
                <?php if ($this->input['is_votable'] === null): ?>
                    <span class="label label-default">
                        <span class="glyphicon glyphicon-question-sign" aria-hidden="true"></span>
                        <?=$this->translate('Unknown');?>
                    </span>
                <?php elseif ($this->input['is_votable']): ?>
                    <span class="label label-success">
                        <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
                        <?=$this->translate('Yes');?>
                    </span>
                <?php elseif (!$this->input['is_votable']): ?>
                    <span class="label label-danger">
                        <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                        <?=$this->translate('No');?>
                    </span>
                <?php endif; ?>
            </span>
        </p>
    </td>
    <td class="col-xs-1 table-cell-top text-center">
        <?php if (in_array($this->input['tid'], $this->inputsWithDiscussion)): ?>
            <a
                href="<?=$this->url([
                    'controller' => 'input-discussion',
                    'action' => 'index',
                    'kid' => $this->kid,
                    'inputId' => $this->input['tid']
                ]);?>"
                class="item-action"
                title="<?=$this->translate('Show discussion');?>"
                >
                <span class="glyphicon glyphicon-comment" aria-hidden="true"></span>
            </a>
        <?php endif; ?>
        <a
            href="<?=$this->url(['action' => 'edit', 'tid' => $this->input['tid']]);?>"
            class="item-action"
            title="<?=$this->translate('Edit contribution');?>"
            >
            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
        </a>
        <button
            class="item-action item-action-danger"
            name="delete"
            value="<?=$this->escape($this->input['tid']);?>"
            data-toggle="confirm"
            data-confirm-message="<?=$this->translate('Delete contribution?');?>"
            data-confirm-yes="<?=$this->translate('Yes');?>"
            data-confirm-no="<?=$this->translate('No');?>"
            title="<?=$this->translate('Delete contribution');?>"
        >
            <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
        </button>
    </td>
</tr>
