<h1><?php echo $this->consultation['titl']; ?></h1>
<?php
echo $this->consultationNavigation('Beiträge');
?>
<p>
<?php foreach ($this->consultation['questions'] as $question): ?>

<a href="<?php echo $this->baseUrl(); ?>/admin/input/index/kid/<?php echo $this->consultation['kid'];
?>/qid/<?php echo $question['qi']; ?>"<?php if ($this->qid == $question['qi']):
?> class="active"<?php endif;?>>
  <?php echo $question['nr'] . ' ' . $question['q'];?>
</a>&emsp;
<?php endforeach;?>
</p>
<h2>Beitrag bearbeiten</h2>
<p>Dieser Beitrag trägt die Datenbank-interne Nr. <?php echo $this->tid; ?>.</p>
<?php echo $this->form; ?>