<section class="section-header">
    <div class="container">

        <h1 class="section-header-title"><?=$this->escape($this->consultation['titl']);?></h1>
        <h2 class="section-header-subtitle"><?=$this->escape($this->consultation['titl_sub']);?></h2>

        <?=$this->consultationTabs($this->consultation['kid'], 'consultation');?>

    </div>
</section>
<section class="section-content">
    <div class="container">
        <div class="row">
            <div class="sidebar offset-bottom-large-sm-max">

                <?=$this->consultationNavigation($this->consultation, 'contributions');?>

            </div>
            <div class="content">

                <a href="<?=$this->returnUrl;?>" class="back"><?=$this->translate('Back to Contributions');?></a>

                <h2><?=$this->translate('Edit Contribution');?></h2>
                <?php if ($this->authorId): ?>
                <a
                    href="<?=$this->url(
                        ['action' => 'list-by-user', 'uid' => $this->authorId, 'tid' => null, 'qi' => null]
                    );?>"
                    class="item-action offset-bottom"
                    target="_blank"
                >
                    <span aria-hidden="true" class="glyphicon glyphicon-list offset-right"></span>
                    <?=$this->translate('List of contributions from this author');?>
                </a>
                <?php endif; ?>
                <?=$this->form;?>

            </div>
        </div>
    </div>
</section>
