<section class="section-header">
    <div class="container">

        <?=$this->helpText('help-text-admin-contribution');?>

        <h1 class="section-header-title"><?=$this->escape($this->consultation['titl']);?></h1>
        <h2 class="section-header-subtitle"><?=$this->escape($this->consultation['titl_sub']);?></h2>

        <?=$this->consultationTabs($this->consultation['kid'], 'consultation');?>

    </div>
</section>
<section class="section-content">
    <div class="container">
        <div class="row">
            <div class="sidebar offset-bottom-large-sm-max">

                <?=$this->consultationNavigation($this->consultation, 'contributions');?>

            </div>
            <div class="content">

                <a class="btn btn-default pull-right" href="<?=$this->url(['action' => 'create']);?>">
                    <span class="glyphicon glyphicon-plus-sign offset-right" aria-hidden="true"></span>
                    <?=$this->translate('New Contribution');?>
                </a>

                <h2><?=$this->translate('Contributions');?></h2>

                <?php if (!count($this->questions) && !count($this->users)): ?>
                    <p class="alert alert-info">
                        <span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>
                        <?=$this->translate('There are no contributions yet.');?>
                    </p>
                <?php endif; ?>

                <?php if (count($this->questions)): ?>
                    <h3><?=$this->translate('By Question');?></h3>
                    <table class="table">
                        <thead>
                            <tr>
                                <th class="table-cell-id sorting-asc" data-toggle="sort" tabindex="0">#</th>
                                <th data-toggle="sort" tabindex="0"><?=$this->translate('Question');?></th>
                                <th data-toggle="sort" tabindex="0"><?=$this->translate('Unread');?></th>
                                <th data-toggle="sort" tabindex="0"><?=$this->translate('Total');?></th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($this->questions as $question): ?>
                                <tr>
                                    <td class="table-cell-id"><?=$this->escape($question->nr);?></td>
                                    <td><?=html_entity_decode($this->escape(strip_tags($question->q)));?></td>
                                    <td data-sort-value="<?=$this->escape($question->inputCountUnread);?>">
                                        <?php if (!empty($question->inputCountUnread)): ?>
                                            <a href="<?=$this->url(['action' => 'list-by-question', 'qi' => $question->qi, 'isUnread' => '1']);?>"><?=$this->translate('Show');?></a>
                                            <span class="badge"><?=$this->escape($question->inputCountUnread);?></span>
                                        <?php else: ?>
                                            <span class="badge">0</span>
                                        <?php endif; ?>
                                    </td>
                                    <td data-sort-value="<?=$this->escape($question->inputCountTotal);?>">
                                        <?php if (!empty($question->inputCountTotal)): ?>
                                            <a href="<?=$this->url(['action' => 'list-by-question', 'qi' => $question->qi, 'isUnread' => null]);?>"><?=$this->translate('Show');?></a>
                                            <span class="badge"><?=$this->escape($question->inputCountTotal);?></span>
                                        <?php else: ?>
                                            <span class="badge">0</span>
                                        <?php endif; ?>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                <?php endif; ?>

                <?php if (count($this->users)): ?>
                    <h3><?=$this->translate('By User');?></h3>
                    <table class="table">
                        <thead>
                            <tr>
                                <th class="table-cell-id sorting-asc" data-toggle="sort">#</th>
                                <th data-toggle="sort" tabindex="0"><?=$this->translate('Name');?></th>
                                <th data-toggle="sort" tabindex="0"><?=$this->translate('Email');?></th>
                                <th data-toggle="sort" tabindex="0"><?=$this->translate('Contributions');?></th>
                                <th data-toggle="sort" tabindex="0"><?=$this->translate('Comment');?></th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($this->users as $user): ?>
                                <tr>
                                    <td class="table-cell-id"><?=$this->escape($user->uid);?></td>
                                    <td>
                                        <a href="<?=$this->url(['controller' => 'user', 'action' => 'edit', 'uid' => $user->uid]);?>">
                                            <?=$this->escape($user->name);?>
                                        </a>
                                    </td>
                                    <td>
                                        <a href="mailto:<?=$this->escape($user->email);?>">
                                            <?=$this->escape($user->email);?>
                                        </a>
                                    </td>
                                    <td data-sort-value="<?=$this->escape($user->inputCount);?>">
                                        <a href="<?=$this->url(['action' => 'list-by-user', 'uid' => $user->uid, 'qi' => null]);?>"><?=$this->translate('Show');?></a>
                                        <span class="badge"><?=$this->escape($user->inputCount);?></span>
                                    </td>
                                    <td><?=$user->cmnt ? '<span class="glyphicon glyphicon-comment" aria-hidden="true"></span>' : '';?></td>
                                </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                <?php endif; ?>

            </div>
        </div>
    </div>
</section>

