<section class="section-header has-tabs">
    <div class="container">

        <h1><?=$this->consultation['titl'];?></h1>
        <h2><?=$this->consultation['titl_sub'];?></h2>

        <?=$this->consultationTabs($this->consultation['kid'], 'consultation');?>

    </div>
</section>
<section class="section-content">
    <div class="container">
        <div class="row">
            <div class="sidebar">

                <?=$this->consultationNavigation($this->consultation['kid'], 'contributions');?>

            </div>
            <div class="content">

                <h2><?=$this->translate('Questions')?></h2>
                <table class="table">
                    <thead>
                        <tr>
                            <th class="table-cell-id">#</th>
                            <th><?=$this->translate('Question');?></th>
                            <th><?=$this->translate('Unread');?></th>
                            <th><?=$this->translate('Total');?></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->questions as $question): ?>
                            <tr>
                                <td class="table-cell-id"><?=$question->qi;?></td>
                                <td><?=$question->q;?></td>
                                <td>
                                    <?php if (!empty($question->inputCountUnread)): ?>
                                        <?=$question->inputCountUnread;?>
                                        <a href="<?=$this->url(['action' => 'list-by-question', 'qi' => $question->qi, 'isUnread' => '1']);?>">
                                            <?=$this->translate('Show');?>
                                        </a>
                                    <?php else: ?>
                                        0
                                    <?php endif?>
                                </td>
                                <td>
                                    <?php if (!empty($question->inputCountTotal)): ?>
                                        <?=$question->inputCountTotal;?>
                                        <a href="<?=$this->url(['action' => 'list-by-question', 'qi' => $question->qi, 'isUnread' => null]);?>">
                                            <?=$this->translate('Show');?>
                                        </a>
                                    <?php else: ?>
                                        0
                                    <?php endif?>
                                </td>
                            </tr>
                        <?php endforeach;?>
                    </tbody>
                </table>

                <h2><?=$this->translate('Users')?></h2>
                <table class="table">
                    <thead>
                        <tr>
                            <th class="table-cell-id">#</th>
                            <th><?=$this->translate('Name');?></th>
                            <th><?=$this->translate('Email');?></th>
                            <th><?=$this->translate('Contributions');?></th>
                            <th><?=$this->translate('Comment');?></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->users as $user): ?>
                            <tr>
                                <td class="table-cell-id"><?=$user->uid;?></td>
                                <td>
                                    <a href="<?=$this->url(['controller' => 'user', 'action' => 'edit', 'uid' => $user->uid]);?>">
                                        <?=$user->name;?>
                                    </a>
                                </td>
                                <td>
                                    <a href="mailto:<?=$user->email;?>">
                                        <?=$user->email;?>
                                    </a>
                                </td>
                                <td>
                                    <?=$user->inputCount;?>
                                    <a href="<?=$this->url(['action' => 'list-by-user', 'uid' => $user->uid, 'qi' => null]);?>">
                                        <?=$this->translate('Show');?>
                                    </a>
                                </td>
                                <td><?=$user->cmnt ? '<span class="glyphicon glyphicon-comment"></span>' : '';?></td>
                            </tr>
                        <?php endforeach;?>
                    </tbody>
                </table>

            </div>
        </div>
    </div>
</section>

