<?=$this->openStreetMapsConfig();?>
<form
    enctype="<?=$this->element->getEnctype();?>"
    method="<?=$this->element->getMethod();?>"
    class="offset-bottom"
    id="js-contribution-form"
>
    <?=$this->element->csrf_token_inputadmin;?>

    <?=$this->element->qi;?>
    <?=$this->element->thes;?>
    <?php if (isset($this->element->uid)) : ?>
        <?=$this->element->uid;?>
    <?php endif; ?>
    <?=$this->element->expl;?>


    <?php if (!$this->element->getVideoEnabled()) :
        $this->element->video_service->setAttrib('disabled', 'disabled');
        $this->element->video_id->setAttrib('disabled', 'disabled');
    endif; ?>

    <div class="form-group js-video-service">
        <div class="row">
            <div class="col-sm-12">
                <label><?=$this->translate('Video');?></label>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-4">
                <?=$this->element->video_service;?>
            </div>
            <div class="col-sm-8">
                <div class="input-group">
                    <span class="input-group-addon js-video-service-url"></span>
                    <?=$this->element->video_id;?>
                </div>
                <?php if (count($this->element->video_id->getErrors())): ?>
                    <ul class="text-danger-block">
                    <?php foreach ($this->element->video_id->getMessages() as $message): ?>
                        <li><?=$message;?></li>
                    <?php endforeach; ?>
                    </ul>
                <?php endif; ?>
            </div>
        </div>
    </div>

    <?php if ($this->element->getVideoEnabled() && $this->element->video_id->getValue()) : ?>
        <div class="form-group">
            <?=$this->embeddedVideo(
                $this->element->video_service->getValue(),
                $this->element->video_id->getValue()
            );?>
        </div>
    <?php endif; ?>

    <div class="form-froup">
        <label for="js-contribution-map-toggle-location">
            <input type="checkbox"
                id="js-contribution-map-toggle-location"
                data-toggle="collapse"
                data-target="#js-contribution-map"
                <?php if ($this->element->latitude->getValue() !== null) :?> checked="checked"<? endif; ?>
            >
                <?=$this->translate('Add location');?>
            </input>
        </label>
    </div>

    <div
        class="collapse<?php if ($this->element->latitude->getValue() !== null) :?> in<? endif; ?>"
        id="js-contribution-map"
    >

        <a
            href="#"
            class="btn btn-default btn-xs"
            id="js-contribution-map-button-my-location"
            style="position: absolute; z-index: 450;right: 50px; margin-top: 10px;"
        >
            <?=$this->translate('Use My location');?>
        </a>
        <div id="js-contribution-map-canvas" style="height: 300px;"></div>
    </div>
    <?=$this->element->latitude;?>
    <?=$this->element->longitude;?>

    <?=$this->element->tags;?>

    <div class="row offset-bottom">
        <?php foreach (['is_confirmed_by_user', 'is_confirmed', 'is_votable'] as $element): ?>
            <div class="col-sm-4">
                <div id="<?=$this->element->{$element}->getName();?>" class="checkbox radio">
                    <h3><?=$this->element->{$element}->getLabel();?></h3>
                    <?php foreach ($this->element->{$element}->options as $value => $option): ?>
                        <label>
                            <input
                                type="radio"
                                name="<?=$this->element->{$element}->getName();?>"
                                id="<?=$this->element->{$element}->getName();?>-<?=$value;?>"
                                value="<?=$value;?>"
                                <?=(string) $this->element->{$element}->getValue() === (string) $value ? 'checked' : '';?>
                            > <?=$option;?>
                        </label>
                        <br>
                    <?php endforeach; ?>
                </div>
            </div>
        <?php endforeach; ?>
    </div>

    <?=$this->element->notiz;?>

    <?=$this->element->submit;?>
    <?=$this->element->delete;?>
    <div class="form-action-static">
        <?=$this->translate('or');?>
        <a href="<?=$this->element->getCancelUrl();?>"><?=$this->translate('Cancel');?></a>
    </div>

</form>
