<?=$this->openStreetMapsConfig();?>
<form
    enctype="<?=$this->element->getEnctype();?>"
    method="<?=$this->element->getMethod();?>"
    class="offset-bottom"
    id="js-contribution-form"
>
    <?=$this->element->csrf_token_inputadmin;?>

    <?=$this->element->qi;?>
    <?=$this->element->thes;?>
    <?php if (isset($this->element->uid)) : ?>
        <?=$this->element->uid;?>
    <?php endif; ?>
    <?=$this->element->expl;?>

    <div class="row">
        <div class="col-sm-4">
            <div class="form-group">
                <label for="js-contribution-map-toggle-location">
                    <input
                        type="checkbox"
                        id="js-contribution-map-toggle-location"
                        data-toggle="collapse"
                        data-target="#js-contribution-map"
                        <?php if (!$this->element->getLocationEnabled()): ?>
                            disabled="disabled"
                            <?php if (get_class($this->element) !== Admin_Form_CreateInput::class): ?>
                                title="<?=$this->translate('Location is disabled. You can enable it in question settings.');?>"
                            <?php endif; ?>
                        <?php endif; ?>
                        <?=($this->element->latitude->getValue() !== null ? 'checked' : ''); ?>
                    >
                        <span class="offset-left"><?=$this->translate('Add location');?></span>
                    </input>
                </label>
            </div>
        </div>
        <div class="col-sm-8">
            <?php if (!$this->element->getLocationEnabled()
                && get_class($this->element) !== Admin_Form_CreateInput::class): ?>
                <span class="alert alert-info">
                    <?=$this->translate('Location is disabled. You can enable it in question settings.');?>
                </span>
            <?php endif; ?>
        </div>
    </div>

    <div
        class="collapse<?=($this->element->latitude->getValue() !== null ? ' in' : ''); ?> offset-bottom"
        id="js-contribution-map"
    >

        <a
            href="#"
            class="btn btn-default btn-xs"
            id="js-contribution-map-button-my-location"
            style="position: absolute; z-index: 450;right: 50px; margin-top: 10px;"
        >
            <?=$this->translate('Use My location');?>
        </a>
        <div
            id="js-contribution-map-canvas"
            <?php if ($this->element->getQuestion()['geo_fence_enabled']): ?>
                data-geo-fence="<?=$this->element->getQuestion()['geo_fence_polygon'];?>"
            <?php endif; ?>
            style="height: 300px;"
        ></div>
    </div>
    <?=$this->element->latitude;?>
    <?=$this->element->longitude;?>

    <?php if (!$this->element->getVideoEnabled()) :
        $this->element->video_service->setAttrib('disabled', 'disabled');
        $this->element->video_id->setAttrib('disabled', 'disabled');
    endif; ?>

    <div class="form-group js-video-service">
        <div class="row">
            <div class="col-sm-12">
                <label><?=$this->translate('Video');?></label>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-4">
                <?=$this->element->video_service;?>
            </div>
            <div class="col-sm-8">
                <div class="input-group">
                    <span class="input-group-addon js-video-service-url"></span>
                    <?=$this->element->video_id;?>
                </div>
                <?php if (count($this->element->video_id->getErrors())): ?>
                    <ul class="text-danger-block">
                    <?php foreach ($this->element->video_id->getMessages() as $message): ?>
                        <li><?=$message;?></li>
                    <?php endforeach; ?>
                    </ul>
                <?php endif; ?>
            </div>
        </div>
    </div>

    <?php if ($this->element->getVideoEnabled() && $this->element->video_id->getValue()) : ?>
        <div class="form-group">
            <?=$this->embeddedVideo(
                $this->element->video_service->getValue(),
                $this->element->video_id->getValue()
            );?>
        </div>
    <?php endif; ?>

    <?=$this->element->tags;?>

    <div class="row offset-bottom">
        <?php foreach (['is_confirmed_by_user', 'is_confirmed', 'is_votable'] as $element): ?>
            <div class="col-sm-4">
                <div id="<?=$this->element->{$element}->getName();?>" class="checkbox radio">
                    <h3><?=$this->element->{$element}->getLabel();?></h3>
                    <?php foreach ($this->element->{$element}->options as $value => $option): ?>
                        <label>
                            <input
                                type="radio"
                                name="<?=$this->element->{$element}->getName();?>"
                                id="<?=$this->element->{$element}->getName();?>-<?=$value;?>"
                                class="js-is-votable-radio"
                                value="<?=$value;?>"
                                <?=(string) $this->element->{$element}->getValue() === (string) $value ? 'checked' : '';?>
                            > <?=$option;?>
                            <?php if ($element === 'is_votable' && $value && $this->element->getAutoVotingInfo()): ?>
                                <span
                                    id="js-is-votable-auto-info"
                                    class="glyphicon glyphicon-info-sign"
                                    data-toggle="tooltip"
                                    data-placement="bottom"
                                    title="<?=$this->translate('This value was automatically changed to yes');?>"
                                ></span>
                            <?php endif; ?>
                        </label>
                        <br>
                    <?php endforeach; ?>
                </div>
            </div>
        <?php endforeach; ?>
    </div>

    <?=$this->element->is_votable_edited;?>

    <?=$this->element->notiz;?>

    <?=$this->element->submit;?>
    <?=$this->element->delete;?>
    <div class="form-action-static">
        <?=$this->translate('or');?>
        <a href="<?=$this->element->getCancelUrl();?>"><?=$this->translate('Cancel');?></a>
    </div>

</form>
