<?php
$date = new Zend_Date();
?>
<h1><?php echo $this->consultation['titl']; ?></h1>
<?php
echo $this->consultationNavigation('Beiträge');
?>
<p><a href="<?php echo $this->baseUrl(); ?>/admin/input/userlist/kid/<?php echo $this->kid; ?>">&laquo; Alle Nutzer_innen anzeigen, die an dieser Beteiligungsrunde teilgenommen haben</a></p>
<?php if (!empty($this->user)): ?>
<table>
	<tr>
		<td class="tbl_lab">User</td>
		<td class="tbl_det">
			<a href="<?php echo $this->baseUrl(); ?>/admin/user/edit/uid/<?php echo $this->user['uid'];?>">
				<h2>
				<?php if (!empty($this->user['name'])):?>
				<?php echo $this->user['name']; ?><br />
				<?php endif;?>
				<?php if (!empty($this->user['email'])):?>
				<?php echo $this->user['email']; ?>
				<?php endif;?>
				</h2>
			</a>
		<td>
	</tr>
	<tr>
		<td class="tbl_lab">Letzte Aktivität</td>
		<td class="tbl_det">
		<?php if (!empty($this->user['last_act'])): ?>
		<?php echo $date->set($this->user['last_act'])->get(Zend_Date::DATETIME_MEDIUM);?>
		<?php endif; ?>
		<td>
	</tr>
	<tr>
	  <td class="tbl_lab">Kontaktperson</td>
		<td class="tbl_det">
		<?php echo $this->escape($this->user_info['name_pers']); ?>
		</td>
	</tr>
	<tr>
	  <td class="tbl_lab">Gruppenbezeichnung</td>
		<td class="tbl_det">
		<?php echo $this->escape($this->user_info['name_group']); ?>
		</td>
	</tr>
	<tr>
	  <td class="tbl_lab">Quelle</td>
		<td class="tbl_det">
		<?php echo $this->escape($this->user_info['source']); ?>
		</td>
	</tr>
	<tr>
	  <td class="tbl_lab">Beschreibung</td>
		<td class="tbl_det">
		<?php echo $this->escape($this->user_info['src_misc']); ?>
		</td>
	</tr>
	<tr>
	  <td class="tbl_lab">Gruppengröße</td>
		<td class="tbl_det">
		<?php $siz_tm = array(
        "0" => "keine Information",
        "1" => "1 (Einzelperson)",
        "10" => "bis 10",
        "30" => "bis 30",
        "80" => "bis 80",
        "150" => "bis 150",
        "200" => "über 150"
      ); ?>
		<?php if (array_key_exists($this->user_info['group_size'], $siz_tm)) {
		   echo $siz_tm[$this->user_info['group_size']];
		} else {
      echo 'k.A.';
    } ?>
		</td>
	</tr>
	<tr>
	  <td class="tbl_lab">Region</td>
		<td class="tbl_det">
		<?php echo $this->escape($this->user_info['regio_pax']); ?>
		</td>
	</tr>
	<tr>
	  <td class="tbl_lab">Altersgruppe</td>
		<td class="tbl_det">
		<?php $age_tm = array(
        "1" => "bis 17 Jahre",
        "2" => "bis 26 Jahre",
        "3" => "ab 27 Jahre",
        "4" => "all age groups",
        "5" => "no information"
      );?>
		<?php if (array_key_exists($this->user_info['age_group'], $age_tm)) {
		  echo $age_tm[$this->user_info['age_group']];
		} else {
      echo 'k.A.';
    }?>
		</td>
	</tr>
	<tr>
	  <td class="tbl_lab">Newsletter abonnieren</td>
		<td class="tbl_det">
		<?php echo $this->escape($this->user_info['newsl_subscr']); ?>
		</td>
	</tr>
	<tr>
	  <td class="tbl_lab">Informieren über Konsultationsergebnisse</td>
		<td class="tbl_det">
		<?php echo $this->escape($this->user_info['cnslt_results']); ?>
		</td>
	</tr>
	<tr>
	  <td class="tbl_lab">Übermittelter Kommentar</td>
		<td class="tbl_det">
		<?php echo $this->escape($this->user_info['cmnt_ext']); ?>
		</td>
	</tr>
</table>
<?php else: ?>
<p class="info">Details zum Nutzer nicht verfügbar! Möglicherweise existiert kein Nutzerdatensatz mit der angegebenen UserID.</p>
<?php endif; ?>
<form name="inp_edit" id="inp_edit" action="<?php echo $this->baseUrl(); ?>/admin/input/editbulk" method="POST">
<input name="return_url" type="hidden" value="<?php echo $this->url(); ?>" />
<?php foreach ($this->questions as $question): ?>
<div style="color: #ffffff; padding: 6px; background-color: #6a9dbc;">
  <b><?php echo $question['nr']; ?> <?php echo $question['q']; ?></b><br />
  <?php echo $question['q_xpl']; ?>
</div>
<div style="color: #000000; padding: 6px; background-color: #d9e8ef;">
  <table>
  <?php foreach ($question['inputs'] as $input): ?>
  <?php
  if ($input['block']=="n") {
    $block_tm="text-decoration: none";
  } elseif ($input['block']=="y") {
    $block_tm="text-decoration: line-through";
  } else {
    $block_tm="color: #ff0000";
  }
  ?>
    <tr>
      <td><input type="checkbox" value="<?php echo $input['tid'];?>" name="inp_list[]" />&nbsp;&nbsp;</td>
      <td>
        <a href="<?php echo $this->baseUrl(); ?>/admin/input/edit/kid/<?php echo $this->kid; ?>/qid/<?php echo $question['qi'];?>/tid/<?php echo $input['tid']; ?>">
          <span style="<?php echo $block_tm; ?>; font-weight: normal;"><?php echo $input['thes'];?><br />
          <?php echo $input['expl'];?></span>
        </a>
      </td>
    </tr>
  <?php endforeach;?>
  </table>
</div>
<?php endforeach;?>
<br />Markierte Einträge: <select name="action">
  <option value="" class="quest" selected="selected">Aktion auswählen...</option>
  <option value="delete" class="quest">Löschen</option>
  <option value="block" class="quest">Sperren</option>
  <option value="publish" class="quest">Freigeben</option>
  </select> <button type="submit">Ausführen</button>
</form>
<br/>
<br/>
<a href="<?php echo $this->baseUrl(); ?>/admin/input/userlist/kid/<?php echo $this->kid; ?>">&laquo; Alle Nutzer_innen anzeigen, die an dieser Beteiligungsrunde teilgenommen haben</a>
