<section class="section-header">
    <div class="container">

        <h1 class="section-header-title"><?=$this->escape($this->consultation['titl']);?></h1>
        <h2 class="section-header-subtitle"><?=$this->escape($this->consultation['titl_sub']);?></h2>

        <?=$this->consultationTabs($this->consultation['kid'], 'consultation');?>

    </div>
</section>
<section class="section-content">
    <div class="container">
        <div class="row">
            <div class="sidebar offset-bottom-large-sm-max">

                <?=$this->consultationNavigation($this->consultation, 'contributions');?>

            </div>
            <div class="content">

                <a href="<?=$this->url(['action' => 'index', 'uid' => null]);?>" class="back">
                    <?=$this->translate('Back to Overview');?>
                </a>
                <h2>
                    <a href="<?=$this->url(['controller' => 'user', 'action' => 'edit', 'kid' => null]);?>">
                        <?=$this->escape($this->user['name']);?>
                        <small><?=$this->escape($this->user['email']);?></small>
                    </a>
                </h2>

                <table class="table table-condensed">
                    <tr>
                        <th class="col-xs-4"><?=$this->translate('Last activity');?></th>
                        <td>
                            <?php if (!empty($this->user['last_act'])): ?>
                                <?=$this->formatDate($this->user['last_act']);?>
                            <?php endif; ?>
                        <td>
                    </tr>
                    <tr>
                        <th><?=$this->translate('Contact person');?></th>
                        <td>
                            <?=$this->escape($this->user_info['name_pers']);?>
                        </td>
                    </tr>
                    <tr>
                        <th><?=$this->translate('Group name');?></th>
                        <td>
                            <?=$this->escape($this->user_info['name_group']);?>
                        </td>
                    </tr>
                    <tr>
                        <th><?=$this->translate('Source');?></th>
                        <td>
                            <?=$this->escape($this->user_info['source']);?>
                        </td>
                    </tr>
                    <tr>
                        <th><?=$this->translate('Description');?></th>
                        <td>
                            <?=$this->escape($this->user_info['src_misc']);?>
                        </td>
                    </tr>
                    <tr>
                        <th><?=$this->translate('Group size');?></th>
                        <td>
                            <?php if (array_key_exists($this->user_info['group_size'], $this->userGroupSizes)): ?>
                                <?=$this->userGroupSizes[$this->user_info['group_size']];?>
                            <?php else: ?>
                                <?=$this->translate('Not available');?>
                            <?php endif; ?>
                        </td>
                    </tr>
                    <tr>
                        <th><?=$this->translate('Region');?></th>
                        <td>
                            <?=$this->escape($this->user_info['regio_pax']);?>
                        </td>
                    </tr>
                    <tr>
                        <th><?=$this->translate('Age groups');?></th>
                        <td>
                            <?php if (array_key_exists($this->user_info['age_group'], $this->contributorAges)): ?>
                                <?=$this->contributorAges[$this->user_info['age_group']];?>
                            <?php else: ?>
                                <?=$this->translate('Not available');?>
                            <?php endif; ?>
                        </td>
                    </tr>
                    <tr>
                        <th><?=$this->translate('Newsletter');?></th>
                        <td>
                            <?=$this->escape($this->user_info['is_subscribed_newsletter']);?>
                        </td>
                    </tr>
                    <tr>
                        <th><?=$this->translate('Inform about consultation results');?></th>
                        <td>
                            <?=$this->escape($this->user_info['is_receiving_consultation_results']);?>
                        </td>
                    </tr>
                    <tr>
                        <th><?=$this->translate('Comment');?></th>
                        <td>
                            <?=$this->escape($this->user_info['cmnt_ext']);?>
                        </td>
                    </tr>
                </table>

                <?php if (count($this->inputs)): ?>
                    <form action="<?=$this->url(['action' => 'edit-list']);?>" method="<?=$this->form->getMethod();?>">
                        <?=$this->form->getElement($this->form->getCsrfTokenName());?>
                        <input name="return_url" type="hidden" value="<?=$this->url();?>" />

                        <!-- Actions -->
                        <div class="well well-sm">
                            <div class="row">
                                <div class="col-xs-3">
                                    <div class="checkbox-inline">
                                        <label for="markAllTop" class="sr-only">
                                            <?=$this->translate('Mark all contributions');?>
                                        </label>
                                        <input
                                            type="checkbox"
                                            id="markAllTop"
                                            class="js-toggle-all"
                                            title="<?=$this->translate('Mark all contributions');?>"
                                        />
                                    </div>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="btn-group">
                                        <button
                                            type="submit"
                                            name="bulkAction"
                                            value="publish"
                                            class="btn btn-default"
                                            data-toggle="confirm"
                                            data-confirm-message="<?=$this->translate('Are you sure?');?>"
                                            data-confirm-yes="<?=$this->translate('Yes');?>"
                                            data-confirm-no="<?=$this->translate('No');?>"
                                        >
                                            <span class="glyphicon glyphicon-ok-sign" aria-hidden="true"></span>
                                            <span class="hidden-xs"><?=$this->translate('Publish');?></span>
                                        </button>
                                        <button
                                            type="submit"
                                            name="bulkAction"
                                            value="block"
                                            class="btn btn-default"
                                            data-toggle="confirm"
                                            data-confirm-message="<?=$this->translate('Are you sure?');?>"
                                            data-confirm-yes="<?=$this->translate('Yes');?>"
                                            data-confirm-no="<?=$this->translate('No');?>"
                                        >
                                            <span class="glyphicon glyphicon-ban-circle" aria-hidden="true"></span>
                                            <span class="hidden-xs"><?=$this->translate('Block');?></span>
                                        </button>
                                        <button
                                            type="submit"
                                            name="bulkAction"
                                            value="delete"
                                            class="btn btn-danger"
                                            data-toggle="confirm"
                                            data-confirm-message="<?=$this->translate('Are you sure?');?>"
                                            data-confirm-yes="<?=$this->translate('Yes');?>"
                                            data-confirm-no="<?=$this->translate('No');?>"
                                        >
                                            <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                                            <span class="hidden-xs"><?=$this->translate('Delete');?></span>
                                        </button>
                                    </div>
                                </div>
                            </div><!-- .row -->
                        </div>

                        <!-- Listing -->
                        <?php foreach ($this->inputs as $inputs): ?>
                            <h3><?=isset($inputs['nr']) ? $this->escape($inputs['nr']) : '';?> <?=$this->escape($inputs['q']);?></h3>
                            <div class="table-responsive">
                                <table
                                    class="table table-bordered js-table-rows-toggle"
                                    id="contribution-table"
                                    data-token="<?=$this->csrfToken;?>"
                                >
                                    <?php foreach ($inputs['inputs'] as $input): ?>
                                        <?=$this->partial(
                                            'input/_inputBox.phtml',
                                            [
                                                'input' => $input,
                                                'kid' => $this->consultation['kid'],
                                                'inputsWithDiscussion' => $this->inputsWithDiscussion
                                            ]
                                        );?>
                                    <?php endforeach; ?>
                                </table>
                            </div>
                        <?php endforeach; ?>

                        <!-- Actions -->
                        <div class="well well-sm">
                            <div class="row">
                                <div class="col-xs-3">
                                    <div class="checkbox-inline">
                                        <label for="markAllBottom" class="sr-only">
                                            <?=$this->translate('Mark all contributions');?>
                                        </label>
                                        <input
                                            type="checkbox"
                                            id="markAllBottom"
                                            class="js-toggle-all" title="<?=$this->translate('Mark all contributions');?>"
                                        />
                                    </div>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="btn-group">
                                        <button
                                            type="submit"
                                            name="bulkAction"
                                            value="publish"
                                            class="btn btn-default"
                                            data-toggle="confirm"
                                            data-confirm-message="<?=$this->translate('Are you sure?');?>"
                                            data-confirm-yes="<?=$this->translate('Yes');?>"
                                            data-confirm-no="<?=$this->translate('No');?>"
                                        >
                                            <span class="glyphicon glyphicon-ok-sign" aria-hidden="true"></span>
                                            <span class="hidden-xs"><?=$this->translate('Publish');?></span>
                                        </button>
                                        <button
                                            type="submit"
                                            name="bulkAction"
                                            value="block"
                                            class="btn btn-default"
                                            data-toggle="confirm"
                                            data-confirm-message="<?=$this->translate('Are you sure?');?>"
                                            data-confirm-yes="<?=$this->translate('Yes');?>"
                                            data-confirm-no="<?=$this->translate('No');?>"
                                        >
                                            <span class="glyphicon glyphicon-ban-circle" aria-hidden="true"></span>
                                            <span class="hidden-xs"><?=$this->translate('Block');?></span>
                                        </button>
                                        <button
                                            type="submit"
                                            name="bulkAction"
                                            value="delete"
                                            class="btn btn-danger"
                                            data-toggle="confirm"
                                            data-confirm-message="<?=$this->translate('Are you sure?');?>"
                                            data-confirm-yes="<?=$this->translate('Yes');?>"
                                            data-confirm-no="<?=$this->translate('No');?>"
                                        >
                                            <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                                            <span class="hidden-xs"><?=$this->translate('Delete');?></span>
                                        </button>
                                    </div>
                                </div>
                            </div><!-- .row -->
                        </div>

                    </form>
                <?php else: ?>
                    <p class="alert alert-info">
                        <span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>
                        <?=$this->translate('This user has not contributed yet.');?>
                    </p>
                <?php endif; ?>

            </div>
        </div>
    </div>
</section>
