<section class="section-header has-tabs">
    <div class="container">

        <h1><?=$this->consultation['titl'];?></h1>
        <h2><?=$this->consultation['titl_sub'];?></h2>

        <?=$this->consultationTabs($this->consultation['kid'], 'consultation');?>

    </div>
</section>
<section class="section-content">
    <div class="container">
        <div class="row">
            <div class="col-md-3">

                <?=$this->consultationNavigation($this->consultation['kid'], 'contributions');?>

            </div>
            <div class="col-md-9">

                <a href="<?=$this->url(['action' => 'index', 'qi' => null]);?>" class="back">
                    <?=$this->translate('Back to Overview');?>
                </a>
                <h2>
                    <?=$this->translate('Contributions for');?>:
                    <?=$this->question['q'];?>
                </h2>

                <?php if (count($this->inputs)): ?>

                    <!-- Filter -->
                    <form class="form-filter offset-bottom" data-filter-target="#contribution-table tr">
                        <div class="row">
                            <div class="col-sm-4">
                                <div class="form-group">
                                    <label>
                                        <span class="glyphicon glyphicon-filter"></span> <?=$this->translate('Admin Confirmation');?>
                                    </label>
                                    <select
                                        class="form-control"
                                        data-toggle="filter"
                                        data-filter-attrib="admin-confirmation"
                                        data-filter-operator="intersect"
                                    >
                                        <option value=""><?=$this->translate('All');?></option>
                                        <option value="u"><?=$this->translate('Waiting for revision');?></option>
                                        <option value="n"><?=$this->translate('Confirmed');?></option>
                                        <option value="y"><?=$this->translate('Blocked');?></option>
                                    </select>
                                </div>
                            </div>
                            <div class="col-sm-4">
                                <div class="form-group">
                                    <label>
                                        <span class="glyphicon glyphicon-filter"></span> <?=$this->translate('User Confirmation');?>
                                    </label>
                                    <select
                                        class="form-control"
                                        data-toggle="filter"
                                        data-filter-attrib="user-confirmation"
                                        data-filter-operator="intersect"
                                    >
                                        <option value=""><?=$this->translate('All');?></option>
                                        <option value="u"><?=$this->translate('Waiting for revision');?></option>
                                        <option value="c"><?=$this->translate('Confirmed');?></option>
                                        <option value="r"><?=$this->translate('Blocked');?></option>
                                    </select>
                                </div>
                            </div>
                            <div class="col-sm-4">
                                <div class="form-group">
                                    <label>
                                        <span class="glyphicon glyphicon-filter"></span> <?=$this->translate('Voting');?>
                                    </label>
                                    <select
                                        class="form-control"
                                        data-toggle="filter"
                                        data-filter-attrib="voting"
                                        data-filter-operator="intersect"
                                    >
                                        <option value=""><?=$this->translate('All');?></option>
                                        <option value="u"><?=$this->translate('Unknown');?></option>
                                        <option value="y"><?=$this->translate('Allowed');?></option>
                                        <option value="n"><?=$this->translate('Blocked');?></option>
                                    </select>
                                </div>
                            </div>
                        </div><!-- .row -->
                        <div class="row">
                            <div class="col-sm-8">
                                    <div class="form-group">
                                        <label for="tags"><?=$this->translate('Tags');?></label>
                                        <select
                                            name="tags[]"
                                            class="form-control js-select2"
                                            multiple
                                            data-toggle="filter"
                                            data-filter-attrib="tags"
                                            data-filter-operator="subset"
                                        >
                                            <?php foreach ($this->tags as $tag): ?>
                                                <option
                                                    value="<?=$tag['tg_nr'];?>"
                                                    <?=!empty($tag['selected']) ? 'selected="selected"' : '';?>
                                                >
                                                    <?=$tag['tg_de'];?>
                                                </option>
                                            <?php endforeach;?>
                                        </select>
                                    </div>
                                </div>
                            <div class="col-sm-4">
                                <div class="form-actions">
                                    <button
                                        type="button"
                                        class="btn btn-default btn-block"
                                        data-toggle="filter-reset"
                                    >
                                        <?=$this->translate('Reset Filter');?>
                                    </button>
                                </div>
                            </div>
                        </div><!-- .row -->
                    </form>

                    <?php if ($this->tag['tg_nr'] > 0): ?>
                        <p class="alert alert-info">
                            <?=$this->translate('Only contributions with &ldquo;%s&rdquo; keywords are listed.', $this->tag['tg_de']);?>
                            <a href="<?php echo $this->url(array('tag' => null));?>">Show all contributions</a>
                        </p>
                    <?php endif;?>

                    <form action="<?=$this->url(['action' => 'edit-list']);?>" method="<?=$this->form->getMethod();?>">
                        <?=$this->form->getElement($this->form->getCsrfTokenName());?>
                        <input name="return_url" type="hidden" value="<?=$this->url();?>" />

                        <!-- Actions -->
                        <div class="well well-sm">
                            <div class="row">
                                <div class="col-xs-6 col-sm-3">
                                    <div class="checkbox">
                                        <label>
                                            <input type="checkbox" class="js-toggle-all" />
                                            <?=$this->translate('Marked entries');?>:
                                        </label>
                                    </div>
                                </div>
                                <div class="col-xs-6 col-sm-9 text-right">
                                    <div class="btn-group">
                                        <button type="submit" name="bulkAction" value="publish" class="btn btn-default">
                                            <span class="glyphicon glyphicon-ok-sign"></span>
                                            <span class="hidden-xs"><?=$this->translate('Publish');?></span>
                                        </button>
                                        <button type="submit" name="bulkAction" value="block" class="btn btn-default">
                                            <span class="glyphicon glyphicon-ban-circle"></span>
                                            <span class="hidden-xs"><?=$this->translate('Block');?></span>
                                        </button>
                                        <button type="submit" name="bulkAction" value="delete" class="btn btn-danger">
                                            <span class="glyphicon glyphicon-trash"></span>
                                            <span class="hidden-xs"><?=$this->translate('Delete');?></span>
                                        </button>
                                    </div>
                                </div>
                            </div><!-- .row -->
                        </div>

                        <!-- Listing -->
                        <table class="table table-bordered table-responsive js-table-rows-toggle" id="contribution-table">
                            <?php foreach ($this->inputs as $input): ?>
                                <?=$this->partial(
                                    'input/_inputBox.phtml',
                                    [
                                        'input' => $input,
                                        'kid' => $this->consultation['kid'],
                                        'inputsWithDiscussion' => $this->inputsWithDiscussion]
                                );?>
                            <?php endforeach;?>
                        </table>

                        <!-- Actions -->
                        <div class="well well-sm">
                            <div class="row">
                                <div class="col-xs-6 col-sm-3">
                                    <div class="checkbox">
                                        <label>
                                            <input type="checkbox" class="js-toggle-all" />
                                            <?=$this->translate('Marked entries');?>:
                                        </label>
                                    </div>
                                </div>
                                <div class="col-xs-6 col-sm-9 text-right">
                                    <div class="btn-group">
                                        <button type="submit" name="bulkAction" value="publish" class="btn btn-default">
                                            <span class="glyphicon glyphicon-ok-sign"></span>
                                            <span class="hidden-xs"><?=$this->translate('Publish');?></span>
                                        </button>
                                        <button type="submit" name="bulkAction" value="block" class="btn btn-default">
                                            <span class="glyphicon glyphicon-ban-circle"></span>
                                            <span class="hidden-xs"><?=$this->translate('Block');?></span>
                                        </button>
                                        <button type="submit" name="bulkAction" value="delete" class="btn btn-danger">
                                            <span class="glyphicon glyphicon-trash"></span>
                                            <span class="hidden-xs"><?=$this->translate('Delete');?></span>
                                        </button>
                                    </div>
                                </div>
                            </div><!-- .row -->
                        </div>

                    </form>

                    <div class="well">
                        <div class="row">
                            <div class="col-sm-6">

                                <h4>
                                    <span class="glyphicon glyphicon-save"></span>
                                    <?=$this->translate('CSV Export');?>:
                                </h4>
                                <ul class="offset-bottom">
                                    <li><a href="<?php echo $this->url(array(
                                            'action' => 'export',
                                            'kid' => $this->consultation['kid'],
                                            'qid' => $this->question['qi'],
                                            'cod' => 'utf8',
                                            'mod' => 'all',
                                        ));?>">All contributions</a></li>
                                    <li><a href="<?php echo $this->url(array(
                                            'action' => 'export',
                                            'kid' => $this->consultation['kid'],
                                            'qid' => $this->question['qi'],
                                            'cod' => 'utf8',
                                            'mod' => 'cnf',
                                        ));?>">Confirmed contributions</a></li>
                                    <li><a href="<?php echo $this->url(array(
                                            'action' => 'export',
                                            'kid' => $this->consultation['kid'],
                                            'qid' => $this->question['qi'],
                                            'cod' => 'utf8',
                                            'mod' => 'unc',
                                        ));?>">Unconfirmed contributions</a></li>
                                    <li><a href="<?php echo $this->url(array(
                                            'action' => 'export',
                                            'kid' => $this->consultation['kid'],
                                            'qid' => $this->question['qi'],
                                            'cod' => 'utf8',
                                            'mod' => 'vot',
                                        ));?>">Voting theses</a></li>
                                    <li><a href="<?php echo $this->url(array(
                                            'action' => 'export',
                                            'kid' => $this->consultation['kid'],
                                            'qid' => $this->question['qi'],
                                            'cod' => 'utf8',
                                            'mod' => 'edt',
                                        ));?>">Voting theses – edited</a>
                                    </li>
                                </ul>

                            </div>
                            <div class="col-sm-6">

                                <h4>
                                    <span class="glyphicon glyphicon-save"></span>
                                    <?=$this->translate('MS Excel Export');?>:
                                </h4>
                                <ul>
                                    <li><a href="<?php echo $this->url(array(
                                        'action' => 'export',
                                        'kid' => $this->consultation['kid'],
                                        'qid' => $this->question['qi'],
                                        'cod' => 'xls',
                                        'mod' => 'all',
                                    ));?>">All contributions</a></li>
                                </ul>

                            </div>
                        </div><!-- .row -->
                    </div><!-- .well -->

                <?php else: ?>
                    <p class="alert alert-info">
                        <span class="glyphicon glyphicon-info-sign"></span>
                        <?=$this->translate('There are no contributions for this question yet.');?>
                    </p>
                <?php endif; ?>

            </div>
        </div>
    </div>
</section>
