<h1><?php echo $this->consultation['titl']; ?></h1>
<?php echo $this->consultationNavigation('Beiträge')?>

<p>
    <a href="<?php echo $this->url(array('action' => 'index')); ?>">Beiträge nach Fragen &raquo;</a>
</p>

<h2>Alle Teilnehmenden zu „<?php echo $this->consultation['titl_short']; ?>“</h2>
<ol>
    <?php foreach ($this->users as $user): ?>
        <li>
            <a href="<?php echo $this->baseUrl()?>/admin/input/list/kid/<?php echo $this->consultation['kid']?>/uid/<?php echo $user->uid?>">
                <?php echo $user->name?>&nbsp;·&nbsp;<?php echo $user->email?>&nbsp;<?php echo $user->uid?>
            </a>
            <a href="mailto:<?php echo $user->email;?>" title="Mail in externem Programm schreiben">
                <img src="<?php echo $this->baseUrl(); ?>/images/mail.gif" alt="E-Mail" />
            </a>
    <?php endforeach;?>
</ol>
