<?php

?>
<h1><?php echo $this->consultation['titl']; ?></h1>
<?php
echo $this->consultationNavigation('Beiträge');
?>
<h2>Alle Teilnehmenden zu „<?php echo $this->consultation['titl_short']; ?>“</h2>
<ol>
<?php foreach ($this->users as $user): ?>
  <li>
    <a href="/admin/input/list/kid/<?php echo $this->consultation['kid']?>/uid/<?php echo $user['uid']; ?>">
      <?php echo $user['name'];?>&nbsp;·&nbsp;<?php echo $user['email']; ?>&nbsp;<?php echo $user['uid']; ?>
    </a>
    <a href="mailto:<?php echo $user['email'];?>" title="Mail in externem Programm schreiben"><img src="/images/mail.gif" alt="E-Mail" /></a>
<?php endforeach;?>
</ol>