<?php
    $date = new Zend_Date();
    $locale = new Zend_Locale();
?>

<?php echo $this->secondNavigation('follow-up') ?>

<div class="content-holder">
    <div class="row">
        <aside class="span3">
            <?php echo $this->followupNavigation('overview') ?>
        </aside>

        <section class="main-content span9">

            <h1>
                <?=$this->translate("Wie's weiterging:")?>
                <br />
                <?=$this->translate('Reaktionen & Wirkung')?>
            </h1>
            <p>
                <?=$this->translate('Hier erfahrt ihr, wie es mit euren Beiträgen weiterging, in welche Prozesse und Dokumente sie eingeflossen sind, wer wie darauf reagiert hat und inwieweit bereits Ergebnisse erreicht wurden.')?>
            </p>

            <div class="well-large-alt text-center">
                <span class="label sticker label-reaktion-alt"><?=$this->translate('Reaktion')?></span>
                <h2 class="alt"><?=$this->translate('Bisherige Reaktionen im Überblick')?></h2>
                <ul class="thumbnails thumbnails-follow-up">

                    <?php $i = 1; ?>
                    <?php foreach ($this->followups as $followup): ?>
                        <li class="span2">
                            <div class="thumbnail">
                                <h3 class="thumbnail-title"><?php echo $followup['titl'] ?></h3>
                                <a
                                    <?php if ($followup['referenceType'] === 'http'): ?>
                                        href="<?php echo $followup['ref_doc']; ?>"
                                    <?php else: ?>
                                        href="<?php echo $this->mediaCnsltDir . $followup['ref_doc']; ?>"
                                    <?php endif?>
                                    class="thumbnail-image pull-left"
                                    target="_blank"
                                    title="Dokument ansehen"
                                    name="<?php echo $followup['ref_doc']?>"
                                >
                                    <img
                                        alt="Vorschau <?php echo $followup['titl'] ?>"
                                        src="<?php echo $this->mediaCnsltDir . $followup['gfx_who']; ?>"
                                    />
                                </a>
                                <time class="muted">
                                    <?php
                                        if ($followup['show_no_day'] === "y") {
                                            echo strftime("%m/%Y", strtotime($followup['when']));
                                        } else
                                            echo strftime("%d.%m.%Y", strtotime($followup['when']));
                                        ?>
                                </time>
                                <p class="thumbnail-author"><?php echo $followup['who']; ?></p>
                                <a
                                    <?php if ($followup['referenceType'] === 'http'): ?>
                                        href="<?php echo $followup['ref_doc']; ?>"
                                    <?php else: ?>
                                        href="<?php $this->mediaCnsltDir . $followup['ref_doc']; ?>"
                                    <?php endif?>
                                    target="_blank"
                                    title="Dokument ansehen"
                                >
                                    <i class="icon-angle-right"></i> <?=$this->translate('Ansehen')?>
                                </a>
                                <?php if ($followup['referenceType'] === 'file'): ?>
                                    <form
                                        method="post"
                                        action="<?php echo $this->url(array('action' => 'download', 'page' => null)); ?>"
                                    >
                                        <input type="hidden" name="filename" value="<?php echo $followup['ref_doc']; ?>" />
                                        <button type="submit" class="btn-link" title="Dokument herunterladen">
                                            <i class="icon-file"></i> <?=$this->translate('Download')?>
                                        </button>
                                    </form>
                                <?php endif?>

                            </div><!-- .thumbnail -->
                        </li>
                        <?php if ($i === 4): ?>
                            </ul>
                            <ul class="thumbnails thumbnails-follow-up">
                        <?php endif; ?>
                        <?php $i++; ?>
                    <?php endforeach; ?>

                </ul>
            </div><!-- .well-large-alt -->

            <div class="well-large-alt text-center">
                <span class="label sticker label-reaktion-alt"><?=$this->translate('Reaktion')?></span>
                <h2 class="alt"><?=$this->translate('Reaktionen und Feedback auf einzelne Beiträge')?></h2>

                <p>
                    <?=$this->translate('Einfach auf die betreffende Fragestellung klicken oder zum Bereich Schlagwörter wechseln.')?>
                </p>
                <?php echo $this->questionNavigation(NULL, 'follow-up-box'); ?>
                <br/>
                <a href="<?php echo $this->url(array('action' => 'tags', 'page' => null)); ?>" class="btn">
                    <?=$this->translate('Sortiert nach Schlagwörtern')?>
                </a>
            </div><!-- .well-large-alt -->

        </section>
    </div><!-- .row -->
</div><!-- .content-holder -->

<?php echo $this->render('_partials/topLink.phtml') ?>
