<?php
/**
 * index
 *
 * @description   Übersicht Followup
 * @author        Marco Dinnbier
 */
$date = new Zend_Date();
$locale = new Zend_Locale();
?>

<?php echo $this->secondNavigation('follow-up') ?>

<div class="content-holder">
    <div class="row">
        <aside class="span3">

			<?php echo $this->followupNavigation('overview') ?>

        </aside>
        <section class="main-content span8">

            <h1>Lorem ipsum Headline, die auch zweizeilig sein kann wenn denn nötig</h1>
            <p>Bildung findet nicht nur in der (Hoch-)Schule oder am Ausbildungsplatz
				statt. Wissen, neue Kenntnisse, Fähigkeiten und Fertigkeiten erwirbt
				man auch außerhalb des sogenannten formalen Bildungssystems. Eine
				besondere Rolle spielen dabei außerschulisch organisierte
				Gruppenaktivitäten, bei denen die Teilnahme freiwillig ist.</p>

            <div class="well-large-alt">
				<h2>Bisherige Reaktionen im Überblick</h2>
                <ul class="unstyled">
					<?php foreach ($this->latest_followups as $followup): ?>
						<li class="media">
							<a href="<?php echo $this->media_cnslt_dir . $followup['ref_doc']; ?>" class="pull-left">
								<img src="<?php echo $this->media_cnslt_dir . $followup['gfx_who']; ?>" />
							</a>
							<div class="media-body">
								<p>
									<time class="muted"><?php echo $followup['when']; ?></time>
									<br />
									<h4 class="media-heading"><?php echo $followup['who']; ?></h4>
								</p>
								<a href="<?php echo $this->media_cnslt_dir . $followup['ref_doc']; ?>">Ansehen <i class="icon-angle-right"></i></a>
							</div>
						</li>
					<?php endforeach; ?>
                </ul>
            </div>
            <div class="well-large-alt">
                <h2>Reaktionen und Feedback auf einzelne Beiträge</h2>
                <p>Einfach auf die betreffende Fragestellung klicken oder zum Bereich Schlagwörter wechseln.</p>
				<?php echo $this->questionNavigation(NULL, 'follow-up'); ?>
				<br />
                <a href="<?php echo $this->url(array('action' => 'show', 'page' => null)); ?>" class="btn">Sortiert nach Schlagwörtern</a>
            </div>

        </section>
    </div>
</div>

<?php echo $this->render('_partials/topLink.phtml') ?>
