<?=$this->secondNavigation('follow-up');?>

<div class="main-content">
    <div class="row">
        <div class="sidebar-left hidden-print">

            <?=$this->followupNavigation('inputs-by-question', $this->question['qi']);?>

        </div>
        <div class="content">

            <div class="row">
                <div class="col-md-10">

                    <?php if (isset($this->tag) && !empty($this->tag)): ?>
                        <p class="alert alert-info">
                            <span class="glyphicon glyphicon-info-sign icon-offset" aria-hidden="true"></span>
                            <?php if ($this->numberInputs > 0): ?>
                                <?=sprintf($this->translate('Only contributions with the keyword %s are shown.'), '<em>' . $this->tag['tg_de'] . '</em>');?>
                            <?php else: ?>
                                <?=sprintf($this->translate('There are no contributions with the keyword %s on this question.'), '<em>' . $this->tag['tg_de'] . '</em>');?>
                            <?php endif; ?>
                            <a href="<?=$this->url(['tag' => null]);?>">
                                <?=$this->translate('Show all contributions');?>
                            </a>
                        </p>
                    <?php endif; ?>

                    <div class="text-muted">
                        <small>
                            <?=$this->numberInputs;?>
                            <?=$this->translate('contributions');?>
                        </small>
                    </div>

                    <h1>
                        <?=$this->question['nr'];?>
                        <?=$this->question['q'];?>
                    </h1>

                </div>
            </div><!-- .row -->

            <div class="offset-bottom-large">
                <?=$this->question['q_xpl'];?>
            </div>

            <hr/>

            <!-- Contributions -->
            <?php if (count($this->paginator)): ?>
                <?php foreach ($this->paginator as $input): ?>
                    <a name="input-<?=$input['tid'];?>"></a>

                    <article class="media">
                        <header>
                            <time datetime="<?=$this->formatDate($input['when'], 'y-MM-dd');?>">
                                <?=$this->translate('written on');?>
                                <?=$this->formatDate($input['when'], Zend_Date::DATE_MEDIUM);?>
                            </time>
                        </header>

                        <p>
                            <strong><?=$this->escape($input['thes']);?></strong>
                        </p>

                        <?php if (!empty($input['expl'])): ?>
                            <p>
                                <?=$this->escape($input['expl']);?>
                            </p>
                        <?php endif; ?>

                        <!-- Actions -->
                        <footer>

                            <!-- Support -->
                            <?php if ($this->consultation->spprt_show == 'y'): ?>
                                <span id="click-support-wrap-<?=$this->escape($input['tid']);?>" class="offset-right">
                                    <span class="glyphicon glyphicon-ok-sign icon-offset icon-shift-down text-accent" aria-hidden="true"></span>
                                    <small id="badge-<?=$this->escape($input['tid']);?>" class="badge<?=$this->escape($input['spprts']) > 0 ? ' badge-accent' : '';?>">
                                        <?=$this->escape($input['spprts']);?>
                                    </small>
                                    <?php // Apart from contributions support, always show the "I agree" button. ?>
                                    <?php /*if (in_array($input['tid'], $supports->clicks) || $supportsDisabled): ?>
                                        <small><?=$this->translate('supporters');?></small>
                                    <?php else:*/ ?>
                                        <a
                                            href="#"
                                            id="click-support-<?=$this->escape($input['tid']);?>"
                                            class="btn btn-default btn-xs hidden-print js-click-support"
                                            data-kid="<?=$this->consultation->kid;?>"
                                            rel="<?=$this->escape($input['tid']);?>"
                                        >
                                            <?=$this->translate('I agree!');?>
                                        </a>
                                    <?php //endif; ?>
                                </span>
                            <?php endif; ?>

                            <!-- Discussion -->
                            <?php if ($this->consultation->is_discussion_active): ?>
                                <span class="offset-right">
                                    <a
                                        href="<?=$this->url(['controller' => 'input', 'action' => 'discussion', 'kid' => $this->consultation->kid, 'inputId' => $this->escape($input['tid'])]);?>"
                                        class="link-unstyled link-print-nourl"
                                    >
                                        <span class="glyphicon glyphicon-comment icon-offset icon-shift-down text-accent" aria-hidden="true"></span>
                                    </a>
                                    <a
                                        href="<?=$this->url(['controller' => 'input', 'action' => 'discussion', 'kid' => $this->consultation->kid, 'inputId' => $this->escape($input['tid'])]);?>"
                                        class="link-unstyled link-print-nourl"
                                    >
                                        <small class="badge<?=$this->escape($input['discussionPostCount']) > 0 ? ' badge-accent' : '';?>">
                                            <?=$this->escape($input['discussionPostCount']);?>
                                        </small>
                                    </a>
                                    <a
                                        href="<?=$this->url(['controller' => 'input', 'action' => 'discussion', 'kid' => $this->consultation->kid, 'inputId' => $this->escape($input['tid'])]);?>"
                                        class="btn btn-default btn-xs hidden-print"
                                    >
                                        <?php if(Zend_Date::now()->isLater(new Zend_Date($this->consultation->discussion_from, Zend_Date::ISO_8601))
                                            && Zend_Date::now()->isEarlier(new Zend_Date($this->consultation->discussion_to, Zend_Date::ISO_8601))
                                        ): ?>
                                            <?=$this->translate('I would like to discuss that!');?>
                                        <?php else : ?>
                                            <?=$this->translate('Show discussion');?>
                                        <?php endif; ?>
                                    </a>
                                </span>
                            <?php endif; ?>

                            <!-- Followup -->
                            <?=$this->followupLink($input['tid'], $this->question['qi'], explode(',', $input['rel_tid']));?>

                        </footer>
                    </article>

                    <hr/>
                <?php endforeach; ?>
            <?php else: ?>
                <p>
                    <span class="glyphicon glyphicon-info-sign text-info icon-offset" aria-hidden="true"></span>
                    <?=$this->translate('There are no contributions on this question.');?>
                </p>
            <?php endif; ?>

            <!-- Paging -->
            <?=$this->paginationControl(
                $this->paginator,
                'Jumping',
                '_partials/pagination.phtml',
                ['titlePrev' => $this->translate('Newer contributions'), 'titleNext' => $this->translate('Older contributions')]
            );?>

        </div>
    </div><!-- .row -->

    <?=$this->partial('_partials/pageLinks.phtml', ['help' => 'help-text-consultation-followup']);?>

</div><!-- main-content -->
