<?php
    $date = new Zend_Date();
    $locale = new Zend_Locale();
?>

<?php echo $this->secondNavigation('follow-up') ?>

<div class="content-holder">
    <div class="row">
        <aside class="span3">
            <?php echo $this->followupNavigation('inputs-by-question', $this->question['qi']) ?>
        </aside>

        <section class="main-content span9">
            <?php if (isset($this->tag) && !empty($this->tag)): ?>
                <?php if ($this->numberInputs > 0): ?>
                    <h3>
                        <?=sprintf($this->translate('Es werden nur Beiträge mit dem Schlagwort %s angezeigt.'), '<em>' . $this->tag['tg_de'] . '</em>')?>
                    </h3>
                <?php else: ?>
                    <h3>
                        <?=sprintf($this->translate('Zu dieser Frage gibt es keine mit %s verschlagworteten Beiträge.'), '<em>' . $this->tag['tg_de'] . '</em>')?>
                    </h3>
                <?php endif; ?>
                <p>
                    <a href="<?php echo $this->url(array('tag' => null)); ?>">
                        <?=$this->translate('Alle Beiträge anzeigen')?>
                    </a>
                </p>
            <?php endif; ?>

            <small class="muted count"><?php echo $this->numberInputs; ?> Beiträge</small>

            <article class="article">
                <h1><?php echo $this->question['nr']; ?> <?php echo $this->question['q']; ?></h1>
                <p><?php echo $this->question['q_xpl']; ?></p>
            </article>

            <hr/>

            <!-- Contributions -->
            <?php if (count($this->paginator)): ?>
                <?php foreach ($this->paginator as $input): ?>
                    <a name="input-<?php echo $input['tid']; ?>"></a>
                    <article class="media">
                        <time pubdate datetime="<?php echo $date->set($input['when'])->get('y-MM-dd') ?>">
                            <?=$this->translate('verfasst am')?>
                            <?php echo $date->get(Zend_Date::DATE_MEDIUM); ?>
                        </time>
                        <p class="lead"><?php echo $input['thes'] ?></p>

                        <p><?php echo $input['expl'] ?></p>

                        <p class="article-actions">
                            <?php if ($this->consultation->spprt_show == 'y'): ?>
                                <a
                                    href="#"
                                    id="click-support-<?php echo $input['tid']; ?>"
                                    class="article-action click-support<?php echo (in_array($input['tid'], $supports->clicks) || $supportsDisabled) ? 'disabled' : ''?>"
                                    rel="<?php echo $input['tid']; ?>"
                                >
                                    <i class="icon-ok-sign"></i>
                                    <span class="badge" id="badge-<?php echo $input['tid']; ?>">
                                        (<?php echo $input['spprts']; ?>)
                                    </span>
                                    <span class="label"><?=$this->translate('Dieser Meinung bin ich auch!')?></span>
                                </a>
                            <?php endif; ?>

                            <?php if ($this->consultation->is_discussion_active): ?>
                                <a href="#" class="article-action">
                                    <i class="icon-comment icon-orange icon-2x"></i>
                                    <?php if(isset($input['pts'])): ?>
                                        (<?php echo $input['pts']?>)
                                    <?php endif?>
                                    <span class="label"><?=$this->translate('Das möchte ich gerne diskutieren!')?></span>
                                </a>
                            <?php endif?>

                            <?php echo $this->followupLink($input['tid'], $this->question['qi']); ?>
                        </p>
                    </article>
                    <hr/>
                <?php endforeach; ?>
            <?php endif; ?>

            <!-- Paging -->
            <?php echo $this->paginationControl(
                $this->paginator,
                'Jumping',
                '_partials/pagination.phtml',
                array('titlePrev' => 'Neuere Beiträge', 'titleNext' => 'Ältere Beiträge')
            ); ?>

        </section>
    </div><!-- .row -->
</div><!-- content-holder -->

<?php echo $this->render('_partials/topLink.phtml')?>
