<?=$this->secondNavigation('follow-up');?>

<div class="main-content">

    <h1 class="text-center"><?=$this->translate('Reactions & Impact');?></h1>

    <div class="well well-bordered well-accent">

        <!-- Back link -->
        <div class="row offset-bottom-large">
            <div class="col-sm-3">

                <a
                    href="<?=$this->url(['action' => 'index', 'page' => null]);?>"
                    class="followup-back-link followup-link media link-unstyled link-unstyled-alt"
                    title="<?=$this->translate('Back to overview of Reactions & Impact');?>"
                >
                    <div class="media-left">
                        <div class="followup-back-link-question-mark followup-sprite followup-sprite-question-mark" aria-hidden="true">?</div>
                    </div>
                    <div class="media-body">
                        <strong class="small">
                            <?=$this->translate('Follow the Reactions to your contribution here. Click on the arrows for the next steps.');?>
                        </strong>
                    </div>
                </a>

            </div>
        </div><!-- .row -->

        <!-- Chart -->
        <div id="followup" class="followup">
            <div class="row">
                <div class="col-sm-4 js-col" data-id="0" id="el-0">

                    <!-- Boxes -->
                    <?php if (count($this->reltothis_inputs)): ?>
                        <?php foreach ($this->reltothis_inputs as $relInput): ?>
                            <div class="followup-timeline-box">

                                <div class="well well-bordered">
                                    <p>
                                        <?=$relInput['thes'];?>
                                    </p>
                                    <div class="text-accent">
                                        <?=$this->translate('Result of voting: X. position');?>
                                    </div>
                                </div>

                                <?php if ($relInput['relFowupCount'] != 0): ?>
                                    <span class="followup-link followup-timeline-count followup-sprite followup-sprite-timeline-count">
                                        <?=$relInput['relFowupCount'];?>
                                    </span>
                                <?php endif; ?>

                            </div><!-- .followup-timeline-box -->
                        <?php endforeach; ?>
                    <?php endif; ?>

                    <?php foreach ($this->reltothis_snippets as $relSnippet): ?>
                        <?=$this->partial(
                            '_partials/followup-snippet-box.phtml',
                            [
                                'snippet' => $relSnippet,
                                'followPathLink' => true,
                                'relFollowupCount' => true,
                                'kid' => $this->kid
                            ]
                        ) ?>
                    <?php endforeach; ?>

                </div>
                <div class="col-sm-4 js-col" data-id="1" id="el-1">

                    <?=$this->partial(
                        '_partials/followup-snippet-box.phtml',
                        [
                            'snippet' => $this->snippet,
                            'followPathLink' => true,
                            'relFollowupCount' => true,
                            'kid' => $this->kid
                        ]
                    );?>

                </div>
            </div>
        </div><!-- .followup -->

        <!-- Loader -->
        <div id="followuploader"><?=$this->translate('Loading…');?></div>

    </div>

    <?=$this->partial('_partials/pageLinks.phtml', ['help' => 'help-text-consultation-followup']);?>

</div><!-- .main-content -->
