<?=$this->secondNavigation('follow-up');?>

<div class="main-content">

    <h1 class="text-center"><?=$this->translate('Reactions & Impact');?></h1>

    <div class="well well-bordered well-accent">

        <!-- Back link -->
        <div class="row offset-bottom-large">
            <div class="col-sm-3">

                <a
                    href="<?=$this->url(['action' => 'index', 'page' => null]);?>"
                    class="followup-back-link followup-link media link-unstyled link-unstyled-alt"
                    title="<?=$this->translate('Back to overview of Reactions & Impact');?>"
                >
                    <div class="media-left">
                        <div class="followup-back-link-question-mark followup-sprite followup-sprite-question-mark" aria-hidden="true">?</div>
                    </div>
                    <div class="media-body">
                        <strong class="small">
                            <?=$this->translate('Follow the Reactions to your contribution here. Click on the arrows for the next steps.');?>
                        </strong>
                    </div>
                </a>

            </div>
        </div><!-- .row -->

        <!-- Chart -->
        <div id="followup" class="followup">
            <div class="row js-row">
                <div class="col-sm-4">

                    <!-- Box -->
                    <div class="followup-timeline-box js-timeline-box">

                        <a
                            href="<?=$this->url(['action' => 'inputs-by-question', 'qid' => $this->question['qi'], 'page' => null]);?>"
                            class="link-alt link-unstyled link-unstyled-alt"
                            title="<?=$this->translate('Back to overview of contributions sorted by questions');?>"
                        >
                            <h4 class="offset-bottom">
                                <?=$this->question['nr'];?>
                                <?=$this->question['q'];?>
                            </h4>
                        </a>

                        <div class="well well-bordered followup-well">
                            <p>
                                <?=$this->input['thes'];?>
                            </p>

                            <?php if (!empty($this->input['expl'])): ?>
                                <div class="explbutton">
                                    <span class="glyphicon glyphicon-menu-down" aria-hidden="true"></span>
                                </div>
                                <div class="toggleexpl">
                                    <p><?=$this->input['expl'];?></p>
                                </div>
                            <?php endif; ?>

                            <?php if ($this->input['vot'] == 'y'): ?>
                                <div class="text-accent">
                                    <?=$this->translate('Result of voting: X. position');?>
                                </div>
                            <?php endif; ?>
                        </div><!-- .well -->

                        <?php if ($this->relatedCount): ?>
                            <a
                                href="<?=$this->url(['action' => 'show', 'tid' => $this->input['tid'], 'page' => null]);?>/foreset/1"
                                class="link-unstyled followup-link followup-timeline-count followup-sprite followup-sprite-timeline-count js-ajaxclick reset"
                            >
                                <?=$this->relatedCount;?>
                            </a>
                        <?php endif; ?>

                    </div><!-- .followup-timeline-box -->

                </div>
                <div class="col-sm-4">

                    <?php if (count($this->relInput)): ?>
                        <?php foreach ($this->relInput as $relInput): ?>
                            <div class="followup-timeline-box js-timeline-box">
                                <div class="well well-bordered followup-well">
                                    <p>
                                        <?=$relInput['thes'];?>
                                    </p>

                                    <?php if ($relInput['vot'] == 'y'): ?>
                                        <div class="text-accent">
                                            <?=$this->translate('Result of voting: X. position');?>
                                        </div>
                                    <?php endif; ?>
                                </div><!-- .well -->

                                <?php if ($relInput['relFowupCount'] != 0): ?>
                                    <a
                                        href="<?=$this->url(['action' => 'json', 'tid' => $relInput['tid'], 'page' => null]);?>"
                                        class="link-unstyled followup-link followup-timeline-count followup-sprite followup-sprite-timeline-count js-ajaxclick"
                                    >
                                        <?=$relInput['relFowupCount'];?>
                                    </a>
                                <?php endif; ?>

                            </div><!-- .followup-timeline-box -->
                        <?php endforeach; ?>
                    <?php endif; ?>

                    <?php if (count($this->relSnippets)): ?>
                        <?php foreach ($this->relSnippets as $snippet): ?>
                            <?=$this->partial(
                                '_partials/followup-snippet-box.phtml',
                                [
                                    'snippet' => $snippet,
                                    'followPathLink' => true,
                                    'relFollowupCount' => true,
                                    'kid' => $this->kid
                                ]
                            );?>
                        <?php endforeach; ?>
                    <?php endif; ?>

                </div>
            </div><!-- .row -->

            <!-- Loader -->
            <div id="followuploader"><?=$this->translate('Loading…');?></div>

        </div><!-- #followup -->

    </div><!-- .well -->

    <?=$this->partial('_partials/pageLinks.phtml', ['help' => 'help-text-consultation-followup']);?>

</div><!-- .main-content -->
