<?=$this->secondNavigation('follow-up');?>

<div class="main-content">

    <h1 class="text-center"><?=$this->translate('Reactions & Impact');?></h1>

    <script>
      var followupApiUrl = '<?=$this->followupApiUrl?>';
      var embedVideoUrl = {
        <?php foreach ($this->embedVideoUrl as $key => $url): ?>
          <?=$key?>: '<?=$url?>',
        <?php endforeach; ?>
      };
      var followupTranslations = {
        <?php foreach ($this->followupTranslations as $key => $translatedString): ?>
          <?=$key?>: '<?=$translatedString?>',
        <?php endforeach; ?>
      };
    </script>

    <div id="followup-timeline"></div>

    <?=$this->partial('_partials/pageLinks.phtml', ['help' => 'help-text-consultation-followup']);?>

</div><!-- .main-content -->
