<?=$this->secondNavigation('follow-up');?>

<div class="main-content">
    <div class="row">
        <div class="sidebar-left hidden-print">

            <?=$this->followupNavigation('tags');?>

        </div>
        <div class="content">

            <div class="text-muted">
                <small>
                    <?=$this->inputCount;?>
                    <?=$this->translate('confirmed contributions');?>
                </small>
            </div>

            <h1 class="main-content-title-thin"><?=$this->translate('All contributions');?></h1>

            <p class="offset-bottom-large">
                <?=$this->translate('You want to participate in this participation round? Just click on a question during the input period, and the input field will appear where you can insert your contributions. After the input period has finished, you are no longer allowed to draw up contributions, but by clicking on a question you can read all other contributions.');?>
            </p>

            <!-- Questions -->
            <?php if (!empty($this->tags)): ?>
                <div class="well well-bordered text-center">
                    <h2><?=$this->translate('Contributions sorted by keywords:');?></h2>
                    <ul class="list-inline tag-cloud tag-cloud-large small offset-bottom">
                        <?php foreach ($this->tags as $tag): ?>
                            <li class="tag-<?=$tag['frequency'];?>">
                                <a href="<?=$this->url(['action' => 'inputs-by-question', 'tag' => $tag['tg_nr']]);?>" class="link-unstyled link-print-nourl">
                                    <?=$tag['tg_de'];?>
                                </a>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                    <a href="<?=$this->url(['action' => 'index', 'qid' => null]);?>" class="btn btn-default">
                        <span class="glyphicon glyphicon-menu-left" aria-hidden="true"></span>
                        <?=$this->translate('Back to overview of questions');?>
                    </a>
                </div><!-- .well -->
            <?php endif; ?>

        </div><!-- .main-content -->
    </div><!-- .row -->

    <?=$this->partial('_partials/pageLinks.phtml', ['help' => 'help-text-consultation-followup']);?>

</div><!-- .main-content -->
