<?php echo $this->secondNavigation('follow-up') ?>

<div class="main-content">
    <div class="row">
        <div class="sidebar-left">

            <?php echo $this->followupNavigation('tags') ?>

        </div>
        <div class="content">

            <small class="count muted">
                <?php echo $this->inputCount ?>
                <?=$this->translate('confirmed contributions')?>
            </small>
            <h1><?=$this->translate('All contributions')?></h1>
            <p>
                <?=$this->translate('You want to participate in this participation round? Just click on a question during the input period, and the input field will appear where you can insert your contributions. After the input period has finished, you are no longer allowed to draw up contributions, but by clicking on a question you can read all other contributions.')?>
            </p>

            <!-- Questions -->
            <?php if (!empty($this->tags)): ?>
                <div class="well-large-alt text-center">
                    <h2><?=$this->translate('Contributions sorted by keywords:')?></h2>
                    <ul class="tag-cloud">
                        <?php foreach ($this->tags as $tag): ?>
                            <li class="tag-<?php echo $tag['frequency']; ?>">
                                <a href="<?php echo $this->url(array('action' => 'inputs-by-question', 'tag' => $tag['tg_nr'])); ?>">
                                    <?php echo $tag['tg_de']; ?>
                                </a>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                    <a href="<?php echo $this->url(array('action' => 'inputs-by-question')); ?>" class="btn">
                        <?=$this->translate('Back to overview of questions')?>
                    </a>
                </div><!-- .well-large-alt -->
            <?php endif; ?>

        </div><!-- .main-content -->
    </div><!-- .row -->

    <?=$this->render('_partials/pageLinks.phtml');?>

</div><!-- .main-content -->
