<section class="section-header">
    <div class="container">
        <h1><?=$this->translate('New User');?></h1>
    </div>
</section>
<section class="section-content">
    <div class="container">

        <a href="<?=$this->url(array('action' => 'index'));?>" class="back">&larr; <?=$this->translate('Back to Users');?></a>

        <?=$this->form;?>
        <p>
            <?=$this->translate('or');?>
            <a href="<?=$this->url(array('action' => 'index'));?>"><?=$this->translate('Cancel');?></a>
        </p>

    </div>
</section>
