<section class="section-header">
    <div class="container">
        <h1>New User</h1>
    </div>
</section>
<section class="section-content">
    <div class="container">

        <p class="back-link">
            <a href="<?=$this->url(array('action' => 'index'));?>">&larr; Back to Users</a>
        </p>
        <?=$this->form;?>
        <p>
            or
            <a href="<?=$this->url(array('action' => 'index'));?>">Cancel</a>
        </p>

    </div>
</section>
