<section class="section-header">
    <div class="container">
        <div class="row">
            <div class="col-sm-8">
                <h1><?=$this->translate('Users');?></h1>
            </div>
            <div class="col-sm-4">
                <a href="<?=$this->url(['action' => 'create']);?>" class="btn btn-primary cta">
                    <span class="glyphicon glyphicon-plus-sign"></span>
                    <?=$this->translate('New User');?>
                </a>
            </div>
        </div>
    </div>
</section>
<section class="section-content">
    <div class="container">

        <?php if (!count($this->userlist)): ?>
            <p class="alert alert-info">
                <span class="glyphicon glyphicon-info-sign"></span>
                <?=$this->translate('There are no users yet.');?>
            </p>
        <?php else: ?>

            <div class="row">
                <div class="col-sm-1 col-sm-push-11 sortable-table-nav" id="letterNavigation"></div>
                <div class="col-sm-11 col-sm-pull-1">

                    <div class="table-responsive">
                        <form method="<?=$this->form->getMethod();?>" action="<?=$this->url(['action' => 'delete']);?>">
                            <?=$this->form->getElement($this->form->getCsrfTokenName());?>
                            <table class="table" data-sort-navigation="#letterNavigation">
                                <thead>
                                    <tr>
                                        <th class="table-cell-id" data-toggle="sort" tabindex="0">#</th>
                                        <th data-toggle="sort" data-sort-onload="asc" tabindex="0"><?=$this->translate('Name');?></th>
                                        <th data-toggle="sort" tabindex="0"><?=$this->translate('Email');?></th>
                                        <th data-toggle="sort" tabindex="0"><?=$this->translate('Role');?></th>
                                        <th data-toggle="sort" tabindex="0"><?=$this->translate('Last Activity');?></th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php $i = 1; ?>
                                    <?php foreach ($this->userlist as $user): ?>
                                        <tr>
                                            <td class="table-cell-id"><?=$i;?></td>
                                            <td data-sort-group="<?=empty($user->name)? '–' : strtoupper(substr($this->escape($user->name), 0, 1));?>">
                                                <?=(empty($user->name))? '<span class="text-muted">–</span>' : $this->escape($user->name);?>
                                            </td>
                                            <td>
                                                <?php if (empty($user->email)): ?>
                                                    <em class="text-muted"><?=$this->translate('Not available');?></em>
                                                <?php else: ?>
                                                    <a href="mailto:<?=$this->escape($user->email);?>" title="<?=$this->translate('Send email to user');?>">
                                                        <?=$this->escape($user->email);?>
                                                    </a>
                                                <?php endif; ?>
                                            </td>
                                            <td>
                                                <?php switch($user->lvl) {
                                                    case 'usr':
                                                        $userLevel = $this->translate('User');
                                                        break;
                                                    case 'edt':
                                                        $userLevel = $this->translate('Editor');
                                                        break;
                                                    case 'adm':
                                                        $userLevel = $this->translate('Administrator');
                                                        break;
                                                };?>
                                                <?=$userLevel;?>
                                            </td>
                                            <td data-sort-value="<?=$user->last_act?>">
                                                <?=$this->formatDate($user->last_act, Zend_Date::DATETIME_SHORT);?>
                                            </td>
                                            <td class="table-cell-actions">
                                                <a class="item-action" href="<?=$this->url(['action' => 'edit', 'uid' => $user->uid]);?>" title="<?=$this->translate('Edit user');?>">
                                                    <span class="glyphicon glyphicon-pencil"></span>
                                                </a>
                                                <a
                                                    class="item-action"
                                                    href="<?=$this->url(['action' => 'transfer-contributions', 'uid' => $user->uid]);?>"
                                                    title="<?=$this->translate('Transfer contributions to another user');?>"
                                                >
                                                    <span class="glyphicon glyphicon-transfer"></span>
                                                </a>
                                                <button
                                                    value="<?=$this->escape($user->uid);?>"
                                                    class="item-action item-action-danger"
                                                    name="delete"
                                                    data-toggle="confirm"
                                                    data-confirm-message="<?=$this->translate('Are you sure? All contributions by this user will be made anonymous.');?>"
                                                >
                                                    <span class="glyphicon glyphicon-trash"></span>
                                                </button>
                                            </td>
                                        </tr>
                                        <?php $i++; ?>
                                    <?php endforeach; ?>
                                </tbody>
                            </table>
                        </form>
                    </div>

                <?php endif; ?>

            </div>
        </div>
    </div>
</section>
