<section class="section-header">
    <div class="container">
        <div class="row">
            <div class="col-sm-8">
                <h1><?=$this->translate('Transfer User Contributions');?></h1>
            </div>
        </div>
    </div>
</section>
<section class="section-content">
    <div class="container">

        <a href="<?=$this->url(array('action' => 'index'));?>" class="back">&larr; <?=$this->translate('Back to Users');?></a>

        <?=$this->form;?>

    </div>
</section>
