adminer:
    image: clue/adminer
    links:
        - db
    ports:
        - 127.0.0.1:81:80
db:
    image: mysql:5.5
    ports:
        - "127.0.0.1:3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: pass
php:
    build: docker/PHP
    volumes:
        - .:/www
    working_dir: /www
    links:
        - db
        - mail
tools:
    build: docker/Tools
    volumes:
        - .:/www
    working_dir: /www
    links:
        - db
web:
    build: docker/Apache
    volumes:
        - .:/www
    links:
        - php
    ports:
        - 80:80
mail:
    image: mailhog/mailhog
    ports:
        - 127.0.0.1:82:8025
