adminer:
    image: clue/adminer
    links:
        - db
    ports:
        - 127.0.0.1:81:80
db:
    build: docker/MySql
    environment:
        MYSQL_ROOT_PASSWORD: pass
web:
    image: visionappscz/apache-php:7.1
    links:
        - db
        - mail
    ports:
        - 80:80
    volumes:
        - .:/www:z
mail:
    image: mailhog/mailhog
    ports:
        - 127.0.0.1:82:8025
