<div class="main-content">
    <div class="row">
        <div class="content content-narrow content-offset">
            <div class="span9">
            <h1><?=$this->translate('Confirm contribution')?></h1>
            <blockquote>
                <p>
                    <a
                        href="<?=$this->url([
                            'controller' => 'input',
                            'action' => 'discussion',
                            'kid' => $this->question['kid'],
                            'inputId' => $this->discussionContribution['input_id']], null, true);?>"
                        target="_blank"
                    >
                        <?=$this->escape($this->contribution['thes']);?>
                    </a>
                </p>
                <p>
                    <?=$this->escape($this->discussionContribution->body);?>
                </p>

                <?php if ($this->consultation['discussion_video_enabled']
                    && isset($this->discussionContribution['video_service'])
                    && $this->discussionContribution['video_id']
                    && $this->videoServicesStatus['video_' . $this->discussionContribution['video_service'] . '_enabled']) : ?>
                    <div class="embed-responsive embed-responsive-16by9 offset-bottom">
                        <?=$this->embeddedVideo(
                            $this->discussionContribution['video_service'],
                            $this->discussionContribution['video_id']
                        );?>
                    </div>
                <?php endif; ?>

                <small><?=$this->formatDate($this->discussionContribution['time_created']);?></small>
            </blockquote>
            <?=$this->form;?>

            </div>
        </div>
    </div><!-- .row -->
</div><!-- .main-content -->
