<div class="main-content content-holder">
    <div class="row">
        <div class="span9">

            <h1><?=$this->translate('Confirm contribution')?></h1>
            <blockquote>
                <p><?=$this->contribution['thes'];?></p>
                <p>
                    <a
                        href="<?=$this->url([
                            'controller' => 'input',
                            'action' => 'discussion',
                            'kid' => $this->question['kid'],
                            'inputId' => $this->discussionContribution['input_id']], null, true);?>#post-<?=$this->discussionContribution['id'];
                        ?>"
                        target="_blank"
                    >
                        <?=$this->discussionContribution->body;?>
                        <?=$this->discussionContribution->body;?>
                    </a>
                </p>
                <small><?=$this->formatDate($this->discussionContribution['time_created']);?></small>
            </blockquote>
            <?=$this->form;?>

        </div>
    </div>
</div><!-- .main-content -->
