<?php
$this->layout()->pageTitle = $this->pageTitle(
    Application_View_Helper_PageTitle::STATIC_PAGE,
    $this->translate('Unsubscribe')
);
?>
<div class="main-content">
    <div class="row">
        <div class="content content-narrow content-offset">

            <h1><?=$this->translate('Unsubscribe');?></h1>
            <?=$this->form;?>

        </div>
    </div><!-- .row -->
</div><!-- .main-content -->
