<section class="section-header">
    <div class="container">
        <div class="row">
            <div class="col-sm-8">
                <h1><?=$this->translate('Consultations');?></h1>
            </div>
            <div class="col-sm-4">
                <a href="<?=$this->url(['controller' => 'consultation', 'action' => 'new']);?>" class="cta btn btn-primary">
                    <span class="glyphicon glyphicon-plus-sign"></span> <?=$this->translate('New Consultation');?>
                </a>
            </div>
        </div>
    </div>
</section>
<section class="section-content">
    <div class="container">

        <!-- Consultations -->
        <?php if (!empty($this->consultations)): ?>
            <?php foreach ($this->consultations as $kid => $consultation): ?>

                <div class="panel panel-primary">
                    <div class="panel-heading panel-heading-extended">
                        <a href="<?=$this->url(['controller' => 'consultation', 'action' => 'edit', 'kid' => $kid]);?>" class="panel-action" title="<?=$this->translate('Consultation settings');?>">
                            <span class="glyphicon glyphicon-cog"></span>
                        </a>
                        <a href="<?=$this->url(['controller' => 'consultation', 'action' => 'index', 'kid' => $kid]);?>">
                            <h2 class="panel-title panel-title-big"><?=$consultation['titl'];?></h2>
                            <h3 class="panel-title panel-title-subtitle"><?=$consultation['titl_sub'];?></h3>
                        </a>
                    </div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-md-3">

                                <img
                                    src="<?=$this->baseUrl();?>/media/<?=Service_Media::MEDIA_DIR_CONSULTATIONS?>/<?=$kid . '/' . $consultation['img_file'];?>"
                                    class="img-responsive img-thumbnail offset-bottom"
                                    alt="<?=$consultation['img_expl'];?>"
                                    />

                                <ul class="nav nav-pills nav-stacked">
                                    <li><a href="<?=$this->url(['controller' => 'article', 'kid' => $kid]);?>"><?=$this->translate('Info');?></a></li>
                                    <li><a href="<?=$this->url(['controller' => 'question', 'kid' => $kid]);?>"><?=$this->translate('Questions');?></a></li>
                                    <li><a href="<?=$this->url(['controller' => 'input', 'kid' => $kid]);?>"><?=$this->translate('Contributions');?></a></li>
                                    <li><a href="<?=$this->url(['controller' => 'votingprepare', 'kid' => $kid]);?>"><?=$this->translate('Voting');?></a></li>
                                    <li><a href="<?=$this->url(['controller' => 'followup', 'kid' => $kid]);?>"><?=$this->translate('Follow Up');?></a></li>
                                </ul>

                            </div>
                            <form method="<?=$this->form->getMethod();?>">
                                <?=$this->form->getElement($this->form->getCsrfTokenName());?>
                                <div class="col-md-5">
                                    <h4><?=$this->translate('Latest Contributions');?></h4>
                                    <?php if (count($consultation['inputs'])): ?>
                                        <div class="overflow-vertical offset-bottom">
                                            <div class="overflow-vertical-inner">
                                                <?php foreach ($consultation['inputs'] as $input): ?>
                                                    <blockquote>

                                                        <div class="media">
                                                            <div class="media-right pull-right">
                                                                <button
                                                                    class="item-action item-action-danger"
                                                                    name="deleteInput"
                                                                    value="<?=$input['tid'];?>"
                                                                    data-toggle="confirm"
                                                                    data-confirm-message="<?=$this->translate('Delete contribution?');?>"
                                                                    title="<?=$this->translate('Delete');?>"
                                                                    >
                                                                    <span class="glyphicon glyphicon-remove-sign"></span>
                                                                </button>
                                                            </div>
                                                            <div class="media-body">
                                                                <a href="<?=$this->url(['controller' => 'input', 'action' => 'edit', 'kid' => $kid, 'qid' => $input['qi'], 'tid' => $input['tid'], 'uid' => $input['uid']]);?>">
                                                                    <p>
                                                                        <?=$input['thes'];?>
                                                                    </p>
                                                                </a>
                                                            </div>
                                                        </div><!-- .media -->

                                                        <footer>
                                                            <?php if (!empty($input['name'])): ?>
                                                                <span class="glyphicon glyphicon-user"></span>
                                                                <a
                                                                    href="<?=$this->url(['controller' => 'input', 'action' => 'list-by-user', 'uid' => $input['uid'], 'kid' => $kid]);?>"
                                                                    title="<?=$this->translate('Show contributions by');?> <?=$input['name'];?>"
                                                                    >
                                                                    <?=$input['name'];?>
                                                                </a>,
                                                            <?php endif; ?>
                                                            <?=$this->formatDate($input['when']);?>
                                                        </footer>

                                                    </blockquote>
                                                <?php endforeach;?>
                                            </div>
                                        </div>
                                        <p>
                                            <a href="<?=$this->url(['controller' => 'input', 'action' => 'index', 'kid' => $kid]);?>">
                                                <?=$this->translate('Show all contributions');?> &rarr;
                                            </a>
                                        </p>
                                    <?php else: ?>
                                        <p>
                                            <span class="glyphicon glyphicon-info-sign"></span>
                                            <?=$this->translate('No contributions yet.');?>
                                        </p>
                                    <?php endif; ?>

                                </div>
                                <div class="col-md-4">

                                    <h4><?=$this->translate('Latest Discussion Posts');?></h4>
                                    <?php if (count($consultation['discussionContribs'])): ?>
                                        <div class="overflow-vertical offset-bottom">
                                            <div class="overflow-vertical-inner">
                                                <?php foreach($consultation['discussionContribs'] as $contrib): ?>
                                                    <blockquote>

                                                        <div class="media">
                                                            <div class="media-right pull-right">
                                                                <button
                                                                    class="item-action item-action-danger"
                                                                    name="deleteDiscContrib"
                                                                    value="<?=$contrib->id;?>"
                                                                    data-toggle="confirm"
                                                                    data-confirm-message="<?=$this->translate('Delete discussion post?');?>"
                                                                    title="<?=$this->translate('Delete');?>"
                                                                    >
                                                                    <span class="glyphicon glyphicon-remove-sign"></span>
                                                                </button>
                                                            </div>
                                                            <div class="media-body">
                                                                <a href="<?=$this->baseUrl()?>/admin/input-discussion/index/kid/<?=$kid;?>/inputId/<?=$this->escape($contrib->input_id);?>#<?=$this->escape($contrib->id);?>">
                                                                    <?=$this->escape($contrib->body);?>
                                                                </a>
                                                            </div>
                                                        </div><!-- .media -->

                                                        <footer>
                                                            <?php if (!empty($contrib['name'])): ?>
                                                                <span class="glyphicon glyphicon-user"></span>
                                                                <?=$contrib['name'];?>,
                                                            <?php endif; ?>
                                                            <?=$this->formatDate($contrib->time_created);?>
                                                        </footer>

                                                    </blockquote>
                                                <?php endforeach;?>
                                            </div>
                                        </div>
                                        <a href="<?=$this->url(['controller' => 'consultation', 'kid' => $kid]);?>">
                                            <?=$this->translate('Show all discussion posts');?> &rarr;
                                        </a>
                                    <?php else: ?>
                                        <p>
                                            <span class="glyphicon glyphicon-info-sign"></span>
                                            <?=$this->translate('No posts yet.');?>
                                        </p>
                                    <?php endif;?>

                                </div>
                            </form>
                        </div><!-- .row -->

                    </div>
                </div><!-- .panel -->

            <?php endforeach; ?>
        <?php else: ?>
            <p class="alert alert-info">
                <span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>
                <?=$this->translate('There are no consultations yet.');?>
            </p>
        <?php endif; ?>

    </div>
</section>
