<section class="section-header">
    <div class="container">

        <h1 class="section-header-title"><?php //$this->consultation->titl;?></h1>
        <h2 class="section-header-subtitle"><?php //$this->consultation->titl_sub;?></h2>

        <?php //$this->consultationTabs($this->consultation->kid, 'settings');?>

    </div>
</section>
<section class="section-content">
    <div class="container">
        <div class="row">
            <div class="sidebar offset-bottom-large-sm-max">

                <?php //$this->consultationEditNavigation($this->consultation->kid, 'settings');?>

            </div>
            <div class="content">

                    <?=$this->render('_partials/close/closenavigation.phtml');?>

            </div>
        </div><!-- .row -->
    </div><!-- .container -->
</section>
