<div class="main-content">
    <?=$this->partial('_partials/userMenu.phtml', ['page' => 'activity']);?>
    <div class="row offset-top offset-bottom">
        <div class="col-md-6 offset-bottom-xs-max">

            <h2 class="h1"><?=$this->translate('My Contributions');?></h2>
            <?php $contributionsListCount = count($this->contributionsList); $i = 1; ?>
            <?php if (!empty($this->contributionsList)): ?>
                <?php foreach ($this->contributionsList as $contribution): ?>
                    <p>
                        <?=$contribution['thes'];?>
                    </p>
                    <p class="text-right">
                        <?=$this->formatDate($contribution['when'], 'd. M. Y H:m:s');?>
                        in
                        <a
                            href="<?=$this->url(['cl' => null, 'pl' => null, 'controller' => 'article', 'action' => 'show', 'kid' => $contribution['kid']]);?>"
                        >
                            <?=$contribution['titl'];?>
                        </a>
                    </p>
                    <hr />
                    <?php if ($contributionsListCount == $i++ && $this->contributionsSum > $this->contributionsLimit): ?>
                        <a href="<?=$this->url(['cl' => $this->contributionsLimit + $this->step]);?>" class='btn btn-lg btn-default offset-bottom'>Load More</a>
                    <?php endif; ?>
                <?php endforeach; ?>
            <?php else: ?>
                <p class="alert alert-info">
                    <span class="glyphicon glyphicon-info-sign icon-offset" aria-hidden="true"></span>
                    <?=$this->translate("You have no confirmed contributions");?>
                </p>
            <?php endif; ?>

        </div>
        <div class="col-md-6">

            <h2 class="h1"><?=$this->translate('My Discussion Posts');?></h2>
            <?php $postsListCount = count($this->postsList); $i = 1; ?>
            <?php if (!empty($this->postsList)): ?>
                <?php foreach ($this->postsList as $post): ?>
                    <p>
                        <a
                            href="<?=$this->url(['cl' => null, 'pl' => null, 'controller' => 'input', 'action' => 'discussion', 'kid' => $post['kid'], 'qid' => $post['qi'], 'inputId' => $post['tid']]);?>#post-<?=$post['id'];?>"
                        >
                            <?=$post['body'];?>
                        </a>
                    </p>
                    <p class="text-right">
                        <?=$this->formatDate($post['time_created'], 'd. M. Y H:m');?> in
                        in
                        <a
                            href="<?=$this->url(['cl' => null, 'pl' => null, 'controller' => 'article', 'action' => 'show', 'kid' => $post['kid']]);?>"
                        >
                            <?=$post['titl'];?>
                        </a>
                        -
                        <a
                            href="<?=$this->url(['cl' => null, 'pl' => null, 'controller' => 'input', 'action' => 'show', 'kid' => $post['kid'], 'qid' => $post['qi']]);?>"
                        >
                            <?=$post['q'];?>
                        </a>
                    </p>
                    <hr />

                    <?php if ($postsListCount == $i++ && $this->postsSum > $this->postsLimit): ?>
                        <a href="<?=$this->url(['pl' => $this->postsLimit + $this->step]);?>" class='btn btn-lg btn-default offset-bottom'>Load More</a>
                    <?php endif; ?>
                <?php endforeach; ?>
            <?php else: ?>
                <p class="alert alert-info">
                    <span class="glyphicon glyphicon-info-sign icon-offset" aria-hidden="true"></span>
                    <?=$this->translate("You have no confirmed discussion posts");?>
                </p>
            <?php endif; ?>

        </div>
    </div>
    <?=$this->partial('_partials/pageLinks.phtml');?>
</div><!-- .main-content -->
