<div class="main-content">
    <?=$this->partial('_partials/userMenu.phtml', ['page' => 'activity']);?>
    <div class="row offset-top offset-bottom">
        <div class="col-md-6 offset-bottom-xs-max">

            <h2 class="h1"><?=$this->translate('My Contributions');?></h2>
            <?php $contributionsListCount = count($this->contributionsList);?>
            <?php $i = 1;?>
            <?php if (!empty($this->contributionsList)): ?>
                <?php foreach ($this->contributionsList as $contribution): ?>
                    <?php if ($contribution['location_enabled'] && $contribution['latitude'] !== null): ?>
                        <div class="row offset-bottom">
                            <div class="col-sm-9">
                    <?php endif; ?>

                    <p>
                        <a
                            href="<?=$this->url([
                                'controller' => 'input',
                                'action' => 'edit',
                                'kid' => $contribution['kid'],
                                'tid' => $contribution['tid'],
                            ], null, true);?>"
                            title="<?=$this->translate('Edit');?>"
                        >
                            <span class="glyphicon glyphicon-pencil"></span>
                            <?=$this->escape($contribution['thes']);?>
                        </a>
                    </p>

                    <?php if ($contribution['location_enabled'] && $contribution['latitude'] !== null): ?>
                            </div>
                            <div class="col-sm-3">
                                <div class="map-static map-static-small map-static-right-sm">
                                    <?=$this->openStreetStaticMap(
                                        $contribution['latitude'],
                                        $contribution['longitude'],
                                        90,
                                        90,
                                        12
                                    );?>
                                </div>
                            </div>
                        </div>
                    <?php endif; ?>

                    <p class="text-right">
                        <?=$this->formatDate($contribution['when'], 'd. M. Y H:m:s');?>
                        <?=$this->translate('in');?>
                        <a
                            href="<?=$this->url(['cl' => null, 'pl' => null, 'controller' => 'article', 'action' => 'show', 'kid' => $contribution['kid']]);?>"
                        >
                            <?=$contribution['titl'];?>
                        </a>
                    </p>
                    <hr />

                    <?php if ($contributionsListCount == $i++ && $this->contributionsSum > $this->contributionsLimit): ?>
                        <a href="<?=$this->url(['cl' => $this->contributionsLimit + $this->step]);?>" class='btn btn-lg btn-default offset-bottom'>
                            <?=$this->translate('Load More');?>
                        </a>
                    <?php endif; ?>
                <?php endforeach; ?>
            <?php else: ?>
                <p class="alert alert-info">
                    <span class="glyphicon glyphicon-info-sign icon-offset" aria-hidden="true"></span>
                    <?=$this->translate('You have no confirmed contributions.');?>
                </p>
            <?php endif; ?>

        </div>
        <div class="col-md-6">

            <h2 class="h1"><?=$this->translate('My Discussion Posts');?></h2>
            <?php $postsListCount = count($this->postsList);?>
            <?php $i = 1;?>
            <?php if (!empty($this->postsList)): ?>
                <?php foreach ($this->postsList as $post): ?>
                    <p>
                        <a
                            href="<?=$this->url(['cl' => null, 'pl' => null, 'controller' => 'input', 'action' => 'discussion', 'kid' => $post['kid'], 'qid' => $post['qi'], 'inputId' => $post['tid']]);?>#post-<?=$post['id'];?>"
                        >
                            <?=$post['body'];?>
                        </a>
                    </p>
                    <p class="text-right">
                        <?=$this->formatDate($post['time_created'], 'd. M. Y H:m');?> in
                        in
                        <a
                            href="<?=$this->url(['cl' => null, 'pl' => null, 'controller' => 'article', 'action' => 'show', 'kid' => $post['kid']]);?>"
                        >
                            <?=$post['titl'];?>
                        </a>
                        -
                        <a
                            href="<?=$this->url(['cl' => null, 'pl' => null, 'controller' => 'input', 'action' => 'show', 'kid' => $post['kid'], 'qid' => $post['qi']]);?>"
                        >
                            <?=$post['q'];?>
                        </a>
                    </p>
                    <hr />

                    <?php if ($postsListCount == $i++ && $this->postsSum > $this->postsLimit): ?>
                        <a href="<?=$this->url(['pl' => $this->postsLimit + $this->step]);?>" class='btn btn-lg btn-default offset-bottom'>
                            <?=$this->translate('Load More');?>
                        </a>
                    <?php endif; ?>
                <?php endforeach; ?>
            <?php else: ?>
                <p class="alert alert-info">
                    <span class="glyphicon glyphicon-info-sign icon-offset" aria-hidden="true"></span>
                    <?=$this->translate('You have no confirmed discussion posts.');?>
                </p>
            <?php endif; ?>

        </div>
    </div>
    <?=$this->partial('_partials/pageLinks.phtml');?>
</div><!-- .main-content -->
