<div class="main-content">
    <?=$this->partial('_partials/userMenu.phtml', ['page' => 'activity']);?>
    <div class="row">
            <div class="col-sm-6">
                <h1><?=$this->translate('My Contributions');?></h1>
                <?php if (!empty($this->contributionsList)): ?>
                    <?php foreach ($this->contributionsList as $i => $contribution): ?>
                        <p id="contribution-link-<?=$i;?>">
                            <?=$contribution['thes'];?><br />
                            <?=$this->formatDate($contribution['when'], 'd. M. Y H:m:s');?> in
                            <a href="<?=$this->url(['cl' => null, 'pl' => null, 'controller' => 'article', 'action' => 'show', 'kid' => $contribution['kid']]);?>">
                                <?=$contribution['titl'];?>
                            </a>
                        </p>
                    <?php endforeach;?>
                    <?php if ($this->contributionsSum > $this->contributionsLimit): ?>
                        <a
                            href="<?=$this->url(['cl' => $this->contributionsLimit + $this->step]);?>#contribution-link-<?=$this->contributionsLimit;?>"
                            class='btn btn-lg btn-default'
                        >
                            <?=$this->translate('Load More');?>
                        </a>
                    <?php endif; ?>
                <?php else: ?>
                <p class="alert alert-info">
                    <span class="glyphicon glyphicon-info-sign icon-offset" aria-hidden="true"></span>
                    <?=$this->translate("You have no confirmed contributions");?>
                </p>
                <?php endif; ?>
            </div>

            <div class="col-sm-6">
                <h1><?=$this->translate('My Discussion Posts');?></h1>
                <?php if (!empty($this->postsList)): ?>
                    <?php foreach ($this->postsList as $i => $post): ?>
                        <p id="discussion-link-<?=$i;?>">
                            <a href="<?=$this->url(['cl' => null, 'pl' => null, 'controller' => 'input', 'action' => 'discussion', 'kid' => $post['kid'], 'qid' => $post['qi'], 'inputId' => $post['tid']]);?>#post-<?=$post['id'];?>">
                                <?=$post['body'];?>
                            </a>
                            <br />
                            <?=$this->formatDate($post['time_created'], 'd. M. Y H:m');?> in
                            <a href="<?=$this->url(['cl' => null, 'pl' => null, 'controller' => 'article', 'action' => 'show', 'kid' => $post['kid']]);?>">
                                <?=$post['titl'];?>
                            </a>
                            -
                            <a href="<?=$this->url(['cl' => null, 'pl' => null, 'controller' => 'input', 'action' => 'show', 'kid' => $post['kid'], 'qid' => $post['qi']]);?>">
                                <?=$post['q'];?>
                            </a>
                        </p>
                    <?php endforeach; ?>
                    <?php if ($this->postsSum > $this->postsLimit): ?>
                        <a
                            href="<?=$this->url(['pl' => $this->postsLimit + $this->step]);?>#discussion-link-<?=$this->postsLimit;?>"
                            class='btn btn-lg btn-default'
                        >
                            <?=$this->translate('Load More');?>
                        </a>
                    <?php endif; ?>
                <?php else: ?>
                <p class="alert alert-info">
                    <span class="glyphicon glyphicon-info-sign icon-offset" aria-hidden="true"></span>
                    <?=$this->translate("You have no confirmed discussion posts");?>
                </p>
                <?php endif; ?>
            </div>

    <?=$this->partial('_partials/pageLinks.phtml');?>
    </div>
</div><!-- .main-content -->
