<div class="main-content">
    <div class="row">
        <div class="content content-narrow content-offset">

            <h1><?=$this->translate('All my contributions');?></h1>

            <?php if (isset($this->consultationList)): ?>

                <p><?=$this->translate('There are contributions in the following participation rounds:');?></p>

                <?php if (!empty($this->consultationList)): ?>
                    <ul>
                        <?php foreach ($this->consultationList as $consultation): ?>
                            <li>
                                <h2>
                                    <a
                                        href="<?=$this->url(['kid' => $consultation['kid']]);?>"
                                        title="<?=$this->translate('Show my contributions to this participation round');?>"
                                    >
                                        <?=$consultation['titl'];?>
                                    </a>
                                </h2>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                <?php else: ?>
                    <p class="alert alert-info">
                        <span class="glyphicon glyphicon-info-sign icon-offset" aria-hidden="true"></span>
                        <?=$this->translate("You haven't contributed yet.");?>
                    </p>
                <?php endif; ?>

            <?php elseif (isset($this->consultation)): ?>

                <h2 class="page-header">
                    <?=$this->translate('Consultation round:');?>
                    <?=$this->consultation->titl;?>
                </h2>

                <?php if (!empty($this->inputs)): ?>
                    <?php foreach ($this->inputs as $question): ?>

                        <h3>
                            <?=$this->translate('Question:');?>
                            <a href="<?=$this->url(['controller' => 'input', 'action' => 'show', 'kid' => $this->consultation->kid, 'qid' => $question['qi']], 'default', true);?>">
                                <?=$question['q'];?>
                            </a>
                        </h3>

                        <?php if (!empty($question['inputs'])): ?>
                            <h4><?=$this->translate('Contributions:');?></h4>
                            <ul class="offset-bottom">
                                <?php foreach ($question['inputs'] as $input): ?>
                                    <li>
                                        <a
                                            href="<?=$this->url(['controller' => 'input', 'action' => 'edit', 'kid' => $this->consultation->kid, 'tid' => $input['tid']]);?>"
                                            title="<?=$this->translate('Click to edit');?>"
                                        >
                                            <p><?=$input['thes'];?></p>
                                        </a>
                                        <?php if (!empty($input['expl'])): ?>
                                            <p class="small"><?=$input['expl'];?></p>
                                        <?php endif; ?>
                                    </li>
                                <?php endforeach; ?>
                            </ul>
                            <hr />
                        <?php else: ?>
                            <p>
                                <span class="glyphicon glyphicon-info-sign icon-offset text-info" aria-hidden="true"></span>
                                <?=$this->translate('No contributions for this question.');?>
                            </p>
                        <?php endif; ?>

                    <?php endforeach; ?>
                <?php endif; ?>

            <?php endif; ?>

        </div>
    </div><!-- .row -->

    <?=$this->partial('_partials/pageLinks.phtml');?>

</div><!-- .main-content -->
