<div class="main-content content-holder">
    <div class="row">
        <div class="span9">

            <h1><?=$this->translate('Alle meine Beiträge')?></h1>

            <?php if (isset($this->consultationList)): ?>
                <p><?=$this->translate('Zu folgenden Beteiligungsrunden wurden Beiträge abgegeben:')?></p>
                <ul>
                <?php foreach ($this->consultationList as $consultation): ?>
                    <li>
                        <h2>
                            <a
                                href="<?=$this->url(['kid' => $consultation['kid']])?>"
                                title="<?=$this->translate('Zeige meine Beiträge zu dieser Beteiligungsrunde')?>">
                                   <?php echo $consultation['titl']; ?>
                            </a>
                        </h2>
                    </li>
                <?php endforeach; ?>
                </ul>

            <?php elseif (isset($this->consultation)): ?>
                <h2>Beteiligungsrunde: <?php echo $this->consultation->titl; ?></h2>
                <?php if (!empty($this->inputs)): ?>
                    <?php foreach ($this->inputs as $question): ?>
                        <h3>
                            <?=$this->translate('Frage:')?>
                            <a href="<?=$this->url(
                                [
                                    'controller' => 'input',
                                    'action' => 'show',
                                    'kid' => $this->consultation->kid,
                                    'qid' => $question['qi']
                                ],
                                'default',
                                true
                            )?>">
                                <?php echo $question['q']; ?>
                            </a>
                        </h3>
                        <?php if (!empty($question['inputs'])): ?>
                            <h4><?=$this->translate('Beiträge:')?></h4>
                            <ul>
                                <?php foreach ($question['inputs'] as $input): ?>
                                    <li>
                                        <a
                                            href="<?=$this->url(
                                                array(
                                                    'controller' => 'input',
                                                    'action' => 'edit',
                                                    'kid' => $this->consultation->kid,
                                                    'tid' => $input['tid']
                                                )
                                            )?>"
                                            title="<?=$this->translate('Klicken zum Bearbeiten')?>"
                                        >
                                            <strong><?php echo $input['thes']; ?></strong>
                                        </a>
                                        <?php if (!empty($input['expl'])): ?>
                                            <p><?php echo $input['expl']; ?></p>
                                        <?php endif; ?>
                                    </li>
                                <?php endforeach; ?>
                            </ul>
                        <?php else: ?>
                            <p><?=$this->translate('Keine Beiträge')?></p>
                        <?php endif; ?>
                    <?php endforeach; ?>
                <?php endif; ?>
            <?php endif; ?>

            <?php echo $this->render('_partials/printLink.phtml') ?>
        </div>
    </div><!-- .row -->
</div><!-- .content-holder -->

<?php echo $this->render('_partials/topLink.phtml') ?>
