<div class="main-content">
    <?=$this->partial('_partials/userMenu.phtml', ['page' => 'notifications']);?>
    <form method="<?=$this->form->getMethod();?>" action="<?=$this->url(['action' => 'notifications']);?>">
        <?=$this->form->getElement($this->form->getCsrfTokenName());?>
        <div class="row offset-bottom">
            <div class="content content-narrow content-offset">

                <h2 class="h1"><?=$this->translate('Contribution Discussion');?></h2>
                <p>
                    <?=$this->translate('Send me an update when someone adds new discussion post');?>.
                </p>
                <hr />

                <?php
                if (count($this->contributionDiscussion) > 0) :
                    foreach ($this->contributionDiscussion as $cd) : ?>
                        <div class="row">
                            <div class="col-sm-9 offset-bottom-xs-max">
                                <?=$this->translate('Contribution in');?>:
                                <a href="<?=$this->url(['controller' => 'article', 'action' => 'show', 'kid' => $cd['kid'], 'qid' => $cd['qi']]);?>">
                                    <?=$cd['nr'];?>
                                    <?=$cd['q'];?>
                                </a>
                                <br />
                                <?=$this->translate('Consultation');?>:
                                <a href="<?=$this->url(['controller' => 'input', 'action' => 'show', 'kid' => $cd['kid'], 'qid' => $cd['qi']]);?>#contribution-<?=$cd['tid']?>">
                                    <?=$cd['titl'];?>
                                </a>
                            </div>
                            <div class="col-sm-3 text-right">
                                <button
                                    value="<?=$cd->id;?>"
                                    class="btn btn-danger btn-sm"
                                    name="unsubscribe-cd"
                                    data-toggle="confirm"
                                    data-confirm-message="<?=$this->translate('Unsubscribe from Contribution Discussion?');?>"
                                >
                                    <?=$this->translate('Unsubscribe');?>
                                </button>
                            </div>
                        </div>
                        <hr />
                    <?php
                    endforeach;
                else :
                ?>
                <p>
                    <span class="glyphicon glyphicon-info-sign text-info offset-right" aria-hidden="true"></span>
                    <?=$this->translate('You are not subscribed to any notifications.');?>
                </p>
            <?php
                endif; ?>

            </div>
        </div><!-- .row -->
        <div class="row offset-bottom">
            <div class="content content-narrow content-offset">

                <h2 class="h1"><?=$this->translate('Questions');?></h2>
                <p>
                    <?=$this->translate('Sends notification when new contribution to particular questions is made');?>.
                </p>
                <hr />

                <?php
                if (count($this->questions) > 0) :
                    foreach ($this->questions as $q) : ?>
                        <div class="row">
                            <div class="col-sm-9 offset-bottom-xs-max">
                                <?=$this->translate('Contribution in');?>:
                                <a href="<?=$this->url(['controller' => 'input', 'action' => 'show', 'kid' => $q['kid'], 'qid' => $q['qi']]);?>">
                                    <?=$q['nr'];?>
                                    <?=$q['q'];?>
                                </a>
                                <br />
                                <?=$this->translate('Consultation');?>:
                                <a href="<?=$this->url(['controller' => 'article', 'action' => 'show', 'kid' => $q['kid'], 'qid' => $q['qi']]);?>">
                                    <?=$q->titl;?>
                                </a>
                            </div>
                            <div class="col-sm-3 text-right">
                                <button
                                    value="<?=$q->id;?>"
                                    class="btn btn-danger btn-sm"
                                    name="unsubscribe-q"
                                    data-toggle="confirm"
                                    data-confirm-message="<?=$this->translate('Unsubscribe from Question?');?>"
                                >
                                    <?=$this->translate('Unsubscribe');?>
                                </button>
                            </div>
                        </div>
                        <hr />
                <?php
                    endforeach;
                else : ?>
                    <p>
                        <span class="glyphicon glyphicon-info-sign text-info offset-right" aria-hidden="true"></span>
                        <?=$this->translate('You are not subscribed to any notifications.');?>
                    </p>
                <?php
                endif; ?>


            </div>
        </div><!-- .row -->
        <div class="row offset-bottom">
            <div class="content content-narrow content-offset">

                <h2 class="h1"><?=$this->translate('Reactions & Impact');?></h2>
                <p>
                    <?=$this->translate('When new document is added');?>.
                </p>
                <hr />

                <?php
                if (count($this->followups) > 0) :
                    foreach ($this->followups as $fu) : ?>
                        <div class="row">
                            <div class="col-sm-9 offset-bottom-xs-max">
                                <a href="<?=$this->url(['controller' => 'followup', 'action' => 'index', 'kid' => $fu['kid']]);?>">
                                    <?=$fu->ffid_titl;?>
                                </a>
                            </div>
                            <div class="col-sm-3 text-right">
                                <button
                                    value="<?= $fu->id; ?>"
                                    class="btn btn-danger btn-sm"
                                    name="unsubscribe-fu"
                                    data-toggle="confirm"
                                    data-confirm-message="<?= $this->translate('Unsubscribe from follow-up?'); ?>"
                                >
                                    <?= $this->translate('Unsubscribe'); ?>
                                </button>
                            </div>
                        </div>
                        <hr />
                        <?php
                    endforeach;
                else :
                ?>
                    <p>
                        <span class="glyphicon glyphicon-info-sign text-info offset-right" aria-hidden="true"></span>
                        <?=$this->translate('You are not subscribed to any notifications.');?>
                    </p>
                <?php
                endif; ?>
            </div>
        </div><!-- .row -->
    </form>
    <?=$this->partial('_partials/pageLinks.phtml');?>
</div><!-- .main-content -->
