<div class="main-content">
    <form method="<?=$this->form->getMethod();?>" action="<?=$this->url(['action' => 'notifications']);?>">
        <?=$this->form->getElement($this->form->getCsrfTokenName());?>
        <div class="row">
            <div class="content content-narrow content-offset">

                <h1><?=$this->translate('Contribution Discussion');?></h1>
                <p>
                    <?=$this->translate('Send me an update when someone adds new discussion post');?>
                </p>
                <hr />

                <?php
                if (count($this->contributionDiscussion) > 0) :
                    foreach ($this->contributionDiscussion as $cd) : ?>
                        <div class="row">
                            <div class="col-sm-9">
                                Contribution: <a href="<?=$this->url(['controller' => 'input', 'action' => 'show', 'kid' => $cd['kid'], 'qid' => $cd['qi']]);?>#contribution-<?=$cd['tid']?>"><?=$cd['titl'];?></a> In
                                <a href="<?=$this->url(['controller' => 'article', 'action' => 'show', 'kid' => $cd['kid'], 'qid' => $cd['qi']]);?>"><?=$cd->q;?></a>
                            </div>
                            <div class="col-sm-3 text-right">
                                <button
                                    value="<?=$cd->id;?>"
                                    class="btn btn-danger btn-sm"
                                    name="unsubscribe-cd"
                                    data-toggle="confirm"
                                    data-confirm-message="<?=$this->translate('Unsubscribe from Contribution Discussion?');?>"
                                >
                                    <?=$this->translate('Unsubscribe');?>
                                </button>
                            </div>
                        </div>
                        <hr />
                    <?php
                    endforeach;
                else :
                ?>
                <p>
                    <span class="glyphicon glyphicon-info-sign text-info offset-right" aria-hidden="true"></span>
                    You are subscribed to no notifications
                </p>
            <?php
                endif; ?>

            </div>
        </div><!-- .row -->
        <div class="row">
            <div class="content content-narrow content-offset">

                <h1><?=$this->translate('Questions');?></h1>
                <p>
                    <?=$this->translate('Sends notification when new contribution to particular questions is made');?>
                </p>
                <hr />
                
                <?php
                if (count($this->questions) > 0) :
                    foreach ($this->questions as $q) : ?>
                        <div class="row">
                            <div class="col-sm-9">
                                Contribution: <a href="<?=$this->url(['controller' => 'input', 'action' => 'show', 'kid' => $q['kid'], 'qid' => $q['qi']]);?>"><?=$q->q;?></a> In
                                <a href="<?=$this->url(['controller' => 'article', 'action' => 'show', 'kid' => $q['kid'], 'qid' => $q['qi']]);?>"><?=$q->titl;?></a>
                            </div>
                            <div class="col-sm-3 text-right">
                                <button
                                    value="<?=$q->id;?>"
                                    class="btn btn-danger btn-sm"
                                    name="unsubscribe-q"
                                    data-toggle="confirm"
                                    data-confirm-message="<?=$this->translate('Unsubscribe from Question?');?>"
                                >
                                    <?=$this->translate('Unsubscribe');?>
                                </button>
                            </div>
                        </div>
                        <hr />
                <?php
                    endforeach;
                else : ?>
                    <p>
                        <span class="glyphicon glyphicon-info-sign text-info offset-right" aria-hidden="true"></span>
                        You are subscribed to no notifications
                    </p>
                <?php
                endif; ?>


            </div>
        </div><!-- .row -->
        <div class="row">
            <div class="content content-narrow content-offset">

                <h1><?=$this->translate('Reactions & Impact');?></h1>
                <p>
                    <?=$this->translate('When new document is added');?>
                </p>
                <hr />

                <?php
                if (count($this->followups) > 0) :
                    foreach ($this->followups as $fu) : ?>
                        <div class="row">
                            <div class="col-sm-9">
                                Contribution: <a href="<?=$this->url(['controller' => 'followup', 'action' => 'index', 'kid' => $fu['kid']]);?>"><?=$fu->ffid_titl;?></a>
                            </div>
                            <div class="col-sm-3 text-right">
                                <button
                                    value="<?= $fu->id; ?>"
                                    class="btn btn-danger btn-sm"
                                    name="unsubscribe-fu"
                                    data-toggle="confirm"
                                    data-confirm-message="<?= $this->translate('Unsubscribe from Followup?'); ?>"
                                >
                                    <?= $this->translate('Unsubscribe'); ?>
                                </button>
                            </div>
                        </div>
                        <hr />
                        <?php
                    endforeach;
                else :
                ?>
                    <p>
                        <span class="glyphicon glyphicon-info-sign text-info offset-right" aria-hidden="true"></span>
                        You are subscribed to no notifications
                    </p>
                <?php
                endif; ?>
            </div>
        </div><!-- .row -->
    </form>
</div><!-- .main-content -->
