<div class="main-content">
    <div class="row">
        <div class="content content-narrow content-offset">

            <h1><?=$this->translate('Forgot password?');?></h1>
            <p>
                <?=$this->translate('You can reset your password by entering your mail address here. In a few moments you will receive an e-mail, which will help you to choose a new password.');?>
            </p>

            <?=$this->form;?>

        </div>
    </div><!-- .row -->
</div><!-- .main-content -->
