<div class="main-content content-holder">
    <div class="row">
        <div class="span9">

            <h1><?=$this->translate('Passwort vergessen?')?></h1>
            <p>
                <?=$this->translate('Du kannst dein Passwort zurücksetzen, wenn du hier deine hinterlegte E-Mail-Adresse einträgst. Du bekommst dann umgehend eine E-Mail, mit Hilfe derer du dir ein neues Passwort aussuchen kannst.')?>
            </p>

            <?php echo $this->form; ?>
        </div>
    </div><!-- .row -->
</div><!-- .content-holder -->

<?php echo $this->render('_partials/topLink.phtml') ?>
