<div class="main-content">
    <?=$this->partial('_partials/userMenu.phtml', ['page' => 'profile']);?>
    <div class="row offset-top offset-bottom">
        <div class="content content-narrow content-offset">

            <h2 class="h1"><?=$this->translate('Profile');?></h2>
            <hr />

            <?=$this->form;?>

        </div>
    </div><!-- .row -->

    <?=$this->partial('_partials/pageLinks.phtml');?>

</div><!-- .main-content -->
