<?php
 $memberships = array(
  'y' => 'bestätigt',
  'n' => 'abgelehnt',
  'u' => '--offen--',
);
?>

<script type="text/javascript">
    $(document).ready(function() {
        $(document).on("click",".useraction", function (event) {
            event.preventDefault();
            var subUser= $(this).attr('data');
            var action = $(this).attr('rel');
            var uidArray = subUser.split('/');

            $.ajax({
                url: "/user/"+action+"/kid/<?=isset($this->consultation->kid) ? $this->escape($this->consultation->kid) : ''?>/"+subUser+"",
                type: "POST",
                data: "format=html",
                cache: false,
                async: "true",
                error: function(){
                    document.getElementById('ua-'+uidArray[3]).innerHTML = "<?=$this->translate('Es ist ein Fehler aufgetreten!')?>";
                },
                beforeSend: function(){
                    document.getElementById('ua-'+uidArray[3]).innerHTML = "<?=$this->translate('Bitte warten .... !')?>";
                },
                success:function(response){
                    document.getElementById('ua-'+uidArray[3]).innerHTML = response ;
                    if(action== 'deny') {
                        document.getElementById('ms-'+uidArray[3]).innerHTML = "<?=$this->translate('abgelehnt')?>";
                    }
                    else if(action== 'confirm') {
                        document.getElementById('ms-'+uidArray[3]).innerHTML = "<?=$this->translate('bestätigt')?>";
                    }
                    else if(action=='delete') {
                        document.getElementById('ms-'+uidArray[3]).innerHTML = "<?=$this->translate('gelöscht')?>";
                    }
                }
            });
        });
    });
</script>

<div class="main-content content-holder">
    <div class="row">
        <div class="span9">
            <h1><?=$this->translate('Teilnehmende Gruppenmitglieder')?></h1>
            <?php if (empty($this->consultationList) && !isset($this->consultation)): ?>
                <p><?=$this->translate('Es wurden in keiner Beteiligungsrunde Gruppenmitglieder gefunden.')?></p>
            <?php endif; ?>

            <?php if (!empty($this->consultationList)): ?>
                <p><?=$this->translate('Zu folgenden Beteiligungsrunden wurden Gruppenmitglieder gefunden:')?></p>
                <ul>
                <?php foreach ($this->consultationList as $consultation): ?>
                    <li>
                        <h2>
                            <a
                                href="<?=$this->url(array('kid' => $consultation['kid']));?>"
                                title="<?=$this->translate('Zeige meine Beiträge zu dieser Beteiligungsrunde')?>"
                            >
                                <?php echo $consultation['titl']; ?>
                            </a>
                        </h2>
                    </li>
                <?php endforeach; ?>
                </ul>

            <?php elseif (isset($this->consultation)): ?>

                <h2><?=$this->translate('Beteiligungsrunde:')?> <?php echo $this->consultation->titl; ?></h2>
                <?php if (!empty($this->group)): ?>
                    <h3><?=$this->translate('Gruppe:')?> <?php echo $this->identity->name.' '.$this->identity->email; ?></h3>
                    <h3><?=$this->translate('Abzustimmende Beiträge:')?> <?php echo $this->inputs; ?></h3>
                    <table style="width: 100%;" border="1" cellpadding="4">
                        <tr>
                        <th><?=$this->translate('Absimmende_*r')?></th>
                        <th><?=$this->translate('Gruppenmitglied')?></th>
                        <th><?=$this->translate('Noch abzustimmen')?></th>
                        <th><?=$this->translate('Aktion')?></th>
                    </tr>
                    <?php foreach ($this->group as $value): ?>
                        <tr>
                            <td><?php echo $value['sub_user']; ?></td>
                            <td id="ms-<?php echo $value['sub_uid']; ?>"><?php echo $memberships[$value['member']]; ?></td>
                            <td><?php echo $this->inputs - $value['count']; ?></td>
                            <td id="ua-<?php echo $value['sub_uid']; ?>">
                                <?php if ($value['member']=="y" || $value['member']=="u"): ?>
                                    <a href="#" rel="deny" data="uid/<?=$value['uid'].'/subuid/'.$value['sub_uid']; ?>" class="useraction">
                                        <?=$this->translate('Ablehnen')?>
                                    </a>
                                    <br/>
                                <?php endif; ?>
                                <?php if ($value['member']=="n" || $value['member']=="u"): ?>
                                    <a href="#" rel="confirm" data="uid/<?=$value['uid'].'/subuid/'.$value['sub_uid']; ?>" class="useraction">
                                        <?=$this->translate('Bestätigen')?>
                                    </a>
                                    <br/>
                                <?php endif; ?>
                                <?php if ($value['member']=="n"): ?>
                                    <a href="#" rel="delete" data="uid/<?=$value['uid'].'/subuid/'.$value['sub_uid']; ?>" class="useraction">
                                        <?=$this->translate('Löschen')?>
                                    </a>
                                    <br/>
                                <?php endif; ?>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    </table>
                <?php endif; ?>
            <?php endif; ?>
            <?php echo $this->render('_partials/printLink.phtml') ?>
        </div>
    </div><!-- .row -->
</div><!-- .content-holder -->

<?php echo $this->render('_partials/topLink.phtml') ?>
