<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width"/>
<!-- build:css mail.css -->
<link href="../../../../www/components/bower/ink/css/ink.css" rel="stylesheet" />
<link href="../../../../www/css/mail.css" rel="stylesheet" />
<!-- /build -->
</head>
<body>
<table class="body">
    <tr>
        <td class="center" align="center" valign="top">
            <center>

                <table class="row header">
                    <tr>
                        <td class="center" align="center">
                            <center>

                                <table class="container">
                                    <tr>
                                        <td class="wrapper last">

                                            <table class="twelve columns">
                                                <tr>
                                                    <td class="six sub-columns">

                                                        <!-- TODO replace with project specific logo: "project/images/logo.png" -->
                                                        <img src="http://placehold.it/200x50">

                                                    </td>
                                                    <td class="six sub-columns last" style="text-align:right; vertical-align:middle;">
                                                        <span class="template-label">

                                                            <!-- TODO replace with project name -->
                                                            Strukturierter Dialog

                                                        </span>
                                                    </td>
                                                    <td class="expander"></td>
                                                </tr>
                                            </table>

                                        </td>
                                    </tr>
                                </table>

                            </center>
                        </td>
                    </tr>
                </table>

                <table class="container">
                    <tr>
                        <td>

                            <table class="row copy">
                                <tr>
                                    <td class="wrapper last">

                                        <table class="twelve columns">
                                            <tr>
                                                <td>

                                                    <!-- TODO replace with actual email body -->
                                                    <!-- email body start -->
                                                    <h1>Hello there!</h1>
                                                    <p class="lead">Phasellus dictum sapien a neque luctus cursus. Pellentesque sem dolor, fringilla et pharetra vitae.</p>
                                                    <p>Phasellus dictum sapien a neque luctus cursus. Pellentesque sem dolor, fringilla et pharetra vitae. consequat vel lacus. Sed iaculis pulvinar ligula, ornare fringilla ante viverra et. In hac habitasse platea dictumst. Donec vel orci mi, eu congue justo. Integer eget odio est, eget malesuada lorem. Aenean sed tellus dui, vitae viverra risus. Nullam massa sapien, pulvinar eleifend fringilla id, convallis eget nisi. Mauris a sagittis dui. Pellentesque non lacinia mi. Fusce sit amet libero sit amet erat venenatis sollicitudin vitae vel eros. Cras nunc sapien, interdum sit amet porttitor ut, congue quis urna.</p>
                                                    <!-- email body end -->

                                                </td>
                                                <td class="expander"></td>
                                            </tr>
                                        </table>

                                    </td>
                                </tr>
                            </table>

                            <table class="row footer">
                                <tr>
                                    <td class="wrapper last">

                                        <table class="twelve columns">
                                            <tr>
                                                <td class="last text-pad">
                                                    <h6>Contact Info:</h6>

                                                    <!-- TODO replace with actual contact info from project settings -->
                                                    <!-- contact start -->
                                                    <p>Phone: 408.341.0600</p>
                                                    <p>Email: <a href="mailto:hseldon@trantor.com">hseldon@trantor.com</a></p>
                                                    <!-- contact end -->

                                                </td>
                                                <td class="expander"></td>
                                            </tr>
                                        </table>

                                    </td>
                                </tr>
                            </table>

                            <table class="row">
                                <tr>
                                    <td class="wrapper last">

                                        <table class="twelve columns">
                                            <tr>
                                                <td align="center">
                                                    <center>

                                                        <!-- TODO add links to Privacy (already exists) and Unsubscribe (TBD) pages -->
                                                        <p style="text-align:center;"><a href="#">Privacy</a> | <a href="#">Unsubscribe</a></p>

                                                    </center>
                                                </td>
                                                <td class="expander"></td>
                                            </tr>
                                        </table>

                                    </td>
                                </tr>
                            </table>

                            <!-- container end below -->
                        </td>
                    </tr>
                </table>

            </center>
        </td>
    </tr>
</table>
</body>
</html>
