<form
    role="element"
    enctype="<?=$this->element->getEnctype();?>"
    method="<?=$this->element->getMethod();?>"
    action="<?=$this->element->getAction();?>"
>
    <?=$this->element->getElement('body');?>

    <?php if ($this->element->getElement('video_service') !== null && $this->element->getElement('video_id') !== null) :
        ?>
        <div class="form-group offset-top offset-bottom js-video-service">
            <div class="row">
                <div class="col-sm-12">
                    <label><?=$this->translate('Video (optional)');?></label>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-4">
                    <?=$this->element->getElement('video_service');?>
                </div>
                <div class="col-sm-8">
                    <div class="input-group">
                        <span class="input-group-addon js-video-service-url"></span>
                        <?=$this->element->getElement('video_id');?>
                    </div>
                </div>
            </div>
        </div>
    <?php endif; ?>

    <?=$this->element->getElement('email');?>

    <?=$this->element->getElement('csrf_token_register');?>
    <?=$this->element->getElement('submit');?>
</form>
