<p>Bitte einloggen oder neu registrieren, um die Beiträge für diese Konsultation zu bestätigen!</p>
<p>Wenn Du als Vertreter einer Gruppe beitragen willst und die entsprechende
 E-Mail-Adresse ist bereits registriert, trage deine Daten bitte trotzdem in das
 Registrierungsformular ein! Die Mail zur Bestätigung der Beiträge wird dann an die hinterlegte Adresse gesendet.</p>
<p>Wenn Du schon an früheren Konsultationen teilgenommen hast und für die aktuelle
 Konsultation abweichende Angaben zu Dir oder Eurer Gruppe übermitteln willst,
 fülle bitte ebenfalls das Registrierungsformular aus!</p>
<h2>Login</h2>
<?php echo $this->loginForm; ?>
<h2>oder Registrierung bzw. Gruppenteilnahme</h2>
<?php echo $this->registerForm; ?>