<?php
/**
 * Input confirm
 *
 * @description   Confirm contribution
 * @author
 */
?>

<?php echo $this->secondNavigation('input'); ?>

<div class="content-holder">
	<div class="row">
		<aside class="span3">

			<?php echo $this->questionNavigation($this->question['qi']); ?>

		</aside>
		<section class="main-content span9">

			<h1>Beitrag beenden</h1>
			<p class="alert alert-info"><i class="icon-info-sign"></i> Bitte fülle das Formular aus, um deine Beiträge für diese Beteiligungsrunde zu bestätigen!</p>
			<p>Wenn du als Vertreter_in einer Gruppe beitragen willst und die entsprechende
				E-Mail-Adresse ist bereits registriert, trage deine Daten bitte trotzdem in das
				Registrierungsformular ein! Die Mail zur Bestätigung der Beiträge wird dann an die hinterlegte Adresse gesendet.</p>
			<p>Wenn du schon an früheren Konsultationen teilgenommen hast und für die aktuelle
				Beteiligungsrunde abweichende Angaben zu dir oder deiner Gruppe übermitteln willst,
				fülle bitte die Angaben zu Person/Gruppe neu aus: Damit sind dann auch alle Daten auf aktuellem Stand.</p>
			<hr />

			<?php echo $this->registerForm; ?>

			<?php echo $this->render('_partials/printLink.phtml') ?>

		</section>
	</div><!-- .row -->
</div><!-- .content-holder -->

<?php echo $this->render('_partials/topLink.phtml') ?>
