<form
    enctype="<?=$this->element->getEnctype();?>"
    method="<?=$this->element->getMethod();?>"
    class="well well-bordered well-accent text-center offset-bottom-large has-sticker hidden-print js-contribution-create-form"
>
    <?=$this->element->csrf_token_input->setDecorators(['ViewHelper']);?>

    <!-- Sticker -->
    <div class="sticker sticker-left hidden-print">
        <div class="sticker-label sticker-label-dark">
            <?=$this->translate('Participate');?>
        </div>
    </div>

    <h2 class="well-title offset-bottom-large">
        <?=$this->translate('Create new contribution');?>
    </h2>

    <?php $i = 0; ?>
    <?php foreach ($this->element->inputs->getSubForms() as $input) : ?>
        <?php if ($i > 0) : ?>
            <hr />
        <?php endif; ?>

        <fieldset class="offset-bottom">

            <!-- Counter -->
            <div class="text-right js-character-counter">
                <span id="inputs-<?=$input->getName();?>-thes_counter" class="counter">
                    <span class="counter-digit">3</span><span class="counter-digit">0</span><span class="counter-digit">0</span>
                </span>
            </div>

            <?=$input->getElements()['thes']->setDecorators(['ViewHelper']);?>

            <?php if ($this->element->getVideoEnabled()) : ?>
                <div class="form-inline form-inline-flex form-group text-left offset-top-small offset-bottom-small js-video-service">
                    <div class="form-group">
                        <?=$input->getElements()['video_service'];?>
                    </div>
                    <div class="form-group form-group-flex">
                        <div class="input-group input-group-full">
                            <?=$input->getElements()['video_id'];?>
                        </div>
                    </div>
                </div>
                <?php if (count($input->getElement('video_id')->getErrors()) > 0) : ?>
                    <ul class="text-danger-block">
                        <?php foreach ($input->getElement('video_id')->getMessages() as $message) : ?>
                            <li><?=$message;?></li>
                        <?php endforeach; ?>
                    </ul>
                <?php endif; ?>
            <?php endif; ?>

            <!-- Expand -->
            <a href="#" class="btn btn-inverse btn-alt btn-separated btn-block btn-xs js-toggle-extended-input">
                <span class="glyphicon glyphicon-menu-down" aria-hidden="true"></span>
                <span class="hidden-xs"><?=$this->translate('Click here to explain contribution');?></span>
                <span class="glyphicon glyphicon-menu-down hidden-xs" aria-hidden="true"></span>
            </a>

            <?=$input->getElements()['expl']->setDecorators(['ViewHelper']);?>

            <!-- Counter -->
            <div class="text-right js-character-counter" style="display: none">
                <span id="inputs-<?=$input->getName();?>-expl_counter" class="counter">
                    <span class="counter-digit">2</span><span class="counter-digit">0</span><span class="counter-digit">0</span><span class="counter-digit">0</span>
                </span>
            </div>

        </fieldset>

        <?php $i++; ?>
    <?php endforeach; ?>

    <!-- Actions -->
    <div class="row">
        <div class="col-sm-6 text-left text-center-xs offset-bottom-xs-max">

            <div class="offset-bottom-xs-small visible-xs-block visible-sm-inline-block visible-md-inline-block visible-lg-inline-block">
                <?=$this->element->add_input_field->setDecorators(['ViewHelper']);?>
            </div>
            <span class="small">
                <?=$this->translate('Click here for another contribution');?>
            </span>

        </div>

        <div class="col-sm-6 text-right text-center-xs">

            <div class="offset-bottom-small visible-xs-block visible-sm-inline-block visible-md-inline-block visible-lg-inline-block">
                <?=$this->element->next_question->setDecorators(['ViewHelper']);?>
            </div>
            <div class="offset-bottom-small visible-xs-block visible-sm-inline-block visible-md-inline-block visible-lg-inline-block">
                <?=$this->element->finished->setDecorators(['ViewHelper']);?>
            </div>

        </div>
    </div><!-- .row -->
</form><!-- .well -->

<form id="contribution-subform-template" style="display: none">
    <fieldset class="offset-bottom">

        <!-- Counter -->
        <div class="text-right js-character-counter">
                <span id="inputs-_id_-thes_counter" class="counter">
                    <span class="counter-digit">3</span><span class="counter-digit">0</span><span class="counter-digit">0</span>
                </span>
        </div>

        <textarea name="inputs[_id_][thes]" id="inputs-_id_-thes" cols="85" rows="3" class="form-control form-control-alt js-has-counter" placeholder="Hier könnt ihr euren Beitrag mit bis zu 300 Buchstaben schreiben" maxlength="300"></textarea>
        <div class="form-inline form-inline-flex form-group text-left offset-top-small offset-bottom-small js-video-service">
            <div class="form-group">
                <label for="inputs-_id_-video_service" class="control-label offset-right optional">Video:</label>

                <select name="inputs[_id_][video_service]" id="inputs-_id_-video_service" data-url="{&quot;youtube&quot;:&quot;www.youtube.com\/watch?v=&quot;,&quot;vimeo&quot;:&quot;vimeo.com\/&quot;,&quot;facebook&quot;:&quot;www.facebook.com\/video.php?v=&quot;}" class="form-control form-control-alt">
                    <option value="youtube">Youtube</option>
                    <option value="vimeo">Vimeo</option>
                    <option value="facebook">Facebook</option>
                </select>                    </div>
            <div class="form-group form-group-flex">
                <div class="input-group input-group-full">
                    <label for="inputs-1-video_id" class="sr-only optional">Video-ID</label>

                    <input type="text" name="inputs[1][video_id]" id="inputs-1-video_id" value="" class="form-control form-control-alt" placeholder="Bitte Webadresse des Videos eintragen">                        </div>
            </div>
        </div>

        <!-- Expand -->
        <a href="#" class="btn btn-inverse btn-alt btn-separated btn-block btn-xs js-toggle-extended-input">
            <span class="glyphicon glyphicon-menu-down" aria-hidden="true"></span>
            <span class="hidden-xs">Klicken, um Eintrag zu erläutern</span>
            <span class="glyphicon glyphicon-menu-down hidden-xs" aria-hidden="true"></span>
        </a>


        <textarea name="inputs[1][expl]" id="inputs-1-expl" cols="85" rows="5" class="form-control form-control-alt js-has-counter" style="display: none;" placeholder="Hier könnt ihr euren Beitrag mit bis zu 2000 Buchstaben erläutern" maxlength="2000"></textarea>
        <!-- Counter -->
        <div class="text-right js-character-counter" style="display: none">
                <span id="inputs-1-expl_counter" class="counter">
                    <span class="counter-digit">2</span><span class="counter-digit">0</span><span class="counter-digit">0</span><span class="counter-digit">0</span>
                </span>
        </div>

    </fieldset>
</form>
