<form
    enctype="<?=$this->element->getEnctype();?>"
    method="<?=$this->element->getMethod();?>"
    class="well well-bordered well-accent text-center offset-bottom-large has-sticker hidden-print js-contribution-create-form"
>
    <?=$this->element->csrf_token_input->setDecorators(['ViewHelper']);?>

    <!-- Sticker -->
    <div class="sticker sticker-left hidden-print">
        <div class="sticker-label sticker-label-dark">
            <?=$this->translate('Participate');?>
        </div>
    </div>

    <h2 class="well-title offset-bottom-large">
        <?=$this->translate('Create new contribution');?>
    </h2>

    <?php foreach($this->element->inputs->getSubForms() as $input): ?>
        <div class="form-group">

            <?php if ($this->element->getVideoEnabled()) : ?>
                <div class="offset-top-large js-video-service">
                    <div class="row">
                        <div class="col-sm-3 col-sm-offset-1 text-left">
                            <?=$input->getElements()['video_service'];?>
                        </div>
                        <div class="col-sm-7">
                            <div class="form-group">
                                <label class="invisible">Video ID</label>
                                <div class="input-group">
                                    <span class="input-group-addon js-video-service-url"></span>
                                    <?=$input->getElements()['video_id'];?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            <?php endif; ?>

            <!-- Counter -->
            <div class="text-right js-character-counter">
                <span id="inputs-<?=$input->getName();?>-thes_counter" class="counter">
                    <span class="counter-digit">3</span><span class="counter-digit">0</span><span class="counter-digit">0</span>
                </span>
            </div>

            <?=$input->getElements()['thes']->setDecorators(['ViewHelper']);?>

            <!-- Expand -->
            <a href="#" class="btn btn-inverse btn-alt btn-separated btn-block btn-xs js-toggle-extended-input">
                <span class="glyphicon glyphicon-menu-down" aria-hidden="true"></span>
                <span class="hidden-xs"><?=$this->translate('Click here to explain contribution');?></span>
                <span class="glyphicon glyphicon-menu-down hidden-xs" aria-hidden="true"></span>
            </a>

            <?=$input->getElements()['expl']->setDecorators(['ViewHelper']);?>

            <!-- Counter -->
            <div class="text-right js-character-counter" style="display: none">
                <span id="inputs-<?=$input->getName();?>-expl_counter" class="counter">
                    <span class="counter-digit">2</span><span class="counter-digit">0</span><span class="counter-digit">0</span><span class="counter-digit">0</span>
                </span>
            </div>

        </div>
    <?php endforeach; ?>

    <!-- Actions -->
    <div class="row">
        <div class="col-sm-8 col-sm-push-2">

            <div class="offset-bottom-xs-max">
                <p class="small help-block">
                    <?=$this->translate('Click here for another contribution');?>
                </p>
                <?=$this->element->next_question->setDecorators(['ViewHelper']);?>
            </div>

        </div>
        <div class="col-xs-6 col-sm-2 col-sm-pull-8 text-left">

            <?=$this->element->add_input_field->setDecorators(['ViewHelper']);?>

        </div>
        <div class="col-xs-6 col-sm-2 text-right">

            <?=$this->element->finished->setDecorators(['ViewHelper']);?>

        </div>
    </div><!-- .row -->
</form><!-- .well -->
