<?php
/**
 * Input edit
 *
 * @description   Edit contribution
 * @author
 */
?>

<?php echo $this->secondNavigation('input'); ?>

<div class="content-holder">
	<div class="row">
		<aside class="span3">

			<?php echo $this->questionNavigation($this->question['qi']); ?>

		</aside>
		<section class="main-content span9">

			<h1>Beitrag bearbeiten</h1>
			<?php if (isset($this->form)): ?>
				<?php echo $this->form; ?>
			<?php endif; ?>
			<?php if (isset($this->message)): ?>
				<p><?php echo $this->message; ?></p>
			<?php endif; ?>
			<p><a href="<?php
				echo $this->url(array(
					'controller' => 'user',
					'action' => 'inputlist'
				));
			?>">&laquo; Zurück</a></p>

			<?php echo $this->render('_partials/printLink.phtml') ?>

		</section>
	</div><!-- .row -->
</div><!-- .content-holder -->

<?php echo $this->render('_partials/topLink.phtml') ?>
