<?php
$this->layout()->pageTitle = $this->pageTitle(
    Application_View_Helper_PageTitle::CONTRIBUTIONS_PAGE,
    $this->consultation
);
?>
<?=$this->secondNavigation('input');?>

<div class="main-content">
    <div class="row offset-bottom">
        <div class="col-md-10 text-center">

            <div class="content content-offset">
                <h1><?=$this->translate('Thank you for contributing');?></h1>

                <?=$this->wysiwyg($this->info);?>
            </div>

        </div>
    </div><!-- .row -->

    <!-- Questions -->
    <div class="row">

    </div><!-- .row -->

    <?=$this->partial('_partials/pageLinks.phtml', ['help' => 'help-text-consultation-input']);?>

</div><!-- .main-content -->
