<?=$this->secondNavigation('input');?>

<div class="main-content">
    <div class="row offset-bottom">
        <div class="col-md-10 col-md-offset-1 text-center">

            <?=$this->wysiwyg($this->info);?>

        </div>
    </div><!-- .row -->

    <!-- Questions -->
    <div class="row">

    </div><!-- .row -->

    <?=$this->partial('_partials/pageLinks.phtml', ['help' => 'help-text-consultation-input']);?>

</div><!-- .main-content -->
