<?php echo $this->secondNavigation('input') ?>

<div class="main-content">
    <div class="row-fluid">
        <div class="text-center span10 offset1">

            <small class="count muted">
                <?php echo $this->inputCount ?> <?=$this->translate('confirmed contributions')?>
            </small>
            <h1><?=$this->translate('All contributions')?></h1>
            <p>
                <?=$this->translate('You want to participate in this participation round? Just click on a question during the input period, and the input field will appear where you can insert your contributions. After the input period has finished, you are no longer allowed to draw up contributions, but by clicking on a question you can read all other contributions.')?>
            </p>

        </div>
    </div><!-- .row -->

    <!-- Questions -->
    <div class="row">

        <?php if (!empty($this->tags)): ?>
            <div class="col-sm-6 col-md-4">
                <div class="well well-bordered">
                        <h2><?=$this->translate('Contributions sorted by keywords:')?></h2>
                        <ul class="tag-cloud">
                            <?php foreach ($this->tags as $tag): ?>
                                <li class="tag-<?php echo $tag['frequency']; ?>">
                                    <a href="<?php echo $this->url(array('action' => 'show', 'tag' => $tag['tg_nr'])); ?>">
                                        <?php echo $tag['tg_de']; ?>
                                    </a>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                        <a href="<?php echo $this->url(array('action' => 'tags')); ?>" class="btn btn-default btn-block">
                            <?=$this->translate('All tags')?>
                        </a>
                    </div>
            </div>
        <?php endif; ?>
        <?php
        foreach ($this->questions as $question):
            $url = $this->url(array('action' => 'show', 'qid' => $question['qi']));
            ?>
            <div class="col-sm-6 col-md-4">
                <div class="well well-bordered">

                    <span class="badge badge-tag badge-tag-small">
                        <?=$this->escape($question['nr']);?>
                    </span>

                    <h2>
                        <a href="<?php echo $url ?>"><?=$this->escape($question['q']);?></a>
                    </h2>

                    <div class="article-list">
                        <?php foreach ($question['inputs'] as $input): ?>
                            <time datetime="<?=$this->formatDate($input['when'], 'y-MM-dd') ?>">
                                <?=sprintf(
                                    $this->translate('written on %s'),
                                    $this->formatDate($input['when'], Zend_Date::DATE_MEDIUM)
                                )?>
                            </time>
                            <p><?php echo mb_substr($this->escape($input['thes']), 0, 120, 'UTF-8') ?></p>
                        <?php endforeach; ?>
                    </div>

                    <?php if (
                        $this->nowDate->isLater(new Zend_Date($this->consultation->inp_fr, Zend_Date::ISO_8601))
                        && $this->nowDate->isEarlier(new Zend_Date($this->consultation->inp_to, Zend_Date::ISO_8601))
                    ): ?>
                        <a href="<?=$url;?>" class="btn btn-default btn-block has-icon-pencil">
                            <span class="icon icon-pencil" aria-hidden="true"></span>
                            <?=$this->translate('Write a contribution')?>
                            ›››
                        </a>
                    <?php else: ?>
                        <a href="<?=$url;?>" class="btn btn-default btn-block">
                            <?=sprintf($this->translate('All contributions'));?>
                            ›››
                        </a>
                    <?php endif; ?>

                </div>
            </div>
        <?php endforeach; ?>

    </div><!-- .row -->

    <?=$this->partial('_partials/pageLinks.phtml', ['help' => 'help-text-consultation-input']);?>

</div><!-- .main-content -->
