<?php
    $date = new Zend_Date();
    $locale = new Zend_Locale();
?>
<a name="page-content"></a>
<?php echo $this->secondNavigation('input') ?>

<div class="main-content content-holder">
    <div class="row">
        <div class="text-center span10 offset1">

            <small class="count muted">
                <?php echo $this->inputCount ?> <?=$this->translate('bestätigte Beiträge')?>
            </small>
            <h1><?=$this->translate('Alle Beiträge im Überblick')?></h1>
            <p>
                <?=$this->translate('Ihr wollt bei dieser Beteiligungsrunde mitmachen? Dann klickt während der Beitragsphase einfach auf eine Frage und schon öffnet sich das Eingabefeld für eure Beiträge. Nach dem Ende der Beitragsphase könnt ihr nicht mehr mitmachen, aber über den Klick auf die Frage alle eingegangenen Beiträge lesen.')?>
            </p>

        </div>
    </div><!-- .row -->

    <!-- Questions -->
    <ul class="questions thumbnails">
        <?php if (!empty($this->tags)): ?>
            <li class="span4">
                <div class="thumbnail">
                    <div class="thumbnail-content">
                        <h2><?=$this->translate('Beiträge sortiert nach Schlagwörtern:')?></h2>
                        <ul class="tag-cloud">
                            <?php foreach ($this->tags as $tag): ?>
                                <li class="tag-<?php echo $tag['frequency']; ?>">
                                    <a href="<?php echo $this->url(array('action' => 'show', 'tag' => $tag['tg_nr'])); ?>">
                                        <?php echo $tag['tg_de']; ?>
                                    </a>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                        <a href="<?php echo $this->url(array('action' => 'tags')); ?>" class="btn">
                            <?=$this->translate('Alle Schlagwörter')?>
                        </a>
                    </div>
                </div><!-- .thumbnail -->
            </li>
        <?php endif; ?>
        <?php
        foreach ($this->questions as $question):
            $url = $this->url(array('action' => 'show', 'qid' => $question['qi']));
            ?>
            <li class="span4">
                <div class="thumbnail">
                    <span class="badge badge-tag badge-tag-small"><?php echo $question['nr'] ?></span>
                    <div class="thumbnail-content">
                        <h2>
                            <a href="<?php echo $url ?>"><?php echo $question['q'] ?></a>
                        </h2>
                        <div class="article-list">
                            <?php foreach ($question['inputs'] as $input): ?>
                                <a href="<?php echo $url ?>">
                                    <article class="media">
                                        <time pubdate datetime="<?php echo $date->set($input['when'])->get('y-MM-dd') ?>">
                                            <?=sprintf($this->translate('verfasst am %s'), $date->get(Zend_Date::DATE_MEDIUM, $locale))?>
                                        </time>
                                        <p><?php echo mb_substr($input['thes'], 0, 120, 'UTF-8') ?></p>
                                    </article>
                                </a>
                            <?php endforeach; ?>
                        </div>
                        <a href="<?php echo $url; ?>" class="btn edit">
                            <?php if (
                                $this->nowDate->isLater($this->consultation->inp_fr)
                                && $this->nowDate->isEarlier($this->consultation->inp_to)
                            ): ?>
                                <i class="icon-edit-alt"></i>
                                <?=$this->translate('Beitrag verfassen')?> ›››
                            <?php else: ?>
                                <?=sprintf($this->translate('Alle Beiträge zu Frage %s'), $question['nr'])?> ›››
                            <?php endif; ?>
                        </a>
                    </div>
                </div><!-- .thumbnail -->
            </li>
        <?php endforeach; ?>
    </ul><!-- .questions -->

    <?php echo $this->render('_partials/printLink.phtml') ?>
</div>

<?php echo $this->render('_partials/topLink.phtml') ?>
