<form
    enctype="<?=$this->element->getEnctype();?>"
    method="<?=$this->element->getMethod();?>"
    class="offset-bottom"
>
    <?=$this->element->csrf_token_inputedit;?>

    <?=$this->element->thes;?>
    <?=$this->element->expl;?>

    <?php if ($this->element->getVideoEnabled()) : ?>
        <div class="form-group offset-top offset-bottom js-video-service">
            <div class="row">
                <div class="col-sm-4">
                    <?=$this->element->video_service;?>
                </div>
                <div class="col-sm-8">
                    <div class="input-group">
                        <span class="input-group-addon js-video-service-url"></span>
                        <?=$this->element->video_id;?>
                    </div>
                </div>
            </div>
        </div>

        <div class="form-group">
            <?php if ($this->element->video_id->getValue()) : ?>
                <?=$this->embeddedVideo(
                    $this->element->video_service->getValue(),
                    $this->element->video_id->getValue()
                );?>
            <?php endif; ?>
        </div>
    <?php endif; ?>

    <?=$this->element->submit;?>

</form>
