<form
    enctype="<?=$this->element->getEnctype();?>"
    method="<?=$this->element->getMethod();?>"
    class="offset-bottom"
>
    <?=$this->element->csrf_token_inputedit;?>

    <?=$this->element->thes;?>
    <?=$this->element->expl;?>

    <?php if ($this->element->getVideoEnabled()) : ?>
        <div class="form-group input-group js-video-service">
            <?=$this->element->video_service;?>
            <span class="input-group-addon"></span>
            <?=$this->element->video_id;?>
        </div>

        <div class="form-group">
            <?php if ($this->element->video_id->getValue()) : ?>
                <?=$this->embeddedVideo(
                    $this->element->video_service->getValue(),
                    $this->element->video_id->getValue()
                );?>
            <?php endif; ?>
        </div>
    <?php endif; ?>
    
    <?=$this->element->submit;?>

</form>
