<?php
    $date = new Zend_Date();
    $supports = new Zend_Session_Namespace('supports');
    if (empty($supports->clicks)) {
        $supports->clicks = array();
    }
    $supportsDisabled = (
        Zend_Date::now()->isEarlier($date->set($this->consultation->spprt_fr))
        || Zend_Date::now()->isLater($date->set($this->consultation->spprt_to))
        || $this->consultation->spprt_fr == '0000-00-00 00:00:00'
        || $this->consultation->spprt_to == '0000-00-00 00:00:00'
        || $this->consultation->spprt_show == 'n'
    );

    $script = '
        $(document).ready(function() {
          var inputform = $("#input");
          if (inputform.length > 0) {
            $(\'.question-nav-item\').click(function(event) {
              event.preventDefault();
              $("#submitmode").val(\'save_goto\');
              $("#goto").val($(this).data("qid"));
              inputform.submit();
            });
          }
        });
        ';
    $this->headScript()->appendScript($script);
?>

<?php echo $this->secondNavigation('input'); ?>

<div class="content-holder">
    <div class="row">
        <aside class="span3">
            <?php echo $this->questionNavigation($this->question['qi']); ?>
        </aside>

        <section class="main-content span9">
            <?php if (isset($this->tag) && !empty($this->tag)): ?>
                <?php if ($this->numberInputs > 0):?>
                    <h3><?=sprintf($this->translate('Es werden nur Beiträge mit dem Schlagwort %s angezeigt.'), '<em>' . $this->tag['tg_de'] . '</em>')?></h3>
                <?php else: ?>
                    <h3><?=sprintf($this->translate('Zu dieser Frage gibt es keine mit %s verschlagworteten Beiträge.'), '<em>' . $this->tag['tg_de'] . '</em>')?></h3>
                <?php endif; ?>
                <p>
                    <a href="<?php echo $this->url(array('tag' => null)); ?>">
                        <?=$this->translate('Alle Beiträge anzeigen')?>
                    </a>
                </p>
            <?php endif; ?>
            <small class="count muted">
                <?php echo $this->numberInputs?>
                <?=$this->translate('Beiträge')?>
            </small>

            <article class="article article-details">
                <h1><?php echo $this->question['nr'] . ' ' . $this->question['q']; ?></h1>
                <p><?php echo $this->question['q_xpl']; ?></p>
            </article>

            <!-- New contribution -->
            <?php echo $this->inputform; ?>

            <hr />

            <!-- Contributions -->
            <?php if (count($this->paginator)): ?>
                <?php
                // Reverse order of entries to show latest first
                $inputs = array();
                foreach ($this->paginator as $item) {
                    $inputs[] = $item;
                }
                $inputs = array_reverse($inputs);
                ?>
                <?php foreach ($inputs as $input): ?>
                    <a name="input-<?php echo $input['tid']; ?>"></a>
                    <article class="media">
                        <header class="article-header">
                            <time pubdate datetime="<?php echo $date->set($input['when'])->get('y-MM-dd') ?>">
                                <?=sprintf($this->translate('verfasst am %s'), $date->get(Zend_Date::DATE_MEDIUM))?>
                            </time>
                        </header>
                        <div class="article-body">
                            <p class="lead"><?php echo $input['thes'] ?></p>
                            <p><?php echo $input['expl'] ?></p>
                        </div>

                        <!-- Actions -->
                        <section class="article-actions">
                            <span class="article-action" id="click-support-wrap-<?php echo $input['tid']; ?>">
                                <?php if (in_array($input['tid'], $supports->clicks) || $supportsDisabled): ?>
                                    <span>
                                <?php else: ?>
                                    <a
                                        href="#"
                                        id="click-support-<?php echo $input['tid']; ?>"
                                        class="click-support"
                                        rel="<?php echo $input['tid']; ?>"
                                    >
                                <?php endif; ?>
                                        <i class="icon-ok-sign icon-orange icon-2x"></i>
                                        <span id="badge-<?php echo $input['tid']; ?>">(<?php echo $input['spprts']; ?>)</span>
                                <?php if (in_array($input['tid'], $supports->clicks) || $supportsDisabled): ?>
                                        <span class="label"><?=$this->translate('Unterstützende')?></span>
                                    </span>
                                <?php else: ?>
                                        <span class="label"><?=$this->translate('Dieser Meinung bin ich auch!')?></span>
                                    </a>
                                <?php endif; ?>
                            </span>

                            <?php if ($this->consultation->is_discussion_active
                                && (!$this->consultation->discussion_to
                                    || Zend_Date::now()->isEarlier($date->set($this->consultation->discussion_to)))
                                && (!$this->consultation->discussion_from
                                    || Zend_Date::now()->isLater($date->set($this->consultation->discussion_from)))
                            ): ?>
                                <span class="article-action">
                                    <i class="icon-comments icon-orange icon-2x"></i>
                                    <small>(<?php echo $input['pts']; ?>)</small>
                                    <a class="label" href="#">Das möchte ich gerne diskutieren!</a>
                                </span>
                            <?php endif?>
                        </section><!-- .actions -->

                    </article>
                    <hr />
                <?php endforeach; ?>
            <?php endif; ?>

            <!-- Paging -->
            <?$this->paginationControl(
                $this->paginator,
                'Sliding',
                '_partials/pagination.phtml',
                array('titlePrev' => 'Ältere Beiträge', 'titleNext' => 'Neuere Beiträge')
            ); ?>

            <hr />

            <?php echo $this->render('_partials/printLink.phtml') ?>

        </section>
    </div><!-- .row -->
</div><!-- .content-holder -->

<?php echo $this->render('_partials/topLink.phtml') ?>

<script type="text/javascript">
    $(document).ready(function() {

        // Toggle extended input
        $('.js-toggle-extended-input').click(function(event) {
            event.preventDefault();
            $(this).next('textarea').toggle();
            $(this).nextAll('.js-character-counter').toggle();
            $(this).toggleClass('expanded');

            if($(this).hasClass('expanded')) {
                $(this).html('<i class="icon-angle-up icon-large"></i> <?=$this->translate('Wieder einklappen')?> <i class="icon-angle-up icon-large"></i>')
            } else {
                $(this).html('<i class="icon-angle-down icon-large"></i> <?=$this->translate('Klicken, um Eintrag zu erläutern')?> <i class="icon-angle-down icon-large"></i>')
            }
        });

        // Support a contribution
        $('.click-support').click(function(event) {
            event.preventDefault();
            var tid = $(this).attr('rel');
            $.post(
                "<?php echo $this->baseUrl(); ?>/input/support/kid/<?php echo $this->consultation->kid; ?>/format/json",
                { "tid": tid }
            ).done(function(data) {
                if (data.count) {
                    $('#click-support-wrap-' + tid).html('<span><i class="icon-ok-sign icon-orange icon-2x"></i>'
                        + ' <span id="badge-' + tid + '">(' + data.count + ')</span>'
                        + ' <span class="label"><?=$this->translate('Unterstützende')?></span></span>');
                }
            });
        });

        $("#finish").click(function () {
            $("#submitmode").val('save_finish');
        });
        $("#plus").click(function () {
            $("#submitmode").val('save_plus');
        });
    });
</script>
