<?php
    $supports = new Zend_Session_Namespace('supports');
    if (empty($supports->clicks)) {
        $supports->clicks = array();
    }
    $supportsDisabled = (
        Zend_Date::now()->isEarlier(new Zend_Date($this->consultation->spprt_fr, Zend_Date::ISO_8601))
        || Zend_Date::now()->isLater(new Zend_Date($this->consultation->spprt_to, Zend_Date::ISO_8601))
        || !$this->consultation->spprt_fr
        || !$this->consultation->spprt_to
        || !$this->consultation->is_support_phase_showed
    );
?>

<?=$this->secondNavigation('input');?>

<div class="main-content">
    <div class="row">
        <div class="sidebar-left hidden-print">

            <nav class="offset-bottom-large">
                <?=$this->questionNavigation($this->question['qi']);?>
            </nav>

        </div>
        <div class="content">

            <div class="row">
                <div class="col-md-10">

                    <?php if (isset($this->tag) && !empty($this->tag)): ?>
                        <p class="alert alert-info">
                            <span class="glyphicon glyphicon-info-sign icon-offset" aria-hidden="true"></span>
                            <?php if ($this->numberInputs > 0): ?>
                                <?=sprintf($this->translate('Only contributions with the keyword %s are shown.'), '<em>' . $this->escape($this->tag['tg_de']) . '</em>');?>
                            <?php else: ?>
                                <?=sprintf($this->translate('There are no contributions with the keyword %s on this question.'), '<em>' . $this->escape($this->tag['tg_de']) . '</em>');?>
                            <?php endif; ?>
                            <a href="<?=$this->url(['tag' => null]);?>">
                                <?=$this->translate('Show all contributions');?>.
                            </a>
                        </p>
                    <?php endif; ?>

                    <div class="text-muted">
                        <small>
                            <?=$this->numberInputs;?>
                            <?=$this->translate('Contributions');?>
                        </small>
                    </div>

                    <h1>
                        <?=isset($this->question['nr']) ? $this->escape($this->question['nr']) : '';?>
                        <?=$this->escape($this->question['q']);?>
                    </h1>

                </div>
            </div><!-- .row -->

            <div class="article offset-bottom-large">
                <?=$this->wysiwyg($this->question['q_xpl']);?>
            </div>

            <!-- Contribution form -->
            <?php if (Zend_Date::now()->isEarlier(new Zend_Date($this->consultation->inp_fr, Zend_Date::ISO_8601))): ?>
                <p class="alert alert-info offset-bottom-large">
                    <span class="glyphicon glyphicon-info-sign icon-offset" aria-hidden="true"></span>
                    <?=$this->translate('Contribution phase has not started yet.');?>
                </p>
            <?php elseif (Zend_Date::now()->isLater(new Zend_Date($this->consultation->inp_to, Zend_Date::ISO_8601))): ?>
                <p class="alert alert-info offset-bottom-large">
                    <span class="glyphicon glyphicon-info-sign icon-offset" aria-hidden="true"></span>
                    <?=$this->translate('Contribution phase is over already.');?>
                </p>
            <?php else: ?>
                <?=$this->inputForm;?>
                <hr />
            <?php endif?>

            <!-- Contributions -->
            <?php if (count($this->paginator)): ?>
                <?php
                    // Reverse order of entries to show latest first.
                    $inputs = [];
                    foreach ($this->paginator as $item) {
                        $inputs[] = $item;
                    }
                    $inputs = array_reverse($inputs);
                ?>
                <?php foreach ($inputs as $input): ?>
                    <a name="input-<?=$this->escape($input['tid']);?>"></a>

                    <article class="media" id="contribution-<?=$input['tid']?>">
                        <header>
                            <time datetime="<?=$this->formatDate($input['when'], 'y-MM-dd');?>">
                                <?=sprintf(
                                    $this->translate('written on %s'),
                                    $this->formatDate($input['when'], Zend_Date::DATE_MEDIUM)
                                );?>
                            </time>
                        </header>

                        <p>
                            <strong><?=$this->escape($input['thes']);?></strong>
                        </p>

                        <?php if (!empty($input['expl'])): ?>
                            <p>
                                <?=$this->escape($input['expl']);?>
                            </p>
                        <?php endif; ?>

                        <?php if ($this->videoEnabled && $input['video_service'] !== null && $input['video_id'] !== null
                            && $this->videoServicesStatus['video_' . $input['video_service'] . '_enabled']): ?>
                            <p>
                                <?=$this->embeddedVideo($input['video_service'], $input['video_id']);?>
                            </p>
                        <?php endif; ?>

                        <!-- Actions -->
                        <footer>
                            <!-- Support -->
                            <?php if ($this->consultation->is_support_phase_showed): ?>
                                <div class="text-nowrap offset-bottom-small visible-xs-inline-block visible-sm-inline-block visible-md-inline-block visible-lg-inline-block">
                                    <span id="click-support-wrap-<?=$this->escape($input['tid']);?>" class="offset-right">
                                        <span class="glyphicon glyphicon-ok-sign icon-offset icon-shift-down text-accent" aria-hidden="true"></span>
                                        <small id="badge-<?=$this->escape($input['tid']);?>" class="badge<?=$this->escape($input['spprts']) > 0 ? ' badge-accent' : '';?>">
                                            <?=$this->escape($input['spprts']);?>
                                        </small>
                                        <?php if (in_array($input['tid'], $supports->clicks) || $supportsDisabled): ?>
                                            <small class="hidden-print"><?=$this->translate('supporters');?></small>
                                        <?php else: ?>
                                            <a
                                                href="#"
                                                id="click-support-<?=$this->escape($input['tid']);?>"
                                                class="btn btn-default btn-xs hidden-print js-click-support"
                                                data-kid="<?=$this->consultation->kid;?>"
                                                rel="<?=$this->escape($input['tid']);?>"
                                            >
                                                <?=$this->translate('I agree!');?>
                                            </a>
                                        <?php endif; ?>
                                    </span>
                                </div>
                            <?php endif;?>

                            <!-- Discussion -->
                            <?php if ($this->consultation->is_discussion_active): ?>
                                <div class="text-nowrap offset-bottom-small visible-xs-inline-block visible-sm-inline-block visible-md-inline-block visible-lg-inline-block">
                                    <a
                                        href="<?=$this->url(['action' => 'discussion', 'kid' => $this->consultation->kid, 'inputId' => $this->escape($input['tid'])]);?>"
                                        class="link-unstyled link-print-nourl"
                                    >
                                        <span class="glyphicon glyphicon-comment icon-offset icon-shift-down text-accent" aria-hidden="true"></span>
                                    </a>
                                    <a
                                        href="<?=$this->url(['action' => 'discussion', 'kid' => $this->consultation->kid, 'inputId' => $this->escape($input['tid'])]);?>"
                                        class="link-unstyled link-print-nourl"
                                    >
                                        <small class="badge<?=$this->escape($input['discussionPostCount']) > 0 ? ' badge-accent' : '';?>">
                                            <?=$this->escape($input['discussionPostCount']);?>
                                        </small>
                                    </a>
                                    <a
                                        href="<?=$this->url(['action' => 'discussion', 'kid' => $this->consultation->kid, 'inputId' => $this->escape($input['tid'])]);?>"
                                        class="btn btn-default btn-xs hidden-print"
                                    >
                                        <?php if(Zend_Date::now()->isLater(new Zend_Date($this->consultation->discussion_from, Zend_Date::ISO_8601))
                                            && Zend_Date::now()->isEarlier(new Zend_Date($this->consultation->discussion_to, Zend_Date::ISO_8601))
                                        ): ?>
                                            <?=$this->translate('I would like to discuss that!');?>
                                        <?php else : ?>
                                            <?=$this->translate('View discussion');?>
                                        <?php endif; ?>
                                    </a>
                                </div>
                            <?php endif?>

                            <!-- Reactions -->
                            <div class="text-nowrap offset-bottom-small visible-xs-inline-block visible-sm-inline-block visible-md-inline-block visible-lg-inline-block">
                                <?=$this->followupLink($input['tid'], $this->question['qi']);?>
                            </div>

                        </footer>
                    </article>

                    <hr />
                <?php endforeach; ?>
            <?php else: ?>
                <p>
                    <span class="glyphicon glyphicon-info-sign text-info icon-offset" aria-hidden="true"></span>
                    <?=$this->translate('There are no contributions on this question.');?>
                </p>
            <?php endif; ?>

            <!-- Paging -->
            <?=$this->paginationControl(
                $this->paginator,
                'Sliding',
                '_partials/pagination.phtml',
                ['titlePrev' => $this->translate('Older contributions'), 'titleNext' => $this->translate('Newer contributions')]
            );?>

            <hr class="hidden-print" />

            <!-- Sign up -->
            <?=$this->subscriptionForm;?>

        </div>
    </div><!-- .row -->

    <?=$this->partial('_partials/pageLinks.phtml', ['help' => 'help-text-consultation-input']);?>

</div><!-- .main-content -->
