<?php
/**
 * Question
 *
 * @description   Beiträge zu Fragen
 * @author        Markus Hackel
 */
$date = new Zend_Date();
$supports = new Zend_Session_Namespace('supports');
$supportsDisabled = (
  Zend_Date::now()->isEarlier($date->set($this->consultation->spprt_fr))
  || Zend_Date::now()->isLater($date->set($this->consultation->spprt_to))
);
?>
<!-- Secondary navigation -->
<?php echo $this->secondNavigation('input'); ?>
<!-- .secondary-navigation -->

<!-- Content start -->

<div class="content-holder">
	<div class="row">
		<aside class="span3">

			<!-- Tertiary navigation -->
<?php echo $this->questionNavigation($this->question['qi']);?>
			<!-- .tertiary-navigation -->

		</aside>

		<section class="main-content span9">
			<?php if (isset($this->tag) && !empty($this->tag)): ?>
			<h3>Es werden nur Beiträge mit dem Schlagwort <em>"<?php echo $this->tag['tg_de']; ?>"</em> angezeigt.</h3>
			<p><a href="<?php echo $this->url(array('tag' => null)); ?>">Alle Beiträge anzeigen</a></p>
			<?php endif; ?>
			<p class="count"><?php echo $this->numberInputs; ?> Beiträge</p>

			<h3><?php echo $this->question['q']; ?></h3>
			<p><?php echo $this->question['q_xpl']; ?></p>

			<!-- New contribution -->
			<?php echo $this->inputform; ?>

			<hr />

			<!-- Contributions -->
			<?php if (count($this->paginator)): ?>
			<?php foreach ($this->paginator as $input):?>
			<a name="input-<?php echo $input['tid']; ?>"></a>
			<article class="media">
				<time pubdate datetime="<?php echo $date->set($input['when'])
							  ->get('y-MM-dd')?>">verfasst am <?php echo $date
							  ->get(Zend_Date::DATE_MEDIUM); ?></time>
				<p class="lead"><?php echo $input['thes']?></p>
				<p><?php echo $input['expl']?></p>

				<?php if ($this->consultation->spprt_show == 'y'): ?>
				<a href="#" id="click-support-<?php echo $input['tid']; ?>" class="click-support<?php
				  if (in_array($input['tid'], $supports->clicks) || $supportsDisabled):
				  ?> disabled<?php endif;?>" rel="<?php echo $input['tid']; ?>">
					<i class="icon-ok-sign"></i>
					<span class="badge" id="badge-<?php echo $input['tid']; ?>">(<?php echo $input['spprts']; ?>)</span>
					<span class="label">Dieser Meinung bin ich auch!</span>
				</a>
				<?php endif; ?>

				<a href="#">
					<i class="icon-comment"></i>
					<span class="badge">(<?php echo $input['pts']; ?>)</span>
					<span class="label">Das möchte ich gerne diskutieren!</span>
				</a>
			</article>

			<hr />
			<?php endforeach;?>
			<?php endif;?>

			<!-- Paging -->
			<?php
			echo $this->paginationControl($this->paginator,
		  'Jumping',
		  '_pagination.phtml',
			  array('titlePrev' => 'Neuere Beiträge', 'titleNext' => 'Ältere Beiträge')
			); ?>

			<hr />

			<!-- Print -->
			<a href="javascript:print();" class="print">Seite drucken <i class="icon-print"></i></a>
		</section>
	</div><!-- .row -->
</div><!-- .content-holder -->

<!-- Content end -->

<!-- Top link -->
<div class="top-link">
	<a href="#top" class="js-scroll"><i class="icon-chevron-up"></i> nach oben</a>
</div>
<script type="text/javascript">
$(document).ready(function() {
  $('.click-support').click(function(event) {
    event.preventDefault();
    var tid = $(this).attr('rel');
    if ($(this).hasClass('disabled')) {
      alert('Entweder hast du diesen Beitrag schon unterstützt oder unterstützen ist derzeit nicht möglich, weil z.B. der Unterstützungszeitraum bereits vorbei ist.');
    } else {
      $.post("<?php echo $this->baseUrl(); ?>/input/support/kid/<?php echo
        $this->consultation->kid; ?>/format/json", { "tid": tid })
      .done(function(data) {
        if (data.count) {
          $('#badge-' + tid).html("(" + data.count + ")");
        }
        $('#click-support-' + tid).addClass('disabled');
      });
    }
  });
});
</script>