<?php
/**
 * index
 *
 * @description   tags overview
 * @author        Markus Hackel
 */
?>

<?php echo $this->secondNavigation('input') ?>

<div class="main-content content-holder">
	<div class="row">
		<div class="text-center span10 offset1">

			<small class="count muted"><?php echo $this->inputCount ?> bestätigte Beiträge</small>
			<h1>Alle Beiträge im Überblick</h1>
			<p>Ihr wollt bei dieser Beteiligungsrunde mitmachen? Dann klickt während der Beitragsphase einfach auf eine Frage und schon öffnet sich das Eingabefeld für eure Beiträge. Nach dem Ende der Beitragsphase könnt ihr nicht mehr mitmachen, aber über den Klick auf die Frage alle eingegangenen Beiträge lesen.</p>

		</div>
	</div><!-- .row -->

	<!-- Questions -->
	<ul class="questions thumbnails">
		<?php if (!empty($this->tags)): ?>
			<li class="span11">
				<div class="thumbnail">
					<div class="thumbnail-content">
						<h2>Beiträge sortiert nach Schlagwörtern:</h2>
						<ul class="tag-cloud">
							<?php foreach ($this->tags as $tag): ?>
								<li class="tag-<?php echo $tag['frequency']; ?>">
									<a href="<?php echo $this->url(array('action' => 'show', 'tag' => $tag['tg_nr'])); ?>"><?php echo $tag['tg_de']; ?></a>
								</li>
							<?php endforeach; ?>
						</ul>
						<a href="<?php echo $this->url(array('action' => 'index')); ?>" class="btn">Zurück zur Fragenübersicht</a>
					</div>
				</div><!-- .thumbnail -->
			</li>
		<?php endif; ?>
	</ul><!-- .questions -->

	<?php echo $this->render('_partials/printLink.phtml') ?>

</div>

<?php echo $this->render('_partials/topLink.phtml') ?>
