<?php
/**
 * index
 *
 * @description   Übersicht der Artikel
 * @author        Markus Hackel
 */
//Zend_Debug::dump($this->consultation);
?>
<!-- Secondary navigation -->
<?php echo $this->secondNavigation('article')?>
<!-- .secondary-navigation -->

<!-- Content start -->

<div class="content-holder">
	<div class="row">
		<aside class="span3">

			<!-- Tertiary navigation -->
<?php echo $this->articleNavigation();?>
			<!-- .tertiary-navigation -->

		</aside>
		<section class="main-content span6">
			<?php echo html_entity_decode($this->consultation->expl); ?>
			<!-- Print -->
			<a href="javascript:print();" class="print">Seite drucken <i class="icon-print"></i></a>
		</section>
		<aside class="span3">

		</aside>
	</div><!-- .row -->
</div><!-- .content-holder -->

<!-- Content end -->

<!-- Top link -->
<div class="top-link">
	<a href="#top" class="js-scroll"><i class="icon-angle-up icon-large"></i> nach oben</a>
</div>