<?php echo $this->secondNavigation('article') ?>

<div class="main-content">
    <div class="row">
        <div class="sidebar-left">

            <?php echo $this->articleNavigation(null, 'info'); ?>

        </div>
        <div class="content">

            <article class="article article-detail">
                <?php echo html_entity_decode($this->consultation->expl, ENT_COMPAT, 'UTF-8'); ?>
            </article>

            <?php echo $this->render('_partials/printLink.phtml') ?>

        </div>
    </div><!-- .row -->
</div><!-- .main-content -->

<?php echo $this->render('_partials/topLink.phtml') ?>
