<?php
/**
 * index
 *
 * @description   Übersicht der Artikel
 * @author        Markus Hackel
 */
//Zend_Debug::dump($this->consultation);
?>
<!-- Secondary navigation -->
<?php echo $this->secondNavigation('article')?>
<!-- .secondary-navigation -->

<!-- Content start -->

<div class="content-holder">
	<div class="row">
		<aside class="span3">

			<!-- Tertiary navigation -->
			<?php echo $this->articleNavigation(null, 'info');?>
			<!-- .tertiary-navigation -->

		</aside>
		<section class="main-content span6">

			<?php echo html_entity_decode($this->consultation->expl, ENT_COMPAT, 'UTF-8'); ?>

			<?php echo $this->render('_partials/printLink.phtml')?>

		</section>
		<aside class="span3">

		</aside>
	</div><!-- .row -->
</div><!-- .content-holder -->

<!-- Content end -->

<?php echo $this->render('_partials/topLink.phtml')?>
