<?php
/**
 * Article
 *
 * @description   Detailansicht Artikel
 * @author        Markus Hackel
 */
?>

<?php if ($this->consultation): ?>
    <?php echo $this->secondNavigation('article') ?>
<?php endif; ?>

<div class="main-content">
    <div class="row">
        <div class="sidebar-left hidden-print">

            <!-- Tertiary navigation -->
            <?php if ($this->article['ref_nm'] != 'about'): // do not show tertiary navigation on "about" page ?>
                <?php echo $this->articleNavigation($this->article['art_id'], 'info'); ?>
            <?php endif; ?>

        </div>
        <div class="content content-narrow">

            <article class="article">
                <?php echo html_entity_decode($this->article['artcl'], ENT_COMPAT, 'UTF-8'); ?>
            </article>

        </div>
        <aside class="sidebar-right hidden-print">

            <?php echo html_entity_decode($this->article['sidebar'], ENT_COMPAT, 'UTF-8'); ?>

        </aside>
    </div><!-- .row -->

    <?php if ($this->consultation): ?>
        <?=$this->partial('_partials/pageLinks.phtml', ['help' => 'help-text-consultation-info']);?>
    <?php else: ?>
        <?=$this->partial('_partials/pageLinks.phtml');?>
    <?php endif; ?>

</div><!-- .main-content -->
