<?php
/**
 * Article
 *
 * @description   Detailansicht Artikel
 * @author        Markus Hackel
 */
?>
<?php if ($this->consultation): ?>
<!-- Secondary navigation -->
<?php echo $this->secondNavigation('article')?>
<!-- .secondary-navigation -->
<?php endif; ?>

<!-- Content start -->

<div class="content-holder">
	<div class="row">
		<aside class="span3">

			<!-- Tertiary navigation -->
<?php echo $this->articleNavigation($this->article['art_id']);?>
			<!-- .tertiary-navigation -->

		</aside>
		<section class="main-content span6">
<?php echo html_entity_decode($this->article['artcl'], ENT_COMPAT, 'UTF-8');?>
			<!-- Print -->
			<a href="javascript:print();" class="print">Seite drucken <i class="icon-print"></i></a>
		</section>
		<aside class="span3">
<?php echo html_entity_decode($this->article['sidebar'], ENT_COMPAT, 'UTF-8');?>
		</aside>
	</div><!-- .row -->
</div><!-- .content-holder -->

<!-- Content end -->

<!-- Top link -->
<div class="top-link">
	<a href="#top" class="js-scroll"><i class="icon-angle-up icon-large"></i> nach oben</a>
</div>