<?php if (!isset($this->useSvgPathOnly)) : ?>
\<svg width="100%" height="100%" viewBox="0 0 56 44" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xml:space="preserve" xmlns:serif="http://www.serif.com/" style="fill-rule:evenodd;clip-rule:evenodd;stroke-linejoin:round;stroke-miterlimit:1.41421;">
<?php endif; ?>

    <g id="label-hearts-disagree">
        <ellipse cx="28" cy="22" rx="28" ry="22" style="fill:none;" />
        <g>
            <path d="M33.425,21.407c0,0.718 -0.394,1.365 -1.022,1.813l0.005,0l-3.391,2.664c-0.339,0.267 -0.678,0.533 -1.017,0.533c-0.339,0 -0.678,-0.266 -1.017,-0.533l-3.391,-2.664l0.005,0c-0.628,-0.448 -1.022,-1.095 -1.022,-1.813c0,-1.353 1.396,-2.449 3.117,-2.449c0.915,0 1.738,0.491 2.308,0.984c0.57,-0.493 1.393,-0.984 2.308,-0.984c1.721,0 3.117,1.096 3.117,2.449" style="fill:#fff;fill-rule:nonzero;" />
            <ellipse cx="28" cy="22" rx="8.75" ry="6.875" style="fill:none;" />
        </g>
    </g>

<?php if (!isset($this->useSvgPathOnly)) : ?>
</svg>
<?php endif; ?>
