<tr
    data-admin-confirmation="<?=$this->escape($this->input['block']);?>"
    data-origin="<?=$this->input['rel_tid'] ? 'adminCreated' : 'userCreated';?>"
    data-voting="<?=$this->escape($this->input['vot']);?>"
    data-tags='<?=json_encode(array_map(function($el) {return $el['tg_nr'];}, $this->input['tags']));?>'
    data-directory="<?=$this->escape($this->input['dir']);?>"
>
    <td class="table-cell-id table-cell-top">
        <div class="checkbox">
            <?php if (empty($this->readonly)): ?>
                <label>
                    <input type ="checkbox" name="inputIds[]" value="<?=$this->escape($this->input['tid']);?>" />
                    <?=$this->escape($this->input['tid']);?>
                </label>
            <?php else: ?>
                <?=$this->escape($this->input['tid']);?>
            <?php endif; ?>
        </div>
    </td>
    <td class="table-cell-top">

        <?php if (!empty($this->input['thes'])): ?>
            <h5><?=$this->translate('Contribution');?></h5>
            <p class="overflow-horizontal"><?=$this->escape($this->input['thes']);?></p>
        <?php endif; ?>

        <?php if (!empty($this->input['expl'])): ?>
            <h5><?=$this->translate('Explanation');?></h5>
            <p class="overflow-horizontal"><?=$this->escape($this->input['expl']);?></p>
        <?php endif; ?>

        <?php if (!empty($this->input['notiz'])): ?>
            <h5><?=$this->translate('Internal note');?></h5>
            <p class="overflow-horizontal"><?=$this->escape($this->input['notiz']);?></p>
        <?php endif; ?>

        <p>
            <small>
                <?php if (!empty($this->input['name'])): ?>
                    <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                    <a href="<?=$this->url(['controller' => 'user', 'action' => 'edit', 'uid' => $this->input['uid']]);?>"><?=$this->escape($this->input['name']);?></a>,
                <?php endif; ?>
                <?=$this->formatDate($this->input['when']);?>
            </small>
        </p>

        <?php if (!empty($this->input['tags'])): ?>
            <p>
                <?php foreach($this->input['tags'] as $tag): ?>
                    <span class="label label-primary"><?=$this->escape($tag['tg_de']);?></span>
                <?php endforeach; ?>
            </p>
        <?php endif; ?>

        <h5>
            <?=$this->translate('Related');?>
            <a
                href="<?=$this->url(['action' => 'add-related', 'inputId' => $this->escape($this->input['tid'])]);?>"
                class="item-action"
                title="<?=$this->translate('Add related contributions');?>"
            >
                <span class="glyphicon glyphicon-plus-sign icon-shift-down" aria-hidden="true"></span>
            </a>
        </h5>
        <?php if (!empty($this->input['related'])): ?>
            <ul>
                <?php foreach ($this->input['related'] as $relInput): ?>
                    <li>
                        <a
                            href="<?=$this->url(['controller' => 'input', 'action' => 'edit', 'tid' => $relInput['tid'], 'return' => 'votingprepare']);?>"
                        >
                            <?=$this->escape($relInput['thes']);?>
                        </a>

                        <button
                            name="unlink"
                            value="<?=$relInput['tid'] . '-' . $this->input['tid'];?>"
                            class="item-action item-action-danger"
                            data-toggle="confirm"
                            title="<?=$this->translate('Unlink contribution');?>"
                            data-confirm-message="<?=$this->translate('Unlink contribution');?>?"
                        >
                            <span class="glyphicon glyphicon-remove-sign" aria-hidden="true"></span>
                        </button>
                    </li>
                <?php endforeach; ?>
            </ul>
        <?php endif; ?>

    </td>
    <td class="col-xs-3 table-cell-top">

        <p>
            <?=$this->translate('Origin');?><br />
            <span class="label label-info">
                <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                <?=$this->input['rel_tid'] ? $this->translate('Admin') : $this->translate('User');?>
            </span>
        </p>
        <p>
            <?=$this->translate('Admin Confirmation');?><br />
            <?php if ($this->input['block'] === 'y'): ?>
                <span class="label label-danger">
                    <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                    <?=$this->translate('Blocked');?>
                </span>
            <?php elseif ($this->input['block'] === 'n'): ?>
                <span class="label label-success">
                    <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
                    <?=$this->translate('Confirmed');?>
                </span>
            <?php else: ?>
                <span class="label label-default">
                    <span class="glyphicon glyphicon-question-sign" aria-hidden="true"></span>
                    <?=$this->translate('Unknown');?>
                </span>
            <?php endif; ?>
        </p>
        <p>
            <?=$this->translate('Voting');?><br />
            <?php if ($this->input['vot'] === 'y'): ?>
                <span class="label label-success">
                    <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
                    <?=$this->translate('Yes');?>
                </span>
            <?php elseif ($this->input['vot'] === 'n'): ?>
                <span class="label label-danger">
                    <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                    <?=$this->translate('No');?>
                </span>
            <?php else: ?>
                <span class="label label-default">
                    <span class="glyphicon glyphicon-question-sign" aria-hidden="true"></span>
                    <?=$this->translate('Unknown');?>
                </span>
            <?php endif; ?>
        </p>

    </td>
    <?php if(empty($this->readonly)): ?>
        <td class="col-xs-1 table-cell-top text-center">
            <a
                class="item-action"
                href="<?=$this->url(['controller' => 'input', 'action' => 'edit', 'tid' => $this->input['tid'], 'return' => 'votingprepare']);?>"
                title="<?=$this->translate('Edit contribution');?>"
            >
                <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
            </a>
            <a
                class="item-action"
                href="<?=$this->url(['action' => 'copy', 'inputId' => $this->input['tid']]);?>"
                title="<?=$this->translate('Copy contribution');?>"
            >
                <span class="glyphicon glyphicon-th-large" aria-hidden="true"></span>
            </a>
            <a
                class="item-action"
                href="<?=$this->url(['action' => 'split', 'inputId' => $this->input['tid']]);?>"
                title="<?=$this->translate('Split contribution');?>"
            >
                <span class="glyphicon glyphicon-resize-full" aria-hidden="true"></span>
            </a>
            <button
                class="item-action item-action-danger"
                name="delete"
                value="<?=$this->escape($this->input['tid']);?>"
                data-toggle="confirm"
                data-confirm-message="<?=$this->translate('Delete contribution?');?>"
                title="<?=$this->translate('Delete contribution');?>"
            >
                <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
            </button>
        </td>
    <?php endif; ?>
</tr>
