<section class="section-header has-tabs">
    <div class="container">

        <h1><?=$this->escape($this->consultation['titl']);?></h1>
        <h2><?=$this->escape($this->consultation['titl_sub']);?></h2>

        <?=$this->consultationTabs($this->consultation['kid'], 'consultation');?>

    </div>
</section>
<section class="section-content">
    <div class="container">
        <div class="row">
            <div class="sidebar">

                <?=$this->consultationNavigation($this->consultation, 'voting-prepare');?>

            </div>
            <div class="content">

                <a href="<?=$this->url(['action' => 'overview', 'inputId' => null]);?>" class="back"><?=$this->translate('Back to Voting Preparation');?></a>
                <h2><?=$this->translate('Copy Contribution');?></h2>
                <?=$this->form;?>

            </div>
        </div>
    </div>
</section>
