<section class="section-header has-tabs">
    <div class="container">

        <h1 class="section-header-title"><?=$this->consultation['titl'];?></h1>
        <h2 class="section-header-subtitle"><?=$this->consultation['titl_sub'];?></h2>

        <?=$this->consultationTabs($this->consultation['kid'], 'consultation');?>

    </div>
</section>
<section class="section-content">
    <div class="container">
        <div class="row">
            <div class="sidebar">

                <?=$this->consultationNavigation($this->consultation['kid'], 'voting-prepare');?>

            </div>
            <div class="content">

                <a href="<?=$this->url(['action' => 'overview']);?>" class="back"><?= $this->translate('Back to Voting Preparation');?></a>

                <h2><?=$this->translate('Create Folder');?></h2>
                <?=$this->form;?>

            </div>
        </div>
    </div>
</section>
