<section class="section-header has-tabs">
    <div class="container">

        <h1><?=$this->consultation['titl'];?></h1>
        <h2><?=$this->consultation['titl_sub'];?></h2>

        <?=$this->consultationTabs($this->consultation['kid'], 'consultation');?>

    </div>
</section>
<section class="section-content">
    <div class="container">
        <div class="row">
            <div class="sidebar">

                <?=$this->consultationNavigation($this->consultation['kid'], 'voting-prepare');?>

            </div>
            <div class="content">

                <a href="<?=$this->url(['action' => 'overview']);?>" class="back">
                    &larr; <?= $this->translate('Back to Voting');?>
                </a>

                <h2><?=$this->translate('Voting');?></h2>

                <h3><?=$this->translate('Create direcotry');?></h3>
                <?=$this->form;?>

            </div>
        </div>
    </div>
</section>
