<section class="section-header has-tabs">
    <div class="container">

        <h1 class="section-header-title"><?=$this->escape($this->consultation['titl']);?></h1>
        <h2 class="section-header-subtitle"><?=$this->escape($this->consultation['titl_sub']);?></h2>

        <?=$this->consultationTabs($this->consultation['kid'], 'consultation');?>

    </div>
</section>
<section class="section-content">
    <div class="container">
        <div class="row">
            <div class="sidebar">

                <?=$this->consultationNavigation($this->consultation, 'voting-prepare');?>

            </div>
            <div class="content">

                <h2><?=$this->translate('Voting Preparation');?></h2>

                <?php if (!empty($this->consultation['questions'])): ?>
                    <table class="table">
                        <thead>
                            <tr>
                                <th class="table-cell-id sorting-asc" data-toggle="sort" tabindex="0">#</th>
                                <th data-toggle="sort" tabindex="0"><?=$this->translate('Question');?></th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach($this->consultation['questions'] as $question): ?>
                                <tr>
                                    <td class="table-cell-id"><?=$this->escape($question['nr']);?></td>
                                    <td>
                                        <a href="<?=$this->url(['controller' => 'votingprepare', 'action' => 'overview', 'kid' => $question['kid'], 'qid' => $question['qi']]);?>">
                                            <?=strip_tags(html_entity_decode($question['q']));?>
                                        </a>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                <?php else: ?>
                    <p class="alert alert-info">
                        <span class="glyphicon glyphicon-info-sign"></span>
                        <?=$this->translate('There are no questions yet.');?>
                    </p>
                <?php endif; ?>

            </div>
        </div>
    </div>
</section>


