<section class="section-header has-tabs">
    <div class="container">

        <h1><?=$this->consultation['titl'];?></h1>
        <h2><?=$this->consultation['titl_sub'];?></h2>

        <?=$this->consultationTabs($this->consultation['kid'], 'consultation');?>

    </div>
</section>
<section class="section-content">
    <div class="container">
        <div class="row">
            <div class="sidebar">

                <?=$this->consultationNavigation($this->consultation['kid'], 'voting-prepare');?>

            </div>
            <div class="content">

                <a href="<?=$this->url(['action' => 'overview', 'inputIds' => null]);?>" class="back"><?=$this->translate('Back to Voting Preparation');?></a>
                <h2><?=$this->translate('Merge Contributions');?></h2>

                <h3><?=$this->translate('Original Contributions');?></h3>
                <table class="table table-bordered">
                    <tbody>
                        <?php foreach ($this->inputs as $input): ?>
                            <?=$this->partial('votingprepare/_input-row.phtml', ['input' => $input, 'readonly' => true])?>
                        <?php endforeach;?>
                    </tbody>
                </table>

                <h3><?=$this->translate('New Contribution');?></h3>
                <?php echo $this->form?>

            </div>
        </div>
    </div>
</section>
