<section class="section-header has-tabs">
    <div class="container">

        <h1><?=$this->consultation['titl'];?></h1>
        <h2><?=$this->consultation['titl_sub'];?></h2>

        <?=$this->consultationTabs($this->consultation['kid'], 'consultation');?>

    </div>
</section>
<section class="section-content">
    <div class="container">
        <div class="row">
            <div class="sidebar">

                <?=$this->consultationNavigation($this->consultation['kid'], 'voting-prepare');?>

            </div>
            <div class="content">

                <h2><?=$this->translate('Voting');?></h2>

                <h3><?=$this->translate('Contribution merge');?></h3>
                <div>
                    <h3><?=$this->translate('Original inputs');?></h3>
                    <form>
                        <table id="contribution-table">
                            <tbody>
                                <?php foreach ($this->inputs as $input): ?>
                                    <?=$this->partial('_partials/votingprepare/inputs.phtml', ['input' => $input])?>
                                <?php endforeach;?>
                            </tbody>
                        </table>
                    </form>
                </div>

                <div>
                    <h3><?=$this->translate('New input');?></h3>
                    <?php echo $this->form?>
                </div>

            </div>
        </div>
    </div>
</section>
