<section class="section-header has-tabs">
    <div class="container">

        <h1 class="section-header-title"><?=$this->consultation['titl'];?></h1>
        <h2 class="section-header-subtitle"><?=$this->consultation['titl_sub'];?></h2>

        <?=$this->consultationTabs($this->consultation['kid'], 'consultation');?>

    </div>
</section>
<section class="section-content">
    <div class="container">
        <div class="row">
            <div class="sidebar">

                <?=$this->consultationNavigation($this->consultation['kid'], 'voting-prepare');?>

            </div>
            <div class="content">

                <a href="<?=$this->url(['action' => 'index']);?>" class="back"><?=$this->translate('Back to Questions');?></a>
                <h2><?=$this->translate('Voting Preparation');?></h2>

                <!-- Search -->
                <form method="get">
                    <div class="form-group">
                        <div class="input-group">
                            <input
                                name="fulltext"
                                type="search"
                                class="form-control"
                                value="<?=$this->fulltext;?>"
                                placeholder="<?=$this->translate('Search contributions');?>"
                            />
                            <span class="input-group-btn">
                                <button type="submit" class="btn btn-primary">
                                    <span class="glyphicon glyphicon-search"></span>
                                    <?=$this->translate('Search');?>
                                </button>
                            </span>
                        </div>
                    </div>
                </form>

                <!-- Filters -->
                <div class="panel-group">

                    <!-- Common filter -->
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <a data-toggle="collapse" href="#filterCommon">
                                <h3 class="panel-title">
                                    <span class="glyphicon glyphicon-chevron-down pull-right"></span>
                                    <span class="glyphicon glyphicon-filter"></span>
                                    <?=$this->translate('Filter');?>
                                </h3>
                            </a>
                        </div>
                        <div id="filterCommon" class="panel-collapse collapse">
                            <div class="panel-body">

                                <form data-filter-target="#contribution-table tr" class="form-filter">
                                    <div class="row">
                                        <div class="col-sm-4">
                                            <div class="form-group">
                                                <label><?=$this->translate('Admin Confirmation');?></label>
                                                <select
                                                    class="form-control"
                                                    data-toggle="filter"
                                                    data-filter-attrib="admin-confirmation"
                                                    data-filter-operator="intersect"
                                                >
                                                    <option value=""><?=$this->translate('All');?></option>
                                                    <option value="u"><?=$this->translate('Waiting for revision');?></option>
                                                    <option value="n"><?=$this->translate('Confirmed');?></option>
                                                    <option value="y"><?=$this->translate('Blocked');?></option>
                                                </select>
                                            </div>
                                        </div>
                                        <div class="col-sm-4">
                                            <div class="form-group">
                                                <label></span> <?=$this->translate('Origin');?></label>
                                                <select
                                                    class="form-control"
                                                    data-toggle="filter"
                                                    data-filter-attrib="origin"
                                                    data-filter-operator="intersect"
                                                >
                                                    <option value=""><?=$this->translate('All');?></option>
                                                    <option value="userCreated"><?=$this->translate('User created');?></option>
                                                    <option value="adminCreated"><?=$this->translate('Admin created');?></option>
                                                </select>
                                            </div>
                                        </div>
                                        <div class="col-sm-4">
                                            <div class="form-group">
                                                <label><?=$this->translate('Voting');?></label>
                                                <select
                                                    class="form-control"
                                                    data-toggle="filter"
                                                    data-filter-attrib="voting"
                                                    data-filter-operator="intersect"
                                                >
                                                    <option value=""><?=$this->translate('All');?></option>
                                                    <option value="u"><?=$this->translate('Unknown');?></option>
                                                    <option value="y"><?=$this->translate('Allowed');?></option>
                                                    <option value="n"><?=$this->translate('Blocked');?></option>
                                                </select>
                                            </div>
                                        </div>
                                    </div><!-- .row -->

                                    <div class="row">
                                        <div class="col-sm-4">
                                            <div class="form-group">
                                                <label><?=$this->translate('Folder');?></label>
                                                <select
                                                    class="form-control"
                                                    data-toggle="filter"
                                                    data-filter-attrib="directory"
                                                    data-filter-operator="="
                                                >
                                                    <option value=""><?=$this->translate('All folders');?></option>
                                                    <option value="0"><?=$this->translate('Folder root');?></option>
                                                    <?php foreach($this->directories as $directory): ?>
                                                        <option value="<?=$directory['id'];?>">
                                                            <?=$directory['dir_name'];?> (<?=$directory['count'];?>)
                                                        </option>
                                                    <?php endforeach?>
                                                </select>
                                            </div>
                                        </div>
                                        <div class="col-sm-6">
                                            <div class="form-group">
                                                <label for="tags"><?=$this->translate('Tags');?></label>
                                                <select
                                                    name="tags[]"
                                                    class="form-control js-select2"
                                                    multiple
                                                    data-toggle="filter"
                                                    data-filter-attrib="tags"
                                                    data-filter-operator="subset"
                                                >
                                                    <?php foreach ($this->tags as $tag): ?>
                                                        <option
                                                            value="<?=$tag['tg_nr'];?>"
                                                            <?=!empty($tag['selected']) ? 'selected="selected"' : '';?>
                                                        >
                                                            <?=$tag['tg_de'];?>
                                                        </option>
                                                    <?php endforeach;?>
                                                </select>
                                            </div>
                                        </div>
                                        <div class="col-sm-2">
                                            <div class="form-actions">
                                                <button
                                                    type="button"
                                                    class="btn btn-default"
                                                    data-toggle="filter-reset"
                                                >
                                                    <?=$this->translate('Reset Filter');?>
                                                </button>
                                            </div>
                                        </div>
                                    </div><!-- .row -->
                                </form>

                            </div>
                        </div>
                    </div><!-- .panel -->

                    <!-- Folders -->
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <a data-toggle="collapse" href="#filterFolders">
                                <h3 class="panel-title">
                                    <span class="glyphicon glyphicon-chevron-down pull-right"></span>
                                    <span class="glyphicon glyphicon-folder-close"></span>
                                    <?=$this->translate('Folders');?>
                                </h3>
                            </a>
                        </div>
                        <div id="filterFolders" class="panel-collapse collapse">
                            <div class="panel-body">

                                <p>
                                    <a href="<?=$this->url(['action' => 'create-directory']);?>">
                                        <span class="glyphicon glyphicon-plus-sign"></span>
                                        <?=$this->translate('Add folder');?>
                                    </a>
                                </p>

                                <form
                                    method="<?=$this->form->getMethod();?>"
                                    action="<?=$this->url(['action' => 'directory-list-control']);?>"
                                >
                                    <?=$this->form->getElement($this->form->getCsrfTokenName());?>
                                    <div class="list-group sortable js-sortable-voting-directory">
                                        <?php foreach($this->directories as $directory): ?>
                                            <div class="list-group-item">
                                                <span class="glyphicon glyphicon-move"></span>
                                                <?=$directory['dir_name'];?>
                                                <button
                                                    class="item-action item-action-danger"
                                                    name="delete"
                                                    value="<?=$directory['id'];?>"
                                                    data-toggle="confirm"
                                                    data-confirm-message="<?=$this->translate('Delete folder?');?>"
                                                    >
                                                    <span class="glyphicon glyphicon-trash"></span>
                                                </button>
                                                <span class="badge"><?=$directory['count'];?></span>
                                                <input type="hidden" name="order[<?=$directory['id'];?>]" value="<?=$directory['order'];?>" />
                                            </div>
                                        <?php endforeach;?>
                                    </div>
                                    <button type="submit" name="saveOrder" value="1" class="btn btn-default" disabled>
                                        <?=$this->translate('Save changes');?>
                                    </button>
                                </form>

                            </div>
                        </div>
                    </div><!-- .panel -->

                </div><!-- .panel-group -->

                <!-- Contributions -->
                <form method="<?=$this->form->getMethod();?>" action="<?=$this->url(['action' => 'input-list-control']);?>">

                    <!-- Actions -->
                    <div class="well well-sm">
                        <?=$this->form->getElement($this->form->getCsrfTokenName());?>

                        <div class="row">
                            <div class="col-xs-1">

                                <div class="checkbox-inline">
                                    <label for="markAllTop" class="sr-only">
                                        <?=$this->translate('Mark all contributions');?>
                                    </label>
                                    <input
                                        type="checkbox"
                                        id="markAllTop"
                                        class="js-toggle-all"
                                        title="<?=$this->translate('Mark all contributions');?>"
                                    />
                                </div>

                            </div>
                            <div class="col-xs-11">

                                <div class="form-group">
                                    <div class="btn-toolbar">

                                        <div class="btn-group">
                                            <button class="btn btn-default" name="merge" value="1" type="submit">
                                                <span class="glyphicon glyphicon-resize-small"></span>
                                                <span class="hidden-xs hidden-md"><?=$this->translate('Merge');?></span>
                                            </button>
                                        </div>

                                        <div class="btn-group">
                                            <button
                                                class="btn btn-default"
                                                name="releaseBulk"
                                                type="submit"
                                                value="1"
                                                data-toggle="confirm"
                                                data-confirm-message="<?=$this->translate('Release contributions?');?>"
                                                >
                                                <span class="glyphicon glyphicon-ok-sign"></span>
                                                <span class="hidden-xs"><?=$this->translate('Release');?></span>
                                            </button>
                                            <button
                                                class="btn btn-default"
                                                name="blockBulk"
                                                type="submit"
                                                value="1"
                                                data-toggle="confirm"
                                                data-confirm-message="<?=$this->translate('Block contributions?');?>"
                                                >
                                                <span class="glyphicon glyphicon-ban-circle"></span>
                                                <span class="hidden-xs"><?=$this->translate('Block');?></span>
                                            </button>
                                        </div>

                                        <div class="btn-group">
                                            <button
                                                class="btn btn-default"
                                                name="enableVotingBulk"
                                                type="submit"
                                                value="1"
                                                data-toggle="confirm"
                                                data-confirm-message="<?=$this->translate('Set contributions for voting?');?>"
                                                >
                                                <span class="glyphicon glyphicon-star"></span>
                                                <span class="hidden-xs"><?=$this->translate('Allow for voting');?></span>
                                            </button>
                                            <button
                                                class="btn btn-default"
                                                name="blockVotingBulk"
                                                type="submit"
                                                value="1"
                                                data-toggle="confirm"
                                                data-confirm-message="<?=$this->translate('Ban contributions from voting?');?>"
                                                >
                                                <span class="glyphicon glyphicon-star-empty"></span>
                                                <span class="hidden-xs"><?=$this->translate('Ban from voting');?></span>
                                            </button>
                                        </div>

                                        <div class="btn-group">
                                            <button
                                                class="btn btn-danger"
                                                name="deleteBulk"
                                                type="submit"
                                                value="1"
                                                data-toggle="confirm"
                                                data-confirm-message="<?=$this->translate('Delete contributions?');?>"
                                                >
                                                <span class="glyphicon glyphicon-trash"></span>
                                                <span class="visible-lg-inline"><?=$this->translate('Delete');?></span>
                                            </button>
                                        </div>

                                    </div><!-- .btn-toolbar -->
                                </div><!-- .form-group -->

                                <div class="input-group">
                                    <select class="form-control" name="sendToDictionaryId">
                                        <option value="0"><?=$this->translate('Folder root');?></option>
                                        <?php foreach($this->directories as $directory): ?>
                                            <option value="<?=$directory['id'];?>">
                                                <?=$directory['dir_name'];?> (<?=$directory['count'];?>)
                                            </option>
                                        <?php endforeach?>
                                    </select>
                                    <span class="input-group-btn">
                                        <button
                                            class="btn btn-default"
                                            name="sendToDictionaryBulk"
                                            type="submit"
                                            value="1"
                                            data-toggle="confirm"
                                            data-confirm-message="<?=$this->translate('Move contributions?');?>"
                                            >
                                            <?=$this->translate('Move to folder');?>
                                        </button>
                                    </span>
                                </div>

                            </div>
                        </div><!-- .row -->
                    </div><!-- .well -->

                    <!-- Contribution listing -->
                    <table id="contribution-table" class="table table-bordered table-responsive js-table-rows-toggle">
                        <tbody>
                            <?php foreach ($this->inputs as $input): ?>
                                <?=$this->partial('votingprepare/_input-row.phtml', ['input' => $input])?>
                            <?php endforeach;?>
                        </tbody>
                    </table>

                </form>

            </div>
        </div>
    </div>
</section>
