<section class="section-header has-tabs">
    <div class="container">

        <h1><?=$this->consultation['titl'];?></h1>
        <h2><?=$this->consultation['titl_sub'];?></h2>

        <?=$this->consultationTabs($this->consultation['kid'], 'consultation');?>

    </div>
</section>
<section class="section-content">
    <div class="container">
        <div class="row">
            <div class="sidebar">

                <?=$this->consultationNavigation($this->consultation['kid'], 'voting-prepare');?>

            </div>
            <div class="content">

                <h2><?=$this->translate('Voting');?></h2>

                <div id="directoryAnchors" class="yform">
                    <h3><?=$this->translate('Folders');?></h3>
                    <ul>
                        <?php foreach($this->directories as $directory): ?>
                            <li>
                                <?php for ($i = 0; $i < $directory['depth']; $i++): ?>
                                    &nbsp;&nbsp;&nbsp;
                                <?php endfor;?>
                                <?=$directory['dir_name'];?> (<?=$directory['count'];?>)
                            </li>
                        <?php endforeach?>
                    </ul>
                </div>

                <div>
                    <h3><?=$this->translate('Search');?></h3>
                    <form method="get">
                        <div class="row">
                            <div class="form-group">
                                <input
                                    name="fulltext"
                                    type="text"
                                    value="<?=$this->fulltext;?>"
                                />
                            </div>
                            <div class="form-actions">
                                <button
                                    type="submit"
                                    class="btn btn-default"
                                >
                                    <?=$this->translate('Search');?>
                                </button>
                            </div>
                        </div><!-- .row -->
                    </form>
                </div>

                <div>
                    <h3><?=$this->translate('Filter');?></h3>
                    <form>
                        <label for="inputs">
                            <input id="inputs" class="inputs" type="checkbox" checked="checked">
                            Alle Beiträge
                        </label>
                        <label for="unfinished">
                            <input id="unfinished" class="unfinished" type="checkbox">
                            Unerledigte Beiträge
                        </label>
                        <label for="finished">
                            <input id="finished" class="finished" type="checkbox">
                            Erledigte Beiträge
                        </label>
                        <label for="org-hidden">
                            <input id="org-hidden" class="org-hidden" type="checkbox">
                            Ausgeblendete Originale
                        </label>
                        <label for="org-o">
                            <input id="org-o" class="org-o" type="checkbox">
                            Originale
                        </label>
                        <label for="org-r">
                            <input id="org-r" class="org-r" type="checkbox">
                            Redaktionsbeiträge:
                        </label>
                        <label for="vot-y">
                            <input id="vot-y" class="vot-y" type="checkbox">
                            Zur Abstimmung freigegegeben:
                        </label>
                        <label for="vot-n">
                            <input id="vot-n" class="vot-n" type="checkbox">
                            Zur Abstimmung nicht freigegeben
                        </label>
                        <label for="vot-orb">
                            <input id="vot-orb" class="vot-orb" type="checkbox">
                            Abstimmungsfreigaben ohne redaktionelle Beiträge
                        </label>
                        <label for="block-y">
                            <input id="block-y" class="block-y" type="checkbox">
                            Blockierte
                        </label>
                        <label for="block-n">
                            <input id="block-n" class="block-n" type="checkbox">
                            Nicht-Blockierte:
                        </label>
                        <label for="vot-u">
                            <input id="vot-u" class="vot-u" type="checkbox">
                            Unbearbeitete Beiträge: (vot-u)
                        </label>
                        <div class="row">
                            <div class="form-group">
                                <label for="tags"><?=$this->translate('Tags');?></label>
                                <select name="tags[]" class="form-control js-select2" multiple>
                                    <?php foreach ($this->tags as $tag): ?>
                                        <option
                                            value="<?=$tag['tg_nr'];?>"
                                            <?=!empty($tag['selected']) ? 'selected="selected"' : '';?>
                                        >
                                            <?=$tag['tg_de'];?>
                                        </option>
                                    <?php endforeach;?>
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="t-directory">Directory ???</label>
                                <input
                                    id="t-directory"
                                    name="directory"
                                    type="radio"
                                    value="<?=$this->directory;?>"
                                    <?=$this->dirs == $this->directory ? 'checked="checked"' : '';?>
                                />
                                <input name="directory" type="hidden" value="0" />
                            </div>
                            <button
                                type="button"
                                class="btn btn-default"
                                data-toggle="reset-filter"
                            >
                                <?=$this->translate('Reset Filter');?>
                            </button>
                        </div>
                    </form>
                </div>

                <div>
                    <h3><?=$this->translate('Inputs');?></h3>
                    <form method="<?=$this->form->getMethod();?>" action="<?=$this->url(['action' => 'update']);?>">
                        <div>
                            <?=$this->form->getElement($this->form->getCsrfTokenName());?>
                            <?=$this->translate('Marked entries');?>
                            <button class="btn btn-default" rel="/admin/votingprepare/split/<?=$this->getParams;?>">
                                <?=$this->translate('Split');?>
                            </button>
                            <button class="btn btn-default" rel="/admin/votingprepare/merge/<?=$this->getParams;?>">
                                <?=$this->translate('Merge');?>
                            </button>
                            <button
                                class="btn btn-default"
                                name="releaseBulk"
                                type="submit"
                                value="1"
                                data-toggle="confirm"
                                data-confirm-message="<?=$this->translate('Release inputs?');?>"
                            >
                                <?=$this->translate('Release');?>
                            </button>
                            <button
                                class="btn btn-default"
                                name="blockBulk"
                                type="submit"
                                value="1"
                                data-toggle="confirm"
                                data-confirm-message="<?=$this->translate('Block inputs?');?>"
                            >
                                <?=$this->translate('Block');?>
                            </button>
                            <button
                                class="btn btn-default"
                                name="enableVotingBulk"
                                type="submit"
                                value="1"
                                data-toggle="confirm"
                                data-confirm-message="<?=$this->translate('Set inputs for voting?');?>"
                            >
                                <?=$this->translate('Allow for voting');?>
                            </button>
                            <button
                                class="btn btn-default"
                                name="blockVotingBulk"
                                type="submit"
                                value="1"
                                data-toggle="confirm"
                                data-confirm-message="<?=$this->translate('Ban inoputs from voting?');?>"
                            >
                                <?=$this->translate('Ban from voting');?>
                            </button>
                            <button
                                class="btn btn-default"
                                name="deleteBulk"
                                type="submit"
                                value="1"
                                data-toggle="confirm"
                                data-confirm-message="<?=$this->translate('Delete inputs?');?>"
                            >
                                <?=$this->translate('Delete');?>
                            </button>
                        </div>

                        <div>
                            <table>
                                <tbody>
                                    <?php foreach ($this->inputs as $input): ?>
                                        <?=$this->partial('_partials/votingprepare/inputs.phtml', ['input' => $input])?>
                                    <?php endforeach;?>
                                </tbody>
                            </table>
                        </div>
                    </form>
                </div>

            </div>
        </div>
    </div>
</section>
