<section class="section-header has-tabs">
    <div class="container">

        <h1><?=$this->consultation['titl'];?></h1>
        <h2><?=$this->consultation['titl_sub'];?></h2>

        <?=$this->consultationTabs($this->consultation['kid'], 'consultation');?>

    </div>
</section>
<section class="section-content">
    <div class="container">
        <div class="row">
            <div class="sidebar">

                <?=$this->consultationNavigation($this->consultation['kid'], 'voting-prepare');?>

            </div>
            <div class="content">

                <h2><?=$this->translate('Voting');?></h2>

                <div id="directoryAnchors" class="yform">
                    <h3><?=$this->translate('Folders');?></h3>
                    <ul>
                        <?php foreach($this->directories as $directory): ?>
                            <li>
                                <?php for ($i = 0; $i < $directory['depth']; $i++): ?>
                                    &nbsp;&nbsp;&nbsp;
                                <?php endfor;?>
                                <?=$directory['dir_name'];?> (<?=$directory['count'];?>)
                            </li>
                        <?php endforeach?>
                    </ul>
                </div>

                <div>
                    <h3><?=$this->translate('Search');?></h3>
                    <form method="get">
                        <div class="row">
                            <div class="form-group">
                                <input
                                    name="fulltext"
                                    type="text"
                                    value="<?=$this->fulltext;?>"
                                />
                            </div>
                            <div class="form-actions">
                                <button
                                    type="submit"
                                    class="btn btn-default"
                                >
                                    <?=$this->translate('Search');?>
                                </button>
                            </div>
                        </div><!-- .row -->
                    </form>
                </div>

                <div>
                    <h3><?=$this->translate('Filter');?></h3>
                    <form data-target="#contribution-table tr">
                        <div class="row">
                            <div class="col-sm-4">
                                <div class="form-group">
                                    <label><?=$this->translate('Admin Confirmation');?></label>
                                    <select
                                        class="form-control"
                                        data-toggle="filter"
                                        data-target-attrib="admin-confirmation"
                                    >
                                        <option value=""><?=$this->translate('All');?></option>
                                        <option value="u"><?=$this->translate('Waiting for revision');?></option>
                                        <option value="n"><?=$this->translate('Confirmed');?></option>
                                        <option value="y"><?=$this->translate('Blocked');?></option>
                                    </select>
                                </div>
                            </div>
                            <div class="col-sm-4">
                                <div class="form-group">
                                    <label></span> <?=$this->translate('Origin');?></label>
                                    <select
                                        class="form-control"
                                        data-toggle="filter"
                                        data-target-attrib="origin"
                                    >
                                        <option value=""><?=$this->translate('All');?></option>
                                        <option value="userCreated"><?=$this->translate('User created');?></option>
                                        <option value="adminCreated"><?=$this->translate('Admin created');?></option>
                                    </select>
                                </div>
                            </div>
                            <div class="col-sm-4">
                                <div class="form-group">
                                    <label><?=$this->translate('Voting');?></label>
                                    <select
                                        class="form-control"
                                        data-toggle="filter"
                                        data-target-attrib="voting"
                                    >
                                        <option value=""><?=$this->translate('All');?></option>
                                        <option value="u"><?=$this->translate('Unknown');?></option>
                                        <option value="y"><?=$this->translate('Allowed');?></option>
                                        <option value="n"><?=$this->translate('Blocked');?></option>
                                    </select>
                                </div>
                            </div>
                        </div><!-- .row -->

                        <div class="row">
                            <div class="form-group">
                                <label for="tags"><?=$this->translate('Tags');?></label>
                                <select
                                    name="tags[]"
                                    class="form-control js-select2"
                                    multiple
                                    data-toggle="filter"
                                    data-target-attrib="tags"
                                >
                                    <?php foreach ($this->tags as $tag): ?>
                                        <option
                                            value="<?=$tag['tg_nr'];?>"
                                            <?=!empty($tag['selected']) ? 'selected="selected"' : '';?>
                                        >
                                            <?=$tag['tg_de'];?>
                                        </option>
                                    <?php endforeach;?>
                                </select>
                            </div>
                            <!--<div class="form-group">
                                <label for="t-directory">Directory ???</label>
                                <input
                                    id="t-directory"
                                    name="directory"
                                    type="radio"
                                    value="<?=$this->directory;?>"
                                    <?=$this->dirs == $this->directory ? 'checked="checked"' : '';?>
                                />
                                <input name="directory" type="hidden" value="0" />
                            </div>-->
                            <button
                                type="button"
                                class="btn btn-default"
                                data-toggle="reset-filter"
                            >
                                <?=$this->translate('Reset Filter');?>
                            </button>
                        </div>
                    </form>
                </div>

                <div>
                    <h3><?=$this->translate('Inputs');?></h3>
                    <form method="<?=$this->form->getMethod();?>" action="<?=$this->url(['action' => 'update']);?>">
                        <div>
                            <?=$this->form->getElement($this->form->getCsrfTokenName());?>
                            <?=$this->translate('Marked entries');?>
                            <button class="btn btn-default" rel="/admin/votingprepare/split/<?=$this->getParams;?>">
                                <?=$this->translate('Split');?>
                            </button>
                            <button class="btn btn-default" rel="/admin/votingprepare/merge/<?=$this->getParams;?>">
                                <?=$this->translate('Merge');?>
                            </button>
                            <button
                                class="btn btn-default"
                                name="releaseBulk"
                                type="submit"
                                value="1"
                                data-toggle="confirm"
                                data-confirm-message="<?=$this->translate('Release inputs?');?>"
                            >
                                <?=$this->translate('Release');?>
                            </button>
                            <button
                                class="btn btn-default"
                                name="blockBulk"
                                type="submit"
                                value="1"
                                data-toggle="confirm"
                                data-confirm-message="<?=$this->translate('Block inputs?');?>"
                            >
                                <?=$this->translate('Block');?>
                            </button>
                            <button
                                class="btn btn-default"
                                name="enableVotingBulk"
                                type="submit"
                                value="1"
                                data-toggle="confirm"
                                data-confirm-message="<?=$this->translate('Set inputs for voting?');?>"
                            >
                                <?=$this->translate('Allow for voting');?>
                            </button>
                            <button
                                class="btn btn-default"
                                name="blockVotingBulk"
                                type="submit"
                                value="1"
                                data-toggle="confirm"
                                data-confirm-message="<?=$this->translate('Ban inoputs from voting?');?>"
                            >
                                <?=$this->translate('Ban from voting');?>
                            </button>
                            <button
                                class="btn btn-default"
                                name="deleteBulk"
                                type="submit"
                                value="1"
                                data-toggle="confirm"
                                data-confirm-message="<?=$this->translate('Delete inputs?');?>"
                            >
                                <?=$this->translate('Delete');?>
                            </button>
                        </div>

                        <div>
                            <table id="contribution-table">
                                <tbody>
                                    <?php foreach ($this->inputs as $input): ?>
                                        <?=$this->partial('_partials/votingprepare/inputs.phtml', ['input' => $input])?>
                                    <?php endforeach;?>
                                </tbody>
                            </table>
                        </div>
                    </form>
                </div>

            </div>
        </div>
    </div>
</section>
