<form
    enctype="<?=$this->element->getEnctype();?>"
    method="<?=$this->element->getMethod();?>"
    class="offset-bottom"
    enctype="<?=$this->element->getEnctype();?>"
>
    <?php
    $translator = Zend_Registry::get('Zend_Translate');
    $elementName = 'button_type';
    $elementObject = $this->element->$elementName;
    ?>
    <div class="row" id="<?=$elementName?>-element" class="checkbox radio">
        <?php $iterator = 0; ?>
        <?php foreach ($elementObject->options as $name => $translation): ?>
            <?php $iterator++; ?>
            <?php $btnInnerImage = ($name === 'yesno' ? 'agree' : 'somewhat-agree'); ?>
            <label class="col-md-3 text-center offset-bottom" for="<?=$elementName . '-' . $name?>">
                <div>
                    <?=$this->partial('_svg/button.svg.phtml', ['btnLabel' => sprintf('_svg/' . Service_Voting::BUTTON_FILENAME_PATTERN, $name, $btnInnerImage)]);?>
                </div>
                <input type="radio"
                       name="<?=$elementName?>"
                       id="<?=$elementName . '-' . $name?>"
                       value="<?=$name?>"
                       <?=($elementObject->getValue() == $name) ? 'checked="checked"' : ''?>
                >
                <?=$translator->translate($translation)?>
                (<?=count(Service_Voting::BUTTONS_SET[$name])?>
                <?=$translator->translate('options')?>)
            </label>
        <?php endforeach; ?>
    </div>

    <?=$this->element->btn_no_opinion?>
    <?=$this->element->is_btn_important?>
    <?=$this->element->btn_important_label?>
    <?=$this->element->btn_important_max?>
    <?=$this->element->btn_important_factor?>
    <?=$this->element->csrf_token_settingsvotingsubmissionformadmin?>
    <?=$this->element->submit?>
    <?=$this->element->preview?>

</form>
