<form
    enctype="<?=$this->element->getEnctype();?>"
    method="<?=$this->element->getMethod();?>"
    class="offset-bottom"
    enctype="<?=$this->element->getEnctype();?>"
    id="js-voting-button-sets-settings-form"
>
    <?php
        $translator = Zend_Registry::get('Zend_Translate');
        $elementName = 'button_type';
        $elementObject = $this->element->{$elementName};
    ?>
    <div class="row" id="<?=$elementName;?>-element" class="checkbox radio offset-top-large">
        <?php foreach ($elementObject->options as $name => $translation): ?>
            <?php $btnInnerImage = ($name === 'yesno' ? 'agree' : 'somewhat-agree'); ?>
            <label class="col-sm-4 text-center offset-bottom" for="<?=$elementName . '-' . $name;?>">
                <div>
                    <?=$this->partial('_svg/button.svg.phtml', [
                        'btnLabel' => sprintf('_svg/' . Service_Voting::BUTTON_FILENAME_PATTERN, $name, $btnInnerImage),
                    ]);?>
                </div>
                <input type="radio"
                       class="js-button-set-selector"
                       name="<?=$elementName;?>"
                       id="<?=$elementName . '-' . $name;?>"
                       value="<?=$name;?>"
                       <?=($elementObject->getValue() == $name) ? 'checked="checked"' : '';?>
                >
                <?=$translator->translate($translation)?>
            </label>
        <?php endforeach; ?>
    </div>

    <hr />

    <?php foreach ($this->element->buttonSets->getSubForms() as $buttonType => $buttonsSet): ?>
        <div class="js-button-set js-button-set-<?=$buttonType;?>">
        <?php foreach ($buttonsSet->getSubForms() as $points => $button): ?>
            <div class="row">
                <div class="col-sm-2">
                    <div class="form-control-static">
                        <?=$this->partial('_svg/button.svg.phtml', [
                            'btnLabel' => sprintf(
                                '_svg/' . Service_Voting::BUTTON_FILENAME_PATTERN,
                                $buttonType,
                                Service_Voting::BUTTONS_SET[$buttonType]['buttons'][$points]['id']
                            ),
                            'width' => '80',
                            'height' => '76',
                        ]);?>
                    </div>
                </div>
                <div class="col-sm-3 offset-top">
                    <?=$button->enabled;?>
                </div>
                <div class="col-sm-5">
                    <?=$button->label;?>
                </div>
                <div class="col-sm-2 offset-top">
                    <div class="form-control-static">
                        <?=$this->translate('Points');?>: <?=$points;?>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
        </div>
    <?php endforeach; ?>

    <hr />

    <div class="row">
        <div class="col-sm-2">
            <?php foreach ($this->element->buttonSets->getSubForms() as $buttonType => $buttonsSet): ?>
                <div class="js-button-set js-button-set-<?=$buttonType;?>">
                    <div class="offset-top">
                        <?=$this->partial('_svg/button.svg.phtml', [
                            'btnLabel' => sprintf(
                                '_svg/' . Service_Voting::BUTTON_FILENAME_PATTERN,
                                $buttonType,
                                'no-opinion'
                            ),
                            'width' => '80',
                            'height' => '76',
                        ]);?>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
        <div class="col-sm-10">
            <?=$this->element->btn_no_opinion?>
        </div>
    </div>

    <div class="form-block-bordered">
        <div class="row offset-bottom">
            <div class="col-sm-2">
                <?php foreach ($this->element->buttonSets->getSubForms() as $buttonType => $buttonsSet): ?>
                    <div class="js-button-set js-button-set-<?=$buttonType;?>">
                        <div class="offset-top">
                            <?=$this->partial('_svg/button.svg.phtml', [
                                'btnLabel' => sprintf(
                                    '_svg/' . Service_Voting::BUTTON_FILENAME_PATTERN,
                                    $buttonType,
                                    'superbutton'
                                ),
                                'width' => '80',
                                'height' => '76',
                            ]);?>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
            <div class="col-sm-10">
                <?=$this->element->is_btn_important?>
            </div>
        </div>
        <div id="js-btn-important-inputs">
            <?=$this->element->btn_important_label?>
            <?=$this->element->btn_important_max?>
            <?=$this->element->btn_important_factor?>
        </div>
    </div>

    <?=$this->element->csrf_token_settingsvotingsubmissionformadmin?>
    <?=$this->element->submit?>

</form>
