
<h1><?php echo $this->consultation['titl']; ?></h1>
<?php
echo $this->consultationNavigation('Ordnerverwaltung');
?>
<h2>Viruelle Ordner</h2>
<div class="c33l pad5r">
<h3>Ordner anlegen</h3>
<?php echo $this->createNewForm; ?>
</div>
<div class="c33l">
	<h3>Vorhandene Ordner</h3>
	 <div class="yform">
	 	<ul class="levels">
<?
	echo '';
	foreach ($this -> directories as $dir) {
		if ((int)$dir['depth']==0)  {
   			echo '<li class="level_'.(int)$dir['depth'].'"><div><b>' . $dir['dir_name'] . '</b></div>
   					<a href="'.$this->baseUrl().'/admin/directories/delete/dir/'.$dir['id'].'/kid/'.$this->consultation['kid'].'" class="delete"  title="Ordner löschen?" onclick="return confirm(\'Diesen Ordner (' . $dir['dir_name'] . ') löschen?\');">Ordner löschen</a>
   					</li>';
		} else {
			echo '<li class="level_'.(int)$dir['depth'].'"><div>&#9492; ' . $dir['dir_name'] . '</div>
			<a href="'.$this->baseUrl().'/admin/directories/delete/dir/'.$dir['id'].'/kid/'.$this->consultation['kid'].'" class="delete"  title="Ordner löschen?" onclick="return confirm(\'Diesen Ordner (' . $dir['dir_name'] . ') löschen?\');">Ordner löschen</a>
			</li>';
		}
	}	
?>
</ul>
</div>
</div>