<section class="section-header">
    <div class="container">

        <h1 class="section-header-title"><?=$this->escape($this->consultation['titl']);?></h1>
        <h2 class="section-header-subtitle"><?=$this->escape($this->consultation['titl_sub']);?></h2>

        <?=$this->consultationTabs($this->consultation['kid'], 'consultation');?>

    </div>
</section>
<section class="section-content">
    <div class="container">
        <div class="row">
            <div class="sidebar offset-bottom-large-sm-max">

                <?=$this->consultationNavigation($this->consultation, 'inputs');?>

            </div>
            <div class="content">

                <?php if (!empty($this->qid)): ?>
                    <a
                        href="<?=$this->url(['controller' => 'input', 'action' => 'list-by-question', 'kid' => $this->consultation['kid'], 'qi' => $this->qid]);?>"
                        class="back"
                    >
                        <?=$this->translate('Back to Contributions');?>
                    </a>
                <?php endif; ?>
                <h2><?=$this->translate('Contribution Discussion');?></h2>

                <?php if (!$this->question['video_enabled']): ?>
                    <p class="alert alert-info">
                        <?=$this->translate('Videos for this question are disabled. If you create a contribution from a comment, the video will be copied, but it will not be visible until you allow it in the question settings');?>.
                    </p>
                <?php endif; ?>
                <?php if (count($this->discussionContribs)): ?>
                    <form method="<?=$this->form->getMethod();?>">
                        <?=$this->form->getElement($this->form->getCsrfTokenName());?>
                        <div class="table-responsive">
                            <table class="table table-bordered">
                                <tbody>
                                    <?php foreach ($this->discussionContribs as $contrib): ?>
                                        <tr>
                                            <td class="table-cell-id table-cell-top">
                                                <span id="<?=$this->escape($contrib->id);?>"><?=$this->escape($contrib->id);?></span>
                                            </td>
                                            <td class="table-cell-top">
                                                <?php if ($contrib->body): ?>
                                                    <p><?=$this->escape($contrib->body);?></p>
                                                <?php endif;?>
                                                <?php if ($contrib['video_service'] !== null && $contrib['video_id'] !== null
                                                    && $this->videoServicesStatus['video_' . $contrib['video_service'] . '_enabled']): ?>
                                                    <?=$this->embeddedVideo($contrib['video_service'], $contrib['video_id']);?>
                                                <?php endif; ?>
                                                <p>
                                                    <small>
                                                        <?=$this->formatDate($contrib->time_created);?>
                                                    </small>
                                                </p>
                                            </td>
                                            <td class="col-xs-3 table-cell-top">
                                                <p>
                                                    <?=$this->translate('User Confirmation');?><br />
                                                    <?php if ($contrib->is_user_confirmed): ?>
                                                        <span class="label label-success">
                                                            <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
                                                            <?=$this->translate('User confirmed');?>
                                                        </span>
                                                    <?php else: ?>
                                                        <span class="label label-danger">
                                                            <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                                                            <?=$this->translate('Not user confirmed');?>
                                                        </span>
                                                    <?php endif; ?>
                                                </p>
                                                <p>
                                                    <?=$this->translate('Visibility');?><br />
                                                    <?php if ($contrib->is_visible): ?>
                                                        <span class="label label-success">
                                                            <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
                                                            <?=$this->translate('Visible');?>
                                                        </span>
                                                    <?php else: ?>
                                                        <span class="label label-danger">
                                                            <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
                                                            <?=$this->translate('Hidden');?>
                                                        </span>
                                                    <?php endif; ?>
                                                </p>
                                            </td>
                                            <td class="table-cell-top col-xs-1">
                                                <?php if (!$contrib->is_user_confirmed): ?>
                                                    <button
                                                        name="confirm"
                                                        title="<?=$this->translate('Confirm');?>"
                                                        value="<?=$this->escape($contrib->id);?>"
                                                        class="item-action"
                                                        data-toggle="confirm"
                                                        data-confirm-message="<?=$this->translate('Mark as user confirmed?');?>"
                                                        data-confirm-yes="<?=$this->translate('Yes');?>"
                                                        data-confirm-no="<?=$this->translate('No');?>"
                                                        >
                                                        <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
                                                    </button>
                                                <?php else: ?>
                                                    <button
                                                        name="unconfirm"
                                                        title="<?=$this->translate('Deny');?>"
                                                        value="<?=$this->escape($contrib->id);?>"
                                                        class="item-action"
                                                        data-toggle="confirm"
                                                        data-confirm-message="<?=$this->translate('Remove user confirmation?');?>"
                                                        data-confirm-yes="<?=$this->translate('Yes');?>"
                                                        data-confirm-no="<?=$this->translate('No');?>"
                                                        >
                                                        <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                                                    </button>
                                                <?php endif; ?>

                                                <?php if ($contrib->is_visible): ?>
                                                    <button
                                                        name="hide"
                                                        title="<?=$this->translate('Mark as hidden');?>"
                                                        value="<?=$this->escape($contrib->id);?>"
                                                        class="item-action"
                                                        data-toggle="confirm"
                                                        data-confirm-message="<?=$this->translate('Mark as hidden?');?>"
                                                        data-confirm-yes="<?=$this->translate('Yes');?>"
                                                        data-confirm-no="<?=$this->translate('No');?>"
                                                    >
                                                        <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
                                                    </button>
                                                <?php else: ?>
                                                    <button
                                                        name="show"
                                                        value="<?=$this->escape($contrib->id);?>"
                                                        title="<?=$this->translate('Mark as visible');?>"
                                                        class="item-action"
                                                        data-toggle="confirm"
                                                        data-confirm-message="<?=$this->translate('Mark as visible?');?>"
                                                        data-confirm-yes="<?=$this->translate('Yes');?>"
                                                        data-confirm-no="<?=$this->translate('No');?>"
                                                    >
                                                        <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
                                                    </button>
                                                <?php endif; ?>

                                                <?php if (!$contrib->childInputId
                                                    && Zend_Date::now()->isEarlier(new Zend_Date($this->consultation['inp_to'], Zend_Date::ISO_8601))
                                                    && Zend_Date::now()->isLater(new Zend_Date($this->consultation['inp_fr'], Zend_Date::ISO_8601))
                                                ): ?>
                                                    <button
                                                        name="createInput"
                                                        value="<?=$this->escape($contrib->id);?>"
                                                        title="<?=$this->translate('Create an input from this discussion contribution.');?>"
                                                        class="item-action"
                                                        data-toggle="confirm"
                                                        data-confirm-message="<?=$this->translate('Create an input from this discussion contribution?');?>"
                                                        data-confirm-yes="<?=$this->translate('Yes');?>"
                                                        data-confirm-no="<?=$this->translate('No');?>"
                                                    >
                                                        <span class="glyphicon glyphicon-asterisk" aria-hidden="true"></span>
                                                    </button>
                                                <?php endif; ?>
                                            </td>
                                        </tr>
                                    <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div><!-- .table-responsive -->
                    </form>
                <?php else: ?>
                    <p class="alert alert-info">
                        <span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>
                        <?=$this->translate('There are no discussion posts yet.');?>
                    </p>
                <?php endif; ?>

            </div>
        </div>
    </div>
</section>
