<footer>

	<!-- Footer navigation -->
	<nav role="navigation" class="footer-navigation navbar navbar-static">
		<div class="navbar-inner">
			<div class="container">

				<ul class="nav">
					<li<?php if (stristr($this->url(), 'imprint')) echo ' class="active"'; ?>>
						<a href="<?php echo $this->url(array(), 'imprint', true); ?>">Impressum</a>
					</li>
					<li<?php if (stristr($this->url(), 'about')) echo ' class="active"'; ?>>
						<a href="<?php echo $this->url(array(), 'about', true); ?>">Über uns</a>
					</li>
					<li<?php if (stristr($this->url(), 'faq')) echo ' class="active"'; ?>>
						<a href="<?php echo $this->url(array(), 'faq', true); ?>">Häufige Fragen</a>
					</li>
					<li<?php if (stristr($this->url(), 'privacy')) echo ' class="active"'; ?>>
						<a href="<?php echo $this->url(array(), 'privacy', true); ?>">Datenschutz</a>
					</li>
					<li<?php if (stristr($this->url(), 'contact')) echo ' class="active"'; ?>>
						<a href="<?php echo $this->url(array(), 'contact', true); ?>">Kontakt</a>
					</li>
				</ul>

				<img src="http://placehold.it/98x34" alt="Lizenz" />

			</div><!-- .container -->
		</div><!-- .navbar-inner -->
	</nav><!-- .footer-navigation -->

	<!-- About -->
	<section role="contentinfo" class="footer-about">
		<div class="container">
			<div class="row">

				<div class="span3">
					<h3>Projektträger</h3>
					<a href="" rel="external" target="_blank">
						<img src="http://placehold.it/140x65" alt="" />
					</a>
				</div>
				<div class="span3">
					<h3>Gefördert vom</h3>
					<a href="" rel="external" target="_blank">
						<img src="http://placehold.it/140x65" alt="" />
					</a>
				</div>
				<div class="span3">
					<h3>Das Tool für ePartizipation</h3>
					<a href="" rel="external" target="_blank">
						<img src="http://placehold.it/140x65" alt="" />
					</a>
				</div>
				<div class="span3 contact">
					<p>Projektbüro Ichmache&gt;Politik<br />
						Jugendbeteiligung an der Entwicklung<br />
						einer Eigenständigen Jugendpolitik</p>
					<p>Mühlendamm 3<br />
						10178 Berlin<br />
						<a href="mailto:ichmache-politik@dbjr.de">ichmache-politik@dbjr.de</a><br />
						<a href="http://www.ichmache-politik.de" rel="external" target="_blank">www.ichmache-politik.de</a></p>
				</div>

			</div><!-- .row -->
		</div><!-- .container -->
	</section><!-- .footer-about -->

</footer>