<footer>

	<!-- Footer navigation -->
	<nav role="navigation" class="footer-navigation navbar navbar-static">
		<div class="navbar-inner">
			<div class="container">

				<ul class="nav">
					<li><a href="">Impressum</a></li>
					<li><a href="">Über uns</a></li>
					<li><a href="">Häufige Fragen</a></li>
					<li><a href="">Datenschutz</a></li>
					<li><a href="">Kontakt</a></li>
					<li class="licence"><img src="images/licence.png" alt="Lizenz" /></li>
				</ul>

			</div><!-- .container -->
		</div><!-- .navbar-inner -->
	</nav><!-- .footer-navigation -->

	<!-- About -->
	<section role="contentinfo" class="footer-about">
		<div class="container">
			<div class="row">

				<div class="span3">
					<h3>Projektträger</h3>
					<a href="" rel="external" target="_blank" title="Deutscher Bundesjugendring">
						<img src="images/logo/dbjr.png" alt="Deutscher Bundesjugendring" />
					</a>
				</div>
				<div class="span3">
					<h3>Gefördert vom</h3>
					<a href="" rel="external" target="_blank" title="Bundesministerium für Familie, Senioren, Frauen und Jugend">
						<img src="images/logo/bmfsfj.png" alt="Bundesministerium für Familie, Senioren, Frauen und Jugend" />
					</a>
				</div>
				<div class="span3">
					<h3>Das Tool für ePartizipation</h3>
					<a href="" rel="external" target="_blank" title="ePartool">
						<img src="images/logo/epartool.png" alt="ePartool" />
					</a>
				</div>
				<div class="span3 contact">
					<p><strong>Projektbüro Ichmache&gt;Politik</strong><br />
						Jugendbeteiligung an der Entwicklung<br />
						einer Eigenständigen Jugendpolitik</p>
					<p>Mühlendamm 3<br />
						10178 Berlin<br />
						<a href="mailto:ichmache-politik@dbjr.de">ichmache-politik@dbjr.de</a><br />
						<a href="http://www.ichmache-politik.de" rel="external" target="_blank">www.ichmache-politik.de</a></p>
				</div>

			</div><!-- .row -->
		</div><!-- .container -->
	</section><!-- .footer-about -->

</footer>