<?php
/**
 * Header
 */
?>
<header>

		<!-- Header region -->
		<div role="banner" class="header-region">
			<div class="container">
				<div class="row">

					<div class="span4">

						<!-- Brand -->
						<a href="<?=$this->url(array('controller' => 'index'), null, true)?>" rel="home" class="brand" title="Startseite">
							<img src="/images/logo.png" itemprop="image" alt="Ichmache&gt;Politik" />
						</a>

					</div>
					<div class="span5">

						<!-- Main navigation -->
						<nav role="navigation" class="main-navigation">
							<h2 class="hide">Hauptmenü</h2>

							<!-- Menu -->
							<ul class="nav nav-pills">
								<li><a href="">Was</a></li>
								<li><a href="">Wir</a></li>
								<li><a href="mit-euch.html">Mit euch</a></li>
								<li><a href="">Machen</a></li>
							</ul>
						</nav><!-- .main-navigation -->

					</div>
					<div class="span3">

						<!-- Search -->
						
						<form method="get" action="" class="form-search">
            	<div class="input-append">
            		<input type="text" name="q" placeholder="Suchebegriff…" class="input-medium search-query" value="" />
            		<button type="submit" class="btn"><i class="icon-search"></i></button>
            	</div>
            </form>

						<!-- Login -->
						<?php echo $this->login(); ?>

						<!-- User box (user is logged in) -->
						<?php echo $this->userBox(); ?>
						<!-- .user-box -->

						<!-- User info in a modified modal -->
						<div id="user-info" class="user-info modal hide fade" tabindex="-1" role="dialog" aria-labelledby="userInfoLabel" aria-hidden="true">
							<div class="modal-header">
								<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
								<h3 id="userInfoLabel">User Info</h3>
							</div><!-- .modal-header -->
							<div class="modal-body">

								<a href=""><i class="icon-chevron-right"></i> Alle meine Beiträge ansehen</a>
								<hr />

								<!-- Change user login or password -->
								<form name="userEdit" action="" method="post" class="user-edit-form">
									<p><i class="icon-chevron-right"></i> Name und Passwort ändern</p>
									<div class="control-group">
										<div class="control-label hide">
											<label for="username">E-Mail Adresse:</label>
										</div>
										<div class="controls">
											<input type="email" name="username" id="username" placeholder="E-mail Adresse" value="" />
										</div>
									</div>
									<div class="control-group">
										<div class="control-label hide">
											<label for="password">Passwort:</label>
										</div>
										<div class="controls">
											<input type="password" name="password" id="password" placeholder="Passwort" value="" />
										</div>
									</div>
									<div class="form-actions">
										<button type="submit" name="userEditSubmit" class="btn">Absenden</button>
									</div>
								</form>
								<hr />

								<a href=""><i class="icon-chevron-right"></i> Neue Gruppenmitglieder zum Freischalten</a>

							</div><!-- .modal-body -->
						</div><!-- #user-info -->

					</div><!-- .span3 -->

				</div><!-- .row -->

				<?php echo $this->partial('_herounit.phtml', $this)?>
				
			</div><!-- .container -->
		</div><!-- .header-region -->

	</header>