<?php
/**
 * Hero Unit
 *
 * @description   Header des Inhaltsbereiches
 * @author        Markus Hackel
 */
?>
<?php

$controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
//$action = Zend_Controller_Front::getInstance()->getRequest()->getParam('action');

?>
<?php
if (isset($this->consultation)):
?>

<!-- Main title -->
<div class="main-title">
	<h1><a href="<?php echo $this->url(array('controller' => 'index'), 'default', true)?>" rel="home" itemprop="name">Mitwirkung</a></h1>
</div><!-- .title -->

<!-- Hero unit -->
<div class="consultation consultation-preview hero-unit">

	<hgroup>
		<h1><?php echo $this->escape($this->consultation->titl)?></h1>
		<h2><?php echo $this->escape($this->consultation->titl_sub)?></h2>
	</hgroup>

	<span class="label label-mitmachen">Mitmachen</span>

	<img src="<?php echo $this->baseUrl(); ?>/media/consultations/<?php echo $this->consultation->kid . '/'
	  . $this->consultation->img_file;?>" width="144" class="title-image"
	  alt="<?php echo $this->consultation->img_expl;?>" />

	<a href="<?php echo $this->url(array('controller' => 'index'), 'default', true)?>" rel="home">Zur Startseite … <i class="icon-angle-right icon-2x"></i></a>

	<a href="#" class="share btn"><i class="icon-share-alt icon-white icon-large"></i> Share</a>

</div>
<!-- .hero-unit -->

<?php else:?>

<!-- Hero unit -->
<div class="main-header hero-unit<?php echo $controller == 'index' ? ' with-teaser' : ''; ?>">

	<h1><a href="<?php echo $this->url(array('controller' => 'index'), 'default', true)?>" rel="home" itemprop="name">Mitwirkung</a></h1>
	<p itemprop="description">Was ist eine Konsultation in einem langen, langen,
		langen, langen Satz erklärt. Kurz und prägnant
		geschrieben. Für den ersten Überblick und das erste
		Verständnis. Und noch einen zweiten Satz. Nur für den
		ersten Überblick und das erste Verständnis.
	</p>

	<?php if ($controller == 'index'): ?>

	<!-- Teaser -->
	<?php echo $this->teaser(); ?>

	<?php endif; ?>

</div>
<!-- .hero-unit -->

<?php endif;?>