<div class="well">
    <h4><?=$this->translate('Placeholders');?></h4>
    <table class="table table-striped">
        <?php foreach ($this->placeholders as $placeholder): ?>
            <tr>
                <th class="col-sm-3">
                    <?php echo Dbjr_Mail::TOKEN_OPEN . $placeholder->name . Dbjr_Mail::TOKEN_CLOSE; ?>
                </th>
                <td><?=$this->escape($placeholder->description);?></td>
            </tr>
        <?php endforeach; ?>
    </table>
</div>

<div class="well">
    <h4><?=$this->translate('Components');?></h4>
    <table class="table table-striped">
        <?php foreach ($this->components as $component): ?>
            <tr>
                <th class="col-sm-3">
                    <?=Dbjr_Mail::TOKEN_OPEN . $component->name . Dbjr_Mail::TOKEN_CLOSE; ?>
                </th>
                <td><?=$this->escape($component->description);?></td>
            </tr>
        <?php endforeach; ?>
    </table>
</div>
