<?php foreach ($this->files as $file):?>
    <div class="<?=($this->lockDir ? 'col-xs-6 col-sm-4 col-md-3' : 'col-xs-6 col-sm-4 col-lg-3');?>">
        <div class="thumbnail thumbnail-fixed">

            <a
                <?php if ($this->targetElId): ?>
                    <?php // We are in select mode. ?>
                    onclick="mediaSelectPopup.insertValue(
                        '<?=$file['dirRefFilename'];?>',
                        '<?=$this->targetElId;?>',
                        '<?=$this->lockDir
                            ? ''
                            : $this->baseUrl() . ($this->targetElId === 'CKEditor' ? MEDIA_URL . '/' : '') .
                                ($file['dirRefDirUrl'] ? $file['dirRefDirUrl'] . '/' : '');?>',
                        '<?=$this->mediaPresenter($file, 'admin_media_form_element');?>',
                        '<?=$this->CKEditorFuncNum;?>'
                        )"
                    href="#"
                    title="<?=$this->translate('Select');?> <?=$file['basename'];?>"
                <?php else: ?>
                    <?php // We are in listing mode. ?>
                    href="<?=$this->url([
                        'action' => 'open',
                        'filename' => $file['basename'],
                        'kid' => $file['kid'],
                        'folder' => $file['folder']
                    ]);?>/"
                    target="_blank"
                    title="<?=$this->translate('Open');?> <?=$this->escape($file['basename']);?>"
                <?php endif; ?>
            >
                <div class="thumbnail-image" style="background-image: url(<?=$this->mediaPresenter($file, 'admin_thumbnail');?>);"></div>
                <div class="caption">
                    <h4 class="thumbnail-title"><?=$this->escape($file['basename']);?></h4>
                    <small class="text-muted">
                        <?=$this->escape($file['size']);?>&nbsp;kB<br />
                    </small>
                </div>
            </a>

            <div class="thumbnail-actions">
                <?php if ($file['folder']): ?>
                    <?php // File is located in a custom folder and thus can be renamed. ?>
                    <a
                        href="<?=$this->url([
                            'action' => 'edit-file',
                            'folder' => $file['folder'],
                            'filename' => $file['basename']
                        ]);?>/"
                        class="item-action"
                        title="<?=$this->translate('Rename');?>"
                    >
                        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                    </a>
                <?php endif; ?>
                <a
                    href="<?=$this->url([
                        'action' => 'download',
                        'filename' => $file['basename'],
                        'kid' => $file['kid'],
                        'folder' => $file['folder']
                    ]);?>/"
                    class="item-action"
                    title="<?=$this->translate('Download');?>"
                >
                    <span class="glyphicon glyphicon-download-alt" aria-hidden="true"></span>
                </a>
                <?=$file['deleteForm'];?>
            </div>

        </div><!-- .thumbnail -->
    </div>
<?php endforeach; ?>
