<!-- Print -->
<div class="main-page-tools hidden-print">
    <?php if (!empty($this->help)): ?>
        <a
            href="<?=$this->url(['controller' => 'help', 'action' => 'index', 'name' => $this->help]);?>"
            class="link-alt has-icon js-toggle-help"
        >
            <?=$this->translate('Help');?>
            <span class="glyphicon glyphicon-question-sign" aria-hidden="true"></span>
        </a>
        <br class="visible-xs visible-sm" />
    <?php endif; ?>
</div>
