<button type="button" class="item-action pull-right" data-toggle="modal" data-target="#helpTextModal">
    <span class="glyphicon glyphicon-question-sign offset-right" aria-hidden="true"></span>
    <?=$this->translate('Help');?>
</button>

<div class="modal fade" id="helpTextModal" tabindex="-1" role="dialog" aria-labelledby="helpTextModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="helpTextModalLabel"><?=$this->helpTextName;?></h4>
            </div>
            <div class="modal-body"><?=$this->escape($this->helpTextBody);?></div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">
                    <?=$this->translate('Close');?>
                </button>
            </div>
        </div>
    </div>
</div>
