<section class="section-header has-tabs">
    <div class="container">

        <h1><?=$this->consultation['titl'];?></h1>
        <h2><?=$this->consultation['titl_sub'];?></h2>

        <?=$this->consultationTabs($this->consultation['kid'], 'consultation');?>

    </div>
</section>
<section class="section-content">
    <div class="container">
        <div class="row">
            <div class="col-md-3">

                <?=$this->consultationNavigation('info');?>

            </div>
            <div class="col-md-9">

                <h2>New Article</h2>
                <?php echo $this->form;?>
                <p>
                    or
                    <a href="<?=$this->url(array('action' => 'index', $this->kid));?>">Cancel</a>
                </p>

            </div>
        </div>
    </div>
</section>

<!-- TODO move to JS -->
<script>
    CKEDITOR.replace( 'artcl' );
    CKEDITOR.replace( 'sidebar' );
</script>
