<section class="section-header has-tabs">
    <div class="container">

        <?php if (isset($this->consultation) && !empty($this->consultation)): ?>
            <h1><?=$this->consultation['titl'];?></h1>
            <h2><?=$this->consultation['titl_sub'];?></h2>
            <?=$this->consultationTabs($this->consultation['kid'], 'consultation');?>
        <?php else: ?>
            <h1><?=$this->translate('General Settings');?></h1>
        <?php endif; ?>

    </div>
</section>
<section class="section-content">
    <div class="container">
        <div class="row">
            <div class="col-md-3">

                <?php if (isset($this->consultation) && !empty($this->consultation)): ?>
                    <?=$this->consultationNavigation('info');?>
                <?php else: ?>
                    <?=$this->settingsNavigation('pages');?>
                <?php endif; ?>

            </div>
            <div class="col-md-9">

                <?php if (isset($this->consultation) && !empty($this->consultation)): ?>
                    <h2><?=$this->translate('Edit Article');?></h2>
                    <p class="back-link">
                        <a href="<?=$this->url(array('action' => 'index', $this->kid));?>">&larr; <?=$this->translate('Back to Articles');?></a>
                    </p>
                <?php else: ?>
                    <h2><?=$this->translate('Edit Page');?></h2>
                    <p class="back-link">
                        <a href="<?=$this->url(array('action' => 'index'));?>">&larr; <?=$this->translate('Back to Pages');?></a>
                    </p>
                <?php endif; ?>

                <?php echo $this->form;?>
                <p>
                    <?=$this->translate('or');?>
                    <a href="<?=$this->url(array('action' => 'index', (isset($this->consultation) && !empty($this->consultation)) ? $this->kid : null));?>"><?=$this->translate('Cancel');?></a>
                </p>

            </div>
        </div>
    </div>
</section>

<!-- TODO move to JS -->
<script>
    CKEDITOR.replace( 'artcl' );
    CKEDITOR.replace( 'sidebar' );
</script>
