<section class="section-header has-tabs">
    <div class="container">

        <?php if (isset($this->consultation) && !empty($this->consultation)): ?>
            <h1><?=$this->escape($this->consultation['titl']);?></h1>
            <h2><?=$this->escape($this->consultation['titl_sub']);?></h2>
            <?=$this->consultationTabs($this->consultation['kid'], 'consultation');?>
        <?php else: ?>
            <h1><?=$this->translate('General Settings');?></h1>
        <?php endif; ?>

    </div>
</section>
<section class="section-content">
    <div class="container">
        <div class="row">
            <div class="sidebar">

                <?php if (isset($this->consultation) && !empty($this->consultation)): ?>
                    <?=$this->consultationNavigation($this->consultation, 'info');?>
                <?php else: ?>
                    <?=$this->settingsNavigation('pages');?>
                <?php endif; ?>

            </div>
            <div class="content">

                <?php if (isset($this->consultation) && !empty($this->consultation)): ?>
                    <a href="<?=$this->url(['action' => 'index', $this->kid]);?>" class="back"><?=$this->translate('Back to Articles');?></a>
                    <h2><?=$this->translate('Edit Article');?></h2>
                <?php else: ?>
                    <a href="<?=$this->url(['action' => 'index']);?>" class="back"><?=$this->translate('Back to Pages');?></a>
                    <h2><?=$this->translate('Edit Page');?></h2>
                <?php endif; ?>

                <?=$this->form;?>

            </div>
        </div>
    </div>
</section>
