<section class="section-header has-tabs">
    <div class="container">

        <?php if (isset($this->consultation)): ?>
            <h1><?=$this->consultation['titl'];?></h1>
            <h2><?=$this->consultation['titl_sub'];?></h2>
            <?=$this->consultationTabs($this->consultation['kid'], 'consultation');?>
        <?php else: ?>
            <h1>General Settings</h1>
        <?php endif; ?>

    </div>
</section>
<section class="section-content">
    <div class="container">

        <div class="row">
            <div class="col-md-3">

                <?php if (isset($this->consultation)): ?>
                    <?=$this->consultationNavigation('info');?>
                <?php else: ?>
                    <?=$this->settingsNavigation('pages');?>
                <?php endif; ?>

            </div>
            <div class="col-md-9">

                <a href="<?=$this->url(array('action' => 'create', 'kid' => $this->consultation['kid']));?>" class="btn btn-default pull-right">
                    <span class="glyphicon glyphicon-plus-sign"></span>
                    <?php if (isset($this->consultation)): ?>
                        New Article
                    <?php else: ?>
                        New Page
                    <?php endif; ?>
                </a>
                <?php if (isset($this->consultation)): ?>
                    <h2>Info</h2>
                <?php else: ?>
                    <h2>Pages</h2>
                <?php endif; ?>

                <table class="table" data-view="table">
                    <thead>
                        <tr>
                            <th class="table-cell-id" data-toggle="sort" tabindex="0">#</th>
                            <th data-toggle="sort" data-order="default" tabindex="0">Title</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->articles as $article): ?>
                            <tr>
                                <td class="table-cell-id"><?=$article['art_id'];?></td>
                                <td>
                                    <a href="<?=$this->url(array('action' => 'edit', 'kid' => $this->consultation['kid'], 'aid' => $article['art_id']));?>" title="Edit article"><?=$article['desc'];?></a>
                                </td>
                                <td class="table-cell-actions">
                                    <a href="<?=$this->url(array('action' => 'edit', 'kid' => $this->consultation['kid'], 'aid' => $article['art_id']));?>" class="table-action" title="Edit article">
                                        <span class="glyphicon glyphicon-pencil"></span>
                                    </a>
                                    <a href="<?=$this->url(array('action' => 'delete', 'kid' => $this->consultation['kid'], 'aid' => $article['art_id']));?>" class="table-action table-action-danger" title="Delete article">
                                        <span class="glyphicon glyphicon-trash"></span>
                                    </a>
                                </td>
                            </tr>
                            <?php if (!empty($article['subpages'])): ?>
                                <?php foreach ($article['subpages'] as $subpage): ?>
                                    <tr class="table-row-nested">
                                        <td class="table-cell-id"><?=$article['art_id'];?></td>
                                        <td>
                                            <a href="<?=$this->url(array('action' => 'edit', 'kid' => $this->consultation['kid'], 'aid' => $subpage['art_id']));?>" title="Edit article"><?=$subpage['desc'];?></a>
                                        </td>
                                        <td class="table-cell-actions">
                                            <a href="<?=$this->url(array('action' => 'edit', 'kid' => $this->consultation['kid'], 'aid' => $subpage['art_id']));?>" class="table-action" title="Edit article">
                                                <span class="glyphicon glyphicon-pencil"></span>
                                            </a>
                                            <a href="<?=$this->url(array('action' => 'delete', 'kid' => $this->consultation['kid'], 'aid' => $subpage['art_id']));?>" class="table-action table-action-danger" title="Delete article">
                                                <span class="glyphicon glyphicon-trash"></span>
                                            </a>
                                        </td>
                                    </tr>
                                <?php endforeach; ?>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    </tbody>
                </table>

            </div>
        </div>
    </div>
</section>
