<section class="section-header has-tabs">
    <div class="container">

        <?php if (isset($this->consultation)): ?>
            <h1><?=$this->consultation['titl'];?></h1>
            <h2><?=$this->consultation['titl_sub'];?></h2>
            <?=$this->consultationTabs($this->consultation['kid'], 'consultation');?>
        <?php else: ?>
            <h1>General Settings</h1>
        <?php endif; ?>

    </div>
</section>
<section class="section-content">
    <div class="container">

        <div class="row">
            <div class="col-md-3">

                <?php if (isset($this->consultation)): ?>
                    <?=$this->consultationNavigation('info');?>
                <?php else: ?>
                    <?=$this->settingsNavigation('pages');?>
                <?php endif; ?>

            </div>
            <div class="col-md-9">

                <a href="<?=$this->url(array('action' => 'create', 'kid' => $this->consultation['kid']));?>" class="btn btn-default pull-right">
                    <span class="glyphicon glyphicon-plus-sign"></span>
                    <?php if (isset($this->consultation)): ?>
                        New Article
                    <?php else: ?>
                        New Page
                    <?php endif; ?>
                </a>
                <?php if (isset($this->consultation)): ?>
                    <h2>Info</h2>
                <?php else: ?>
                    <h2>Pages</h2>
                <?php endif; ?>


                <table class="table">
                    <tr>
                        <th>Seite</th>
                        <th>Ref</th>
                        <th>Inhalt</th>
                        <th>Aktionen</th>
                    </tr>
                    <?php foreach ($this->articles as $article): ?>
                        <tr>
                            <td><?php echo $article['desc']; ?></td>
                            <td><?php echo $article['ref_nm']; ?></td>
                            <td><?php echo substr(strip_tags(html_entity_decode($article['artcl'], ENT_COMPAT, 'UTF-8')), 0, 200); ?></td>
                            <td><a href="<?php echo $this->url(array(
                                    'action' => 'edit',
                                    'kid' => $this->consultation['kid'],
                                    'aid' => $article['art_id']
                                ));?>">Bearbeiten</a>
                                &nbsp;
                                <a href="<?php echo $this->url(array(
                                    'action' => 'delete',
                                    'kid' => $this->consultation['kid'],
                                    'aid' => $article['art_id']
                                ));?>" title="Artikel löschen">Löschen</a>
                        </tr>
                        <?php if (!empty($article['subpages'])): ?>
                            <tr><td colspan="3"><small>Unterseiten:</small></td></tr>
                            <?php foreach ($article['subpages'] as $subpage): ?>
                                <tr class="subpage">
                                    <td><?php echo $subpage['desc']; ?></td>
                                    <td></td>
                                    <td><?php echo substr(strip_tags(html_entity_decode($subpage['artcl'], ENT_COMPAT, 'UTF-8')), 0, 200); ?></td>
                                    <td><a href="<?php echo $this->url(array(
                                            'action' => 'edit',
                                            'kid' => $this->consultation['kid'],
                                            'aid' => $subpage['art_id']
                                        ));?>">Bearbeiten</a>
                                        &nbsp;
                                        <a href="<?php echo $this->url(array(
                                            'action' => 'delete',
                                            'kid' => $this->consultation['kid'],
                                            'aid' => $subpage['art_id']
                                        ));?>" title="Artikel löschen">Löschen</a>
                                </tr>
                            <?php endforeach; ?>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </table>

        <?php if (isset($this->consultation)): ?>
            </div>
        </div>
        <?php endif; ?>
    </div>
</section>
