<section class="section-header has-tabs">
    <div class="container">

        <h1><?=$this->consultation['titl'];?></h1>
        <h2><?=$this->consultation['titl_sub'];?></h2>

        <?=$this->consultationTabs($this->consultation['kid'], 'consultation');?>

    </div>
</section>
<section class="section-content">
    <div class="container">
        <div class="row">
            <div class="sidebar">

                <?=$this->consultationNavigation($this->consultation['kid'], 'questions');?>

            </div>
            <div class="content">

                <a href="<?=$this->url(array('action' => 'index'));?>" class="back">&larr; <?=$this->translate('Back to Question');?>s</a>

                <h2><?=$this->translate('New Question');?></h2>

                <form role="form" enctype="<?=$this->form->getEnctype();?>" method="<?=$this->form->getMethod();?>" action="<?=$this->form->getAction();?>" class="offset-bottom">
                    <div class="row">
                        <div class="col-sm-2">
                            <?=$this->form->getElement('nr')?>
                        </div>
                        <div class="col-sm-10">
                            <?=$this->form->getElement('q')?>
                        </div>
                    </div>
                    <?=$this->form->getElement('q_xpl')?>
                    <?=$this->form->getElement('vot_q')?>
                    <?=$this->form->getElement('csrf_token_question')?>
                    <?=$this->form->getElement('submit')?>
                    <div class="cancel-link">
                        <?=$this->translate('or');?>
                        <a href="<?=$this->url(['action' => 'index']);?>"><?=$this->translate('Cancel');?></a>
                    </div>
                </form>

            </div>
        </div>
    </div>
</section>
