<?php
/**
 * index
 *
 * @description   Admin Dashboard
 * @author        Markus Hackel
 */
?>
<h1><?php echo $this->consultation['titl'];?></h1>
<?php
echo $this->consultationNavigation('Fragen');
?>
<h2>Frage bearbeiten</h2>
<p>
  <a href="<?php echo $this->baseUrl(); ?>/admin/question/index/kid/<?php echo $this->consultation['kid']?>">&laquo; Zur&uuml;ck</a>
</p>
<?php echo $this->form;?>
<p>
  <a href="<?php echo $this->baseUrl(); ?>/admin/question/index/kid/<?php echo $this->consultation['kid']?>">&laquo; Zur&uuml;ck</a>
</p>