<section class="section-header">
    <div class="container">

        <h1 class="section-header-title"><?=$this->escape($this->consultation['titl']);?></h1>
        <h2 class="section-header-subtitle"><?=$this->escape($this->consultation['titl_sub']);?></h2>

        <?=$this->consultationTabs($this->consultation['kid'], 'consultation');?>

    </div>
</section>
<section class="section-content">
    <div class="container">
        <div class="row">
            <div class="sidebar offset-bottom-large-sm-max">

                <?=$this->consultationNavigation($this->consultation, 'questions');?>

            </div>
            <div class="content">

                <a href="<?=$this->url(['action' => 'index']);?>" class="back"><?=$this->translate('Back to Questions');?></a>

                <h2><?=$this->translate('Edit Question');?></h2>

                <form role="form" enctype="<?=$this->form->getEnctype();?>" method="<?=$this->form->getMethod();?>" action="<?=$this->form->getAction();?>" class="offset-bottom">
                    <div class="row">
                        <div class="col-sm-2">
                            <?=$this->form->getElement('nr');?>
                        </div>
                        <div class="col-sm-10">
                            <?=$this->form->getElement('q');?>
                        </div>
                    </div>
                    <?=$this->form->getElement('q_xpl');?>
                    <?=$this->form->getElement('vot_q');?>
                    <div class="row">
                        <div class="col-sm-4">
                            <?=$this->form->getElement('video_enabled');?>
                        </div>
                        <div class="col-sm-8 checkbox">
                            <a
                                href="<?=$this->url(['controller' => 'settings', 'action' => 'services']);?>"
                                target="_blank"
                            >
                                <span class="glyphicon glyphicon-cog offset-right" aria-hidden="true"></span>
                                <?=$this->translate('Video Services Settings');?>
                            </a>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-4">
                            <?=$this->form->getElement('location_enabled');?>
                        </div>
                        <div class="col-sm-8">
                            <?php if (!$this->isConnectionSecured): ?>
                                <p class="alert alert-info js-no-https-info">
                                    <?=$this->translate('Your website in not running over secured connection, browser/device location service will not be available.');?>
                                </p>
                            <?php endif; ?>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-4">
                            <?=$this->form->getElement('geo_fence_enabled');?>
                            <?=$this->form->getElement('geo_fence_polygon');?>
                        </div>
                    </div>

                    <?=$this->openStreetMapsConfig();?>
                    <div class="offset-bottom" id="js-contribution-geo-fence-map">
                        <p class="alert alert-info">
                            <?=$this->translate('Set points on the map by clicking in order to narrow down the area to which contributions can be submitted. The dots will automatically connect to an area (in red).');?>
                        </p>
                        <a
                            href="#"
                            id="js-geo-fence-destroy"
                            class="btn btn-xs btn-default"
                            style="position: absolute; z-index: 450;right: 50px; margin-top: 10px;"
                        >
                            <?=$this->translate('Remove geo fence');?>
                        </a>
                        <div id="js-contribution-geo-fence-map-canvas" style="height: 300px;"></div>
                    </div>

                    <?=$this->form->getElement('csrf_token_question');?>
                    <?=$this->form->getElement('submit');?>
                    <div class="form-action-static">
                        <?=$this->translate('or');?>
                        <a href="<?=$this->url(['action' => 'index']);?>"><?=$this->translate('Cancel');?></a>
                    </div>
                </form>

            </div>
        </div>
    </div>
</section>
