<section class="section-header has-tabs">
    <div class="container">

        <h1><?=$this->consultation['titl'];?></h1>
        <h2><?=$this->consultation['titl_sub'];?></h2>

        <?=$this->consultationTabs($this->kid, 'consultation');?>

    </div>
</section>
<section class="section-content">
    <div class="container">
        <div class="row">
            <div class="sidebar">

                <?=$this->consultationNavigation($this->kid, 'questions');?>

            </div>
            <div class="content">

                <a href="<?=$this->url(array('action' => 'create', 'kid' => $this->kid));?>" class="btn btn-default pull-right">
                    <span class="glyphicon glyphicon-plus-sign"></span>
                    <?=$this->translate('New Question');?>
                </a>
                <h2><?=$this->translate('Questions');?></h2>

                <?php if (!$this->questions): ?>
                    <p class="alert alert-info">
                        <span class="glyphicon glyphicon-info-sign"></span>
                        <?=$this->translate('There are no questions yet.');?>
                    </p>
                <?php else: ?>
                    <form method="<?=$this->form->getMethod();?>" action="<?=$this->url(['action' => 'delete']);?>">
                        <?=$this->form->getElement($this->form->getCsrfTokenName());?>
                        <table class="table" data-view="table">
                            <thead>
                                <tr>
                                    <th class="table-cell-id" data-order="default" data-toggle="sort" tabindex="0">#</th>
                                    <th data-toggle="sort" tabindex="0"><?=$this->translate('Question');?></th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach ($this->questions as $question): ?>
                                    <tr>
                                        <td class="table-cell-id"><?=$question->nr;?></td>
                                        <td><?=$question->q;?></td>
                                        <td class="table-cell-actions">
                                            <a
                                                href="<?=$this->url(['action' => 'edit', 'qid' => $question->qi]);?>"
                                                class="item-action"
                                                title="<?=$this->translate('Edit question');?>"
                                            >
                                                <span class="glyphicon glyphicon-pencil"></span>
                                            </a>
                                            <button
                                                name="delete"
                                                value="<?=$question->qi;?>"
                                                class="item-action item-action-danger"
                                                data-toggle="confirm"
                                                data-confirm-message="<?=$this->translate('Delete question?');?>"
                                            >
                                                <span class="glyphicon glyphicon-trash"></span>
                                            </button>
                                        </td>
                                    </tr>
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                    </form>
                <?php endif; ?>

            </div>
        </div>
    </div>
</section>
