<section class="section-header">
    <div class="container">

        <?=$this->helpText('help-text-admin-question');?>

        <h1 class="section-header-title"><?=$this->escape($this->consultation['titl']);?></h1>
        <h2 class="section-header-subtitle"><?=$this->escape($this->consultation['titl_sub']);?></h2>

        <?=$this->consultationTabs($this->consultation['kid'], 'consultation');?>

    </div>
</section>
<section class="section-content">
    <div class="container">
        <div class="row">
            <div class="sidebar offset-bottom-large-sm-max">

                <?=$this->consultationNavigation($this->consultation, 'questions');?>

            </div>
            <div class="content">

                <a href="<?=$this->url(['action' => 'create', 'kid' => $this->consultation['kid']]);?>" class="btn btn-default pull-right">
                    <span class="glyphicon glyphicon-plus-sign icon-shift-down offset-right" aria-hidden="true"></span>
                    <?=$this->translate('New Question');?>
                </a>
                <h2><?=$this->translate('Questions');?></h2>

                <?php if (count($this->questions)): ?>
                    <form method="<?=$this->form->getMethod();?>" action="<?=$this->url(['action' => 'delete']);?>">
                        <?=$this->form->getElement($this->form->getCsrfTokenName());?>
                        <table class="table">
                            <thead>
                                <tr>
                                    <th class="table-cell-id sorting-asc" data-toggle="sort" tabindex="0">#</th>
                                    <th data-toggle="sort" tabindex="0"><?=$this->translate('Question');?></th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach ($this->questions as $question): ?>
                                    <tr>
                                        <td class="table-cell-id"><?=$this->escape($question->nr);?></td>
                                        <td><?=html_entity_decode($this->escape($question->q));?></td>
                                        <td class="table-cell-actions">
                                            <a
                                                href="<?=$this->url(['action' => 'edit', 'qid' => $this->escape($question->qi)]);?>"
                                                class="item-action"
                                                title="<?=$this->translate('Edit question');?>"
                                            >
                                                <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                                            </a>
                                            <button
                                                name="delete"
                                                value="<?=$this->escape($question->qi);?>"
                                                class="item-action item-action-danger"
                                                data-toggle="confirm"
                                                data-confirm-message="<?=$this->translate('Delete question?');?>"
                                                data-confirm-yes="<?=$this->translate('Yes');?>"
                                                data-confirm-no="<?=$this->translate('No');?>"
                                            >
                                                <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                                            </button>
                                        </td>
                                    </tr>
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                    </form>
                <?php else: ?>
                    <p class="alert alert-info">
                        <span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>
                        <?=$this->translate('There are no questions yet.');?>
                    </p>
                <?php endif; ?>

            </div>
        </div>
    </div>
</section>
