/**
 * Primary
 */
.frame {
    background-color: #<?=$this->colorPrimary;?>;
}

.consultation-phases-full .consultation-phases-item:before {
    border-top-color: #<?=$this->colorPrimary;?>;
}

@media (min-width: 768px) {
    .consultation-phases-full .consultation-phases-item:before {
        border-top-color: transparent;
        border-left-color: #<?=$this->colorPrimary;?>;
    }
}

/**
 * Accent
 */
h1,
h2,
h3,
h5,
h6,
.h1,
.h2,
.h3,
.h5,
.h6 {
    color: #<?=$this->colorAccent1;?>;
}

a {
    color: #<?=$this->colorAccent2;?>;
}

a:hover,
a:focus,
.link-alt:hover,
.link-alt:focus {
    color: #<?=$this->colorAccent1;?>;
}

.text-accent {
    color: #<?=$this->colorAccent1;?>;
}

/* Buttons */
.btn-default,
.btn-default.disabled,
.btn-default.disabled:hover,
.btn-default.disabled:focus,
.btn-default.disabled.focus,
.btn-default[disabled],
.btn-default[disabled]:hover,
.btn-default[disabled]:focus,
.btn-default[disabled].focus {
    border-color: #<?=$this->colorAccent2;?>;
    background-color: #<?=$this->colorAccent2;?>;
}

.btn-default:hover,
.btn-default:focus,
.btn-default.focus,
.btn-default:active,
.btn-default.active,
.btn-default:active:hover,
.btn-default:active:focus,
.btn-default:active.focus,
.btn-default.active:hover,
.btn-default.active:focus,
.btn-default.active.focus,
.btn-default-alt:hover,
.btn-default-alt:focus,
.btn-default-alt.focus,
.btn-default-alt:active,
.btn-default-alt.active,
.btn-default-alt:active:hover,
.btn-default-alt:active:focus,
.btn-default-alt:active.focus,
.btn-default-alt.active:hover,
.btn-default-alt.active:focus,
.btn-default-alt.active.focus,
.open > .dropdown-toggle.btn-default,
.open > .dropdown-toggle.btn-default:hover,
.open > .dropdown-toggle.btn-default:focus,
.open > .dropdown-toggle.btn-default.focus {
    border-color: #<?=$this->colorAccent2;?>;
    background-color: #<?=$this->colorAccent2;?>;
    background-image: linear-gradient(rgba(255, 255, 255, 0.25), rgba(255, 255, 255, 0.25));
}

.btn-primary,
.btn-primary.disabled,
.btn-primary.disabled:hover,
.btn-primary.disabled:focus,
.btn-primary.disabled.focus,
.btn-primary[disabled],
.btn-primary[disabled]:hover,
.btn-primary[disabled]:focus,
.btn-primary[disabled].focus {
    border-color: #<?=$this->colorAccent1;?>;
    background-color: #<?=$this->colorAccent1;?>;
}

.btn-primary:hover,
.btn-primary:focus,
.btn-primary.focus,
.btn-primary:active,
.btn-primary.active,
.btn-primary:active:hover,
.btn-primary:active:focus,
.btn-primary:active.focus,
.btn-primary.active:hover,
.btn-primary.active:focus,
.btn-primary.active.focus,
.btn-primary-alt:hover,
.btn-primary-alt:focus,
.btn-primary-alt.focus,
.btn-primary-alt:active,
.btn-primary-alt.active,
.btn-primary-alt:active:hover,
.btn-primary-alt:active:focus,
.btn-primary-alt:active.focus,
.btn-primary-alt.active:hover,
.btn-primary-alt.active:focus,
.btn-primary-alt.active.focus,
.open > .dropdown-toggle.btn-primary,
.open > .dropdown-toggle.btn-primary:hover,
.open > .dropdown-toggle.btn-primary:focus,
.open > .dropdown-toggle.btn-primary.focus {
    border-color: #<?=$this->colorAccent1;?>;
    background-color: #<?=$this->colorAccent1;?>;
    background-image: linear-gradient(rgba(255, 255, 255, 0.25), rgba(255, 255, 255, 0.25));
}

/* Header */
.header-box-title > a:hover,
.header-box-title > a:focus,
.header-box-title-small > a,
.header-box-title-small > a:hover,
.header-box-title-small > a:focus,
.header-box-subtitle {
    color: #<?=$this->colorAccent1;?>;
}

/* Navigation */
.nav-pills > li > a,
.nav-stacked > li > a {
    background-color: #<?=$this->colorAccent2;?>;
}

.nav-stacked > li > .nav > .active > a,
.nav-stacked > li > .nav > .active > a:hover,
.nav-stacked > li > .nav > .active > a:focus {
    color: #<?=$this->colorAccent1;?>;
}

.nav-pills > li > a:hover,
.nav-pills > li > a:focus,
.nav-pills > .active > a,
.nav-pills > .active > a:hover,
.nav-pills > .active > a:focus,
.nav-stacked > li > a:hover,
.nav-stacked > li > a:focus,
.nav-stacked > .active > a,
.nav-stacked > .active > a:hover,
.nav-stacked > .active > a:focus {
    background-color: #<?=$this->colorAccent1;?>;
}

.nav-stacked > li > .nav > li:first-child > a:after {
    border-top-color: #<?=$this->colorAccent1;?>;
}

.nav-list > li > a {
    background-color: #<?=$this->colorAccent1;?>;
}

.nav-list > li > a:hover,
.nav-list > li > a:focus,
.nav-list > .active > a,
.nav-list > .active > a:hover,
.nav-list > .active > a:focus {
    background-color: #<?=$this->colorAccent2;?>;
}

.nav-tabs > li > a:hover,
.nav-tabs > li > a:focus {
    color: #fff;
    border-color: #<?=$this->colorAccent2;?> #<?=$this->colorAccent2;?> transparent;
    background-color: #<?=$this->colorAccent2;?>;
}

.nav-tabs > li.active > a,
.nav-tabs > li.active > a:hover,
.nav-tabs > li.active > a:focus {
    color: #fff;
    border-color: #<?=$this->colorAccent1;?>;
    background-color: #<?=$this->colorAccent1;?>;
}

.nav-voting > .active > a:before {
    background-color: #<?=$this->colorAccent1;?>;
}

/* Navbar */
.navbar-default {
    background-color: #<?=$this->colorAccent2;?>;
}

.navbar-default .navbar-nav > li > a:hover,
.navbar-default .navbar-nav > li > a:focus {
    background-color: #<?=$this->colorAccent1;?>;
}

/* Pagination */
.pagination > li > a,
.pagination > li > span {
    background-color: #<?=$this->colorAccent2;?>;
}

.pagination > li > a:hover,
.pagination > li > span:hover,
.pagination > li > a:focus,
.pagination > li > span:focus {
    background-color: #<?=$this->colorAccent1;?>;
}

.pagination > .active > a,
.pagination > .active > span,
.pagination > .active > a:hover,
.pagination > .active > span:hover,
.pagination > .active > a:focus,
.pagination > .active > span:focus {
    background-color: #<?=$this->colorAccent1;?>;
}

/* Badges */
.badge-accent {
    background-color: #<?=$this->colorAccent1;?>;
}

/* Stickers */
.sticker-label-accent {
    background-color: #<?=$this->colorAccent1;?>;
}

/* Wells */
.well-title {
    color: #<?=$this->colorAccent1;?>;
}

.well-accent {
    background: #<?=$this->colorAccent1;?>;
}

/* Modals */
.modal-header-jumbo {
    background-color: #<?=$this->colorAccent1;?>;
}

/* Forms */
.form-control:focus {
    border-color: #<?=$this->colorAccent1;?>;
}

.form-search .form-control {
    border-color: #<?=$this->colorAccent1;?>;
    background-color: #<?=$this->colorAccent1;?>;
}

/* Consultation */
.consultation-heading-title,
.consultation-heading-subtitle {
    color: #<?=$this->colorAccent2;?>;
}

.consultation-heading:hover .consultation-heading-title,
.consultation-heading:focus .consultation-heading-title,
.consultation-heading:hover .consultation-heading-subtitle,
.consultation-heading:focus .consultation-heading-subtitle {
    color: #<?=$this->colorAccent1;?>;
}

a.consultation-phases-item:hover,
a.consultation-phases-item:focus {
    background-color: #<?=$this->colorAccent1;?>;
}

a.consultation-phases-item:hover:after,
a.consultation-phases-item:focus:after {
    border-color: #<?=$this->colorAccent1;?> transparent transparent;
}

@media (min-width: 768px) {
    a.consultation-phases-item:hover:after,
    a.consultation-phases-item:focus:after {
        border-color: transparent transparent transparent #<?=$this->colorAccent1;?>;
    }
}

@media (min-width: 992px) {
    .consultation-phases-preview-image-description {
        background-color: #<?=$this->colorAccent1;?>;
    }
}

/* Counter */
.counter-digit {
    color: #<?=$this->colorAccent1;?>;
}

/* Results */
.result-number {
    color: #<?=$this->colorAccent1;?>;
}

.result-bar {
    background-color: #<?=$this->colorAccent1;?>;
}
