<?php
/**
 * index
 *
 * @description   Startseite, Übersicht neueste Konsultationen
 * @author        Jan Suchandt/Markus Hackel
 */
?>
<?php $date = new Zend_Date();?>
<?php foreach ($this->consultations as $con):?>
<?php
$disabled = array(
  'input' => ($date->isEarlier($con->inp_fr) || $date->isLater($con->inp_to)),
  'voting' => ($date->isEarlier($con->vot_fr) || $date->isLater($con->vot_to)),
  'follow-up' => (!$date->isLater($con->vot_to)),
);
?>
<!--//<?php Zend_Debug::dump($con)?>-->
<div class="consultation consultation-preview">
	<a href="<?php echo $this->url(array('controller' => 'article', 'kid' => $con->kid))?>" class="title">
		<hgroup>
			<h1><?php echo $con->titl?></h1>
			<h2><?php echo $con->titl_sub?></h2>
		</hgroup>
	</a>

	<span class="label label-mitmachen">Mitmachen</span>

	<ul class="nav nav-pills">
		<li class="item-title">
			<a href="<?php echo $this->url(array('controller' => 'article', 'kid' => $con->kid))?>">
				<img src="<?php echo $this->baseUrl; ?>/media/consultations/<?php echo $con->kid . '/' . $con->img_file;?>" width="144" alt="<?php echo $con->img_expl?>" />
				<span class="description"><?php echo $con->expl?></span>
			</a>
		</li>
		<li>
			<a href="<?php echo $this->url(array('controller' => 'article', 'kid' => $con->kid))?>">
				<h2>Infos</h2>
			</a>
		</li>
		<li>
			<a href="<?php echo $this->url(array('controller' => 'question', 'kid' => $con->kid))?>">
				<h2>Fragen</h2>
			</a>
		</li>
		<?php if (!$disabled['input']): ?>
		<li>
			<a href="<?php echo $this->url(array('controller' => 'input', 'kid' => $con->kid))?>">
				<h2>Beiträge</h2>

				<!-- Bubble -->
				<div class="bubble bubble-large">
					<h3>Headline zweizeilig!</h3>
					<span>Unterzeile optional ebenfalls zweizeilig</span>
				</div>
			</a>
		</li>
		<?php else: ?>
		<li class="item-disabled">
			<div>
				<h2>Beiträge</h2>

				<small class="info">
					vom <?php echo $date->set($con->inp_fr)->get(Zend_Date::DATE_MEDIUM, new Zend_Locale()) . ' ' . $date->set($con->inp_fr)->get(Zend_Date::TIME_SHORT, new Zend_Locale())?><br />
					bis <?php echo $date->set($con->inp_to)->get(Zend_Date::DATE_MEDIUM, new Zend_Locale()) . ' ' . $date->set($con->inp_to)->get(Zend_Date::TIME_SHORT, new Zend_Locale())?>
				</small>
			</div>
		</li>
		<?php endif; ?>
		<?php if (!$disabled['voting']): ?>
		<li>
			<a href="<?php echo $this->url(array('controller' => 'voting', 'kid' => $con->kid))?>">
				<h2>Abstimmung</h2>
			</a>
		</li>
		<?php else: ?>
		<li class="item-disabled">
			<div>
				<h2>Abstimmung</h2>

				<small class="info">
					vom <?php echo $date->set($con->vot_fr)->get(Zend_Date::DATE_MEDIUM, new Zend_Locale()) . ' ' . $date->set($con->vot_fr)->get(Zend_Date::TIME_SHORT, new Zend_Locale())?><br />
					bis <?php echo $date->set($con->vot_to)->get(Zend_Date::DATE_MEDIUM, new Zend_Locale()) . ' ' . $date->set($con->vot_to)->get(Zend_Date::TIME_SHORT, new Zend_Locale())?>
				</small>
			</div>
		</li>
		<?php endif; ?>
		<?php if(!$disabled['follow-up']): ?>
		<li>
			<a href="<?php // TODO echo $this->url(array('controller' => 'followup', 'kid' => $con->kid))?>">
				<h2>Reaktionen & Wirkung</h2>
			</a>
		</li>
		<?php else: ?>
		<li class="item-disabled">
			<div>
				<h2>Reaktionen & Wirkung</h2>
			</div>
		</li>
		<?php endif; ?>
	</ul>
</div><!-- .consultation -->
<?php endforeach;?>
