<?php
/**
 * search
 *
 * @description   Overview of search results
 * @author        Jan Suchandt
 */
?>

<div class="content-holder main-content">

    <article class="article article-detail">
        <h1>Suche nach &quot;<?php echo $this->needle; ?>&quot;</h1>

        <h2>Suche in Grundinformationen</h2>
        <?php if (count($this->resultsGeneral) > 0): ?>
                <?php $staticArticles = array(
                    'about', 'imprint', 'faq', 'privacy', 'contact'
                );?>
                <ul>
                    <?php foreach ($this->resultsGeneral AS $article): ?>
                        <li>
                            <a
                                href="<?php echo in_array($article['ref_nm'], $staticArticles) ? $this->baseUrl() . '/' . $article['ref_nm'] : $this->baseUrl() . '/article/show/aid/' . $article['art_id']?>"
                                title="<?php echo $article['desc']?>"
                            >
                                <?php echo $article['desc']?>
                            </a>
                       </li>
                    <?php endforeach?>
                </ul>
        <?php else: ?>
            <ul><li>Es wurden keine relevanten Ergebnisse mit diesem Suchbegriff gefunden.</li></ul>
        <?php endif ?>


        <h2>Suche in Beteiligungsrunden</h2>
        <?php if (count($this->resultsConsultations) > 0): ?>
            <?php foreach ($this->resultsConsultations AS $consultation): ?>
                <?php if (
                    count($consultation['articles']) > 0
                    || count($consultation['questions']) > 0
                    || count($consultation['inputs']) > 0
                    || isset($consultation['inExpl']))
                : ?>
                    <h3><?php echo $consultation['titel']?></h3>

                    <?php if (count($consultation['articles']) > 0 || isset($consultation['inExpl'])): ?>
                        <h4>Informationsseiten</h4>
                        <ul>
                            <?php if (isset($consultation['inExpl'])): ?>
                                <li>
                                    <a href="<?php echo $this->baseUrl()?>/article/index/kid/<?php echo $consultation['cid']?>" title="Übersichtsseite">
                                        Übersichtsseite
                                    </a>
                                </li>
                            <?php endif?>
                            <?php foreach ($consultation['articles'] AS $article): ?>
                                <li>
                                    <a
                                        href="<?php echo $this->baseUrl()?>/article/show/kid/<?php echo $consultation['cid']?>/aid/<?php echo $article['art_id']?>"
                                        title="<?php echo $article['desc']?>"
                                    >
                                        <?php echo $article['desc']?>
                                    </a>
                                   </li>
                            <?php endforeach?>
                        </ul>
                    <?php endif?>
                        <?php if (count($consultation['questions']) > 0): ?>
                            <h4>Fragen</h4>
                            <ul>
                                <?php foreach ($consultation['questions'] AS $question): ?>
                                    <li>
                                        <a
                                            href="<?php echo $this->baseUrl()?>/question/show/kid/<?php echo $consultation['cid']?>/qid/<?php echo $question['qi']?>"
                                            title="<?php echo $question['q']?>"
                                        >
                                            <?php echo $question['q']?>
                                        </a>
                                        <br />
                                        <?php echo strip_tags($question['q_xpl'])?>...
                                    </li>
                                <?php endforeach?>
                            </ul>
                    <?php endif?>

                    <?php if (count($consultation['inputs']) > 0): ?>
                        <h4>Nutzerbeitr&auml;ge</h4>
                        <ul>
                            <?php foreach ($consultation['inputs'] AS $input): ?>
                                <li>
                                    <a
                                        href="<?php echo $this->baseUrl()?>/input/show/kid/<?php echo $consultation['cid']?>/qid/<?php echo $input['qi']?>#input-<?php echo $input['tid']?>"
                                        title="' . $thes . '"
                                    >
                                        <?php echo stripslashes(strip_tags($input['thes']))?>
                                    </a>
                                    <br />
                                    <?php echo $this->perex($input['expl'], 150, array('HTML_ENTITY_DECODE', 'STRIP_TAGS', 'STRIPSLASHES'))?>
                                </li>
                            <?php endforeach?>
                        </ul>
                    <?php endif?>
                <?php endif?>
            <?php endforeach?>
        <?php endif?>

        <h2>Suche in Follow-up files</h2>
        <?php if (count($this->resultsFollowFiles) > 0): ?>
            <ul>
                <?php foreach ($this->resultsFollowFiles AS $followUp): ?>
                    <li>
                        <a
                            href="<?php echo $this->baseUrl()?>/followup/index/kid/<?php echo $followUp['kid']?>#<?php echo $followUp['ref_doc']?>"
                        >
                            <?php echo $followUp['titl']?>
                            (<?php echo $followUp['who']?>)
                            <br />
                        </a>
                   </li>
                <?php endforeach?>
            </ul>
        <?php else: ?>
            <ul><li>Es wurden keine relevanten Ergebnisse mit diesem Suchbegriff gefunden.</li></ul>
        <?php endif ?>

        <h2>Suche in Follow-ups</h2>
        <?php if (count($this->resultsFollowUps) > 0): ?>
            <ul>
                <?php foreach ($this->resultsFollowUps AS $followUp): ?>
                    <li>
                            <?php echo $followUp['expl']?>
                            <?php echo $followUp['titl']?>
                            (<?php echo $followUp['who']?>)
                            <br />
                        </a>
                   </li>
                <?php endforeach?>
            </ul>
        <?php else: ?>
            <ul><li>Es wurden keine relevanten Ergebnisse mit diesem Suchbegriff gefunden.</li></ul>
        <?php endif ?>
     </article>

</div><!-- .main-content -->
