<div class="main-content">

    <article class="article">
        <h1><?=sprintf($this->translate('Search for "%s"'), $this->needle)?></h1>

        <h2><?=$this->translate('Search in basic information')?></h2>
        <?php if (count($this->resultsGeneral) > 0): ?>
                <?php $staticArticles = array('about', 'imprint', 'faq', 'privacy', 'contact');?>
                <ul>
                    <?php foreach ($this->resultsGeneral as $article): ?>
                        <li>
                            <a
                                href="<?=in_array($article['ref_nm'], $staticArticles) ? $this->baseUrl() . '/' . $article['ref_nm'] : $this->baseUrl() . '/article/show/aid/' . $article['art_id']?>"
                                title="<?=$this->escape($article['desc']);?>"
                            >
                                <?=$this->escape($article['desc']);?>
                            </a>
                       </li>
                    <?php endforeach?>
                </ul>
        <?php else: ?>
            <ul>
                <li><?=$this->translate('There are no relevant search results on this term.')?></li>
            </ul>
        <?php endif ?>

        <h2><?=$this->translate('Search in participation rounds')?></h2>
        <?php if (count($this->resultsConsultations) > 0): ?>
            <?php foreach ($this->resultsConsultations as $consultation): ?>
                <?php if (
                    count($consultation['articles']) > 0
                    || count($consultation['questions']) > 0
                    || count($consultation['inputs']) > 0
                ): ?>
                    <h3><?=$this->escape($consultation['titel'])?></h3>

                    <?php if (count($consultation['articles']) > 0): ?>
                        <h4><?=$this->translate('Information pages')?></h4>
                        <ul>
                            <?php foreach ($consultation['articles'] AS $article): ?>
                                <li>
                                    <a
                                        href="<?php echo $this->baseUrl()?>/article/show/kid/<?php echo $consultation['cid']?>/aid/<?php echo $article['art_id']?>"
                                        title="<?=$this->escape($article['desc']);?>"
                                    >
                                        <?=$this->escape($article['desc']);?>
                                    </a>
                                   </li>
                            <?php endforeach?>
                        </ul>
                    <?php endif?>
                        <?php if (count($consultation['questions']) > 0): ?>
                            <h4><?=$this->translate('Questions');?></h4>
                            <ul>
                                <?php foreach ($consultation['questions'] AS $question): ?>
                                    <li>
                                        <a
                                            href="<?php echo $this->baseUrl()?>/input/show/kid/<?php echo $consultation['cid']?>/qid/<?php echo $question['qi']?>"
                                            title="<?=$this->escape($question['q']);?>"
                                        >
                                            <?=$this->escape($question['q']);?>
                                        </a>
                                        <br />
                                        <?=$this->escape(strip_tags($question['q_xpl']));?>...
                                    </li>
                                <?php endforeach?>
                            </ul>
                    <?php endif?>

                    <?php if (count($consultation['inputs']) > 0): ?>
                        <h4><?=$this->translate('User Contributions');?></h4>
                        <ul>
                            <?php foreach ($consultation['inputs'] AS $input): ?>
                                <li>
                                    <a
                                        href="<?php echo $this->baseUrl()?>/input/show/kid/<?php echo $consultation['cid']?>/qid/<?php echo $input['qi']?>#input-<?php echo $input['tid']?>"
                                        title="<?=$this->escape(strip_tags($input['thes']));?>"
                                    >
                                        <?=$this->escape(strip_tags($input['thes']));?>
                                    </a>
                                    <br />
                                    <?=$this->escape($this->perex(strip_tags($input['expl']), 150));?>
                                </li>
                            <?php endforeach?>
                        </ul>
                    <?php endif?>
                <?php endif?>
            <?php endforeach?>
        <?php endif?>

        <h2><?=$this->translate('Search in Reactions & Impact');?></h2>
        <ul class="followup-search media-list">
            <?php foreach ($this->resultsFollowUps as $followUp): ?>
                <li>
                    <div class="followup-preview media">
                        <a
                            href="<?php echo $this->baseUrl() . '/media/' . Service_Media::MEDIA_DIR_CONSULTATIONS . '/' . $followUp['consultationId'] . '/' . $followUp['filename']?>"
                            class="followup-image pull-left"
                        >
                            <img
                                src="<?php echo $this->baseUrl() . '/media/' . Service_Media::MEDIA_DIR_CONSULTATIONS . '/' . $followUp['consultationId'] . '/' . $followUp['filenameThumb']?>"
                                alt="<?=$this->escape($followUp['title']);?>"
                            />
                        </a>
                        <div class="media-body">
                            <a href="<?php echo $this->baseUrl() . '/media/' . Service_Media::MEDIA_DIR_CONSULTATIONS . '/' . $followUp['consultationId'] . '/' . $followUp['filename']?>">
                                <h3 class="followup-title"><?=$this->escape($followUp['title']);?></h3>
                            </a>
                            <time class="followup-time">
                                <?php if ($followUp['isOnlyMonthYearShowed']): ?>
                                    <?php echo $this->formatDate($followUp['timeReleased'], Zend_Date::MONTH_NAME . ' ' . Zend_Date::YEAR)?>
                                <?php else:?>
                                    <?php echo $this->formatDate($followUp['timeReleased'])?>
                                <?php endif?>
                            </time><br />
                            <p class="followup-author"><?php echo $followUp['releasedBy']?></p>

                            <h4><?=$this->translate('Reactions');?></h4>
                            <ul>
                                <?php foreach ($followUp['snippets'] as $snippet): ?>
                                    <li>
                                        <p class="followup-snippet">
                                            <?=$this->wysiwyg($snippet['text']);?>
                                        </p>
                                    </li>
                                <?php endforeach?>
                            </ul>
                        </div>
                    </div><!-- .followup-preview -->
                </li>
            <?php endforeach?>
        </ul>

     </article>

    <?=$this->partial('_partials/pageLinks.phtml');?>

</div><!-- .main-content -->
