<div class="main-content">

    <h1>Uups</h1>
    <p><?php echo $this->message; ?></p>

    <?php if ('development' == $this->environment || 'development2' == $this->environment || 'development_karsten' == $this->environment) : ?>
        <h2>Exception:</h2>
        <p><b>Message</b> <?php echo $this->exception->getMessage(); ?></p>
        <h2>Stack trace:</h2>
        <pre><?php echo $this->exception->getTraceAsString(); ?></pre>
    <?php endif; ?>

</div><!-- .main-content -->
