<?php
    $settings = $this->settings;
    $this->layout()->settings = $settings;
    $this->layout()->labels = $array = explode(',', $settings['btn_labels']);
?>

<div class="main-content">

    <h1><?=$this->translate('Confirmation of your votes.');?></h1>
    <p><?=$this->translate('Here you can check your previous votes. Please confirm or delete them with the buttons below.');?></p>

    <div class="offset-bottom">
        <?=$this->form;?>
    </div>

    <!-- Questions -->
    <?=$this->partialLoop('_partials/voting/votingConfirmationQuestionThesis.phtml', $this->votesData);?>

    <?=$this->form;?>

</div><!-- .main-content -->
