<div class="main-content">

    <?php if ($this->act == 'confirm'): ?>
        <h1><?=$this->translate('This group member has now been confirmed.')?></h1>
        <p>
            <?=sprintf($this->translate('Thank you for confirming the group member with the email address "%s". The votes are now being counted for your group.'), $this->subuser)?>
        </p>
    <?php elseif ($this->act == 'reject'): ?>
        <h1><?=$this->translate('Individual vote has been rejected and will not be counted.')?></h1>
        <p>
            <?=sprintf($this->translate('The votings connected to the email address  "%s" will not be included in the end results of your group. The person will not receive information about your decision, but you may contact this person if you wish.'), $this->subuser)?>
        </p>
    <?php endif; ?>

    <p>
        <a href="<?php echo $this->url(array('controller' => 'index'), 'default', true); ?>">
            <?=$this->translate('Back to Home')?>
        </a>
    </p>

</div><!-- .main-content -->
