<?php
/**
 * index
 *
 * @description   Startseite Abstimmung
 * @author        Markus Hackel, Jan Suchandt
 */
?>
<!-- Secondary navigation -->
<?php echo $this->secondNavigation('voting')?>
<!-- .secondary-navigation -->

<!-- Content start -->

<div class="content-holder">
	<div class="row">
		<aside class="span3">

			<?php
			// @todo Sidebar navigation
			?>
			<?php if ($this->consultation->vot_res_show == 'y'): ?>
			<p><a href="<?php echo $this->url(array(
			  'action' => 'results',
			  'authcode' => null
			)); ?>">Votingergebnisse ansehen</a></p>
			<?php endif; ?>

		</aside>
		<section class="main-content span9">

			<h1>Anmelden zur Abstimmung zu &quot;<?php echo $this->consultationTitle; ?>&quot;</h1>
			<p>
			  Hier k&ouml;nnt Ihr dar&uuml;ber abstimmen, welche der Beitr&auml;ge zum Thema &quot;<?php echo $this->consultation['titl_short']; ?>&quot;
			  Ihr besonders wichtig findet! Bei den Beitr&auml;gen handelt es sich um Meinungen, Positionen und Vorschl&auml;ge, die uns
			  Jugendliche und Jugendgruppen in den letzten Wochen und Monaten zurückgemeldet haben.
			</p>

			<!-- Access form -->
			<div class="well well-large text-center">
				<span class="label sticker label-mitmachen-black">Mitmachen!</span>
				<h2>Stimme jetzt ab!</h2>
				<p>Die Abstimmung ist anonym. Deine E-Mail-Adresse nutzen wir nur, um zu überprüfen,<br />
					ob Du berechtigt bist, an der Abstimmung teilzunehmen.
				</p>
				<div class="form-inline">
				<?php echo $this->authform; ?>
				</div>
				<? echo (!empty($this->votingExplanation)) ? '<p>'.$this->votingExplanation.'</p>':''; ?>
			</div>

			<!-- Print -->
			<a href="javascript:print();" class="print">Seite drucken <i class="icon-print"></i></a>
		</section>
	</div><!-- .row -->
</div><!-- .content-holder -->

<!-- Content end -->

<!-- Top link -->
<div class="top-link">
	<a href="#top" class="js-scroll"><i class="icon-angle-up icon-large"></i> nach oben</a>
</div>

