<?php
    $settings = $this->settings;
    $this->layout()->settings = $settings;
    $this->layout()->labels = $array = explode (',', $settings['btn_labels']);
?>

<?php if ($this->error == 1): ?>
    <div class="alert alert-warning">
        <span class="glyphicon glyphicon-warning-sign icon-offset" aria-hidden="true"></span>
        <?=$this->error_comment;?>
    </div>
<?php else: ?>
    <?=$this->partial('_partials/voting/votingPreviewButtons.phtml', $this->feedback);?>
<?php endif; ?>
