<?php
    $settings = $this->settings;
    $this->layout()->settings = $settings;
    $this->layout()->labels = $array = explode (',', $settings['btn_labels']);
?>

<?=$this->secondNavigation('voting');?>

<div class="main-content">
    <div class="row">
        <div class="sidebar-left">

            <p>
                <span class="glyphicon glyphicon-arrow-left icon-offset text-muted" aria-hidden="true"></span>
                <a href="<?=$this->url(['action' => 'overview']);?>"><?=$this->translate('Continue voting');?></a>
                <br />
                <span class="glyphicon glyphicon-log-out icon-offset text-muted" aria-hidden="true"></span>
                <a href="<?=$this->url(['action' => 'stopvoting']);?>"><?=$this->translate('Finish voting');?></a>
            </p>

        </div>
        <div class="content">

            <div class="text-muted">
                <small>
                    <?=sprintf($this->translate('You have already voted on %s out of %s contributions.'), $this->escape($this->votedInputs), $this->escape($this->votableInputs));?>
                </small>
            </div>

            <h1><?=$this->translate('Overview of your votes');?></h1>
            <p>
                <?=$this->translate('Here you can see all contributions to be voted and your votes. You can still change your votes if you like.');?>
            </p>

            <!-- Questions -->
            <?=$this->partialLoop('_partials/voting/votingPreviewQuestion.phtml', $this->questions);?>

        </div>
    </div><!-- .row -->

    <?=$this->partial('_partials/pageLinks.phtml', ['help' => 'help-text-consultation-voting']);?>

</div><!-- .main-content -->
