<?php
    $this->layout()->settings = $this->settings;
    $this->layout()->buttonsDefault = $this->buttonsDefault;
    $this->layout()->buttons = $this->buttons;
?>

<?php if ($this->error == 1): ?>
    <div class="alert alert-warning">
        <span class="glyphicon glyphicon-warning-sign icon-offset" aria-hidden="true"></span>
        <?=$this->error_comment;?>
    </div>
<?php else: ?>
    <?=$this->partial('_partials/voting/votingPreviewButtons.phtml', $this->feedback);?>
<?php endif; ?>
