<?php echo $this->secondNavigation('voting') ?>

<div class="main-content">
	<div class="row">
		<div class="col-md-9 col-md-offset-3">

			<h1><?=$this->translate('Thank you for voting!')?></h1>
			<p>
                <?=$this->translate("If you haven't finished voting on all contributions, you can login any time and finish your votings.")?>
            </p>
			<?php if (!empty($this->groupmember)): ?>
				<p>
                    <?=sprintf($this->translate('An email has been sent to %s. Please check your inbox!'), '<b>' . $this->groupmember . '</b>')?>
                </p>
			<?php endif; ?>
			<p>
                <a href="<?php echo $this->url(array('controller' => 'index'), 'default', true); ?>">
                    <?=$this->translate('Back to Home')?>
                </a>
            </p>
		</div>
	</div><!-- .row -->

	<?=$this->render('_partials/pageLinks.phtml');?>

</div><!-- .main-content -->
