<?php
$this->layout()->pageTitle = $this->pageTitle(
    Application_View_Helper_PageTitle::VOTING_PAGE,
    $this->consultation
);
?>

<?=$this->secondNavigation('voting');?>

<div class="main-content">

    <h1 class="text-center">
        <?=$this->translate('Voting for');?>
        &quot;<?=$this->escape($this->consultation->titl);?>&quot;
    </h1>

    <div class="row">
        <div class="col-sm-12 col-md-10 col-md-offset-1">

            <?php if ($this->noMoreThesis): ?>

                <p>
                    <span class="glyphicon glyphicon-info-sign icon-offset text-info" aria-hidden="true"></span>
                    <?=$this->translate('There are no more contributions to be voted in this category. Please switch to another questions or another keyword.');?>
                </p>

                <p>
                    <a href="<?=$this->url(['controller' => 'voting', 'action' => 'overview', 'kid' => $this->consultation->kid], null, true);?>#voting" class="btn btn-default">
                        <?=$this->translate('Change question or keyword');?>
                    </a>
                    <a href="<?=$this->url(['action' => 'stopvoting', 'tag' => null]);?>" class="btn btn-default" title="<?=$this->translate('Finish voting');?>">
                        <span class="glyphicon glyphicon-log-out icon-offset" aria-hidden="true"></span>
                        <?=$this->translate('Finish');?>
                    </a>
                </p>

            <?php else: ?>
                <?php $this->lightsOut = true; ?>
                <div id="vote" class="well well-bordered well-accent text-center lights-out-content">

                    <div class="row">
                        <div class="col-sm-4 text-left">

                            <!-- Counter -->
                            <div class="offset-bottom">
                                <?php
                                    // Add leading zeros to count voted
                                    $countTotal = $this->thesesCount;
                                    $countVoted = $this->thesesCountVoted;

                                    if (strlen($countTotal) > strlen($countVoted)) {
                                        $format = '%0' . strlen($countTotal) . 'd';
                                        $countVoted = sprintf($format, $countVoted);
                                    }

                                    // Print count voted by number
                                    $countVoted = str_split($countVoted);
                                    $countVotedText = '';

                                    foreach ($countVoted as $number) {
                                        $countVotedText .= '<span class="counter-digit">' . $number . '</span>';
                                    }

                                    $counter = '<span class="counter">' . $countVotedText . '</span>';
                                ?>
                                <?=sprintf($this->translate('You have voted on %s <br /> out of the total of %s contributions.'), $counter, $countTotal);?>
                            </div>

                        </div>
                        <div class="col-sm-4">

                            <h2 class="well-title offset-bottom-large"><?=$this->translate('Vote now!');?></h2>

                        </div>
                    </div><!-- .row -->

                    <!-- Question -->
                    <h3>
                        <?=isset($this->question['nr']) ? $this->escape($this->question['nr']) : '';?>
                        <?=$this->escape($this->question['q']);?>
                    </h3>
                    <?php if (!empty($this->thesis['tagname_de'])): ?>
                        <h4>
                            <?=$this->translate('Keyword');?>:
                            <?=$this->escape($this->thesis['tagname_de']);?>
                        </h4>
                    <?php endif; ?>

                    <!-- Thesis -->
                    <div class="well well-simple text-left well-has-toggle">
                        <p>
                            <?=$this->escape($this->thesis['thes']);?>
                        </p>
                        <?php if ($this->question['video_enabled'] && $this->thesis['video_service'] !== null && $this->thesis['video_id'] !== null
                            && $this->videoServicesStatus['video_' . $this->thesis['video_service'] . '_enabled']): ?>
                            <p>
                                <?=$this->embeddedVideo($this->thesis['video_service'], $this->thesis['video_id']);?>
                            </p>
                        <?php endif; ?>

                        <?php if ($this->question['location_enabled'] && $this->thesis['latitude'] !== null): ?>
                            <div class="thumbnail">
                                <?=$this->openStreetStaticMap(
                                    $this->thesis['latitude'],
                                    $this->thesis['longitude'],
                                    640,
                                    240,
                                    14
                                );?>
                            </div>
                        <?php endif; ?>

                        <!-- Explanation toggle -->
                        <?php if (!empty($this->thesis['expl'])): ?>
                            <button type="button" class="btn btn-inverse btn-xs well-toggle js-toggle-voting-contribution-explanation" title="<?=$this->translate('Show explanation');?>">
                                <span class="glyphicon glyphicon-menu-down" aria-hidden="true"></span>
                                <span class="glyphicon glyphicon-menu-up hide" aria-hidden="true"></span>
                            </button>
                        <?php endif; ?>

                    </div>

                    <!-- Thesis explanation -->
                    <?php if (!empty($this->thesis['expl'])): ?>
                        <div id="voting-contribution-explanation" class="well well-simple well-simple-alt text-left" style="display: none;">
                            <?=$this->escape($this->thesis['expl']);?>
                        </div>
                    <?php endif; ?>

                    <!-- Rating bar -->
                    <div class="rating-bar">
                        <nav class="rating-bar-navigation">

                            <!-- Previous -->
                            <?php if (!empty($this->undoLinkParameters)): ?>
                                <a
                                    href="<?=$this->url($this->undoLinkParameters);?>#vote"
                                    class="btn btn-inverse rating-bar-navigation-prev"
                                >
                                    <span class="glyphicon glyphicon-menu-left icon-shift-down" aria-hidden="true"></span>
                                    <span class="hidden-xs"><?=$this->translate('Undo');?></span>
                                </a>
                            <?php endif; ?>

                            <p>
                                <strong>
                                    <?=$this->translate($this->defaultVoteQuestion);?>
                                </strong>
                            </p>

                            <!-- Next -->
                            <a
                                href="<?=$this->url($this->skipLinkParameters);?>#vote"
                                class="btn btn-inverse rating-bar-navigation-next"
                            >
                                <span class="hidden-xs"><?=$this->translate('Skip');?></span>
                                <span class="glyphicon glyphicon-menu-right icon-shift-down" aria-hidden="true"></span>
                            </a>

                        </nav>

                        <!-- Voting buttons -->
                        <?=$this->partial('_partials/voting/votingButtons.phtml', [
                            'settings' => $this->settings,
                            'votingBasket' => $this->votingBasket,
                            'buttonUndecidedLabel' => $this->buttonUndecidedLabel,
                            'buttonSkipLabel' => $this->buttonSkipLabel,
                            'buttonsDefault' => $this->buttonsDefault,
                            'buttons' => $this->buttons,
                            'skipLinkParameters' => $this->skipLinkParameters,
                            'thesis' => $this->thesis,
                        ]);?>

                    </div><!-- .rating-bar -->

                    <!-- Actions -->
                    <div class="form-group">
                        <a
                            href="<?=$this->url(['controller' => 'voting', 'action' => 'overview', 'kid' => $this->consultation->kid], null, true);?>#voting"
                            id="buttonChangeKeyword"
                            class="btn btn-default btn-default-alt"
                        >
                            <?=$this->translate('Change question or keyword');?>
                        </a>
                    </div>
                    <div class="form-group">
                        <a href="<?=$this->url(['action' => 'stopvoting']);?>" class="btn btn-default btn-default-alt" title="<?=$this->translate('Finish voting');?>">
                            <span class="glyphicon glyphicon-log-out icon-offset" aria-hidden="true"></span>
                            <?=$this->translate('Finish');?>
                        </a>
                        <a href="<?=$this->url(['action' => 'preview']);?>" class="btn btn-default btn-default-alt" title="<?=$this->translate('Preview voting');?>">
                            <span class="glyphicon glyphicon-eye-open icon-offset" aria-hidden="true"></span>
                            <?=$this->translate('Preview voting');?>
                        </a>
                    </div>

                </div><!-- .well -->
            <?php endif; ?>

        </div>
    </div><!-- .row -->

    <?=$this->partial('_partials/pageLinks.phtml', ['help' => 'help-text-consultation-voting']);?>

    <!-- Supervotes modal -->
    <?php if ($this->settings['is_btn_important']): ?>
        <div class="modal fade" id="modalVoting" tabindex="-1" role="dialog" aria-labelledby="modalVotingLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="<?=$this->translate('Close');?>">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <h4 class="modal-title" id="modalVotingLabel">
                            <span class="glyphicon glyphicon-star text-accent icon-offset" aria-hidden="true"></span>
                            <?=$this->translate('Decide what is most important!');?>
                        </h4>
                    </div>
                    <div class="modal-body">

                        <div class="media">
                            <div class="media-body">
                                <p>
                                    <?=$this->translate('The superbutton allows you to give certain contributions a higher vote. The overview shows you what you already marked as "especially important". Use the "–" to reset your markings and allow space for more important contributions.');?>
                                </p>
                            </div>
                            <div class="media-right">
                                <img src="<?=$this->baseUrl('images/voting-rate-superbtn.png');?>" alt="" />
                            </div>
                        </div>

                        <h4>
                            <?=$this->translate('Supervotes used:');?>
                            <span class="js-supervotes-used">
                                            <?=$this->votingBasket['countvotes'];?>
                                        </span>
                            <?=$this->translate('of');?>
                            <?=$this->settings['btn_important_max'];?>
                        </h4>

                        <table class="table table-striped">
                            <tbody>
                            <?php foreach ($this->votingBasket["votes"] as $v): ?>
                                <tr id="thes-<?=$v["tid"];?>">
                                    <td>
                                        <?=$this->escape($v["thes"]);?>
                                    </td>
                                    <td>
                                        <button
                                            type="button"
                                            class="btn btn-default btn-xs js-voting-remove-supervote"
                                            data-kid="<?=$this->consultation->kid;?>"
                                            data-tid="<?=$v["tid"];?>"
                                            title="<?=$this->translate('Remove');?>"
                                            >
                                            <span class="glyphicon glyphicon-minus" aria-hidden="true"></span>
                                        </button>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                            </tbody>
                        </table>

                    </div>
                </div><!-- .modal-content -->
            </div><!-- .modal-dialog -->
        </div><!-- .modal -->
    <?php endif; ?>

</div><!-- .main-content -->
