<?php
/**
 * edit
 *
 * @description   E-Mail-Vorlage bearbeiten/erstellen Forumlaransicht
 * @author        Jan Suchandt
 */
?>
<h2>E-Mail-Vorlage bearbeiten</h2>
<p>
  <a href="<?php echo $this->baseUrl(); ?>/admin/email/template/">&laquo; Zur&uuml;ck zur &Uuml;bersicht</a>
</p>
<?php echo $this->form;?>
<p>
  <b>Platzhalter</b>
  <ul>
    <li>{{USER}} - Nutzername</li>
    <li>{{CNSLT_TITLE}} - Titel der Beteiligungsrunde</li>
    <li>{{CNSLT_TITLE_SHORT}} - Kurztitel der Beteiligungsrunde</li>
    <li>{{SITEURL}} - URL zur Webseite</li>
    <li>{{CID}} - ID der Beteiligungsrunde</li>
    <li>{{INPUT_TO}} - Enddatum der Beitragsphasen</li>
    <li>{{USER_INPUTS}} - Beitr&auml;ge des Nutzers in Kurzform</li>
    <li>{{EMAIL}} - E-Mail-Adresse des Nutzers</li>
    <li>{{PWD}} - Passwort des Nutzers</li>
  </ul>
</p>
<p>
  <a href="<?php echo $this->baseUrl(); ?>/admin/email/template/">&laquo; Zur&uuml;ck zur &Uuml;bersicht</a>
</p>
<script type="text/javascript">
    CKEDITOR.replace('html');
</script>
