<?php
/**
 * index
 *
 * @description   Emails
 * @author        Jan Suchandt
 */
?>
<h1>E-Mail-Verwaltung</h1>

<h2>E-Mail senden</h2>
<p>
  <a href="<?php echo $this->baseUrl(); ?>/admin/email/">&laquo; Zur&uuml;ck zur &Uuml;bersicht</a>
</p>
<?php echo $this->form;?>
<p>
  <a href="<?php echo $this->baseUrl(); ?>/admin/email/">&laquo; Zur&uuml;ck zur &Uuml;bersicht</a>
</p>
<script type="text/javascript">
    CKEDITOR.replace('message');
</script>