<?php
    /**
     * index
     *
     * @description   Media Dashboard
     * @author        Markus Hackel
     */
    $gfxTest = array("jpg", "jpeg", "gif", "png", "svg"); // nur diese werden als Vorschau gezeigt
    $docTest = array("doc", "docx", "dot", "dotx", "odt", "ott", "rtf", "txt");
    $clcTest = array("xls", "xlsx", "xlst", "ods", "ots", "csv");
    $vidTest = array("avi", "divx", "flv", "mkv", "mov", "mpg", "mp4", "mp4v", "m4v", "ogv", "webm", "wmv", "3gp", "3g2");
    $audTest = array("aac", "au", "flac", "mid", "mka", "mp3", "m4a", "m4b", "ogg", "snd", "wav", "wma");
    $prsTest = array("ppt", "pptx", "odp", "otp");
    $pdfTest = array("pdf", "epub", "mobi");
    $pckTest = array("zip", "rar", "tar", "7z");
?>
<script>
    var DbjrAdmin = {
        Popup: {
            insertValue : function( value, elemid ){
                    window.opener.document.getElementById(elemid).value = value;
                    window.close();
            }
        }
    }
</script>

<h1>Datei wählen</h1>
<div class="info">
    <h3>Verzeichnis: <?php echo $this->directory;?></h3>
</div>

<?php if (!empty($this->files)):?>
    <div class="choosepopup">
        <ul id="galerie">
            <?php foreach ($this->files as $file):?>
                <li>
                    <a
                        href="#"
                        class="chooselink"
                        onclick="DbjrAdmin.Popup.insertValue('<?php echo $file['basename']; ?>', '<?php echo $this->elemid; ?>');"
                    >
                        <?php if (in_array(strtolower($file['extension']), $gfxTest)) {
                            echo '<img title ="'.$file['basename'].'" src="'.$this->directory . '/' . $file['basename'].'" width="140" alt="Vorschau" />';
                        } else {
                            echo '<img title ="'.$file['basename'].'" src="';
                            if (in_array(strtolower($file['extension']), $pdfTest)) {
                                echo $this->baseUrl() . '/images/cystal_clear_mimetype_pdf.png';
                            } elseif (in_array(strtolower($file['extension']), $pckTest)) {
                                echo $this->baseUrl() . '/images/crystal_clear_filesystem_folder_tar.png';
                            } elseif (in_array(strtolower($file['extension']), $docTest)) {
                                echo $this->baseUrl() . '/images/crystal_clear_mimetype_txt.png';
                            } elseif (in_array(strtolower($file['extension']), $prsTest)) {
                                echo $this->baseUrl() . '/images/crystal_clear_app_display.png';
                            } elseif (in_array(strtolower($file['extension']), $vidTest)) {
                                echo $this->baseUrl() . '/images/crystal_clear_mimetype_video.png';
                            } elseif (in_array(strtolower($file['extension']), $audTest)) {
                                echo $this->baseUrl() . '/images/crystal_clear_app_xmms.png';
                            } elseif (in_array(strtolower($file['extension']), $clcTest)) {
                                echo $this->baseUrl() . '/images/crystal_clear_mimetype_spreadsheet.png';
                            } else {
                                echo $this->baseUrl() . '/images/crystal_clear_mimetype_encrypted.png';
                            }

                            echo '" width="140" alt="Vorschau" />';
                        } ?>
                    </a>
                    <span>
                        <?php echo $this->CropText($file['filename'], 20, 'middle') . '.' . $file['extension'];?><br />
                        (<?php echo $file['size']; ?> KB)
                    </span>
                    <br />
                    <form action="<?php echo $this->downloadurl; ?>" method="post">
                         <input type="hidden" name="filename" value="<?php echo $file['basename']; ?>" />
                         <input
                            type="hidden"
                            name="file"
                            value="<?php echo $this->directory . '/' . $file['basename'];?>"
                        />
                         <input type="submit" value="Ansehen" />
                    </form>
                </li>
            <?php endforeach;?>
        </ul>
    </div>
<?php endif;?>

<div><?php echo $this->form ?></div>

