<section class="section-header">
    <div class="container">
        <div class="row">
            <div class="col-sm-8">
                <h1><?=$this->translate('Media');?></h1>
            </div>
            <div class="col-sm-4">
                <a
                    href="<?=$this->url(array('action' => 'upload', 'filename' => null));?>"
                    class="btn btn-primary cta"
                    >
                    <span class="glyphicon glyphicon-upload"></span> <?=$this->translate('Upload');?>
                </a>
            </div>
        </div>
    </div>
</section>
<section class="section-content">
    <div class="container">
        <div class="row">
            <div class="sidebar">

                <?php if (!$this->lockDir): ?>
                    <?=$this->mediaNavigation();?>
                <?php endif?>

            </div>
            <div class="content">

                <h2><?=$this->translate('Edit File');?></h2>

                <?=$this->form;?>

            </div>
        </div>
    </div>
</section>
