<section class="section-header">
    <div class="container">
        <div class="row">
            <div class="col-sm-8">
                <h1 class="section-header-title"><?=$this->translate('Media');?></h1>
            </div>
            <div class="col-sm-4">
                <a href="<?=$this->url(['action' => 'upload', 'filename' => null]);?>" class="btn btn-primary btn-raised cta">
                    <span class="glyphicon glyphicon-upload offset-right" aria-hidden="true"></span>
                    <?=$this->translate('Upload');?>
                </a>
            </div>
        </div>
    </div>
</section>
<section class="section-content">
    <div class="container">
        <div class="row">
            <div class="sidebar offset-bottom-large-sm-max">

                <?=$this->mediaNavigation('folders');?>

            </div>
            <div class="content">

                <a href="<?=$this->url(['action' => 'folders', 'folder' => null]);?>" class="back"><?=$this->translate('Back to Folders');?></a>
                <h2><?=$this->escape($this->pageTitle);?></h2>

                <?=$this->form;?>

                <p class="well">
                    <?=$this->translate('Folder name can contain only characters a-z, 0-9 and -.');?>
                </p>

            </div>
        </div>
    </div>
</section>
