<section class="section-header">
    <div class="container">
        <div class="row">
            <div class="col-sm-8">
                <h1><?=$this->translate('Media');?></h1>
            </div>
            <div class="col-sm-4">
                <a href="<?=$this->url(array('action' => 'upload', 'targetElId' => $this->targetElId));?>" class="btn btn-primary cta"><span class="glyphicon glyphicon-upload"></span> <?=$this->translate('Upload');?></a>
            </div>
        </div>
    </div>
</section>
<section class="section-content">
    <div class="container">
        <div class="row">
            <div class="col-md-3">

                <?=$this->mediaNavigation('all');?>

            </div>
            <div class="col-md-9">
                <h2><?=$this->title;?></h2>

                <?php if (!empty($this->files)): ?>
                    <div class="row">
                        <?php foreach ($this->files as $file):?>
                            <div class="col-xs-6 col-sm-4 col-lg-3">
                                <div class="thumbnail">
                                    <a
                                        <?=$this->targetElId
                                            ? 'onclick="mediaSelectPopup.insertValue(
                                                \'' . substr($file['dirname'], strlen(MEDIA_PATH)) . '/' . $file['basename'] . '\',
                                                \'' . $this->targetElId . '\',
                                                \'' . $this->baseUrl . '/media\'
                                            )"'
                                            : 'href="' . $this->url(['action' => 'download', 'filename' => $file['basename'], 'kid' => $file['kid'], 'folder' => $file['folder']]) . '/"';
                                        ?>
                                        title="<?=$file['basename'];?>"
                                    >
                                        <div class="thumbnail-image">
                                            <?php if (empty($file['icon'])): ?>
                                                <!-- TODO use resized thumbnail -->
                                                <img src="<?=$file['dirUrl'];?>/<?=$file['basename'];?>" alt="<?=$this->translate('Preview');?>" />
                                            <?php else: ?>
                                                <img
                                                    src="<?=$this->baseUrl()?>/images/<?=$file['icon']?>.png"
                                                    class="thumbnail-image-icon"
                                                    alt="<?=$this->translate('Preview');?>"
                                                />
                                            <?php endif?>
                                        </div>
                                        <div class="caption">
                                            <h4 class="thumbnail-title"><?=$file['basename'];?></h4>
                                            <small class="text-muted">
                                                <!-- TODO file size view helper -->
                                                <?=$file['size'];?>&nbsp;kB<br />
                                                <!-- TODO upload time -->
                                            </small>
                                        </div>
                                    </a>
                                    <?php if ($file['folder']): ?>
                                        <a href="<?=$this->url(['action' => 'edit-file', 'folder' => $file['folder'], 'filename' => $file['basename']]);?>/" class="item-action"><span class="glyphicon glyphicon-pencil"></span></a>
                                    <?php endif;?>
                                    <?=$file['deleteForm'];?>
                                </div>
                            </div>
                        <?php endforeach;?>
                    </div>
                <?php else: ?>
                    <p class="alert alert-info">
                        <span class="glyphicon glyphicon-info-sign"></span>
                        <?=$this->translate('No media has been uploaded yet.');?>
                    </p>
                <?php endif; ?>

            </div>
        </div>
    </div>
</section>
