<?php
    $settings = $this->layout()->settings;
    $labels = $this->layout()->labels;
?>

<ul class="nav nav-justified nav-voting text-center small">

    <?php if ($settings['is_btn_important']) : ?>
        <li class="nav-voting-<?=$settings['button_type'];?>-superbutton<?=$this->is_pimp ? ' active' : '';?>">
            <span>
                <span class="glyphicon glyphicon-star nav-voting-superbutton-icon icon-lg" aria-hidden="true"></span>
                <br />
                <?=$this->escape($settings['btn_important_label']);?>
            </span>
        </li>
    <?php endif; ?>
    <?php krsort($labels); ?>
    <?php foreach ($labels as $points => $label): ?>
        <li class="voting-button-<?=$settings['button_type'];?>-<?=$points;?><?=($this->points !== null && (int)$this->points === $points) ? ' active' : '';?>">
            <span><?=$this->translate($label);?></span>
        </li>
    <?php endforeach; ?>

    <?php if ($settings['btn_no_opinion']) : ?>
        <li class="voting-button-<?=$settings['button_type'];?>-undecided<?=($this->status === 'voted' && $this->points === null) ? ' active' : '';?>">
            <span><?=$this->translate('No opinion');?></span>
        </li>
    <?php endif; ?>

</ul>
