<?php
    $settings = $this->layout()->settings;
    $buttons = $this->layout()->buttons;
    $buttonsDefault = $this->layout()->buttonsDefault;
?>

<ul class="nav nav-justified nav-voting text-center small">

    <?php if ($settings['is_btn_important']) : ?>
        <li class="nav-voting-<?=$settings['button_type'];?>-superbutton<?=$this->is_pimp ? ' active' : '';?>">
            <span>
                <span class="glyphicon glyphicon-star nav-voting-superbutton-icon icon-lg" aria-hidden="true"></span>
                <br />
                <?=$this->escape($settings['btn_important_label']);?>
            </span>
        </li>
    <?php endif; ?>
    <?php krsort($buttonsDefault); ?>
    <?php foreach ($buttonsDefault as $points => $button): ?>
        <?php \Tracy\Debugger::barDump($button); ?>
        <?php if (isset($buttons[$points]) && $buttons[$points]['enabled']): ?>
            <li class="voting-button-<?=$settings['button_type'];?>-<?=$points;?><?=($this->points !== null && (int)$this->points === $points) ? ' active' : '';?>">
                <span>
                    <?=($buttons[$points]['label']
                        ?: $this->translate(
                            Service_Voting::BUTTONS_SET[$settings['button_type']]['buttons'][$points]['label']
                        ));?>
                </span>
            </li>
        <?php endif; ?>
    <?php endforeach; ?>

    <?php if ($settings['btn_no_opinion']) : ?>
        <li class="voting-button-<?=$settings['button_type'];?>-undecided<?=($this->status === 'voted' && $this->points === null) ? ' active' : '';?>">
            <span><?=$this->translate('No opinion');?></span>
        </li>
    <?php endif; ?>

</ul>
