<div class="row">
    <div class="col-sm-5">

        <div class="text-break">
            <p>
                <strong>
                    <?=$this->escape($this->thes);?>
                </strong>
            </p>
            <?php if (!empty($this->expl)): ?>
                <p>
                    <?=$this->escape($this->expl);?>
                </p>
            <?php endif; ?>

            <?php if ($this->video_enabled && $this->video_service !== null && $this->video_id !== null
                && $this->partialLoop()->view->videoServicesStatus['video_' . $this->video_service . '_enabled']): ?>
                <p>
                    <?=$this->embeddedVideo($this->video_service, $this->video_id);?>
                </p>
            <?php elseif ($this->video_id !== null) : ?>
                <p class="alert alert-info">
                    <span class="glyphicon glyphicon-info-sign text-info icon-offset" aria-hidden="true"></span>
                    <?=sprintf($this->translate('%s videos were disabled by admin for this question'), ucfirst($this->video_service));?>.
                </p>
            <?php endif; ?>
        </div>

    </div>
    <div class="col-sm-7">

        <!-- Voting buttons -->
        <div id="thesis-<?=$this->escape($this->tid);?>" class="js-voting">
            <?=$this->partial('_partials/voting/votingPreviewButtons.phtml', $this);?>
        </div>

    </div>
</div><!-- .row -->

<hr />
