<?php
    $settings = $this->layout()->settings;
    $labels = $this->layout()->labels;
?>

<ul class="nav nav-justified nav-voting text-center small">

    <?php if ($settings['is_btn_important']): ?>
        <li class="nav-voting-superbutton<?=$this['is_pimp'] ? ' active' : '';?>">
            <a href="#"
               data-tid="<?=$this->tid;?>"
               data-kid="<?=$settings['kid'];?>"
               data-rating="y"
               class="js-voting-rate"
            >
                <span class="glyphicon glyphicon-star nav-voting-superbutton-icon icon-lg" aria-hidden="true"></span>
                <br />
                <?=$this->escape($settings['btn_important_label']);?>
            </a>
        </li>
    <?php endif; ?>

    <?php for ($i = $settings['btn_numbers'] - 1; $i >= 0; $i--): ?>
        <li<?=($this->points !== null && $this->points == $i) ? ' class="active"' : '';?>>
            <a href="#"
               data-tid="<?=$this->tid;?>"
               data-kid="<?=$settings['kid'];?>"
               data-rating="<?=$i;?>"
               class="js-voting-rate"
            >
                <?=$this->escape($labels[$i]);?>
            </a>
        </li>
    <?php endfor; ?>

    <?php if ($settings['btn_no_opinion']): ?>
        <li<?=$this->points === null ? ' class="active"' : '';?>>
            <a href="#"
               data-tid="<?=$this->escape($this->tid);?>"
               data-kid="<?=$settings['kid'];?>"
               data-rating=""
               class="js-voting-rate"
            >
                <?=$this->translate('No opinion');?>
            </a>
        </li>
    <?php endif; ?>

</ul>
