<?php
    $settings = $this->layout()->settings;
    $labels = $this->layout()->labels;
    $votingBasket = $this->layout()->votingBasket;
    $linkOptions = ['action' => 'thesissupervote', 'tid' => $this->thesis['tid']];

    if (!empty($this->qid)) {
        $linkOptions['qid'] = $this->qid;
    }

    if (isset($this->thesis['tg_nr'])) {
        $linkOptions['tag'] = $this->thesis['tg_nr'];
    }
?>

<ul class="list-inline rating-bar-buttons">

    <!-- Super button -->
    <?php if ($settings['btn_important'] == 'y'): ?>
        <?php $linkOptions['pts'] = 'y'; ?>
        <li class="offset-bottom-small">
            <div class="offset-bottom-small">

                <?php if ($votingBasket['countvotes'] !== $settings['btn_important_max']): ?>
                    <a href="<?=$this->url($linkOptions);?>#vote" class="link-unstyled link-unstyled-alt">
                <?php else: ?>
                    <a href="#modalVoting" data-toggle="modal" class="link-unstyled link-unstyled-alt">
                <?php endif; ?>
                    <img
                        src="<?=$this->baseUrl('images/voting-rate-superbtn.png');?>"
                        class="offset-bottom-small"
                        alt="<?=$this->escape($settings['btn_important_label']);?>"
                        title="<?=$this->escape($settings['btn_important_label']);?>"
                    />
                    <br />
                    <strong<?=$this->pimp == 'y' ? ' class="text-danger"' : '';?>>
                        <?=$this->escape($settings['btn_important_label']);?>
                        <br />
                        (<span class="js-supervotes-used"><?=$votingBasket['countvotes'];?></span>
                        <?=$this->translate('of');?>
                        <?=$settings['btn_important_max'];?>)
                    </strong>
                </a>

            </div>

            <!-- Voting basket toggle -->
            <a href="#modalVoting"  data-toggle="modal" class="link-unstyled link-unstyled-alt" title="<?=$this->translate('Open voting basket');?>">
                <span class="glyphicon glyphicon-menu-down icon-md" aria-hidden="true"></span>
            </a>

        </li>
    <?php endif; ?>

    <!-- Regular votes -->
    <?php $linkOptions['action'] = 'thesisvote'; ?>
    <?php for ($i = $settings['btn_numbers'] - 1; $i >= 0; $i--): ?>
        <?php $linkOptions['pts'] = $i; ?>
        <li class="offset-bottom-small">
            <a href="<?=$this->url($linkOptions);?>#vote" class="link-unstyled link-unstyled-alt">
                <img
                    src="<?=$this->baseUrl('images/voting-rate-' . $i . '.png');?>"
                    class="offset-bottom-small"
                    alt="<?=$this->escape($labels[$i]);?>"
                    title="<?=$this->escape($labels[$i]);?>"
                />
                <br />
                <strong><?=$this->escape($labels[$i]);?></strong>
            </a>
        </li>
    <?php endfor; ?>

    <!-- No opinion -->
    <?php $linkOptions['pts'] = 5; ?>
    <li class="offset-bottom-small">
        <a href="<?=$this->url($linkOptions);?>#vote" class="link-unstyled link-unstyled-alt">
            <img src="<?=$this->baseUrl('images/voting-rate-no-opinion.png');?>" class="offset-bottom-small" alt="" />
            <br />
            <strong><?=$this->translate('No opinion');?></strong>
        </a>
    </li>

</ul>
