<div class="row">
    <div class="col-sm-5">

        <div class="text-break">
            <p>
                <strong>
                    <?=$this->escape($this->thes);?>
                </strong>
            </p>
            <?php if (!empty($this->expl)): ?>
                <p>
                    <?=$this->escape($this->expl);?>
                </p>
            <?php endif; ?>

            <?php if ($this->video_enabled && $this->video_service !== null && $this->video_id !== null
                && $this->partialLoop()->view->videoServicesStatus['video_' . $this->video_service . '_enabled']): ?>
                <p>
                    <?=$this->embeddedVideo($this->video_service, $this->video_id);?>
                </p>
            <?php endif; ?>
        </div>

    </div>
    <div class="col-sm-7">

        <!-- Voting buttons -->
        <div id="thesis-<?=$this->escape($this->tid);?>" class="js-voting">
            <?=$this->partial('_partials/voting/votingPreviewButtons.phtml', $this);?>
        </div>

    </div>
</div><!-- .row -->

<hr />
