<div class="row">
    <div class="col-sm-5">

        <div class="text-break">
            <p>
                <strong>
                    <?=$this->escape($this->thes);?>
                </strong>
            </p>
            <?php if (!empty($this->expl)) : ?>
                <p>
                    <?=$this->escape($this->expl);?>
                </p>
            <?php endif; ?>
        </div>

    </div>
    <div class="col-sm-7">

        <!-- Voting buttons -->
        <?=$this->partial('_partials/voting/votingConfirmationAnswers.phtml', $this);?>

    </div>
</div><!-- .row -->

<hr />
