<?php
    $linkParameters = ['action' => 'thesissupervote', 'tid' => $this->thesis['tid']];

    if (!empty($this->qid)) {
        $linkParameters['qid'] = $this->qid;
    }

    if (isset($this->thesis['tg_nr'])) {
        $linkParameters['tag'] = $this->thesis['tg_nr'];
    }

    $btnLabelPattern = sprintf('_svg/%s', Service_Voting::BUTTON_FILENAME_PATTERN);
?>

<ul class="list-inline rating-bar-buttons">

    <!-- Super button -->
    <?php if ($this->settings['is_btn_important']): ?>
        <?php $linkParameters['pts'] = 'y'; ?>
        <li class="offset-bottom-small">
            <div class="offset-bottom-small">

                <?php if ($this->votingBasket['countvotes'] < $this->settings['btn_important_max']): ?>
                    <a href="<?=$this->url($linkParameters);?>#vote" class="link-unstyled link-unstyled-alt">
                <?php else: ?>
                    <a href="#modalVoting" data-toggle="modal" class="link-unstyled link-unstyled-alt">
                <?php endif; ?>

                    <span class="icon-offset offset-bottom-small">
                        <?=$this->partial('_svg/button.svg.phtml', ['btnLabel' => sprintf($btnLabelPattern, $this->settings['button_type'], 'superbutton')]);?>
                    </span>

                    <strong<?=$this->is_pimp ? ' class="text-danger"' : '';?>>
                        <?=$this->escape($this->translate($this->settings['btn_important_label']));?>
                        <br />
                        (<span class="js-supervotes-used"><?=$this->votingBasket['countvotes'];?></span>
                        <?=$this->translate('of');?>
                        <?=$this->settings['btn_important_max'];?>)
                    </strong>
                </a>

            </div>

            <!-- Voting basket toggle -->
            <a href="#modalVoting"  data-toggle="modal" class="link-unstyled link-unstyled-alt" title="<?=$this->translate('Open voting basket');?>">
                <span class="glyphicon glyphicon-menu-down icon-md" aria-hidden="true"></span>
            </a>

        </li>
    <?php endif; ?>

    <!-- Regular votes -->
    <?php $linkParameters['action'] = 'thesisvote'; ?>
    <?php krsort($this->labels); ?>
    <?php foreach ($this->labels as $points => $label): ?>
        <?php $linkParameters['pts'] = $points; ?>
        <li class="offset-bottom-small">
            <a href="<?=$this->url($linkParameters);?>#vote" class="link-unstyled link-unstyled-alt">

                <?php
                if ($this->settings['button_type'] === 'yesno') {
                    $voteLabels = [
                        '-1' => 'disagree',
                        '0' => 'unsure',
                        '1' => 'agree',
                    ];
                } else {
                    $voteLabels = [
                        '0' => 'strongly-disagree',
                        '1' => 'disagree',
                        '2' => 'somewhat-disagree',
                        '3' => 'somewhat-agree',
                        '4' => 'agree',
                        '5' => 'strongly-agree',
                    ];
                }

                $btnLabel = '';
                if (array_key_exists($points, $voteLabels)) {
                    $btnLabel = sprintf($btnLabelPattern, $this->settings['button_type'], $voteLabels[$points]);
                }
                ?>
                <span class="icon-offset offset-bottom-small">
                    <?=$this->partial('_svg/button.svg.phtml', ['btnLabel' => $btnLabel]);?>
                </span>
                <strong><?=$this->translate($label);?></strong>
            </a>
        </li>
    <?php endforeach; ?>

    <!-- No opinion -->
    <?php if ($this->settings['btn_no_opinion']): ?>
        <?php $linkParameters['pts'] = null; ?>

        <li class="item-break offset-bottom-small">
            <a href="<?=$this->url($linkParameters);?>#vote" class="link-unstyled link-unstyled-alt">
                <?=$this->partial('_svg/button.svg.phtml', ['btnLabel' => sprintf($btnLabelPattern, $this->settings['button_type'], 'no-opinion')]);?>
                <strong><?=$this->translate($this->buttonUndecidedLabel);?></strong>
            </a>
        </li>
    <?php endif; ?>

</ul>
