<h1>Sent Emails</h1>

<form method="<?=$this->form->getMethod()?>">
    <?=$this->form->getElement('email_list_control_csrf_token')?>
    <table>
        <tr>
            <th>Time Sent</th>
            <th>Subject</th>
            <th>Aktionen</th>
        </tr>

                <?php foreach ($this->emails as $email): ?>
            <tr>
                <td>
                    <?php
                        $zendDate = new Zend_Date($email->time_sent);
                        echo($zendDate->get(Zend_Date::DATETIME_MEDIUM));
                    ?>
                </td>
                <td><?php echo $email->subject?></td>
                <td>
                    <button
                        name="resendId"
                        type="submit"
                        onclick="return confirm('Are you sure?');"
                        value="<?php echo $email->id?>"
                    >
                        Resend
                    </button>
                </td>
            </tr>
        <?php endforeach;?>

    </table>
</form>
