<section class="section-header">
    <div class="container">
        <div class="row">
            <div class="col-sm-8">
                <h1 class="section-header-title"><?=$this->translate('Email');?></h1>
            </div>
            <div class="col-sm-4">
                <a href="<?=$this->url(['controller' => 'mail-send', 'action' => 'index']);?>" class="btn btn-primary btn-raised cta">
                    <span class="glyphicon glyphicon-pencil offset-right" aria-hidden="true"></span>
                    <?=$this->translate('New Email');?>
                </a>
            </div>
        </div>
        <?=$this->emailTabs('emailing');?>
    </div>
</section>
<section class="section-content">
    <div class="container">
        <div class="row">
            <div class="sidebar offset-bottom-large-sm-max">

                <?=$this->emailNavigation('sent');?>

            </div>
            <div class="content">

                <h2><?=$this->translate('Sent Emails');?></h2>

                <?php if (!count($this->emails)): ?>
                    <p class="alert alert-info">
                        <span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>
                        <?=$this->translate('No emails have been sent yet.');?>
                    </p>
                <?php else: ?>

                    <form method="<?=$this->form->getMethod();?>">
                        <?=$this->form->getElement($this->form->getCsrfTokenName());?>
                        <table class="table">
                            <thead>
                                <tr>
                                    <th class="col-xs-3 sorting-desc" data-toggle="sort" tabindex="0"><?=$this->translate('Time Sent');?></th>
                                    <th data-toggle="sort" tabindex="0"><?=$this->translate('Subject');?></th>
                                    <th data-toggle="sort" tabindex="0"><?=$this->translate('Recipient');?></th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach ($this->emails as $email): ?>
                                    <tr>
                                        <td data-sort-value="<?=$this->escape($email['time_sent']);?>">
                                            <?=$this->formatDate($email['time_sent']);?>
                                        </td>
                                        <td><?=$this->escape($email['subject']);?></td>
                                        <td>
                                            <?php if (isset($email['recipients']['to'])): ?>
                                                <?=$this->translate('To')?>: <?=implode (', ', $email['recipients']['to']); ?>
                                            <?php endif;?>
                                            <?php if (isset($email['recipients']['cc'])): ?>
                                                <br />
                                                <?=$this->translate('Cc')?>: <?=implode (', ', $email['recipients']['cc']); ?>
                                            <?php endif;?>
                                            <?php if (isset($email['recipients']['bcc'])): ?>
                                                <br />
                                                <?=$this->translate('Bcc')?>: <?=implode (', ', $email['recipients']['bcc']); ?>
                                            <?php endif;?>
                                        </td>
                                        <td>
                                            <button
                                                class="item-action item-action-danger"
                                                name="resendId"
                                                type="submit"
                                                data-toggle="confirm"
                                                data-confirm-message="<?=$this->translate('Resend email?');?>"
                                                data-confirm-yes="<?=$this->translate('Yes');?>"
                                                data-confirm-no="<?=$this->translate('No');?>"
                                                value="<?=$this->escape($email['id']);?>"
                                                title="<?=$this->translate('Resend email');?>"
                                            >
                                                <span class="glyphicon glyphicon-share-alt" aria-hidden="true"></span>
                                            </button>
                                        </td>
                                    </tr>
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                    </form>

                <?php endif; ?>

            </div>
        </div>
    </div>
</section>
