<?php $btnId = '-' . rand(0, 1000000);?>
<svg class="btn-voting<?= (isset($this->btnHtmlClass) ? ' ' . $this->btnHtmlClass : '')?>" width="100%" height="100%" viewBox="0 0 64 61" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xml:space="preserve" xmlns:serif="http://www.serif.com/" style="fill-rule:evenodd;clip-rule:evenodd;stroke-linejoin:round;stroke-miterlimit:1.41421;">
    <g id="BUTTON<?=$btnId?>">
        <g id="BOTTOM<?=$btnId?>">
            <ellipse id="BUTTON-SHADOW<?=$btnId?>" cx="32" cy="36.291" rx="31.499" ry="23.924" style="fill:url(#_Radial1<?=$btnId?>);" />
            <ellipse id="COLOR<?=$btnId?>" cx="31.731" cy="35" rx="31" ry="24.357" style="fill:#f8fafe;" />
            <path id="COLOR1" serif:id="COLOR<?=$btnId?>" d="M0.731,35c0,-0.673 0,-3.327 0,-4c0,-13.443 13.89,-24.357 31,-24.357c17.109,0 31,10.914 31,24.357c0,0.673 0,3.327 0,4c0,13.443 -13.891,24.357 -31,24.357c-17.11,0 -31,-10.914 -31,-24.357Z" style="fill:#f8fafe;" />
            <path id="SHADOW-BLACK" d="M0.731,35c0,-0.673 0,-3.327 0,-4c0,-13.443 13.89,-24.357 31,-24.357c17.109,0 31,10.914 31,24.357c0,0.673 0,3.327 0,4c0,13.443 -13.891,24.357 -31,24.357c-17.11,0 -31,-10.914 -31,-24.357Z" style="fill:url(#_Linear2<?=$btnId?>);" />
            <ellipse id="SHADOW-WHITE" cx="31.731" cy="31" rx="31" ry="24.357" style="fill:url(#_Linear3<?=$btnId?>);" />
            <ellipse id="COLOR2<?=$btnId?>" serif:id="COLOR<?=$btnId?>" cx="31.731" cy="30.006" rx="29" ry="22.786" style="fill:url(#_Radial4<?=$btnId?>);" />
        </g>
        <path id="BUTTON-MASK<?=$btnId?>" d="M3.731,30c0,-1.366 0,-6.634 0,-8c0,-12.142 12.546,-22 28,-22c15.453,0 28,9.858 28,22c0,1.366 0,6.634 0,8c0,12.142 -12.547,22 -28,22c-15.454,0 -28,-9.858 -28,-22Z" style="fill:none;" />
        <clipPath id="_clip5">
            <path d="M3.731,30c0,-1.366 0,-6.634 0,-8c0,-12.142 12.546,-22 28,-22c15.453,0 28,9.858 28,22c0,1.366 0,6.634 0,8c0,12.142 -12.547,22 -28,22c-15.454,0 -28,-9.858 -28,-22Z" />
        </clipPath>
        <g clip-path="url(#_clip5)">
            <g id="BUTTON1<?=$btnId?>" serif:id="BUTTON<?=$btnId?>">
                <g id="BODY<?=$btnId?>">
                    <g id="BODY1<?=$btnId?>" serif:id="BODY<?=$btnId?>">
                        <path id="COLOR3<?=$btnId?>" serif:id="COLOR<?=$btnId?>" d="M3.731,30c0,-1.366 0,-6.634 0,-8c0,-12.142 12.546,-22 28,-22c15.453,0 28,9.858 28,22c0,1.366 0,6.634 0,8c0,12.142 -12.547,22 -28,22c-15.454,0 -28,-9.858 -28,-22Z" style="fill:#00b6ea;" />
                        <path id="BLACK-SHADOW<?=$btnId?>" d="M3.731,30c0,-1.366 0,-6.634 0,-8c0,-12.142 12.546,-22 28,-22c15.453,0 28,9.858 28,22c0,1.366 0,6.634 0,8c0,12.142 -12.547,22 -28,22c-15.454,0 -28,-9.858 -28,-22Z" style="fill:url(#_Radial6<?=$btnId?>);" />
                        <path id="BLACK-SHADOW1<?=$btnId?>" serif:id="BLACK-SHADOW<?=$btnId?>" d="M3.731,30c0,-1.366 0,-6.634 0,-8c0,-12.142 12.546,-22 28,-22c15.453,0 28,9.858 28,22c0,1.366 0,6.634 0,8c0,12.142 -12.547,22 -28,22c-15.454,0 -28,-9.858 -28,-22Z" style="fill:url(#_Linear7<?=$btnId?>);" />
                        <path id="WHITE-SHADOW<?=$btnId?>" d="M3.731,30c0,-1.366 0,-6.634 0,-8c0,-12.142 12.546,-22 28,-22c15.453,0 28,9.858 28,22c0,1.366 0,6.634 0,8c0,12.142 -12.547,22 -28,22c-15.454,0 -28,-9.858 -28,-22Z" style="fill:url(#_Linear8<?=$btnId?>);" />
                        <path id="WHITE-SHADOW1<?=$btnId?>" serif:id="WHITE-SHADOW<?=$btnId?>" d="M3.731,30c0,-1.366 0,-6.634 0,-8c0,-12.142 12.546,-22 28,-22c15.453,0 28,9.858 28,22c0,1.366 0,6.634 0,8c0,12.142 -12.547,22 -28,22c-15.454,0 -28,-9.858 -28,-22Z" style="fill:url(#_Radial9<?=$btnId?>);" />
                    </g>
                    <g id="TOP<?=$btnId?>">
                        <ellipse id="COLOR4<?=$btnId?>" serif:id="COLOR<?=$btnId?>" cx="31.731" cy="22" rx="28" ry="22" style="fill:#00b6ea;" />
                        <ellipse id="WHITE-SHADOW2<?=$btnId?>" serif:id="WHITE-SHADOW<?=$btnId?>" cx="31.731" cy="22" rx="28" ry="22" style="fill:url(#_Radial10<?=$btnId?>);" />
                        <ellipse id="WHITE-SHADOW3<?=$btnId?>" serif:id="WHITE-SHADOW<?=$btnId?>" cx="31.731" cy="22" rx="28" ry="22" style="fill:url(#_Radial11<?=$btnId?>);" />
                        <ellipse id="WHITE-SHADOW4<?=$btnId?>" serif:id="WHITE-SHADOW<?=$btnId?>" cx="31.731" cy="22" rx="28" ry="22" style="fill:url(#_Radial12<?=$btnId?>);" />
                    </g>
                </g>
                <?php if (isset($this->btnLabel) && $this->btnClean !== true) : ?>
                    <?=$this->partial($this->btnLabel, ['useSvgPathOnly' => true]);?>
                <?php // else ~ empty button without any icon ?>
                <?php endif; ?>
            </g>
        </g>
    </g>
    <defs>
        <radialGradient id="_Radial1<?=$btnId?>" cx="0" cy="0" r="1" gradientUnits="userSpaceOnUse" gradientTransform="matrix(31.4988,0,0,23.9236,32,36.2908)">
            <stop offset="0" style="stop-color:#000;stop-opacity:1" />
            <stop offset="0.51" style="stop-color:#000;stop-opacity:1" />
            <stop offset="0.67" style="stop-color:#000;stop-opacity:1" />
            <stop offset="0.8" style="stop-color:#000;stop-opacity:1" />
            <stop offset="1" style="stop-color:#000;stop-opacity:0" />
        </radialGradient>
        <linearGradient id="_Linear2<?=$btnId?>" x1="0" y1="0" x2="1" y2="0" gradientUnits="userSpaceOnUse" gradientTransform="matrix(62,0,0,62,0.730706,33)">
            <stop offset="0" style="stop-color:#000;stop-opacity:0.341176" />
            <stop offset="0.12" style="stop-color:#000;stop-opacity:0.0764706" />
            <stop offset="0.26" style="stop-color:#000;stop-opacity:0" />
            <stop offset="0.67" style="stop-color:#000;stop-opacity:0.421569" />
            <stop offset="0.83" style="stop-color:#000;stop-opacity:0.392157" />
            <stop offset="1" style="stop-color:#000;stop-opacity:0.311765" />
        </linearGradient>
        <linearGradient id="_Linear3<?=$btnId?>" x1="0" y1="0" x2="1" y2="0" gradientUnits="userSpaceOnUse" gradientTransform="matrix(62,0,0,57.2954,0.730706,31)">
            <stop offset="0" style="stop-color:#fff;stop-opacity:0.5" />
            <stop offset="0.16" style="stop-color:#fff;stop-opacity:0.5" />
            <stop offset="0.43" style="stop-color:#fff;stop-opacity:0.421569" />
            <stop offset="0.64" style="stop-color:#fff;stop-opacity:0.121569" />
            <stop offset="0.84" style="stop-color:#fff;stop-opacity:0.164706" />
            <stop offset="1" style="stop-color:#fff;stop-opacity:0.327451" />
        </linearGradient>
        <radialGradient id="_Radial4<?=$btnId?>" cx="0" cy="0" r="1" gradientUnits="userSpaceOnUse" gradientTransform="matrix(29,0,0,22.7538,31.7307,30.0065)">
            <stop offset="0" style="stop-color:#000;stop-opacity:0.5" />
            <stop offset="0.94" style="stop-color:#000;stop-opacity:0.25098" />
            <stop offset="1" style="stop-color:#000;stop-opacity:0" />
        </radialGradient>
        <radialGradient id="_Radial6<?=$btnId?>" cx="0" cy="0" r="1" gradientUnits="userSpaceOnUse" gradientTransform="matrix(32,0,0,29.8584,31.7307,30.1416)">
            <stop offset="0" style="stop-color:#000;stop-opacity:0" />
            <stop offset="0.48" style="stop-color:#000;stop-opacity:0" />
            <stop offset="0.63" style="stop-color:#000;stop-opacity:0" />
            <stop offset="0.76" style="stop-color:#000;stop-opacity:0" />
            <stop offset="1" style="stop-color:#000;stop-opacity:0.278431" />
        </radialGradient>
        <linearGradient id="_Linear7<?=$btnId?>" x1="0" y1="0" x2="1" y2="0" gradientUnits="userSpaceOnUse" gradientTransform="matrix(56,0,0,56,3.73071,31)">
            <stop offset="0" style="stop-color:#000;stop-opacity:0" />
            <stop offset="0.37" style="stop-color:#000;stop-opacity:0.156863" />
            <stop offset="0.8" style="stop-color:#000;stop-opacity:0.552941" />
            <stop offset="0.91" style="stop-color:#000;stop-opacity:0.462745" />
            <stop offset="1" style="stop-color:#000;stop-opacity:0.133333" />
        </linearGradient>
        <linearGradient id="_Linear8<?=$btnId?>" x1="0" y1="0" x2="1" y2="0" gradientUnits="userSpaceOnUse" gradientTransform="matrix(56,0,0,56,3.73071,31)">
            <stop offset="0" style="stop-color:#fff;stop-opacity:0" />
            <stop offset="0.1" style="stop-color:#fff;stop-opacity:0.368627" />
            <stop offset="0.2" style="stop-color:#fff;stop-opacity:0.494118" />
            <stop offset="0.48" style="stop-color:#fff;stop-opacity:0.117647" />
            <stop offset="0.62" style="stop-color:#fff;stop-opacity:0.0235294" />
            <stop offset="0.8" style="stop-color:#fff;stop-opacity:0" />
            <stop offset="0.9" style="stop-color:#fff;stop-opacity:0.0509804" />
            <stop offset="1" style="stop-color:#fff;stop-opacity:0.211765" />
        </linearGradient>
        <radialGradient id="_Radial9<?=$btnId?>" cx="0" cy="0" r="1" gradientUnits="userSpaceOnUse" gradientTransform="matrix(32,1.42109e-14,-1.15463e-14,26,31.7307,22.2526)">
            <stop offset="0" style="stop-color:#fff;stop-opacity:1" />
            <stop offset="0.81" style="stop-color:#fff;stop-opacity:0.623529" />
            <stop offset="0.9" style="stop-color:#fff;stop-opacity:0.137255" />
            <stop offset="1" style="stop-color:#fff;stop-opacity:0" />
        </radialGradient>
        <radialGradient id="_Radial10<?=$btnId?>" cx="0" cy="0" r="1" gradientUnits="userSpaceOnUse" gradientTransform="matrix(18.9359,28.7303,-44,29,18.7307,5)">
            <stop offset="0" style="stop-color:#fff;stop-opacity:0.623529" />
            <stop offset="0.48" style="stop-color:#fff;stop-opacity:0.14902" />
            <stop offset="1" style="stop-color:#fff;stop-opacity:0" />
        </radialGradient>
        <radialGradient id="_Radial11<?=$btnId?>" cx="0" cy="0" r="1" gradientUnits="userSpaceOnUse" gradientTransform="matrix(28,-4.54747e-13,3.57301e-13,22,31.7307,22)">
            <stop offset="0" style="stop-color:#fff;stop-opacity:0" />
            <stop offset="0.63" style="stop-color:#fff;stop-opacity:0.0470588" />
            <stop offset="0.83" style="stop-color:#fff;stop-opacity:0.168627" />
            <stop offset="1" style="stop-color:#fff;stop-opacity:0.305882" />
        </radialGradient>
        <radialGradient id="_Radial12<?=$btnId?>" cx="0" cy="0" r="1" gradientUnits="userSpaceOnUse" gradientTransform="matrix(36,11,-11.6788,38.2217,18.7307,38)">
            <stop offset="0" style="stop-color:#fff;stop-opacity:0.588235" />
            <stop offset="0.45" style="stop-color:#fff;stop-opacity:0.12549" />
            <stop offset="1" style="stop-color:#fff;stop-opacity:0" />
        </radialGradient>
    </defs>
</svg>
