<?php if (!isset($this->useSvgPathOnly)) : ?>
<svg width="100%" height="100%" viewBox="0 0 56 44" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xml:space="preserve" xmlns:serif="http://www.serif.com/" style="fill-rule:evenodd;clip-rule:evenodd;stroke-linejoin:round;stroke-miterlimit:1.41421;">
<?php endif; ?>

    <g id="label-hearts-superbutton">
        <ellipse cx="28" cy="22" rx="28" ry="22" style="fill:none;" />
        <g>
            <path d="M38.853,20.809c0,1.438 -0.789,2.732 -2.045,3.628l0.01,0l-6.783,5.33c-0.678,0.533 -1.357,1.066 -2.035,1.066c-0.678,0 -1.357,-0.533 -2.035,-1.066l-6.783,-5.33l0.01,0c-1.256,-0.896 -2.045,-2.19 -2.045,-3.628c0,-2.706 2.792,-4.899 6.235,-4.899c1.831,0 3.477,0.982 4.618,1.968c1.141,-0.986 2.787,-1.968 4.618,-1.968c3.443,0 6.235,2.193 6.235,4.899" style="fill:#fff;fill-rule:nonzero;" />
            <ellipse cx="28" cy="21.996" rx="17.505" ry="13.754" style="fill:none;" />
        </g>
    </g>

<?php if (!isset($this->useSvgPathOnly)) : ?>
</svg>
<?php endif; ?>

