<section class="section-header">
    <div class="container">
        <h1><?=$this->translate('General Settings');?></h1>
    </div>
</section>
<section class="section-content">
    <div class="container">
        <div class="row">
            <div class="sidebar">

                <?=$this->settingsNavigation('keywords');?>

            </div>
            <div class="content">

                <h2><?=$this->translate('Add New Keyword');?></h2>
                <?=$this->createForm;?>
                <p>
                    <?=$this->translate('or');?>
                    <a href="<?=$this->url(array('controller' => 'tag', 'action' => 'index'));?>"><?=$this->translate('Cancel');?></a>
                </p>

            </div>
        </div>
    </div>
</section>
