<section class="section-header">
    <div class="container">
        <h1 class="section-header-title"><?=$this->translate('General Settings');?></h1>
    </div>
</section>
<section class="section-content">
    <div class="container">
        <div class="row">
            <div class="sidebar">

                <?=$this->settingsNavigation('keywords');?>

            </div>
            <div class="content">

                <a href="<?=$this->url(array('action' => 'create'));?>" class="btn btn-default pull-right">
                    <span class="glyphicon glyphicon-plus-sign"></span>
                    <?=$this->translate('New Keyword');?>
                </a>
                <h2>Keywords</h2>

                <?php if (!count($this->tags)): ?>
                    <p class="alert alert-info">
                        <span class="glyphicon glyphicon-info-sign"></span>
                        <?=$this->translate('There are no keywords yet.');?>
                    </p>
                <?php else: ?>

                    <div class="row">
                        <div class="col-sm-1 col-sm-push-11">

                            <ul id="letterNavigation" class="nav nav-letters">
                                <?php foreach ($this->letters as $letter): ?>
                                    <li><a href="#letter-<?=$letter;?>"><?=$letter;?></a></li>
                                <?php endforeach; ?>
                            </ul>

                        </div>
                        <div class="col-sm-11 col-sm-pull-1">

                            <form action="<?=$this->url(['action' => 'edit']);?>" method="<?=$this->form->getMethod();?>">
                                <?=$this->form->getElement($this->form->getCsrfTokenName());?>
                                <div class="form-group">
                                    <input type="submit" name="editsubmit" class="btn btn-primary pull-right" value="<?=$this->translate('Save Changes');?>" />
                                    <span class="help-block">
                                        <span class="glyphicon glyphicon-info-sign"></span>
                                        <?=$this->translate('Please note only unused keywords can be deleted.');?>
                                    </span>
                                </div>
                                <hr />

                                <?php foreach ($this->tags as $letter => $tags): ?>
                                    <div class="form-group">
                                        <h3 id="letter-<?=$letter;?>" class="offset-bottom"><?=$letter;?></h3>
                                        <div class="row">
                                            <div class="col-sm-6">

                                                <?php $i = 1; ?>
                                                <?php $breakAfter = ceil(count($tags) / 2); ?>
                                                <?php foreach ($tags as $tag): ?>
                                                    <div class="form-group">
                                                        <div class="input-group">
                                                            <input name="tg_de[<?=$tag['tg_nr'];?>]" class="form-control input-sm" value="<?=$tag['tg_de'];?>" />
                                                            <span class="input-group-btn">
                                                                <button
                                                                    value="<?=$tag['tg_nr'];?>"
                                                                    name="delete"
                                                                    type="submit"
                                                                    class="item-action item-action-danger"
                                                                    data-toggle="confirm"
                                                                    data-confirm-message="<?=$this->translate('Delete keyword?');?>"
                                                                >
                                                                    <span class="glyphicon glyphicon-remove-sign"></span>
                                                                </button>
                                                            </span>
                                                        </div>
                                                        <input name="tag_old[<?=$tag['tg_nr'];?>]" value="<?=$tag['tg_de'];?>" type="hidden" />
                                                    </div>
                                                    <?php if ($i == $breakAfter): ?>
                                                        </div>
                                                        <div class="col-sm-6">
                                                    <?php endif; ?>
                                                    <?php $i++; ?>
                                                <?php endforeach;?>

                                            </div>
                                        </div>
                                    </div>
                                <?php endforeach; ?>
                                <hr />

                                <div class="form-group">
                                    <input type="submit" name="editsubmit" class="btn btn-primary pull-right" value="<?=$this->translate('Save Changes');?>" />
                                    <span class="help-block">
                                        <span class="glyphicon glyphicon-info-sign"></span>
                                        <?=$this->translate('Please note only unused keywords can be deleted.');?>
                                    </span>
                                </div>
                            </form>

                        </div>
                    </div>

                <?php endif; ?>

            </div>
        </div>
    </div>
</section>
