<li id="li-<? echo $this-> tid; ?>" style="display: none;" class="inputs <? if ($this->vot =="u") echo 'unfinished'; ?> <? if ($this->vot !="u") echo 'finished'; ?> <? if ($this->vot !="n" && $this->uid =='1') echo 'org-hidden'; ?>  <? if ($this->uid !='1') echo 'org-o'; ?> <? if ($this->uid =='1') echo 'org-r'; ?> vot-<? echo $this->vot ?> <? if ($this->vot =='y' && $this->uid !='1') echo 'vot-orb'; ?> block-<? echo $this->block; ?> ">
  <label for="<? echo $this-> tid; ?>" class="thesis clearfix">
  		<? echo $this-> thes; ?>
  	</label>
  	<input type ="checkbox" class="cbx-th" id="<? echo $this-> tid; ?>" name="thesis[]" value="<? echo $this-> tid; ?>">
  	<div class="clearfix" style="clear: both;">&nbsp;</div>
  	<? if (!empty($this-> expl)): ?>
  	<div class="expl-header">
  			<a class="expl-<? echo $this-> tid; ?>" title="Klicken um Ergänzung anzuzeigen">Ergänzung  &#9660;</a>
  	</div>
  <div class="expl-content expl-<? echo $this-> tid; ?>" rel="<? echo $this-> tid; ?>" >
  		<? echo $this-> expl; ?>
  </div>
	<? endif; ?>
	
	<? if (!empty($this->notiz)): ?>
	<div class="notice-header">
  			<a class="notice-<? echo $this-> tid; ?>"  title="Klicken um Notizen anzuzeigen"> Interne Notiz &#9660;</a>
  	</div>
  <div class="notice-content notice-<? echo $this-> tid; ?>">
  		Notiz:<? echo $this->notiz; ?>
  </div>
  <? endif; ?>
  
  <div class="tagrow">
  	<?php if (!empty($this->tags)) echo $this -> partialLoop('_partials/dashboard/tags-by-input.phtml', $this->tags); ?>
  	<div class="clear">&nbsp;</div>
</div>
	<div class="info-box">
  		
  		<span class="input-box" title="<? echo ($this->uid==1)?  "Redaktionsbeitrag" : "Originalbeitrag"; ?>"><? echo ($this->uid==1)?  "&#9415;" : "&#9412;"; ?></span>
  		
  		<span class="block-box" rel="<? echo $this-> tid; ?>" id="block-box-<? echo $this-> tid; ?>" title="Freigabe zur Anzeige: | &#9407; y = ja |  &#9399; n = blockiert | &#9418; u = unchecked">
  				<? 
  				if ($this->block=="y") echo '&#9407;'; 
				if ($this->block=="u") echo '&#9418;'; 
				if ($this->block=="n") echo '&#9399;'; 
  				?>
  		</span>
  		<span class="vot-box" rel="<? echo $this-> tid; ?>" id="vot-box-<? echo $this-> tid; ?>" title="Votingfreigabe: &#9411; u = unbearbeitet  | &#9419; v  = zur Abstimmuung freigegeben |  &#9399; n = nicht zur Abstimmung freigegeben">
  				<? 
  				if ($this->vot=="y") echo '&#9419;'; 
				if ($this->vot=="u") echo '&#9411;'; 
				if ($this->vot=="n") echo '&#9399;'; 
  				?>
  		</span>
   </div>
  
  <? if (!empty($this->related)): ?>
  	<div class="related-header">
  			<a class="related-<? echo $this-> tid; ?>" title="Klicken um Beiträge anzuzeigen">Zusammenfassung aus:  &#9660;</a>
  	</div>
  	<div class="related-content related-<? echo $this-> tid; ?>"> 
  		<ul>
  		<?  echo $this -> partialLoop('_partials/dashboard/related.phtml', $this->related); ?>
  		</ul>
  	<div class="append-inputs" rel="<? echo $this-> tid; ?>" id="append-inputs-<? echo $this-> tid; ?>">+ markierte hinzufügen +</div>
  	</div>
  	<? else: ?>
  	<div class="append-inputs" rel="<? echo $this-> tid; ?>" id="append-inputs-<? echo $this-> tid; ?>">+ markierte hinzufügen +</div>
  <? endif; ?>
  	<div class="clearfix" style="clear: both;">&nbsp;</div>
</li>