<li
    id="li-<? echo $this-> tid; ?>"
    style="display: none;"
    class="
        inputs
        <?php echo ($this->vot == "u" ? 'unfinished' : ''); ?>
        <?php echo ($this->vot != "u" ? 'finished' : ''); ?>
        <?php echo ($this->vot != "n" && $this->uid == '1' ? 'org-hidden' : ''); ?>
        <?php echo ($this->uid != '1' ? 'org-o' : ''); ?>
        <?php echo ($this->uid == '1' ? 'org-r' : ''); ?>
        vot-<?php echo $this->vot ?>
        <?php echo ($this->vot == 'y' && $this->uid != '1' ? 'vot-orb' : ''); ?>
        block-<?php echo $this->block; ?>
    "
>
    <label for="<? echo $this->tid; ?>" class="thesis clearfix">
        <? echo $this->thes; ?>
    </label>
    <input
        type ="checkbox"
        class="cbx-th"
        id="<?php echo $this->tid;?>" name="thesis[]" value="<?php echo $this->tid;?>"
    />

    <div class="clearfix" style="clear: both;">&nbsp;</div>

    <?php if (!empty($this->expl)): ?>
        <div class="expl-header">
            <a class="expl-<?php echo $this->tid; ?>" title="Klicken um Ergänzung anzuzeigen">Ergänzung  &#9660;</a>
        </div>
        <div class="expl-content expl-<?php echo $this->tid; ?>" rel="<?php echo $this->tid; ?>" >
            <?php echo $this->expl; ?>
        </div>
    <?php endif; ?>

    <?php if (!empty($this->notiz)): ?>
        <div class="notice-header">
            <a class="notice-<? echo $this->tid; ?>"  title="Klicken um Notizen anzuzeigen"> Interne Notiz &#9660;</a>
        </div>
        <div class="notice-content notice-<? echo $this->tid; ?>">
            Notiz:<? echo $this->notiz; ?>
        </div>
    <?php endif; ?>

    <div class="tagrow">
        <?php if (!empty($this->tags)): ?>
            <?php echo $this->partialLoop('_partials/dashboard/tags-by-input.phtml', $this->tags); ?>
        <?php endif; ?>
        <div class="clear">&nbsp;</div>
    </div>

    <div class="info-box">
        <span class="input-box" title="<?php echo ($this->uid==1)?  "Redaktionsbeitrag" : "Originalbeitrag"; ?>">
            <?php echo ($this->uid==1)?  "&#9415;" : "&#9412;"; ?>
        </span>

  		<span
            class="block-box"
            rel="<?php echo $this->tid; ?>"
            id="block-box-<?php echo $this->tid; ?>"
            title="Freigabe zur Anzeige: | &#9407; y = ja |  &#9399; n = blockiert | &#9418; u = unchecked"
        >
            <?php if ($this->block=="y") echo '&#9407;'; ?>
            <?php if ($this->block=="u") echo '&#9418;'; ?>
            <?php if ($this->block=="n") echo '&#9399;'; ?>
        </span>
        <span
            class="vot-box"
            rel="<?php echo $this->tid; ?>"
            id="vot-box-<?php echo $this->tid; ?>"
            title="Votingfreigabe: &#9411; u = unbearbeitet | &#9419; v  = zur Abstimmuung freigegeben | &#9399; n = nicht zur Abstimmung freigegeben"
        >
            <?php if ($this->vot=="y") echo '&#9419;'; ?>
            <?php if ($this->vot=="u") echo '&#9411;'; ?>
            <?php if ($this->vot=="n") echo '&#9399;'; ?>
        </span>
   </div>

    <?php if (!empty($this->related)): ?>
        <div class="related-header">
            <a class="related-<?php echo $this->tid; ?>" title="Klicken um Beiträge anzuzeigen">
                Zusammenfassung aus:  &#9660;
            </a>
        </div>
        <div class="related-content related-<?php echo $this->tid; ?>">
            <ul>
                <?php echo $this->partialLoop('_partials/dashboard/related.phtml', $this->related); ?>
            </ul>
          	<div class="append-inputs" rel="<?php echo $this->tid; ?>" id="append-inputs-<?php echo $this->tid; ?>">
                + markierte hinzufügen +
            </div>
        </div>
  	<?php else: ?>
      	<div class="append-inputs" rel="<?php echo $this->tid; ?>" id="append-inputs-<?php echo $this->tid; ?>">
            + markierte hinzufügen +
        </div>
    <?php endif; ?>
  	<div class="clearfix" style="clear: both;">&nbsp;</div>
</li>
