<section class="section-header">
    <div class="container">
        <h1 class="section-header-title"><?=$this->translate('Contribution Submission Form');?></h1>
    </div>
</section>
<section class="section-content">
    <div class="container">
        <div class="row">
            <div class="sidebar">

                <?=$this->settingsNavigation('contributionSubmissionForm');?>

            </div>
            <div class="content">

                <?=$this->form;?>

            </div>
        </div>
    </div>
</section>
