<section class="section-header">
    <div class="container">
        <h1 class="section-header-title"><?=$this->translate('General Settings');?></h1>
    </div>
</section>
<section class="section-content">
    <div class="container">
        <div class="row">
            <div class="sidebar">

                <?=$this->settingsNavigation('contribution');?>

            </div>
            <div class="content">

                <h2><?=$this->translate('Contribution');?></h2>

                <div id="form">
                    <?=$this->form;?>
                </div>

                <div id="anonymous-form">
                    <?=$this->anonymousForm;?>
                </div>

            </div>
        </div>
    </div>
</section>
