<form
    enctype="<?=$this->element->getEnctype();?>"
    method="<?=$this->element->getMethod();?>"
    class="offset-bottom"
    enctype="<?=$this->element->getEnctype();?>"
>
    <?=$this->element->csrf_token_settingscontributionsubmissionformadmin;?>

    <?=$this->element->state_field_label;?>
    <?=$this->element->contribution_confirmation_info;?>
    <?=$this->element->license;?>

    <?=$this->element->submit;?>

</form>
