<form
    enctype="<?=$this->element->getEnctype();?>"
    method="<?=$this->element->getMethod();?>"
    class="offset-bottom"
    enctype="<?=$this->element->getEnctype();?>"
>
    <?=$this->element->csrf_token_contributionsubmissionformadmin;?>

    <h2><?=$this->translate('Fields settings');?></h2>
    <?=$this->element->state_label;?>

    <?=$this->element->license;?>

    <?=$this->element->submit;?>

</form>
