<form
    enctype="<?=$this->element->getEnctype();?>"
    method="<?=$this->element->getMethod();?>"
    class="offset-bottom"
    enctype="<?=$this->element->getEnctype();?>"
>
    <?=$this->element->csrf_token_contributionsubmissionformadmin;?>

    <?=$this->element->state_field_label;?>

    <?=$this->element->field_switch_name;?>
    <?=$this->element->field_switch_age;?>
    <?=$this->element->field_switch_state;?>
    <?=$this->element->field_switch_comments;?>

    <?=$this->element->allow_groups;?>

    <?=$this->element->field_switch_contribution_origin;?>
    <?=$this->element->field_switch_individuals_num;?>
    <?=$this->element->field_switch_group_name;?>
    <?=$this->element->field_switch_contact_person;?>

    <?=$this->element->field_switch_notification;?>
    <?=$this->element->field_switch_newsletter;?>

    <?=$this->element->license;?>

    <?=$this->element->submit;?>

</form>
