<section class="section-header">
    <div class="container">
        <h1 class="section-header-title"><?=$this->translate('Finish contribution');?></h1>
    </div>
</section>
<section class="section-content">
    <div class="container">
        <div class="row">
            <div class="sidebar">

                <?=$this->settingsNavigation('finishContribution');?>

            </div>
            <div class="content">

                <h2><?=$this->translate('Finish contribution');?></h2>

                <?=$this->form;?>

            </div>
        </div>
    </div>
</section>
