<section class="section-header">
    <div class="container">
        <h1 class="section-header-title"><?=$this->translate('General Settings');?></h1>
    </div>
</section>
<section class="section-content">
    <div class="container">
        <div class="row">
            <div class="sidebar">

                <?=$this->settingsNavigation('helpTexts');?>

            </div>
            <div class="content">

                <h2><?=$this->translate('Help Texts');?></h2>

                <table class="table">
                    <thead>
                        <tr>
                            <th class="table-cell-id">#</th>
                            <th><?=$this->translate('Title');?></th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->helpTexts as $helpText): ?>
                            <tr>
                                <td class="table-cell-id"><?=$this->escape($helpText->id);?></td>
                                <td>
                                    <a
                                        href="<?=$this->url(['action' => 'help-text-edit', 'id' => $helpText->id]);?>"
                                        title="<?=$this->translate('Edit help text');?>"
                                    >
                                        <?=Model_HelpText::getTranslatedName($helpText->name);?>
                                    </a>
                                </td>
                                <td class="table-cell-actions">
                                    <a
                                        class="item-action"
                                        href="<?=$this->url(['action' => 'help-text-edit', 'id' => $helpText->id]);?>"
                                        title="<?=$this->translate('Edit help text');?>"
                                    >
                                        <span class="glyphicon glyphicon-pencil"></span>
                                    </a>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>
