<section class="section-header">
    <div class="container">
        <h1>General Settings</h1>
    </div>
</section>
<section class="section-content">
    <div class="container">
        <div class="row">
            <div class="col-md-3">

                <?=$this->settingsNavigation('site');?>

            </div>
            <div class="col-md-9">

                <h2>Site</h2>
                <!-- TODO -->

            </div>
        </div>
    </div>
</section>
