<section class="section-header">
    <div class="container">
        <h1><?=$this->translate('Help Texts');?></h1>
    </div>
</section>
<section class="section-content">
    <div class="container">
        <div class="row">
            <div class="sidebar">

                <?=$this->settingsNavigation('site');?>

            </div>
            <div class="content">
                <?=$this->form;?>
            </div>
        </div>
    </div>
</section>
