<form
    enctype="<?=$this->element->getEnctype();?>"
    method="<?=$this->element->getMethod();?>"
    class="offset-bottom"
    enctype="<?=$this->element->getEnctype();?>"
>
    <?=$this->element->csrf_token_lookandfeeladmin;?>

    <h2><?=$this->translate('Logo');?></h2>
    <?=$this->element->logo;?>

    <h2><?=$this->translate('Icon');?></h2>
    <?=$this->element->favicon;?>

    <h2><?=$this->translate('Header');?></h2>
    <?=$this->element->mitmachen_bubble;?>

    <h2><?=$this->translate('Predefined themens');?></h2>
    <div id="themes">
    <?php foreach ($this->element->theme_id->options as $themeId => $themeName) : ?>
        <label>
            <img src="<?=$this->baseUrl('images/themes/theme_' . $themeId . '.jpg');?>" /><br />
            <input
                id="theme-<?=$themeId;?>"
                class="js-theme-preset"
                type="radio" name="theme_id"
                value="<?=$themeId;?>"
                data-colors="<?=$this->escape($this->element->theme_id->color_config[$themeId]);?>"
                <?php if ($this->element->theme_id->getValue() === (string) $themeId) : ?>
                    checked="checked"
                <?php endif; ?>
                />
            <?=$themeName;?>
        </label>
    <?php endforeach; ?>
    </div>

    <h2><?=$this->translate('Custom Colours');?></h2>
    <div class="row offset-bottom">
        <label
            <?php if ($this->element->color_headings->isRequired()) : ?>
                class="required"
            <?php endif;?>
            for="<?=$this->element->color_headings->getName();?>"
        >
            <?=$this->element->color_headings->getLabel()?>
        </label>

        <div class="input-group colorpicker-component">
            <input
                id="<?=$this->element->color_headings->getName();?>"
                type="text"
                name="color_headings"
                value="#<?=$this->element->color_headings->getValue();?>"
                class="form-control"
            />
            <span class="input-group-addon"><i></i></span>
            <?php if (count($this->element->color_headings->getErrors()) > 0) : ?>
                <ul class="text-danger-block">
                    <?php foreach ($this->element->color_headings->getErrors() as $error) : ?>
                        <li><?=$error?></li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?>
        </div>
    </div>

    <div class="row offset-bottom">
        <label
            <?php if ($this->element->color_frame_background->isRequired()) : ?>
                class="required"
            <?php endif;?>
            for="<?=$this->element->color_frame_background->getName();?>"
        >
            <?=$this->element->color_frame_background->getLabel()?>
        </label>

        <div class="input-group colorpicker-component">
            <input
                id="<?=$this->element->color_frame_background->getName();?>"
                type="text"
                name="color_frame_background"
                value="#<?=$this->element->color_frame_background->getValue();?>"
                class="form-control"
            />
            <span class="input-group-addon"><i></i></span>
            <?php if (count($this->element->color_frame_background->getErrors()) > 0) : ?>
                <ul class="text-danger-block">
                    <?php foreach ($this->element->color_frame_background->getErrors() as $error) : ?>
                        <li><?=$error?></li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?>
        </div>
    </div>

    <div class="row offset-bottom">
        <label
            <?php if ($this->element->color_active_link->isRequired()) : ?>
                class="required"
            <?php endif;?>
            for="<?=$this->element->color_active_link->getName();?>"
        >
            <?=$this->element->color_active_link->getLabel()?>
        </label>

        <div class="input-group colorpicker-component">
            <input
                id="<?=$this->element->color_active_link->getName();?>"
                type="text"
                name="color_active_link"
                value="#<?=$this->element->color_active_link->getValue();?>"
                class="form-control"
            />
            <span class="input-group-addon"><i></i></span>
            <?php if (count($this->element->color_active_link->getErrors()) > 0) : ?>
                <ul class="text-danger-block">
                    <?php foreach ($this->element->color_active_link->getErrors() as $error) : ?>
                        <li><?=$error?></li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?>
        </div>
    </div>


    <?=$this->element->submit;?>
    
</form>
