<section class="section-header">
    <div class="container">
        <h1 class="section-header-title"><?=$this->translate('General Settings');?></h1>
    </div>
</section>
<section class="section-content">
    <div class="container">
        <div class="row">
            <div class="sidebar">

                <?=$this->settingsNavigation('lookAndFeel');?>

            </div>
            <div class="content">

                <h2><?=$this->translate('Look and Feel');?></h2>
                
                <?=$this->form;?>

            </div>
        </div>
    </div>
</section>
