<section class="section-header">
    <div class="container">
        <h1><?=$this->translate('Partners');?></h1>
    </div>
</section>
<section class="section-content">
    <div class="container">
        <div class="row">
            <div class="sidebar">
                <?=$this->settingsNavigation('partners');?>
            </div>

            <div class="content">
                <?=$this->form;?>
            </div>

        </div>
    </div>
</section>
