<section class="section-header">
    <div class="container">
        <h1 class="section-header-title"><?=$this->translate('Help Texts');?></h1>
    </div>
</section>
<section class="section-content">
    <div class="container">
        <div class="row">
            <div class="sidebar">

                <?=$this->settingsNavigation('partners');?>

            </div>
            <div class="content">

                <form method="<?=$this->form->getMethod();?>">
                    <?=$this->form->getElement($this->form->getCsrfTokenName());?>

                    <div class="form-group text-right">
                        <button type="submit" name="saveOrder" value="1" class="btn btn-primary" disabled>
                            <?=$this->translate('Save changes');?>
                        </button>
                    </div>

                    <div>
                        <table class="table">
                            <thead>
                                <tr>
                                    <th></th>
                                    <th><?=$this->translate('Name');?></th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody class="sortable js-sortable-partners">
                                <?php foreach ($this->partners as $partner): ?>
                                    <tr>
                                        <td>
                                            <span class="glyphicon glyphicon-move"></span>
                                            <input
                                                type="hidden"
                                                name="order[<?=$this->escape($partner->id);?>]"
                                                value="<?=$this->escape($partner->order);?>"
                                            />
                                        </td>
                                        <td>
                                            <a
                                                href="<?=$this->url(['action' => 'partner-edit', 'id' => $partner->id]);?>"
                                                title="<?=$this->translate('Edit partner data');?>"
                                            >
                                                <?=$this->escape($partner->name);?>
                                            </a>
                                        </td>
                                        <td class="table-cell-actions">
                                            <a
                                                class="item-action"
                                                href="<?=$this->url(['action' => 'partner-edit', 'id' => $partner->id]);?>"
                                                title="<?=$this->translate('Edit help text');?>"
                                            >
                                                <span class="glyphicon glyphicon-pencil"></span>
                                            </a>
                                            <button
                                                type="submit"
                                                class="item-action item-action-danger"
                                                name="delete"
                                                value="<?=$this->escape($partner->id);?>"
                                                data-toggle="confirm"
                                                data-confirm-message="<?=$this->translate('Delete partner?');?>"
                                            >
                                                <span class="glyphicon glyphicon-trash"></span>
                                            </button>
                                        </td>
                                    </tr>
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                    <div>
                </form>
            </div>
        </div>
    </div>
</section>
