<section class="section-header">
    <div class="container">
        <h1 class="section-header-title"><?=$this->translate('Services Settings');?></h1>
    </div>
</section>
<section class="section-content">
    <div class="container">
        <div class="row">
            <div class="sidebar">

                <?=$this->settingsNavigation('services');?>

            </div>
            <div class="content">

                <h2><?=$this->translate('Services');?></h2>
                <?=$this->form;?>
                <?php if (!$this->form->getVideosServiceAccess()) : ?>
                <p>In case one or more of the services is greyed-out and cannot be activated, please contact you
                    administrator or support. It is probably due to misconfiguration of service access applications in
                    ePartool configuration files.</p>
                <?php endif; ?>

            </div>
        </div>
    </div>
</section>
