<section class="section-header">
    <div class="container">
        <h1 class="section-header-title"><?=$this->translate('General Settings');?></h1>
    </div>
</section>
<section class="section-content">
    <div class="container">
        <div class="row">
            <div class="sidebar offset-bottom-large-sm-max">

                <?=$this->settingsNavigation('services');?>

            </div>
            <div class="content">

                <h2><?=$this->translate('Services');?></h2>
                <?php if (!$this->form->getVideosServiceAccess()) : ?>
                    <p class="alert alert-info">
                        <span class="glyphicon glyphicon-info-sign offset-right" aria-hidden="true"></span>
                        <?=$this->translate('In case one or more services are greyed out and cannot be activated, it is probably due to misconfiguration of service access applications in ePartool configuration files.');?>
                    </p>
                <?php endif; ?>
                <p class="alert alert-info">
                    <span class="glyphicon glyphicon-info-sign offset-right" aria-hidden="true"></span>
                    <?=$this->translate('Here you can specify available video services used for attaching of a video to contributions.');?>
                </p>
                <?=$this->form;?>
            </div>
        </div>
    </div>
</section>
