<section class="section-header">
    <div class="container">
        <h1 class="section-header-title"><?=$this->translate('Services Settings');?></h1>
    </div>
</section>
<section class="section-content">
    <div class="container">
        <div class="row">
            <div class="sidebar">

                <?=$this->settingsNavigation('services');?>

            </div>
            <div class="content">

                <h2><?=$this->translate('Services');?></h2>
                <?php if (!$this->form->getVideosServiceAccess()) : ?>
                    <p class="alert alert-info">
                        <span class="glyphicon glyphicon-info-sign icon-offset" aria-hidden="true"></span>
                        In case one or more of the services is greyed-out and cannot be activated, please contact you
                        administrator or support. It is probably due to misconfiguration of service access applications in
                        ePartool configuration files.
                    </p>
                <?php endif; ?>
                <?=$this->form;?>

            </div>
        </div>
    </div>
</section>
