<section class="section-header">
    <div class="container">
        <h1 class="section-header-title"><?=$this->translate('General Settings');?></h1>
    </div>
</section>
<section class="section-content">
    <div class="container">
        <div class="row">
            <div class="sidebar offset-bottom-large-sm-max">

                <?=$this->settingsNavigation('voting');?>

            </div>
            <div class="content">

                <h2><?=$this->translate('Voting');?></h2>
                <?=$this->form;?>

            </div>
        </div>
    </div>
</section>
