<h3 class="offset-bottom">
    <?=$this->translate('Please make sure all of the folders below exist and are writable by the php process.');?>
</h3>

<ul class="list-unstyled offset-bottom-large">
    <?php foreach ($this->allFolders as $folder) :?>
        <li>
            <span
                class="
                    glyphicon
                    glyphicon-<?=in_array($folder, $this->nonWritableFolders) ? 'remove text-danger' : 'ok text-success';?>
                    icon-offset
                    icon-vertically-aligned
                "
            ></span>
            <code><?=$folder;?></code>
        </li>
    <?php endforeach;?>

</ul>

<form method="get">
    <input type="hidden" value="<?=$this->locale;?>" name="locale" />
    <button type="submit" class="btn btn-primary">
        <?=$this->translate('Continue');?>
        <span class="glyphicon glyphicon-menu-right icon-vertically-aligned"></span>
    </button>
</form>
