<h2 class="h3 offset-bottom">Please choose installation wizzard language</h2>

<a href="?locale=cs_CZ" class="btn btn-default">Česky</a>
<a href="?locale=de_DE" class="btn btn-default">Deutsch</a>
<a href="?locale=en_US" class="btn btn-default">English</a>
<a href="?locale=es_ES" class="btn btn-default">Español</a>
<a href="?locale=fr_FR" class="btn btn-default">Français</a>
<a href="?locale=pl_PL" class="btn btn-default">Polski</a>
<a href="?locale=ru_RU" class="btn btn-default">русский</a>
<a href="?locale=ar_AR" class="btn btn-default">العربية</a>
