<p class="offset-bottom">
    <span class="glyphicon glyphicon-ok-sign icon-vertically-aligned offset-right text-success"></span>
    <?=$this->translate(
        'The installation is finished. Please make sure to delete the install folder from your website root folder.'
    );?>
</p>
<p>
    <a href="<?=$this->baseUrl('/');?>" class="btn btn-primary"><?=$this->translate('Go to my site');?></a>
</p>
