<!DOCTYPE html>
<html lang="<?=Zend_Registry::get('Zend_Locale')->getLanguage();?>">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><?=$this->translate('DBJR TOOL Admin');?></title>
    <meta name="robots" content="noindex, nofollow" />

    <link href="//fonts.googleapis.com/css?family=Open+Sans:400,300,700&amp;subset=latin,cyrillic-ext,cyrillic,latin-ext" rel="stylesheet" />

    <?php if (APPLICATION_ENV === 'development'): ?>
        <link rel="stylesheet" href="<?=$this->baseUrl('css/admin.css');?>" />
    <?php else: ?>
        <link rel="stylesheet" href="<?=$this->baseUrl('css/admin.min.css');?>" />
    <?php endif;?>

    <link rel="shortcut icon" href="<?=$this->baseUrl('project/images/icon/favicon.ico');?>" />
    <link rel="shortcut icon" href="<?=$this->baseUrl('project/images/icon/favicon.png');?>" />
    <link rel="apple-touch-icon-precomposed" href="<?=$this->baseUrl('project/images/icon/touch-icon.png');?>" />
    <meta name="msapplication-TileImage" content="<?=$this->baseUrl('project/images/icon/touch-icon-w8.png');?>" />
    <meta name="msapplication-TileColor" content="#ffffff" />

    <?php if (APPLICATION_ENV === 'development'): ?>
        <script src="<?=$this->baseUrl('js/admin.js');?>"></script>
    <?php else: ?>
        <script src="<?=$this->baseUrl('js/admin.min.js');?>"></script>
    <?php endif;?>
    <script src="<?=$this->baseUrl('js/admin.i18n.' . Zend_Registry::get('Zend_Locale')->getLanguage() . '.js');?>"></script>
    <script>
        var baseUrl = '<?=$this->baseUrl()?>';
    </script>
    <script src="<?=$this->baseUrl('vendor/ckeditor/ckeditor.js');?>"></script>
    <script src="<?=$this->baseUrl('vendor/ckeditor/adapters/jquery.js');?>"></script>
</head>
<body class="has-footer-sticky">

    <header role="banner">

        <!-- Main navigation -->
        <nav class="navbar navbar-static-top navbar-default">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#menu">
                        <span class="sr-only"><?=$this->translate('Menu');?></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a
                        href="<?=$this->url(['module' => 'admin', 'controller' => 'index', 'action' => 'index'], null, true);?>"
                        class="navbar-brand"
                        title="<?=$this->translate('ePartool admin dashboard');?>"
                    >
                        <span class="hidden-sm">
                            <?php include(APPLICATION_PATH . '/../www/images/admin/logo.svg'); ?>
                        </span>
                        <span class="visible-sm">
                            <?php include(APPLICATION_PATH . '/../www/images/admin/icon.svg'); ?>
                        </span>
                    </a>
                </div>
                <div class="collapse navbar-collapse" id="menu">
                    <?=$this->navigation()->menu();?>
                    <ul class="nav navbar-nav navbar-right">
                        <li class="navbar-icon">
                            <a href="<?=$this->url([], null, true);?>" target="_blank" title="<?=$this->translate('Open site in a new tab');?>">
                                <span class="glyphicon glyphicon-home"></span>
                                <span class="visible-xs-inline"><?=$this->translate('Homepage');?></span>
                            </a>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <span class="glyphicon glyphicon-user visible-sm-inline-block"></span>
                                <span class="hidden-sm">
                                    <?=Zend_Auth::getInstance()->getIdentity()->name;?>
                                </span>
                                <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">
                                <li class="dropdown-header visible-sm"><?=Zend_Auth::getInstance()->getIdentity()->name;?></li>
                                <li class="divider visible-sm"></li>
                                <li>
                                    <a href="<?=$this->baseUrl();?>/user/logout">
                                        <span class="glyphicon glyphicon-off"></span>
                                        <?=$this->translate('Log off');?>
                                    </a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

    </header>
    <main role="main">

        <!-- Flash Messages -->
        <?=$this->partial('_partials/flashMessages.phtml', $this->layout()->getView());?>

        <!-- Content -->
        <?=$this->layout()->content;?>

    </main>
    <footer role="contentinfo" class="footer footer-sticky">
        <div class="container">
            © DBJR <?=date('Y');?>
            <a href="http://www.synergic.cz/en" target="_blank" class="footer-author" title="Created by Synergic">
                <?php include(APPLICATION_PATH . '/../www/images/admin/synergic.svg'); ?>
            </a>
        </div>
    </footer>

</body>
</html>
