<!DOCTYPE html>
<html lang="<?=Zend_Registry::get('Zend_Locale')->getLanguage();?>">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><?=$this->translate('DBJR TOOL Admin');?></title>
    <meta name="robots" content="noindex, nofollow" />

    <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Titillium+Web:400,300,700&amp;subset=latin,latin-ext,cyrillic,cyrillic-ext" />

    <?php if (APPLICATION_ENV === 'development'): ?>
        <link rel="stylesheet" href="<?=$this->baseUrl('css/admin.css');?>?v=<?=$this->toolVersion();?>" />
    <?php else: ?>
        <link rel="stylesheet" href="<?=$this->baseUrl('css/admin.min.css');?>?v=<?=$this->toolVersion();?>" />
    <?php endif;?>

    <link rel="shortcut icon" href="<?=$this->baseUrl('project/images/icon/favicon.ico');?>" />
    <link rel="shortcut icon" href="<?=$this->baseUrl('project/images/icon/favicon.png');?>" />
    <link rel="apple-touch-icon-precomposed" href="<?=$this->baseUrl('project/images/icon/touch-icon.png');?>" />
    <meta name="msapplication-TileImage" content="<?=$this->baseUrl('project/images/icon/touch-icon-w8.png');?>" />
    <meta name="msapplication-TileColor" content="#ffffff" />

    <?php if (APPLICATION_ENV === 'development'): ?>
        <script src="<?=$this->baseUrl('js/admin.js');?>?v=<?=$this->toolVersion();?>"></script>
    <?php else: ?>
        <script src="<?=$this->baseUrl('js/admin.min.js');?>?v=<?=$this->toolVersion();?>"></script>
    <?php endif;?>
    <script src="<?=$this->baseUrl('js/admin.i18n.' . Zend_Registry::get('Zend_Locale')->getLanguage() . '.js');?>?v=<?=$this->toolVersion();?>"></script>
    <script>
        var baseUrl = '<?=$this->baseUrl()?>';
    </script>
</head>
<body>

<!-- Flash Messages -->
<?=$this->partial('_partials/flashMessages.phtml', $this->layout()->getView());?>

<!-- Content -->
<?=$this->layout()->content;?>

</body>
</html>
