<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

<head>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
    <title>DBJR - Administration</title>
    <!-- add your meta tags here -->

    <link href="<?php echo $this->baseUrl(); ?>/css/backend/style.css" rel="stylesheet" type="text/css" />
    <!--[if lte IE 7]>
    <link href="<?php echo $this->baseUrl(); ?>/css/backend/patches/patch_layout.css" rel="stylesheet" type="text/css" />
    <![endif]-->
    <?php echo $this->headScript(); ?>

    <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/jquery-1.7.2.min.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/ajaxloader.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/components/ckeditor/ckeditor.js"></script>
</head>

<body>
    <div class="page_margins">
        <!-- start: skip link navigation -->
        <!-- end: skip link navigation -->
        <div class="page">
            <div id="header">
                <h1><a href="<?php echo $this->baseUrl(); ?>/admin">Administration</a></h1>
                <div id="topnav">
                    <a href="<?php echo $this->baseUrl(); ?>/">Startseite</a><br />
                    <a href="<?php echo $this->baseUrl(); ?>/admin">Startseite Administration</a><br />
                </div>
            </div>
            <div id="main">
                <div id="col1">
                    <div id="col1_content" class="clearfix">
                        <!-- Navigation -->
                        <?php echo $this->navigation()->menu(); ?>
                    </div>
                </div>
                <div id="col3">
                    <div id="col3_content" class="clearfix">
                        <!-- Flash Messages -->
                        <?php if(!empty($this->layout()->messages)): ?>
                            <?php foreach ($this->layout()->messages as $level => $messages): ?>
                                <?php if (!empty($messages)): ?>
                                    <?php foreach ($messages as $message): ?>
                                        <p class="<?php echo $level; ?>">
                                            <?php echo $message; ?>
                                        </p>
                                    <?php endforeach;?>
                                <?php endif;?>
                            <?php endforeach;?>
                        <?php endif;?>

                        <!-- Content -->
                        <?php echo $this->layout()->content; ?>
                    </div>
                    <!-- IE Column Clearing -->
                    <div id="ie_clearing"> &#160; </div>
                </div>
            </div>
            <!-- begin: #footer -->
            <div id="footer">
                <p>Layout based on <a href="http://www.yaml.de">YAML</a></p>
            </div>
        </div>
    </div>
</body>

</html>

