<?php $lang = Zend_Registry::get('Zend_Locale')->getLanguage(); ?>
<?php $controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName(); ?>
<!DOCTYPE html>
<html lang="<?=$lang;?>" itemscope itemtype="https://schema.org/Event">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="IE=Edge" />
    <!--[if lte IE 8]><meta http-equiv="cleartype" content="on" /><![endif]-->

    <title><?=$this->parameter('site.title');?></title>

    <meta name="description" content="<?=$this->parameter('site.description');?>" />
    <meta name="author" content="ePartool © DBJR" />
    <meta name="DC.title" content="<?=$this->parameter('site.title');?>" />
    <meta property="og:title" content="<?=$this->parameter('site.title');?>" />
    <meta property="og:description" content="<?=$this->parameter('site.description');?>" />

    <?php if (APPLICATION_ENV === 'development'): ?>
        <link rel="stylesheet" href="<?=$this->baseUrl('css/front.css');?>?v=<?=$this->toolVersion();?>" type="text/css" />
    <?php else: ?>
        <link rel="stylesheet" href="<?=$this->baseUrl('css/front.min.css');?>?v=<?=$this->toolVersion();?>" type="text/css" />
    <?php endif; ?>
    <link rel="stylesheet" href="<?=$this->url(['controller' => 'index', 'action' => 'custom-css'], 'default');?>?v=<?=$this->toolVersion();?>" type="text/css" />

    <?php if (!empty($this->themeAssets()['favicon'])) : ?>
        <link rel="icon" href="<?=$this->mediaPresenter('media' . $this->themeAssets()['favicon'], 'favicon');?>" sizes="32x32" type="image/png" />
        <link rel="apple-touch-icon-precomposed" href="<?=$this->mediaPresenter('media' . $this->themeAssets()['favicon'], 'apple_touch_icon');?>" />
        <meta name="msapplication-TileImage" content="<?=$this->mediaPresenter('media' . $this->themeAssets()['favicon'], 'ms_touch_icon');?>" />
        <meta name="msapplication-TileColor" content="#ffffff" />
    <?php else : ?>
        <link rel="icon" href="<?=$this->baseUrl('images/favicon.png');?>" sizes="32x32" type="image/png" />
        <link rel="apple-touch-icon-precomposed" href="<?=$this->baseUrl('images/touch-icon.png');?>" />
        <meta name="msapplication-TileImage" content="<?=$this->baseUrl('images/touch-icon-w8.png');?>" />
        <meta name="msapplication-TileColor" content="#ffffff" />
    <?php endif; ?>

    <!--[if lt IE 9]><script src="<?=$this->baseUrl('vendor/html5shiv.min.js');?>?v=<?=$this->toolVersion();?>"></script><![endif]-->

    <!-- JS must be loaded in page head as it might be used in user generated content. -->
    <!-- It is not best practice and product owner is aware of that. -->
    <?php if (APPLICATION_ENV === 'development'): ?>
        <script src="<?=$this->baseUrl('js/dbjr.js');?>?v=<?=$this->toolVersion();?>"></script>
    <?php else: ?>
        <script src="<?=$this->baseUrl('js/dbjr.min.js');?>?v=<?=$this->toolVersion();?>"></script>
    <?php endif;?>
</head>
<body>



<!-- Flash Messages -->
<?=$this->partial('_partials/flashMessages.phtml', $this->layout()->getView());?>



<!-- Frame -->
<div id="top" class="container">
    <div class="frame">



        <!-- Header -->
        <header role="banner" class="header">

            <!-- Logo -->
            <a
                href="<?=$this->url(['controller' => 'index'], 'default', true);?>"
                rel="home"
                class="header-brand link-print-nourl"
                title="<?=$this->translate('Home');?>"
            >
                <img
                    <?php if (!empty($this->themeAssets()['logo'])) : ?>
                        src="<?=$this->mediaPresenter('media' . $this->themeAssets()['logo'], 'front_logo');?>"
                        srcset="
                            <?=$this->mediaPresenter('media' . $this->themeAssets()['logo'], 'front_logo');?>,
                            <?=$this->mediaPresenter('media' . $this->themeAssets()['logo'], 'front_logo_retina');?> 2x
                        "
                    <?php else : ?>
                        src="<?=$this->baseUrl('images/logo.png');?>"
                        srcset="<?=$this->baseUrl('images/logo.png');?>, <?=$this->baseUrl('images/logo@2x.png');?> 2x"
                    <?php endif; ?>
                    class="img-responsive"
                    itemprop="image"
                    alt="<?=$this->parameter('site.title');?>"
                />
            </a>

            <!-- Main navigation -->
            <nav role="navigation" class="header-nav hidden-print" aria-label="<?=$this->translate('Menu');?>">
                <ul class="nav nav-pills nav-centered">
                    <li><a href="<?=$this->url([], 'about');?>#what"><?=$this->translate('What');?></a></li>
                    <li><a href="<?=$this->url([], 'about');?>#us"><?=$this->translate('We');?></a></li>
                    <?php if (Zend_Registry::get('Zend_Translate')->getAdapter()->getLocale() === 'de'): ?>
                        <li><a href="<?=$this->url([], 'about');?>#you"><?=$this->translate('With You');?></a></li>
                        <li><a href="<?=$this->url([], 'about');?>#vision"><?=$this->translate('Do');?></a></li>
                    <?php elseif (Zend_Registry::get('Zend_Translate')->getAdapter()->getLocale() === 'en'): ?>
                        <li><a href="<?=$this->url([], 'about');?>#vision"><?=$this->translate('Do');?></a></li>
                        <li><a href="<?=$this->url([], 'about');?>#you"><?=$this->translate('With You');?></a></li>
                    <?php endif; ?>
                </ul>
            </nav>

            <!-- Search and user -->
            <div class="header-widgets hidden-print">

                <!-- Search -->
                <form class="form-search" method="get" action="<?=$this->url(['controller' => 'index', 'action' => 'search'], 'default', true);?>">
                    <div class="input-group input-group-sm">
                        <input type="text" class="form-control" name="q" placeholder="<?=$this->translate('Search…');?>" value="" />
                        <span class="input-group-btn">
                            <button type="submit" class="btn btn-primary" title="<?=$this->translate('Search');?>">
                                <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                            </button>
                        </span>
                    </div>
                </form>

                <!-- Login -->
                <?=$this->login($this->layout()->disableLoginMsg);?>

                <!-- User box (user is logged in) -->
                <?=$this->userBox();?>

            </div>

            <?php if (isset($this->consultation)): ?>

                <!-- Main title -->
                <h1 class="header-title<?php if ($this->themeAssets()['mitmachen_bubble']) : ?> header-title-with-bubble<?php endif; ?>">
                    <a href="<?=$this->url(['controller' => 'index'], 'default', true);?>" class="link-print-nourl" rel="home" itemprop="name">
                        <?=$this->translate('Participation');?>
                    </a>
                </h1>

                <!-- Header box: Consultation -->
                <div class="header-box has-sticker">

                    <!-- Sticker -->
                    <div class="hidden-xs hidden-print">
                        <?=$this->ribbonImage($this->consultation);?>
                    </div>

                    <div class="row">
                        <div class="col-sm-10 col-sm-offset-1 col-md-6 col-md-push-3 col-md-offset-0">

                            <!-- Title -->
                            <h1 class="header-box-title header-box-title-small">
                                <a href="<?=$this->url(['controller' => 'article', 'action' => 'show', 'kid' => $this->consultation->kid]);?>" class="link-print-nourl">
                                    <?=$this->escape($this->consultation->titl);?>
                                </a>
                            </h1>
                            <h2 class="header-box-subtitle"><?=$this->escape($this->consultation->titl_sub);?></h2>

                            <!-- Sticker -->
                            <div class="visible-xs hidden-print">
                                <?=$this->ribbonImage($this->consultation);?>
                            </div>

                        </div>
                        <div class="col-sm-12 col-md-3 col-md-pull-6">

                            <!-- Image -->
                            <img
                                src="<?=$this->baseUrl('media/' . Service_Media::MEDIA_DIR_CONSULTATIONS . '/' . $this->consultation->kid . '/' . $this->consultation->img_file);?>"
                                class="header-box-image hidden-print"
                                alt="<?=$this->consultation->img_expl;?>"
                                />

                        </div>
                        <div class="col-md-3">

                            <!-- Home link -->
                            <div class="header-box-home hidden-print">
                                <a href="<?=$this->url(['controller' => 'index'], 'default', true);?>" class="link-alt has-icon" rel="home">
                                    <?=$this->translate('Home');?>…
                                    <span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span>
                                </a>
                            </div>

                            <!-- Share -->
                            <div class="header-box-share hidden-print">
                                <button type="button" class="btn btn-default btn-sm has-icon-lg dropdown-toggle js-share">
                                    <span class="icon-offset icon-lg icon-white glyphicon glyphicon-share-alt" aria-hidden="true"></span>
                                    <?=$this->translate('Share');?>
                                </button>
                                <div id="sharebtn-holder" class="share-dropdown"></div>
                            </div>

                        </div>
                    </div><!-- .row -->
                </div><!-- .header-box -->

            <?php else: ?>

                <!-- Header box: Homepage -->
                <div class="header-box<?=($controller === 'index' ? ' has-nav-list' : '');?>">

                    <h1 class="header-box-title<?php if ($this->themeAssets()['mitmachen_bubble']) : ?> header-box-title-with-bubble<?php endif; ?>">
                        <a href="<?=$this->url(['controller' => 'index'], 'default', true);?>" class="link-print-nourl" rel="home" itemprop="name">
                            <?=$this->translate('Participation');?>
                        </a>
                    </h1>

                    <!-- Help -->
                    <?php if ($controller === 'index'): ?>
                        <a
                            href="<?=$this->url(['controller' => 'help', 'action' => 'index', 'name' => 'help-text-home']);?>"
                            class="header-box-help has-icon hidden-print js-toggle-help"
                            title="<?=$this->translate('Help');?>"
                        >
                            <span class="icon-md glyphicon glyphicon-question-sign" aria-hidden="true"></span>
                        </a>
                    <?php endif; ?>

                    <p class="header-box-description" itemprop="description">
                        <?=$this->parameter('site.motto');?>
                    </p>

                    <!-- Menu -->
                    <?php if ($controller === 'index'): ?>
                        <?=$this->teaser();?>
                    <?php endif; ?>

                </div><!-- .header-box -->

            <?php endif; ?>

        </header>



        <!-- Main -->
        <main role="main" class="main">

            <?=$this->layout()->content;?>

        </main>


    </div><!-- .frame -->
</div><!-- .container -->



<!-- Footer -->
<footer class="footer">

    <!-- Footer navigation -->
    <nav role="navigation" class="navbar navbar-default navbar-static hidden-print">
        <div class="container">

            <ul class="nav navbar-nav">

                <?=$this->footerLinks();?>

                <li class="licence">
                    <a
                        href="<?=Zend_Registry::get('systemconfig')->content->$lang->creativeCommonsLicenseLink;?>"
                        rel="license"
                        target="_blank"
                        title="<?=$this->translate('Creative Commons license 4.0: attribution, non-commercial');?>"
                        >
                        <img src="<?=$this->baseUrl('images/licence.svg');?>" width="98" height="34" alt="CC-BY-NC 4.0" />
                    </a>
                </li>
            </ul>

        </div><!-- .container -->
    </nav>

    <hr class="visible-print" />

    <!-- About -->
    <div role="contentinfo">
        <div class="container">
            <div class="row">

                <?=$this->footer();?>

            </div><!-- .row -->
        </div><!-- .container -->
    </div>

</footer>



<!-- Scripts -->
<script>
    var baseUrl = '<?=$this->baseUrl()?>';
</script>
<script src="https://apis.google.com/js/client:platform.js?onload=initGoogle" async defer></script>
<script src="<?=$this->baseUrl('/index/i18n');?>?v=<?=$this->toolVersion();?>"></script>

<?php if (isset($this->hasFollowupTimeline)): ?>
    <script>
        $(document).ready(function() {
            var followUp = new FollowUp(<?=$this->consultation['kid'];?>);
        });
    </script>
<?php endif; ?>

</body>
<?php if (isset($this->lightsOut)): ?>
<div class="lights-out"></div>
<?php endif; ?>
</html>
