<?php
$config = Zend_Registry::get('config');
$sysconfig = Zend_Registry::get('systemconfig');
?>
<!DOCTYPE html>
<html lang="<?=Zend_Registry::get('Zend_Locale')->getLanguage();?>" itemscope itemtype="http://schema.org/Event">
	<head>
		<meta charset="utf-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=Edge" />
		<!--[if lte IE 8]><meta http-equiv="cleartype" content="on" /><![endif]-->

		<?php echo $this->headTitle(); ?>

		<meta name="description" content="<?php echo Zend_Registry::get('systemconfig')->meta->description?>" />
		<meta name="author" content="Content © 2013 DBJR" />
		<meta name="DC.title" content="Mitwirkung mit Wirkung" />
		<meta name="DC.creator" content="" />
		<meta property="og:title" content="Mitwirkung mit Wirkung" />
		<meta property="og:image" content="" />
		<meta property="og:description" content="<?php echo Zend_Registry::get('systemconfig')->meta->property->ogDescription?>" />
		<!--link rel="author" type="text/plain" href="<?php echo $this->baseUrl(); ?>/humans.txt" /-->

		<link
			rel="shortcut icon"
			href="<?php echo $this->baseUrl()?>/project/favicon.ico"
		/>

		<link rel="stylesheet" href="<?= $this->baseUrl() . $config->path->css->fonts ?>" type="text/css" />
		<link rel="stylesheet" href="<?= $this->baseUrl() . $config->path->css->bootstrap ?>" type="text/css" />
		<link rel="stylesheet" href="<?= $this->baseUrl() . $config->path->css->fontAwesome ?>" type="text/css" />
		<link rel="stylesheet" href="<?= $this->baseUrl() . $config->path->css->main ?>" type="text/css" />
		<?php echo $this->headLink(); ?>

        <link
            rel="stylesheet"
            href="<?php echo $this->baseUrl() .'/project/css/style.css'?>" type="text/css"
        />

		<!--[if lte IE 7]><link rel="stylesheet" href="<?= $this->baseUrl() . $config->path->css->ie7 ?>" type="text/css" /><![endif]-->

		<!-- HTML5 shim for IE6-8 support of HTML5 elements -->
		<!--[if lt IE 9]><script src="components/bower/html5shiv/dist/html5shiv.js"></script><![endif]-->

		<!--script has to be included here as there is still inline js code depending on jQuery-->
		<?php if (APPLICATION_ENV === 'development'): ?>
			<script src="<?=$this->baseUrl('js/web.js');?>"></script>
		<?php else: ?>
			<script src="<?=$this->baseUrl('js/web.min.js');?>"></script>
		<?php endif;?>
		<script src="<?=$this->baseUrl('/index/i18n');?>"></script>

		<script type="text/javascript">
			var baseUrl = '<?php echo $this->baseUrl(); ?>';
		</script>

	</head>
	<body>

        <!-- Flash messages -->
        <?php if (!empty($this->layout()->messages)): ?>
            <?php foreach ($this->layout()->messages as $level => $messages): ?>
                <?php if (!empty($messages)): ?>
                    <?php foreach ($messages as $message): ?>
                        <?php echo $this->partial('_partials/flashMessage.phtml', array('message' => $message, 'level' => $level))?>
                    <?php endforeach; ?>
                <?php endif; ?>
            <?php endforeach; ?>
        <?php endif; ?>

		<!-- Document wrap -->
		<div class="document-wrap" id="top">
			<div class="container">

				<!-- Header -->
				<?php echo $this->partial('_partials/header.phtml', $this->layout()->getView()); ?>

				<!-- Body copy -->
				<div role="main" class="main">

					<!-- Content start -->

					<?php echo $this->layout()->content; ?>

					<!-- Content end -->

				</div>
				<!-- .main -->
			</div>
			<!-- .container -->
		</div>
		<!-- .document-wrap -->
		<hr class="hide" />

		<!-- Footer -->
		<?php echo $this->render('_partials/footer.phtml') ?>

		<?php
		// echo '<!-- Debug-Info -->';
		// echo '<pre>';
		// $request = Zend_Controller_Front::getInstance() -> getRequest();
		// echo('<dt>Zend Version: </dt><dd>' . Zend_Version::VERSION . '</dd>');
		// echo('<dt>Application environment: </dt><dd>' . APPLICATION_ENV . '</dd>');
		// echo('<dt>Module:</dt><dd> ' . $request -> getModuleName() . '</dd>');
		// echo('<dt>Controller: </dt><dd>' . $request -> getControllerName() . '</dd>');
		// echo('<dt>Action:</dt><dd> ' . $request -> getActionName() . '</dd>');
		// $params = $request -> getParams();
		// echo '<dl>';
		// foreach ($params as $key => $value) {
			// switch ($key) {
				// case 'module' :
				// case 'controller' :
				// case 'action' :
					// continue;
//
				// default :
					// echo "<dt>" . $key . "</dt><dd>" . $value . "</dd>";
			// }
		// }
		// echo '</dl></pre>';
		// echo '<pre>';
		// print_r($_SESSION);
//
		// echo '</pre>';
		?>

	</body>
</html>
