<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
	<head>
		<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
		<title>DBJR - Administration</title>
		<!-- add your meta tags here -->

		<link href="<?php echo $this->baseUrl(); ?>/css/backend/style.css" rel="stylesheet" type="text/css" />
		<!--[if lte IE 7]>
		<link href="<?php echo $this->baseUrl(); ?>/css/backend/patches/patch_layout.css" rel="stylesheet" type="text/css" />
		<![endif]-->
		<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/components/bower/jquery/jquery.min.js"></script>
		<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/components/bower/ckeditor/ckeditor.js"></script>
	</head>
	<body>
		<div class="page_margins popup">
			<!-- start: skip link navigation -->
			<!-- end: skip link navigation -->
			<div class="page">

				<div id="main">
					<!-- Flash Messages -->
					<?php if (!empty($this->layout()->messages)): ?>
						<?php foreach ($this->layout()->messages as $level => $messages): ?>
							<?php if (!empty($messages)): ?>
								<?php foreach ($messages as $message): ?>
									<p class="<?php echo $level; ?>">
										<?php echo $message; ?>
									</p>
								<?php endforeach; ?>
							<?php endif; ?>
						<?php endforeach; ?>
					<?php endif; ?>
					<div class="clearfix">
						<!-- Content -->
						<?php echo $this->layout()->content; ?>
					</div>
				</div>
			</div>
		</div>
	</body>
</html>
