<?php
/**
 * index
 *
 * @description   Übersicht der Fragen zur Konsultation
 * @author        Markus Hackel
 */
?>
<!-- Secondary navigation -->
<?php echo $this->secondNavigation('question')?>
<!-- .secondary-navigation -->

<!-- Content start -->

<section class="main-content content-holder">
	<?php foreach ($this->questions as $question): ?>
  <h3><?php echo $question['q']?></h3>
  <?php echo $question['q_xpl']?>
  <?php endforeach; ?>
  <!-- Print -->
  <a href="javascript:print();" class="print">Seite drucken <i class="icon-print"></i></a>
</section><!-- .content-holder -->

<!-- Content end -->

<!-- Top link -->
<div class="top-link">
	<a href="#top" class="js-scroll"><i class="icon-angle-up icon-large"></i> nach oben</a>
</div>