<?php
    $linkHeadlineToInputs = false;
    if ((new Zend_Date($this->consultation->inp_fr, Zend_Date::ISO_8601))->isEarlier(Zend_Date::now())
        && (new Zend_Date($this->consultation->inp_to, Zend_Date::ISO_8601))->isLater(Zend_Date::now())
        && $this->consultation->inp_show == 'y') {
              $linkHeadlineToInputs = true;
        }
?>

<?php echo $this->secondNavigation('question') ?>

<div class="main-content">

    <h1><?=$this->translate('All questions')?></h1>

    <?php foreach ($this->questions as $question): ?>
        <article class="article article-preview">
            <?php if (!empty($question['nr'])): ?>
                <h2 class="alt numbered heading-with-cta">
                    <span class="numbered-number pull-left"><?= $question['nr'] ?></span>
                    <span class="numbered-title"><?= $question['q'] ?></span>
                </h2>
            <?php else: ?>
                <h2 class="alt"><?= $question['q'] ?></h2>
            <?php endif; ?>
            <?php if ($linkHeadlineToInputs): ?>
                <a
                    href="<?=$this->url(
                        array(
                            'controller' => 'input',
                            'action' => 'show',
                            'kid' => $this->consultation->kid,
                            'qid' => $question['qi'],
                           )
                   );?>"
                   class="btn edit pull-right hidden-print"
                   title="<?=$this->translate('Click here to answer')?>"
                >
                    <i class="icon-edit-alt"></i> <?=$this->translate('Write a contribution')?>
                </a>
            <?php endif; ?>
            <div class="row-fluid">
                <div class="span9">
                    <?php echo $question['q_xpl'] ?>
                </div>
            </div>
        </article>
    <?php endforeach; ?>

    <?=$this->render('_partials/pageLinks.phtml');?>

</div><!-- .main-content -->
