<section class="section-header has-tabs">
    <div class="container">
        <div class="row">
            <div class="col-sm-8">
                <h1><?=$this->translate('Email');?></h1>
            </div>
            <div class="col-sm-4">
                <a href="<?=$this->url(array('controller' => 'mail-send', 'action' => 'index'));?>" class="btn btn-primary cta"><span class="glyphicon glyphicon-pencil"></span> <?=$this->translate('New Email');?></a>
            </div>
        </div>
        <?=$this->emailTabs('settings');?>
    </div>
</section>
<section class="section-content">
    <div class="container">
        <div class="row">
            <div class="col-sm-3">

                <?=$this->emailSettingsNavigation('templates');?>

            </div>
            <div class="col-sm-9">

                <h2><?php echo !$this->templateId ? 'New' : 'Edit'?> <?=$this->translate('Email Template');?></h2>
                <p class="back-link">
                    <a href="<?php echo $this->baseUrl(); ?>/admin/mail-template">&larr; <?=$this->translate('Back to Email Templates');?></a>
                </p>
                <?php echo $this->form;?>

                <h3><?=$this->translate('Placeholders');?></h3>
                <dl>
                    <?php foreach ($this->placeholders as $placeholder): ?>
                        <dt>{{<?php echo $placeholder->name?>}}</dt>
                        <dd><?php echo $placeholder->description?></dd>
                    <?php endforeach?>
                </dl>

                <h3>Components</h3>
                <dl>
                    <?php foreach ($this->components as $component): ?>
                        <dt><?php echo Dbjr_Mail::TOKEN_OPEN . $component->name . Dbjr_Mail::TOKEN_CLOSE?></dt>
                        <dd><?php echo $component->description?></dd>
                    <?php endforeach?>
                </dl>

            </div>
        </div>
    </div>
</section>

<script type="text/javascript">
    CKEDITOR.replace('body_html', {
        removePlugins: 'horizontalrule,list,justify,indent,indentlist,indentblock,image2',
        removeButtons: 'Underline,Anchor,Superscript,Subscript,Strike'
        // filebrowserImageBrowseUrl: '/';
        // filebrowserImageUploadUrl: '/';
    });
</script>
