<h1><?php echo !$this->templateId ? 'Insert' : 'Edit'?> email template</h1>

<a href="<?php echo $this->baseUrl(); ?>/admin/mail-template">
    &laquo; Zur&uuml;ck zur &Uuml;bersicht
</a>

<?php echo $this->form;?>

<b>Placeholders</b>
<dl>
    <?php foreach ($this->placeholders as $placeholder): ?>
        <dt>{{<?php echo $placeholder->name?>}}</dt>
        <dd><?php echo $placeholder->description?></dd>
    <?php endforeach?>
</dl>

<a href="<?php echo $this->baseUrl(); ?>/admin/mail-template">
    &laquo; Zur&uuml;ck zur &Uuml;bersicht
</a>

<script type="text/javascript">
    CKEDITOR.replace('body_html');
</script>
