<h1>Email templates</h1>


<a class="icon icon-plus" href="<?php echo $this->url(array('action' => 'detail')); ?>">
    New email template
</a>

<form method="<?=$this->form->getMethod()?>" action="<?php echo $this->url(array('action' => 'delete'));?>">
    <?=$this->form->getElement('email_list_control_csrf_token')?>
    <table>
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Subject</th>
                <th></th>
            </tr>
        </thead>

        <tbody>
            <?php foreach ($this->templates as $template): ?>
                <tr>
                    <td><?php echo $template->id?></td>
                    <td><?php echo $template->name?></td>
                    <td><?php echo $template->subject?></td>
                    <td>
                        <a href="<?php echo $this->url(array('action' => 'detail', 'id' => $template->id));?>">
                            Bearbeiten
                        </a>
                        <?php if($template->findModel_Mail_Template_Type()->current()->name !== Model_Mail_Template_Type::TEMPLATE_TYPE_SYSTEM): ?>
                            <button
                                name="deleteId"
                                type="submit"
                                onclick="return confirm('Are you sure?');"
                                value="<?php echo $template->id?>"
                            >
                                Delete
                            </button>
                        <?php endif?>
                    </td>
                </tr>
            <?php endforeach?>
        </tbody>
    </table>
</form>

<a class="icon icon-plus" href="<?php echo $this->url(array('action' => 'detail')); ?>">
    New email template
</a>
