<section class="section-header has-tabs">
    <div class="container">
        <div class="row">
            <div class="col-sm-8">
                <h1><?=$this->translate('Email');?></h1>
            </div>
            <div class="col-sm-4">
                <a href="<?=$this->url(array('controller' => 'mail-send', 'action' => 'index'));?>" class="btn btn-primary cta"><span class="glyphicon glyphicon-pencil"></span> <?=$this->translate('New Email');?></a>
            </div>
        </div>
        <?=$this->emailTabs('settings');?>
    </div>
</section>
<section class="section-content">
    <div class="container">
        <div class="row">
            <div class="sidebar">

                <?=$this->emailSettingsNavigation('templates');?>

            </div>
            <div class="content">

                <a href="<?php echo $this->url(array('action' => 'detail')); ?>" class="btn btn-default pull-right">
                    <span class="glyphicon glyphicon-plus-sign"></span>
                    <?=$this->translate('New Email Template');?>
                </a>
                <h2><?=$this->translate('Email Templates');?></h2>

                <form method="<?=$this->form->getMethod()?>" action="<?=$this->url(['action' => 'delete']);?>">
                    <?=$this->form->getElement($this->form->getCsrfTokenName())?>
                    <table class="table">
                        <thead>
                            <tr>
                                <th class="table-cell-id sorting-asc" data-toggle="sort" tabindex="0">#</th>
                                <th data-toggle="sort" tabindex="0"><?=$this->translate('Name');?></th>
                                <th data-toggle="sort" tabindex="0"><?=$this->translate('Subject');?></th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($this->templates as $template): ?>
                                <tr>
                                    <td class="table-cell-id"><?=$this->escape($template->id);?></td>
                                    <td><?=$this->escape($template->name);?></td>
                                    <td><?=$this->escape($template->subject);?></td>
                                    <td class="table-cell-actions">
                                        <a href="<?php echo $this->url(array('action' => 'detail', 'id' => $template->id));?>" class="item-action" title="<?=$this->translate('Edit template');?>">
                                            <span class="glyphicon glyphicon-pencil"></span>
                                        </a>
                                        <?php if($template->findModel_Mail_Template_Type()->current()->name !== Model_Mail_Template_Type::TEMPLATE_TYPE_SYSTEM): ?>
                                            <button
                                                name="deleteId"
                                                type="submit"
                                                class="item-action item-action-danger"
                                                data-toggle="confirm"
                                                data-confirm-message="<?=$this->translate('Delete email template?');?>"
                                                value="<?=$this->escape($template->id)?>"
                                                title="<?=$this->translate('Delete template');?>"
                                            >
                                                <span class="glyphicon glyphicon-trash"></span>
                                            </button>
                                        <?php endif?>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                </form>

            </div>
        </div>
    </div>
</section>
