<form
    enctype="<?=$this->element->getEnctype();?>"
    method="<?=$this->element->getMethod();?>"
    class="offset-bottom"
    enctype="<?=$this->element->getEnctype();?>"
>
    <div class="form-group offset-bottom">
        <?=$this->element->field_switch_name;?>
        <?=$this->element->field_switch_age;?>
    </div>

    <div class="form-group offset-bottom">
        <?=$this->element->allow_groups;?>
        <?=$this->element->field_switch_contribution_origin;?>
        <?=$this->element->field_switch_individuals_sum;?>
        <?=$this->element->field_switch_group_name;?>
        <?=$this->element->field_switch_contact_person;?>
    </div>

    <div class="form-group offset-bottom">
        <?=$this->element->field_switch_notification;?>
        <?=$this->element->field_switch_newsletter;?>
        <?=$this->element->field_switch_comments;?>
    </div>

    <?=$this->element->field_switch_state;?>
    <?=$this->element->state_field_label;?>
    <?=$this->element->contribution_confirmation_info;?>

    <?=$this->element->submit;?>

    <?=$this->element->csrf_token_contributionsubmissionformadmin;?>

</form>
