<section class="section-header has-tabs">
    <div class="container">

        <h1><?=$this->consultation->titl;?></h1>
        <h2><?=$this->consultation->titl_sub;?></h2>

        <?=$this->consultationTabs($this->consultation->kid, 'settings');?>

    </div>
</section>
<section class="section-content">
    <div class="container">
        <div class="row">
            <div class="sidebar">

                <?=$this->consultationEditNavigation($this->consultation->kid, 'settings');?>

            </div>
            <div class="content">

                <div class="row">
                    <div class="col-sm-4 col-sm-push-8 text-right">

                        <?php if (Zend_Auth::getInstance()->getIdentity()->lvl === 'adm'): ?>
                            <?php // TODO change links to POST form button ?>
                            <div class="btn-group offset-bottom">
                                <a href="<?=$this->url(array('controller' => 'close', 'action' => 'index', $this->consultation->kid));?>" class="btn btn-default">
                                    <span class="glyphicon glyphicon-remove-sign"></span>
                                    <?=$this->translate('Close');?>
                                </a>
                                <a href="<?=$this->url(array('action' => 'delete', $this->consultation->kid));?>" class="btn btn-danger">
                                    <span class="glyphicon glyphicon-trash"></span>
                                    <?=$this->translate('Delete');?>
                                </a>
                            </div>
                        <?php endif; ?>

                    </div>
                    <div class="col-sm-8 col-sm-pull-4">
                        <h2><?=$this->translate('Consultation Settings');?></h2>
                    </div>
                </div><!-- .row -->

                <?=$this->form?>
                <p>
                    <?=$this->translate('or');?>
                    <a href="<?=$this->url(array('action' => 'index', $this->consultation->kid));?>"><?=$this->translate('Cancel');?></a>
                </p>

            </div>
        </div><!-- .row -->
    </div><!-- .container -->
</section>
