<section class="section-header">
    <div class="container">

        <?=$this->helpText('help-text-admin-consultation-settings-groups');?>

        <h1 class="section-header-title"><?=$this->escape($this->consultation->titl);?></h1>
        <h2 class="section-header-subtitle"><?=$this->escape($this->consultation->titl_sub);?></h2>

        <?=$this->consultationTabs($this->consultation->kid, 'settings');?>

    </div>
</section>
<section class="section-content">
    <div class="container">
        <div class="row">
            <div class="sidebar offset-bottom-large-sm-max">

                <?=$this->consultationEditNavigation($this->consultation->kid, 'groups');?>

            </div>
            <div class="content">

                <h2><?=$this->translate('Groups');?></h2>
                <?=$this->partial('consultation/_groupsForm.phtml', ['form' => $this->formGroups]);?>

            </div>
        </div><!-- .row -->
    </div><!-- .container -->
</section>
