<section class="section-header has-tabs" xmlns="http://www.w3.org/1999/html">
    <div class="container">

        <h1 class="section-header-title"><?=$this->consultation->titl;?></h1>
        <h2 class="section-header-subtitle"><?=$this->consultation->titl_sub;?></h2>

        <?=$this->consultationTabs($this->consultation->kid, 'consultation');?>

    </div>
</section>
<section class="section-content">
    <div class="container">
        <div class="row">
            <div class="sidebar">

                <?=$this->consultationNavigation($this->consultation['kid'], 'dashboard');?>

            </div>
            <div class="content">

                <div class="row">
                    <form method="<?=$this->form->getMethod();?>">
                        <?=$this->form->getElement($this->form->getCsrfTokenName());?>
                        <div class="col-md-6">

                            <h2>
                                <?=$this->translate('New Contributions');?>
                                <span class="badge"><?=count($this->inputs);?></span>
                            </h2>

                            <?php if ($this->inputs): ?>
                                <?php foreach($this->inputs as $input): ?>
                                    <blockquote>

                                        <div class="media">
                                            <div class="media-right pull-right">
                                                <button
                                                    class="item-action item-action-danger"
                                                    name="deleteInput"
                                                    value="<?=$input['tid'];?>"
                                                    data-toggle="confirm"
                                                    data-confirm-message="<?=$this->translate('Delete contribution?');?>"
                                                    title="<?=$this->translate('Delete');?>"
                                                    >
                                                    <span class="glyphicon glyphicon-remove-sign"></span>
                                                </button>
                                            </div>
                                            <div class="media-body">
                                                <a href="<?=$this->url(['controller' => 'input', 'action' => 'edit', 'tid' => $input['tid'], 'uid' => $input['uid']]);?>">
                                                    <p><?=$input['thes'];?></p>
                                                </a>
                                            </div>
                                        </div><!-- .media -->

                                        <footer>
                                            <?php if (!empty($input['name'])): ?>
                                                <span class="glyphicon glyphicon-user"></span>
                                                <a
                                                    href="<?=$this->url(['controller' => 'input', 'action' => 'list-by-user', 'uid' => $input['uid']]);?>"
                                                    title="<?=$this->translate('Show contributions by');?> <?=$input['name'];?>"
                                                    >
                                                    <?=$input['name'];?>
                                                </a>,
                                            <?php endif; ?>
                                            <?=$this->formatDate($input['when']);?>
                                        </footer>

                                    </blockquote>
                                <?php endforeach; ?>
                            <?php else: ?>
                                <p class="alert alert-info">
                                    <span class="glyphicon glyphicon-info-sign"></span>
                                    <?=$this->translate('There are no unprocessed contributions.');?>
                                </p>
                            <?php endif; ?>

                        </div>
                        <div class="col-md-6">

                            <h2>
                                <?=$this->translate('Discussion Posts');?>
                                <span class="badge"><?=count($this->discussionContribs);?></span>
                            </h2>

                            <?php if (count($this->discussionContribs)): ?>
                                <?php foreach($this->discussionContribs as $contrib): ?>
                                    <blockquote>

                                        <div class="media">
                                            <div class="media-right pull-right">
                                                <button
                                                    class="item-action item-action-danger"
                                                    name="deleteDiscContrib"
                                                    value="<?=$contrib->id;?>"
                                                    data-toggle="confirm"
                                                    data-confirm-message="<?=$this->translate('Delete discussion post?');?>"
                                                    title="<?=$this->translate('Delete');?>"
                                                    >
                                                    <span class="glyphicon glyphicon-remove-sign"></span>
                                                </button>
                                            </div>
                                            <div class="media-body">
                                                <a href="<?=$this->baseUrl()?>/admin/input-discussion/index/kid/<?=$this->consultation['kid'];?>/inputId/<?=$this->escape($contrib->input_id);?>#<?=$this->escape($contrib->id);?>">
                                                    <?=$this->escape($contrib->body);?>
                                                </a>
                                            </div>
                                        </div><!-- .media -->

                                        <footer>
                                            <?php if (!empty($contrib['name'])): ?>
                                                <span class="glyphicon glyphicon-user"></span>
                                                <?=$contrib['name'];?>,
                                            <?php endif; ?>
                                            <?=$this->formatDate($contrib->time_created);?>
                                        </footer>

                                    </blockquote>
                                <?php endforeach; ?>
                            <?php else: ?>
                                <p class="alert alert-info">
                                    <span class="glyphicon glyphicon-info-sign"></span>
                                    <?=$this->translate('There are no discussion posts yet.');?>
                                </p>
                            <?php endif; ?>

                        </div>
                    </form>
                </div><!-- .row -->

            </div>
        </div><!-- .row -->
    </div>
</section>
