<section class="section-header has-tabs">
    <div class="container">

        <h1><?=$this->consultation->titl;?></h1>
        <h2><?=$this->consultation->titl_sub;?></h2>

        <?=$this->consultationTabs($this->consultation->kid, 'consultation');?>

    </div>
</section>
<section class="section-content">
    <div class="container">
        <div class="row">
            <div class="sidebar">

                <?=$this->consultationNavigation($this->consultation['kid'], 'dashboard');?>

            </div>
            <div class="content">
                <div class="row">
                    <div class="col-lg-9">

                        <h2>
                            <?=$this->translate('New Contributions');?>
                            <span class="badge"><?=$this->inputsCount;?></span>
                        </h2>

                        <?php if (!$this->inputsCount): ?>
                            <p class="alert alert-info">
                                <span class="glyphicon glyphicon-info-sign"></span>
                                <?=$this->translate('There are no unprocessed contributions. Good job!');?>
                            </p>
                        <?php endif; ?>

                        <?php foreach($this->inputs as $input): ?>
                            <div class="well">
                                <a href="<?=$this->url(['controller' => 'input', 'action' => 'edit', 'tid' => $input['tid']]);?>">
                                    <p><?=$input['thes'];?></p>
                                </a>

                                <?=(!empty($input['expl']) ? ('<p>' . $input['expl'] . '</p>') : '');?>
                                <small>
                                    <span class="glyphicon glyphicon-user"></span>
                                    <?php if (!empty($input['name'])): ?>
                                        <a
                                            href="<?=$this->url(['controller' => 'input', 'action' => 'list-by-user', 'uid' => $input['uid']]);?>"
                                            title="<?=$this->translate('Show contributions by');?> <?=$input['name'];?>"
                                            ><?=$input['name'];?></a>,
                                    <?php endif; ?>
                                    <?=(new Zend_Date())->set($input['when'])->get(Zend_Date::DATETIME_MEDIUM);?>
                                </small>
                            </div>
                        <?php endforeach?>

                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- TODO move to JS -->
<script>
    $(document).ready(function(){
        $('.delete-action a').click(function(event){
            event.preventDefault();
            var check = confirm('Wollen sie diese Beteiligungsrunde wirklich löschen?');
            if(check === true) {
                window.location = "/admin/consultation/delete/kid/<?php echo $this->consultation->kid; ?>";
            }
        });
    });
</script>
