<?php
/**
 * index
 *
 * @description   consultation create form
 * @author        Markus Hackel
 */
?>
<?php foreach ($this->messages as $level => $messages):?>
  <?php foreach ($messages as $message):?>
<p class="<?php echo $level?>"><?php echo $message?></p>
  <?php endforeach;?>
<?php endforeach;?>
<h2>Neue Konsultation</h2>
<?php echo $this->form?>
<p>
  <a href="/admin/index">Zur&uuml;ck</a>
</p>
<script>
    CKEDITOR.replace( 'expl' );
    CKEDITOR.replace( 'vot_expl' );
</script>