<section class="section-header">
    <div class="container">

        <h1><?=$this->translate('New Consultation');?></h1>

    </div>
</section>
<section class="section-content">
    <div class="container">

        <a href="<?=$this->url(array('controller' => 'index', 'action' => 'index'));?>" class="back">&larr; <?=$this->translate('Back to Consultations');?></a>

        <?php echo $this->form?>

    </div>
</section>
