<section class="section-header">
    <div class="container">

        <h1 class="section-header-title"><?=$this->escape($this->consultation->titl);?></h1>
        <h2 class="section-header-subtitle"><?=$this->escape($this->consultation->titl_sub);?></h2>

        <?=$this->consultationTabs($this->consultation->kid, 'consultation');?>

    </div>
</section>
<section class="section-content">
    <div class="container">
        <div class="row">
            <div class="sidebar offset-bottom-large-sm-max">

                <?=$this->consultationNavigation($this->consultation, 'stats');?>

            </div>
            <div class="content">

                <h2><?=$this->translate('Statistics');?></h2>
                <p>
                    <b>
                        <a href="<?php echo $this->url([
                            'controller' => 'input',
                            'action' => 'index'
                            ]); ?>"
                          title="<?=$this->translate('All Contributors');?>">
                            <?=$this->translate('Number of contributors in current consultation');?>:
                            <?php echo $this->nrParticipants; ?>
                        </a>
                    </b>
                    <br/><?=$this->translate('Accumulated number of individuals and groups, even if they contributed in several sessions in this particular consultation');?>
                </p>
                <p>
                    <strong><?=$this->translate('All contributions in the contribution period');?>: <?php echo $this->nrInputs; ?></strong>
                </p>
                <ul>
                    <li>
                        <?=$this->translate('of which the contributions that were confirmed');?>: <?php echo $this->nrInputsConfirmed; ?>
                    </li>
                    <li>
                        <?=$this->translate('of which remained unconfirmed or anonymous');?>: <?php echo $this->nrInputsUnconfirmed; ?>
                    </li>
                    <li>
                        <?=$this->translate('of which were blocked by organisers');?>: <?php echo $this->nrInputsBlocked; ?>
                    </li>
                </ul>
                <p>
                    <strong><?=$this->translate('Contributions that were available to vote on');?>: <?php echo $this->nrInputsVoting; ?></strong><br />
                    <span class="text-muted small"><?=$this->translate('All contributions except ones with voting disabled');?></span>
                </p>

                <h3 class="offset-top-large"><?=$this->translate('Questions');?></h3>

                <?php foreach ($this->questions as $question): ?>
                    <div class="offset-bottom">
                        <p>
                            <a href="<?php echo $this->url(array(
                                'controller' => 'input',
                                'action' => 'index',
                                'qid' => $question['qi']
                            )); ?>"
                               title="<?=$this->translate('See Contribution');?>"
                            >
                                <strong><?php echo $question['nr']; ?> <?php echo $question['q']; ?></strong>
                            </a>
                        </p>
                        <p>
                            <?=$this->translate('Number of confirmed contributions');?>: <?php echo $question['nrInputsConfirmed']; ?><br />
                        </p>
                        <p>
                            <?=$this->translate('Number of contributions for voting');?>: <?php echo $question['nrInputsVoting']; ?><br />
                            <span class="text-muted small"><?=$this->translate('All contributions except ones with voting disabled');?></span>
                        </p>
                    </div>
                <?php endforeach; ?>

                <h3 class="offset-top-large"><?=$this->translate('Votes');?></h3>

                <p>
                    <a href="<?php echo $this->url(array(
                        'controller' => 'voting',
                        'action' => 'participants'
                        )); ?>"
                       title="<?=$this->translate('Absolute number of votes');?>"
                    >
                        <strong><?=$this->translate('Absolute number of votes');?>: <?php echo $this->votingCountIndiv; ?></strong>
                    </a><br />
                    <span class="text-muted small"><?=$this->translate('Raw amount, voting weight not taken into account');?></span>
                </p>

                <p>
                    <a href="<?php echo $this->url(array(
                        'controller' => 'voting',
                        'action' => 'index'
                        )); ?>"
                      title="<?=$this->translate('Groups that have voting rights and number of actually participating ones');?>"
                    >
                        <strong><?=$this->translate('Groups that have voting rights and number of actually participating ones');?></strong>
                    </a>
                </p>

                <h4 class="offset-top"><?=$this->translate('Voting weights');?></h4>
                <table>
                    <?php foreach ($this->weightCounts as $weight): ?>
                        <tr>
                            <th scope="row">
                                <?php switch ($weight['vt_weight']) {
                                    case 0:
                                        echo $this->translate('Test accounts');
                                        break;
                                    case 1:
                                        echo $this->translate('Individuals');
                                        break;
                                    default:
                                        echo $this->translate('Group weight') . ' ' . $weight["vt_weight"];
                                        break;
                                } ?>:
                            </th>
                            <td>
                                <span class="offset-left-large"><?php echo $weight['participating_count']; ?> / <?php echo $weight['weight_count']; ?></span>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </table>

            </div>
        </div>
    </div>
</section>
