<?php
/**
 * statistical Report
 */
?>
<h1><?php echo !empty($this->consultation) ? $this->consultation->titl : 'Übersicht'; ?></h1>
<?php
echo $this->consultationNavigation('Statistik');
?>

<h2>Statistischer Bericht</h2>
<p>
  <b><a href="<?php echo $this->url(array(
    'controller' => 'input',
    'action' => 'userlist'
  )); ?>" title="Alle Beitragende ansehen">Anzahl Beitragende im Konsultationszeitraum: <?php echo $this->nrParticipants; ?></a></b>
  <br/>(absolute Anzahl der Einzelpersonen und Organisationen/Träger, auch wenn sie evtl. mehrere Projekte eingetragen haben)
</p>
<p>
  <b>Alle Beiträge im Konsultationszeitraum: <?php echo $this->nrInputs; ?></b>
  <br/>&raquo; davon von den Beitragendenden bestätigte: <?php echo $this->nrInputsConfirmed; ?>
  <br/>&raquo; davon unbestätigte oder anonyme: <?php echo $this->nrInputsUnconfirmed; ?>
  <br/>&raquo; von der Redaktion geblockte: <?php echo $this->nrInputsBlocked; ?>
</p>
<p>
  <b>Zur Abstimmung gestellte Beiträge: <?php echo $this->nrInputsVoting; ?></b>
  <br />(tw. durch die Redaktion zusammengefasst aus inhaltlich überschneidenden Beiträgen)
</p>

<hr />

<?php foreach ($this->questions as $question): ?>
<p>
  <b><a href="<?php echo $this->url(array(
    'controller' => 'input',
    'action' => 'index',
    'qid' => $question['qi']
  )); ?>" title="Beiträge sichten"><?php echo $question['nr']; ?> <?php echo $question['q']; ?></a></b>
  <br />Anzahl Beiträge: <?php echo $question['nrInputsConfirmed']; ?> (nur bestätigte)
  <br />Zur Abstimmung gestellt: <?php echo $question['nrInputsVoting']; ?> (tw. durch die Redaktion bearbeitet)
</p>
<?php endforeach; ?>

<hr />

<p><b>Anzahl abgegebener Stimmen: <?php // TODO: insert Voting count ?></b></p>

<p><b>Übersicht über abstimmungsberechtigte Gruppen</b></p>
<?php // TODO: insert Voting Defs ?>