<?
		if ((int)$this -> depth==0)  {
   			echo '<li class="level_'.(int)$this -> depth.'">
   						<a class="moveto" rel="'.$this -> baseUrl().'/admin/votingprepare/setdirectory/kid/'.$this -> kid.'/qid/'.$this -> qid.'/dir/'.$this -> id.'" title="Ausgewählte Beiträge in diesen Ordner verschieben">&#8883;</a>
   						<div><a href="'.$this -> baseUrl().'/admin/votingprepare/overview/kid/'.$this -> kid.'/qid/'.$this -> qid.'/dir/'.$this -> id.'" title="Gehe zum Ordner"><b>' . $this -> dir_name . ' ('.$this -> count.')</b></a></div>
   						</li>';
		} else {
			echo '<li class="level_'.(int)$this -> depth.'">
					 	<a class="moveto" rel="'.$this -> baseUrl().'/admin/votingprepare/setdirectory/kid/'.$this -> kid.'/qid/'.$this -> qid.'/dir/'.$this -> id.'" title="Ausgewählte Beiträge in diesen Ordner verschieben">&#8883;</a>
						<div><a href="'.$this -> baseUrl().'/admin/votingprepare/overview/kid/'.$this -> kid.'/qid/'.$this -> qid.'/dir/'.$this -> id.'" title="Gehe zum Ordner">&#9492; ' . $this -> dir_name . ' ('.$this -> count.')</a></div>
					</li>';
		}
?>
