<tr
    data-admin-confirmation="<?=$this->input['block'];?>"
    data-origin="<?=$this->input['user_conf'];?>"
    data-voting="<?=$this->input['vot'];?>"
    data-tags='<?=json_encode(array_map(function($el) {return $el['tg_nr'];}, $this->input['tags']));?>'
    data-directory="<?=$this->input['dir'];?>"
>
    <td>
        <input type ="checkbox" name="inputIds[]" value="<?=$this->escape($this->input['tid']);?>" />
        <?=$this->escape($this->input['tid']);?>
    </td>
    <td>
        <h6>Input</h6>
        <?=$this->escape($this->input['thes']);?>
        <h6>Input explanation</h6>
        <?=$this->escape($this->input['expl']);?>
        <h6>Internal note</h6>
        <?=$this->escape($this->input['notiz'])?>
        <h6>Tags</h6>
        <?php foreach($this->input['tags'] as $tag): ?>
            <?=$this->escape($tag['tg_de']);?>
        <?php endforeach?>
        <h6>Related</h6>
        <?php foreach ($this->input['related'] as $relInput): ?>
            <div>
                <?=$this->escape($relInput['thes']);?>
            </div>
        <?php endforeach;?>
    </td>
    <td>
        <h6>Origin:</h6>
        <?=$this->input['uid'] ? $this->translate('User') : $this->translate('Admin');?>
        <h6>Admin Confirmation:</h6>
        <?php if ($this->input['block'] === 'y'): ?>
            <?=$this->translate('Blocked');?>
        <?php elseif ($this->input['block'] === 'n'): ?>
            <?=$this->translate('Confirmed');?>
        <?php else: ?>
            <?=$this->translate('Unknown');?>
        <?php endif;?>
        <h6>Voting:</h6>
        <?php if ($this->input['vot'] === 'y'): ?>
            <?=$this->translate('Yes');?>
        <?php elseif ($this->input['vot'] === 'n'): ?>
            <?=$this->translate('No');?>
        <?php else: ?>
            <?=$this->translate('Unknown');?>
        <?php endif;?>
    </td>
    <td>
        <a
            class="btn btn-default item-action"
            href="<?=$this->url(['controller' => 'input', 'action' => 'edit', 'tid' => $this->input['tid'], 'return' => 'votingprepare']);?>"
        >
            <span class="glyphicon glyphicon-pencil"></span>
        </a>
        <a
            class="btn btn-default item-action"
            href="<?=$this->url(['action' => 'copy', 'inputId' => $this->input['tid']]);?>"
        >
            <span class="glyphicon glyphicon-tags"></span>
        </a>
        <a
            class="btn btn-default item-action"
            href="<?=$this->url(['action' => 'split', 'inputId' => $this->input['tid']]);?>"
        >
            <span class="glyphicon glyphicon-resize-full"></span>
        </a>
        <button
            class="btn btn-default item-action item-action-danger"
            name="delete"
            value="<?=$this->input['tid']?>"
            data-toggle="confirm"
            data-confirm-message="<?=$this->translate('Delete input?');?>"
        >
            <span class="glyphicon glyphicon-trash"></span>
        </button>
    </td>
</tr>
