<li class="related clearfix" >
	<div class="article">
<?php
	echo $this->thes; 
?>
	</div>
	<div class="work" id="work-<? echo $this->tid; 	// cancel shortcut to  original // ?>">
<?
	echo '<a rel="'.$this->tid.'"  data="'.$this->parent.'"  class="cancel-shortcut">Verknüpfung aufheben!</a>';
	if ($this->uid==1) { // delete only article from office //
		echo '<a rel="'.$this->tid.'" class="del-input">Redaktionsbeitrag löschen!</a>';
	};
?>
	</div>
</li>