<?php
/**
 *  create-snippet.phtml
 * 
 *  @description       create followup Snippet
 *  @author            Marco Dinnbier
 */
?>
<h1><?php echo $this->consultation['titl']; ?></h1>
<?php echo $this->consultationNavigation('Follow-up'); ?>
<h2>Neuen Follow-up-Schnippsel erstellen</h2>
<!--uniqueEditSnippetSTART-->
<?php echo $this->form;?>
<script>
    CKEDITOR.replace( 'expl' );   
</script>
<!--uniqueEditSnippetEND-->
