<?php
/**
 *  create-doc.phtml
 * 
 *  @description   edit followup files and handle followup snippets
 *  @author        Marco Dinnbier
 */
?>
<h1><?php echo $this->consultation['titl']; ?></h1>
<?php echo $this->consultationNavigation('Follow-up'); ?>
<h2>Follow-up Dokument bearbeiten</h2>
<?php echo $this->form;?>
<!--<p><a href="<?php echo $this->url(array(
  'action' => 'create',
  'kid' => isset($this->consultation) ? $this->consultation['kid'] : 0
));?>">Neues Follow-up</a></p>-->
<h2>Übersicht der Follow-ups</h2>

<table style="width: 100%">
    <tbody>

        <tr>
            <th>
            <?php if($this->movefollowup && $this->movefollowup['docorg'] != 1): ?>
                <a href="<?php echo $this->url(array(
                            'module' => 'admin',
                            'controller' => 'followup',
                            'action' => 'move',
                            'kid' => $this->consultation['kid'],
                            'ffid' => $this->ffid,
                            'movefid' => $this->movefollowup['fid'],
                            'prev' => 0
                              ),null,true);?>">Hier einfügen</a>
           <?php endif; ?>
                <a href="<?php echo $this->url(array(
                            'action' => 'create-snippet',
                            'kid' => $this->consultation['kid'],
                            'ffid' => $this->ffid,
                            'prev' => 0                      
                              ));?>">Neu</a>    
         
          </th>
        </tr>
         </tbody>
</table>
<?php foreach ($this->followups as $followup): ?>
<?php 
    $marg = $followup['hlvl'] > 1 ? $followup['hlvl'] * 3 : 0;
    $width = 100 - $marg;
    $style = "margin-left:$marg%;width:$width%;";
    if ($followup['fid'] == $this->movefollowup['fid']) $style.="background:#bbb;";
?>
<table style="<?php echo $style; ?>border:2px solid #888888;"><tbody>
            <tr>                
                <td style="vertical-align:top;">
                    <?php 
                   
                       $popupurl = $this->url(array(
                            'action' => 'reference',
                            'kid' => $this->consultation['kid'],
                            'fid' => $followup['fid'],
                            'ffid' => $this->ffid
                              ));
                       $popuplinkstyle = 'background: none repeat scroll 0 0 #4D87C7;border-radius:9px;color: #FFFFFF;display: block;margin-bottom: 1px;padding: 3px;text-align: center;outline:0 none;';
                       echo $this->Popuplink( $popupurl, 'Follow-up Referenzen zuweisen', 1100, 600, $followup['relFowupCount'], 'Referenzen bearbeiten' ,$popuplinkstyle); ?>
                    <br />
                    <?php if($followup['hlvl'] < 6): ?>
                    <a href="<?php echo $this->url(array(
                            'action' => 'hierarchy',
                            'kid' => $this->consultation['kid'],
                            'fid' => $followup['fid'],
                            'ffid' => $this->ffid,
                            'hlvl' => $followup['hlvl'] + 1
                              ));?>" title="Level up">&raquo;</a><br/>
                    <?php endif; ?>
                    <?php if ($followup['hlvl'] > 1): ?>
                    <a href="<?php echo $this->url(array(
                            'action' => 'hierarchy',
                            'kid' => $this->consultation['kid'],
                            'fid' => $followup['fid'],
                            'ffid' => $this->ffid,
                            'hlvl' => $followup['hlvl'] - 1
                              ));?>" title="Level down">&laquo;</a>
                    <?php endif; ?>
                    
                </td>
                <td style="width:60%;"><?php echo substr(html_entity_decode($followup['expl']), 0, 400).'...'; ?></td>
                <!--<td><?php echo $followup['lkyea']; ?> / <?php echo $followup['lknay']; ?></td>-->
                <td style="text-align: right;"><a href="<?php echo $this->url(array(
                            'action' => 'edit-snippet',
                            'kid' => $this->consultation['kid'],
                            'fid' => $followup['fid'],
                            'ffid' => $this->ffid
                              ));?>" title="Follow-up bearbeiten">Bearbeiten</a>
                                       &nbsp;
                    <a href="<?php echo $this->url(array(
                            'module' => 'admin',
                            'controller' => 'followup',
                            'action' => 'move',
                            'kid' => $this->consultation['kid'],
                            'fid' => $followup['fid'],
                            'ffid' => $this->ffid                           
                            ),null, true);?>" title="Artikel löschen">Verschieben</a>
                              &nbsp;
                    <a href="<?php echo $this->url(array(
                            'action' => 'delete-snippet',
                            'kid' => $this->consultation['kid'],
                            'fid' => $followup['fid'],
                            'ffid' => $this->ffid    
                            ));?>" title="Follow-up löschen">Löschen</a>
           
                </td>

            </tr>
            <tr>
                <td colspan="3" style="background:#888;color:#fff;">
                    Hierarchy Level: <?php echo $followup['hlvl']; ?> &nbsp;&bull;&nbsp;
                    Likes / Unlikes: <?php echo $followup['lkyea']; ?> / <?php echo $followup['lknay']; ?> &nbsp;&bull;&nbsp;
                    Typ: <?php $typ = array('g' => 'general', 'a'=>'action','r'=>'rejected','e'=>'end'); echo $typ[$followup['typ']]; ?> 
                </td>
            </tr>
            </tbody>
            </table>
<table style="width: 100%">
    <tbody>
            <tr>
                <th colspan="4">
                <?php if($this->movefollowup && $this->movefollowup['fid'] != $followup['fid'] && $followup['docorg'] != $this->movefollowup['docorg']-1): ?>
                    <a href="<?php echo $this->url(array(
                              'module' => 'admin',
                              'controller' => 'followup',
                              'action' => 'move',
                              'kid' => $this->consultation['kid'],
                              'ffid' => $this->ffid,
                              'movefid' => $this->movefollowup['fid'],
                              'prev' => $followup['docorg']
                                ),null,true);?>">Hier einfügen</a>
                <?php endif; ?>
                    <a href="<?php echo $this->url(array(
                              'module' => 'admin',
                              'controller' => 'followup',
                              'action' => 'create-snippet',
                              'kid' => $this->consultation['kid'],
                              'ffid' => $this->ffid,
                              'prev' => $followup['docorg']
                                ),null,true);?>">Neu</a>
         
                </th>
            </tr>
</tbody></table>
        <?php endforeach; ?>        
    </tbody>
</table>
