<?php
/**
 *  create-doc.phtml
 * 
 *  @description   
 *  @author             Marco Dinnbier
 */
?>
<h1><?php echo $this->consultation['titl']; ?></h1>
<?php echo $this->consultationNavigation('Follow-up'); ?>
<h2>Follow-up Dokument bearbeiten</h2>
<?php echo $this->form;?>
<!--<p><a href="<?php echo $this->url(array(
  'action' => 'create',
  'kid' => isset($this->consultation) ? $this->consultation['kid'] : 0
));?>">Neues Follow-up</a></p>-->
<h2>Übersicht der Follow-ups</h2>

<table style="width: 100%">
    <tbody>
        <tr>
            <th></th>
            <th style="width: 55%">Erläuterung</th>
            <th>Likes</th>
            <th>Unlikes</th>
            <th style="text-align: right;">Aktionen</th>
            
        </tr>
        <tr>
            <td colspan="5">
            <?php if($this->movefollowup && $this->movefollowup['docorg'] != 1): ?>
                <a href="<?php echo $this->url(array(
                            'module' => 'admin',
                            'controller' => 'followup',
                            'action' => 'move',
                            'kid' => $this->consultation['kid'],
                            'ffid' => $this->ffid,
                            'movefid' => $this->movefollowup['fid'],
                            'prev' => 0
                              ),null,true);?>">Hier einfügen</a>
           <?php endif; ?>
                <a href="<?php echo $this->url(array(
                            'action' => 'create-snippet',
                            'kid' => $this->consultation['kid'],
                            'ffid' => $this->ffid,
                            'prev' => 0                      
                              ));?>">Neu</a>    
         
          </td>
        </tr>
        <?php foreach ($this->followups as $followup): ?>
            <tr>                
                <td>
                    <?php 
                   
                       $popupurl = $this->url(array(
                            'action' => 'reference',
                            'kid' => $this->consultation['kid'],
                            'fid' => $followup['fid'],
                            'ffid' => $this->ffid
                              ));
                       
                       echo $this->Popuplink( $popupurl, 'Follow-up Referenzen zuweisen', 1100, 600, $followup['relFowupCount'], 'Referenzen bearbeiten' ); ?>
                    <br />
                    <?php if($followup['hlvl'] < 6): ?>
                    <a href="<?php echo $this->url(array(
                            'action' => 'hierarchy',
                            'kid' => $this->consultation['kid'],
                            'fid' => $followup['fid'],
                            'ffid' => $this->ffid,
                            'hlvl' => $followup['hlvl'] + 1
                              ));?>" title="Level up">&raquo;</a><br/>
                    <?php endif; ?>
                    <?php if ($followup['hlvl'] > 1): ?>
                    <a href="<?php echo $this->url(array(
                            'action' => 'hierarchy',
                            'kid' => $this->consultation['kid'],
                            'fid' => $followup['fid'],
                            'ffid' => $this->ffid,
                            'hlvl' => $followup['hlvl'] - 1
                              ));?>" title="Level down">&laquo;</a>
                    <?php endif; ?>
                    
                </td>
                <td><?php echo substr(strip_tags(html_entity_decode($followup['expl'])), 0, 400).'...'; ?></td>
                <td><?php echo $followup['lkyea']; ?></td>
                <td><?php echo $followup['lknay']; ?></td>
                
                <td style="text-align: right;"><a href="<?php echo $this->url(array(
                            'action' => 'edit-snippet',
                            'kid' => $this->consultation['kid'],
                            'fid' => $followup['fid'],
                            'ffid' => $this->ffid
                              ));?>" title="Follow-up bearbeiten">Bearbeiten</a>
                              &nbsp;
                    <a href="<?php echo $this->url(array(
                            'action' => 'delete-snippet',
                            'kid' => $this->consultation['kid'],
                            'fid' => $followup['fid'],
                            'ffid' => $this->ffid    
                            ));?>" title="Follow-up löschen">Löschen</a>
                              &nbsp;
                    <a href="<?php echo $this->url(array(
                            'module' => 'admin',
                            'controller' => 'followup',
                            'action' => 'move',
                            'kid' => $this->consultation['kid'],
                            'fid' => $followup['fid'],
                            'ffid' => $this->ffid                           
                            ),null, true);?>" title="Artikel löschen">Verschieben</a>
                </td>

            </tr>
            <tr>
                <td colspan="5">
                <?php if($this->movefollowup && $this->movefollowup['fid'] != $followup['fid'] && $followup['docorg'] != $this->movefollowup['docorg']-1): ?>
                    <a href="<?php echo $this->url(array(
                              'module' => 'admin',
                              'controller' => 'followup',
                              'action' => 'move',
                              'kid' => $this->consultation['kid'],
                              'ffid' => $this->ffid,
                              'movefid' => $this->movefollowup['fid'],
                              'prev' => $followup['docorg']
                                ),null,true);?>">Hier einfügen</a>
                <?php endif; ?>
                    <a href="<?php echo $this->url(array(
                              'action' => 'create-snippet',
                              'kid' => $this->consultation['kid'],
                              'ffid' => $this->ffid,
                              'prev' => $followup['docorg']
                                ));?>">Neu</a>
         
                </td>
            </tr>
        <?php endforeach; ?>        
    </tbody>
</table>
