<section class="section-header has-tabs">
    <div class="container">

        <h1 class="section-header-title"><?=$this->escape($this->consultation['titl']);?></h1>
        <h2 class="section-header-subtitle"><?=$this->escape($this->consultation['titl_sub']);?></h2>

        <?=$this->consultationTabs($this->consultation['kid'], 'consultation');?>

    </div>
</section>
<section class="section-content">
    <div class="container">
        <div class="row">
            <div class="sidebar">

                <?=$this->consultationNavigation($this->consultation, 'followup');?>

            </div>
            <div class="content">

                <a href="<?=$this->url(['action' => 'index', 'ffid' => null]);?>" class="back"><?=$this->translate('Back to Follow-ups');?></a>

                <h2><?=$this->pageTitle;?></h2>
                <?=$this->form;?>

            </div>
        </div>
    </div>
</section>
