<section class="section-header has-tabs">
    <div class="container">

        <h1><?=$this->consultation['titl'];?></h1>
        <h2><?=$this->consultation['titl_sub'];?></h2>

        <?=$this->consultationTabs($this->consultation['kid'], 'consultation');?>

    </div>
</section>
<section class="section-content">
    <div class="container">
        <div class="row">
            <div class="col-md-3">

                <?=$this->consultationNavigation($this->consultation['kid'], 'followup');?>

            </div>
            <div class="col-md-9">

                <h2><?=$this->pageTitle;?></h2>
                <p class="back-link">
                    <a href="<?=$this->url(['action' => 'index', 'ffid' => null]);?>">
                        &larr; <?=$this->translate('Back to Followups');?>
                    </a>
                </p>
                <?=$this->form;?>

            </div>
        </div>
    </div>
</section>
