<section class="section-header has-tabs">
    <div class="container">

        <h1><?=$this->escape($this->consultation['titl']);?></h1>
        <h2><?=$this->escape($this->consultation['titl_sub']);?></h2>

        <?=$this->consultationTabs($this->consultation['kid'], 'consultation');?>

    </div>
</section>
<section class="section-content">
    <div class="container">
        <div class="row">
            <div class="sidebar">

                <?=$this->consultationNavigation($this->consultation['kid'], 'followup');?>

            </div>
            <div class="content">

                <a href="<?=$this->url(['action' => 'create-followup']);?>" class="btn btn-default pull-right">
                    <span class="glyphicon glyphicon-plus-sign"></span>
                    <?=$this->translate('New Follow-up');?>
                </a>
                <h2><?=$this->translate('Follow-up');?></h2>

                <?php if (!count($this->followupFiles)): ?>
                    <p class="alert alert-info">
                        <span class="glyphicon glyphicon-info-sign"></span>
                        <?=$this->translate('There are no follow-ups yet.');?>
                    </p>
                <?php else: ?>

                    <form method="<?=$this->form->getMethod();?>" action="<?=$this->url(['action' => 'delete-followup']);?>">
                        <?=$this->form->getElement($this->form->getCsrfTokenName());?>
                        <table class="table">
                            <thead>
                                <tr>
                                    <th class="table-cell-id" data-toggle="sort" tabindex="0">#</th>
                                    <th data-toggle="sort" tabindex="0" class="sorting-desc"><?=$this->translate('Time Added');?></th>
                                    <th data-toggle="sort" tabindex="0"><?=$this->translate('Stakeholder');?></th>
                                    <th data-toggle="sort" tabindex="0"><?=$this->translate('Title');?></th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach ($this->followupFiles as $followupFile): ?>
                                    <tr>
                                        <td class="table-cell-id"><?=$this->escape($followupFile['ffid']);?></td>
                                        <td data-sort-value="<?=$followupFile['when'];?>">
                                            <?=$this->formatDate($followupFile['when']);?>
                                        </td>
                                        <td><?=$this->escape($followupFile['who']);?></td>
                                        <td><?=$this->escape($followupFile['titl']);?></td>
                                        <td class="table-cell-actions">
                                            <a
                                                href="<?=$this->url(['action' => 'edit-followup', 'ffid' => $followupFile['ffid']]);?>"
                                                class="item-action"
                                                title="<?=$this->translate('Edit follow-up');?>"
                                            >
                                                <span class="glyphicon glyphicon-pencil"></span>
                                            </a>
                                            <a
                                                href="<?=$this->url(['action' => 'snippets', 'ffid' => $followupFile['ffid']]);?>"
                                                class="item-action"
                                                title="<?=$this->translate('Edit snippets');?>"
                                            >
                                                <span class="glyphicon glyphicon-th-list"></span>
                                            </a>
                                            <button
                                                value="<?=$this->escape($followupFile['ffid']);?>"
                                                class="item-action item-action-danger"
                                                name="delete"
                                                data-toggle="confirm"
                                                data-confirm-message="<?=$this->translate('Delete follow-up?');?>"
                                                title="<?=$this->translate('Delete follow-up');?>"
                                            >
                                                <span class="glyphicon glyphicon-trash"></span>
                                            </button>
                                        </td>
                                    </tr>
                                <?php endforeach;?>
                            </tbody>
                        </table>
                    </form>

                <?php endif; ?>

            </div>
        </div>
    </div>
</section>
