<section class="section-header has-tabs">
    <div class="container">

        <h1><?=$this->consultation['titl'];?></h1>
        <h2><?=$this->consultation['titl_sub'];?></h2>

        <?=$this->consultationTabs($this->consultation['kid'], 'consultation');?>

    </div>
</section>
<section class="section-content">
    <div class="container">
        <div class="row">
            <div class="sidebar">

                <?=$this->consultationNavigation($this->consultation['kid'], 'followup');?>

            </div>
            <div class="content">

                <a href="<?=$this->url(['action' => 'create-followup']);?>" class="btn btn-default pull-right">
                    <span class="glyphicon glyphicon-plus-sign"></span>
                    <?=$this->translate('New Followup');?>
                </a>
                <h2><?=$this->translate('Followup');?></h2>

                <table class="table" data-view="table">
                    <thead>
                        <tr>
                            <th data-toggle="sort" data-order="default desc" tabindex="0"><?=$this->translate('Time Added');?></th>
                            <th data-toggle="sort" tabindex="0"><?=$this->translate('Stakeholder');?></th>
                            <th data-toggle="sort" tabindex="0"><?=$this->translate('Title');?></th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->followupFiles as $followupFile): ?>
                            <tr>
                                <td><?php $zendDate = new Zend_Date($followupFile['when']); echo $zendDate->get(Zend_Date::DATETIME_MEDIUM); ?></td>
                                <td><?=$followupFile['who'];?></td>
                                <td><?=$followupFile['titl'];?></td>
                                <td class="table-cell-actions">
                                    <a
                                        href="<?=$this->url(['action' => 'snippets', 'ffid' => $followupFile['ffid']]);?>"
                                        class="item-action"
                                    >
                                        <span class="glyphicon glyphicon-random"></span>
                                    </a>
                                    <a
                                        href="<?=$this->url(['action' => 'edit-followup', 'ffid' => $followupFile['ffid']]);?>"
                                        class="item-action"
                                    >
                                        <span class="glyphicon glyphicon-pencil"></span>
                                    </a>
                                    <a
                                        href="<?=$this->url(['action' => 'delete-followup', 'ffid' => $followupFile['ffid']]);?>"
                                        class="item-action item-action-danger"
                                    >
                                        <span class="glyphicon glyphicon-trash"></span>
                                    </a>
                                </td>
                            </tr>
                        <?php endforeach;?>
                    </tbody>
                </table>

            </div>
        </div>
    </div>
</section>
