<?php
/**
 *  index.phtml
 * 
 *  @description   Followup-File Overview
 *  @author        Marco Dinnbier
 */
?>
<h1><?php echo $this->consultation['titl']; ?></h1>
<?php echo $this->consultationNavigation('Follow-up'); ?>
<h2>Übersicht der Follow-up-Dokumente</h2>
<p><a href="<?php echo $this->url(array(
  'action' => 'create-file',
  'kid' => isset($this->consultation) ? $this->consultation['kid'] : 0
));?>">Neues Follow-up-Dokument</a></p>
<table style="width: 100%">
    <tbody>
        <tr>
            <th>Datum</th>
            <th>Akteur_in</th>
            <th>Titel</th>
            <th>Aktionen</th>
        </tr>
        <?php foreach ($this->followupFiles as $followupFile): ?>
            <tr>
                
                <td><?php $zendDate = new Zend_Date($followupFile['when']); echo $zendDate->get('dd.MM.yy'); ?></td>
                <td><?php echo $followupFile['who']; ?></td>
                <td><?php echo $followupFile['titl']; ?></td>
                <td><a href="<?php echo $this->url(array(
                            'action' => 'edit-file',
                            'kid' => $this->consultation['kid'],
                            'ffid' => $followupFile['ffid']
                              ));?>">Bearbeiten</a>
                              &nbsp;
                    <a href="<?php echo $this->url(array(
                            'action' => 'delete-file',
                            'kid' => $this->consultation['kid'],
                            'ffid' => $followupFile['ffid']
                            ));?>" title="Löschen">Löschen</a>
                </td>

            </tr>
        <?php endforeach; ?>        
    </tbody>
</table>
