<section class="section-header has-tabs">
    <div class="container">

        <h1 class="section-header-title"><?=$this->escape($this->consultation['titl']);?></h1>
        <h2 class="section-header-subtitle"><?=$this->escape($this->consultation['titl_sub']);?></h2>

        <?=$this->consultationTabs($this->consultation['kid'], 'consultation');?>

    </div>
</section>
<section class="section-content">
    <div class="container">
        <div class="row">
            <div class="sidebar">

                <?=$this->consultationNavigation($this->consultation, 'followup');?>

            </div>
            <div class="content">

                <a href="<?=$this->url(['action' => 'snippets']);?>" class="back">
                    <?=$this->translate('Back to Snippets');?>
                </a>

                <h2><?=$this->translate('Snippet Links');?></h2>

                <!-- Collapsible panels -->
                <?php if (count($this->questions)): ?>
                    <form method="post" class="offset-bottom-large">
                        <div class="row">
                            <div class="col-sm-8">
                                <h3 class="offset-bottom">
                                    <?=$this->translate('Contributions');?>
                                    <span class="badge"><?=isset($this->related['inputs']) ? count($this->related['inputs']) : '0';?></span>
                                </h3>
                            </div>
                            <div class="col-sm-4">
                                <div class="form-group text-right">
                                    <input name="link_inputs" type="submit" class="btn btn-default" value="<?=$this->translate('Save contribution links');?>" />
                                </div>
                            </div>
                        </div>
                        <div class="panel-group" id="accordionContributions" role="tablist" aria-multiselectable="true">

                            <?php $i = 0; ?>
                            <?php foreach ($this->questions as $question): ?>
                                <div class="panel panel-default">
                                    <div class="panel-heading" role="tab" id="headingContributions<?=$i;?>">
                                        <a data-toggle="collapse" data-parent="#accordionContributions" href="#collapseContributions<?=$i;?>" aria-controls="collapseContributions<?=$i;?>">
                                            <h4 class="panel-title">
                                                <span class="pull-right glyphicon glyphicon-chevron-down" aria-hidden="true"></span>
                                                <?=$this->escape($question['q']);?>
                                            </h4>
                                        </a>
                                    </div>
                                    <div id="collapseContributions<?=$i;?>" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingContributions<?=$i;?>">
                                        <div class="panel-body">
                                            <?php if (count($question['inputs'])): ?>
                                                <table class="table js-table-rows-toggle">
                                                    <tbody>
                                                        <?php foreach ($question['inputs'] as $input): ?>
                                                            <tr<?=!empty($this->related['inputs'][$input->tid]) ? ' class="info"' : '';?>>
                                                                <td class="table-cell-id table-cell-top">
                                                                    <input
                                                                        type="checkbox"
                                                                        name="input_links[]"
                                                                        value="<?=$this->escape($input->tid);?>"
                                                                        <?=!empty($this->related['inputs'][$input->tid]) ? 'checked' : '';?>
                                                                    />
                                                                </td>
                                                                <td class="table-cell-top"><?=$this->escape($input->thes);?></td>
                                                                <td class="col-xs-1 table-cell-top">
                                                                    <?=$this->translate('Voting');?><br />
                                                                    <?php if ($input['vot'] === 'y'): ?>
                                                                        <span class="label label-success">
                                                                            <span class="glyphicon glyphicon-ok"></span>
                                                                            <?=$this->translate('Yes');?>
                                                                         </span>
                                                                    <?php elseif ($input['vot'] === 'n'): ?>
                                                                        <span class="label label-danger">
                                                                            <span class="glyphicon glyphicon-remove"></span>
                                                                            <?=$this->translate('No');?>
                                                                        </span>
                                                                    <?php else: ?>
                                                                        <span class="label label-default">
                                                                             <span class="glyphicon glyphicon-question-sign"></span>
                                                                            <?=$this->translate('Unknown');?>
                                                                        </span>
                                                                    <?php endif; ?>
                                                                </td>
                                                            </tr>
                                                        <?php endforeach; ?>
                                                    </tbody>
                                                </table>
                                            <?php else: ?>
                                                <p class="alert alert-info">
                                                    <span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>
                                                    <?=$this->translate('There are no contributions for this question yet.');?>
                                                </p>
                                            <?php endif; ?>
                                        </div>
                                    </div><!-- .panel-collapse -->
                                </div><!-- .panel -->
                                <?php $i++; ?>
                            <?php endforeach; ?>

                        </div><!-- .panel-group -->
                        <div class="form-group text-right">
                            <input name="link_inputs" type="submit" class="btn btn-default" value="<?=$this->translate('Save contribution links');?>" />
                        </div>
                    </form>
                <?php else: ?>
                    <p class="alert alert-info">
                        <span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>
                        <?=$this->translate('There are no questions for this consultation yet.');?>
                    </p>
                <?php endif; ?>

                <!-- Collapsible panels -->
                <?php if (count($this->followups)): ?>
                    <form method="post" class="offset-bottom-large">
                        <div class="row">
                            <div class="col-sm-8">
                                <h3 class="offset-bottom">
                                    <?=$this->translate('Follow-Up Snippets');?>
                                    <span class="badge"><?=isset($this->related['snippets']) ? count($this->related['snippets']) : '0';?></span>
                                </h3>
                            </div>
                            <div class="col-sm-4">
                                <div class="form-group text-right">
                                    <input name="link_snippets" type="submit" class="btn btn-default" value="<?=$this->translate('Save snippet links');?>" />
                                </div>
                            </div>
                        </div>

                        <div class="panel-group" id="accordionSnippets" role="tablist" aria-multiselectable="true">

                            <?php $i = 0; ?>
                            <?php foreach ($this->followups as $followup): ?>
                                <div class="panel panel-default">
                                    <div class="panel-heading" role="tab" id="headingSnippets<?=$i;?>">
                                        <a data-toggle="collapse" data-parent="#accordionSnippets" href="#collapseSnippets<?=$i;?>" aria-controls="collapseSnippets<?=$i;?>">
                                            <h4 class="panel-title">
                                                <span class="pull-right glyphicon glyphicon-chevron-down" aria-hidden="true"></span>
                                                <?=$this->escape($followup['titl']);?>
                                            </h4>
                                        </a>
                                    </div>
                                    <div id="collapseSnippets<?=$i;?>" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingSnippets<?=$i;?>">
                                        <div class="panel-body">

                                            <?php if (count($followup['snippets'])): ?>
                                                <table class="table js-table-rows-toggle">
                                                    <tbody>
                                                        <?php foreach ($followup['snippets'] as $snippet): ?>
                                                            <tr<?=!empty($this->related['snippets'][$snippet->fid]) ? ' class="info"' : '';?>>
                                                                <td class="table-cell-id table-cell-top">
                                                                    <input
                                                                        type="checkbox"
                                                                        name="snippet_links[]"
                                                                        value="<?=$this->escape($snippet->fid);?>"
                                                                        <?=!empty($this->related['snippets'][$snippet->fid]) ? 'checked' : '';?>
                                                                    />
                                                                </td>
                                                                <td class="table-cell-top">
                                                                    <?=strip_tags(html_entity_decode($snippet['expl']));?>
                                                                </td>
                                                            </tr>
                                                        <?php endforeach; ?>
                                                    </tbody>
                                                </table>
                                            <?php else: ?>
                                                <p class="alert alert-info">
                                                    <span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>
                                                    <?=$this->translate('There are no snippets for this follow-up yet.');?>
                                                </p>
                                            <?php endif; ?>

                                        </div>
                                    </div><!-- .panel-collapse -->
                                </div><!-- .panel -->
                                <?php $i++; ?>
                            <?php endforeach; ?>

                        </div><!-- .panel-group -->
                        <div class="form-group text-right">
                            <input name="link_snippets" type="submit" class="btn btn-default" value="<?=$this->translate('Save snippet links');?>" />
                        </div>
                    </form>
                <?php else: ?>
                    <p class="alert alert-info">
                        <span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>
                        <?=$this->translate('There are no follow-ups for this consultation yet.');?>
                    </p>
                <?php endif; ?>

                <h3>
                    <?=$this->translate('Follow-Ups');?>
                    <span class="badge"><?=isset($this->related['followups']) ? count($this->related['followups']) : '0';?></span>
                </h3>
                <?php if (count($this->followups)): ?>
                    <form method="post">
                        <div class="form-group text-right">
                            <input name="link_followups" type="submit" class="btn btn-default" value="<?=$this->translate('Save follow-up links');?>" />
                        </div>
                        <table class="table table-bordered js-table-rows-toggle">
                            <tbody>
                                <?php foreach ($this->followups as $followupId => $followup): ?>
                                    <?php if ($followupId != $this->followupId): ?>
                                        <tr<?=!empty($this->related['followups'][$followupId]) ? ' class="info"' : '';?>>
                                            <td class="table-cell-id table-cell-top">
                                                <input
                                                    type="checkbox"
                                                    name="followup_links[]"
                                                    value="<?=$this->escape($followupId);?>"
                                                    <?=!empty($this->related['followups'][$followupId]) ? 'checked' : '';?>
                                                />
                                            </td>
                                            <td class="table-cell-top">
                                                <?=$this->escape($followup['titl']);?>
                                            </td>
                                        </tr>
                                    <?php endif; ?>
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                        <div class="form-group text-right">
                            <input name="link_followups" type="submit" class="btn btn-default" value="<?=$this->translate('Save follow-up links');?>" />
                        </div>
                    </form>
                <?php else: ?>
                    <p class="alert alert-info">
                        <span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>
                        <?=$this->translate('There are no follow-ups for this consultation yet.');?>
                    </p>
                <?php endif; ?>

            </div>
        </div>
    </div>
</section>
