<div class="main-content">
    <div class="row">
        <div class="content">

            <h1><?=Model_HelpText::getTranslatedName($this->helpText->name);?></h1>
            <?php // Do not escape as the script tag has been stripped in controller and we need other tags ;?>
            <?=$this->helpText->body;?>

        </div>
    </div><!-- .row -->

    <?=$this->partial('_partials/pageLinks.phtml');?>

</div>
