<?php
/**
 * Consultation overview
 *
 */
?>

<div class="content-holder main-content">

	<h1>Alle Konsultationen im Überblick</h1>

<?php echo $this->render('_consultationPreview.phtml'); ?>

	<!-- Print -->
	<a href="javascript:print();" class="print">Seite drucken <i class="icon-print"></i></a>
</div><!-- .content-holder -->

<!-- Content end -->

<!-- Top link -->
<div class="top-link">
	<a href="#top" class="js-scroll"><i class="icon-angle-up icon-large"></i> nach oben</a>
</div>
