paths:
    migrations: '%%PHINX_CONFIG_DIR%%/../../data/phinx-migrations'
    seeds: '%%PHINX_CONFIG_DIR%%/../../data/phinx-migrations/seeds'

environments:
    default_migration_table: phinxlog
    # these credentials has to be stored even in config.local.ini
    production:
        adapter: mysql
        host: db
        name: dbjr
        user: root
        pass: pass
        port: 3306
        charset: utf8

    test:
        adapter: mysql
        host: db
        name: dbjr_test
        user: root
        pass: pass
        port: 3306
        charset: utf8
