<div class="dropdown hidden-print">
    <button type="button" id="loginDropdown" class="btn btn-default btn-sm btn-block text-left" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <?=$this->translate('Login');?>
    </button>
    <div class="dropdown-menu dropdown-menu-right dropdown-menu-combo" role="menu" aria-labelledby="loginDropdown">
        <h3 id="loginLabel" class="dropdown-title"><?=$this->translate('Login');?></h3>

        <?=$this->form;?>

        <?php if ($this->webserviceLoginCsrf): ?>
            <input type="hidden" value="<?=$this->webserviceLoginCsrf;?>" id="webserviceLoginCsrf" />
        <?php endif;?>

        <?php if (Zend_Registry::get('systemconfig')->webservice->google->clientId): ?>
            <span id="signinButton">
                <span
                    class="g-signin"
                    data-callback="googleSignInCallback"
                    data-clientid="<?=Zend_Registry::get('systemconfig')->webservice->google->clientId;?>"
                    data-cookiepolicy="single_host_origin"
                    data-scope="profile email">
                </span>
            </span>
        <?php endif;?>

        <?php if (Zend_Registry::get('systemconfig')->webservice->facebook->appId): ?>
            <div id="fb-root"></div>
            <script>
                (function(d, s, id) {
                    var js, fjs = d.getElementsByTagName(s)[0];
                    if (d.getElementById(id)) return;
                    js = d.createElement(s); js.id = id;
                    js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&appId=<?=Zend_Registry::get('systemconfig')->webservice->facebook->appId;?>&version=v2.0";
                    fjs.parentNode.insertBefore(js, fjs);
                }(document, 'script', 'facebook-jssdk'));</script>
            <div
                class="fb-login-button"
                data-max-rows="1"
                data-size="large"
                data-show-faces="false"
                data-auto-logout-link="false"
                data-onlogin="facebookSignInCallback"
            ></div>
        <?php endif;?>

        <hr class="divider" />
        <a href="<?=$this->url(['controller' => 'user', 'action' => 'passwordrecover'], 'default', true);?>">
            <?=$this->translate('Forgot password?');?>
        </a>
    </div>
</div>
