<?php for ($i = 0, $size = count($this->partners); $i < $size; ++$i): ?>
    <div class="col-sm-4">
        <p><?=$this->escape($this->partners[$i]->description);?></p>
        <p>
            <?php if ($this->partners[$i]->image): ?>
                <a
                    href="<?=$this->escape($this->partners[$i]->link_url);?>"
                    rel="external"
                    target="_blank"
                    title="<?=$this->escape($this->partners[$i]->name);?>"
                >
                    <img
                        src="<?=$this->baseUrl('media/' . $this->partners[$i]->image);?>"
                        alt="<?=$this->escape($this->partners[$i]->name);?>"
                    />
                </a>
            <?php endif;?>
        </p>
    </div>
<?php endfor;?>
