<div class="row">
    <div class="col-xs-10 col-sm-9">

        <!-- User name -->
        <div class="smaller text-right">
            <?php if (empty($this->user->name)): ?>
                <strong><?=$this->user->name;?></strong><br />
            <?php else: ?>
                <?=$this->translate('Logged in as');?><br />
            <?php endif; ?>
            <a href="mailto:<?=$this->user->email;?>"><?=$this->user->email;?></a>
        </div>

    </div>
    <div class="col-xs-2 col-sm-3">

        <!-- User menu -->
        <div class="dropdown pull-right">
            <button type="button" id="userDropdown" class="btn btn-primary btn-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="icon-sm glyphicon glyphicon-menu-down" aria-hidden="true"></span>
            </button>
            <ul class="dropdown-menu dropdown-menu-right" role="menu" aria-labelledby="userDropdown">
                <li>
                    <a href="<?=$this->url(['controller' => 'user', 'action' => 'inputlist'], 'default', true);?>">
                        <span class="glyphicon glyphicon-list-alt icon-offset" aria-hidden="true"></span>
                        <?=$this->translate('View all my contributions');?>
                    </a>
                </li>
                <li>
                    <a href="<?=$this->url(['controller' => 'user', 'action' => 'userlist'], 'default', true);?>">
                        <span class="glyphicon glyphicon-user icon-offset" aria-hidden="true"></span>
                        <?=$this->translate('View group members');?>
                    </a>
                </li>
                <?php if ($this->user->lvl == 'adm' || $this->user->lvl == 'edt'): ?>
                    <li>
                        <a href="<?=$this->url(['module' => 'admin', 'controller' => 'index'], 'default', true);?>" target="_blank">
                            <span class="glyphicon glyphicon-cog icon-offset" aria-hidden="true"></span>
                            <?=$this->translate('To admin pages');?>
                        </a>
                    </li>
                <?php endif; ?>
                <li class="divider"></li>
                <li>
                    <a href="<?=$this->url(['controller' => 'user', 'action' => 'logout'], 'default', true);?>">
                        <span class="glyphicon glyphicon-off icon-offset" aria-hidden="true"></span>
                        <?=$this->translate('Logout');?>
                    </a>
                </li>
            </ul>
        </div>

    </div>
</div><!-- .row -->
