<section class="section-header has-tabs">
    <div class="container">
        <h1><?=$this->translate('New Email');?></h1>
        <?=$this->emailTabs('emailing');?>
    </div>
</section>
<section class="section-content">
    <div class="container">

        <p class="back-link">
            <a href="<?=$this->url(array('controller' => 'mail-sent', 'action' => 'index'));?>">&larr; <?=$this->translate('Back to Sent Emails');?></a>
        </p>
        <h3><?=$this->translate('Templates');?></h3>
        <select class="js-template-selector">
            <option value="0">--<?=$this->translate('Select');?>--</option>
            <?php foreach ($this->templates as $template): ?>
                <option value="<?php echo $template->id?>"><?php echo $template->name?></option>
            <?php endforeach ?>
        </select>

        <h3><?=$this->translate('Email');?></h3>
        <?php echo $this->form?>

        <h3><?=$this->translate('Placeholders');?></h3>
        <dl>
            <?php foreach ($this->placeholders as $placeholder): ?>
                <dt><?php echo Dbjr_Mail::TOKEN_OPEN . $placeholder->name . Dbjr_Mail::TOKEN_CLOSE?></dt>
                <dd><?php echo $placeholder->description?></dd>
            <?php endforeach?>
        </dl>

        <h3><?=$this->translate('Components');?></h3>
        <dl>
            <?php foreach ($this->components as $component): ?>
                <dt><?php echo Dbjr_Mail::TOKEN_OPEN . $component->name . Dbjr_Mail::TOKEN_CLOSE?></dt>
                <dd><?php echo $component->description?></dd>
            <?php endforeach?>
        </dl>

        <p>
            <?=$this->translate('or');?>
            <a href="<?=$this->url(array('controller' => 'mail-sent', 'action' => 'index'));?>"><?=$this->translate('Cancel');?></a>
        </p>

    </div>
</section>
