<section class="section-header has-tabs">
    <div class="container">
        <h1 class="section-header-title"><?=$this->translate('New Email');?></h1>
        <?=$this->emailTabs('emailing');?>
    </div>
</section>
<section class="section-content">
    <div class="container">

        <a href="<?=$this->url(['controller' => 'mail-sent', 'action' => 'index']);?>" class="back">
            <?=$this->translate('Back to Sent Emails');?>
        </a>

        <h3><?=$this->translate('Create from template');?></h3>
        <select class="form-control js-template-selector">
            <option value="0"><?=$this->translate('Please select…');?></option>
            <?php foreach ($this->templates as $template): ?>
                <option value="<?=$this->escape($template->id);?>"><?=$this->escape($template->name);?></option>
            <?php endforeach; ?>
        </select>

        <h3><?=$this->translate('Email');?></h3>
        <?=$this->form;?>
        <?=$this->partial('_partials/mail-replacable-tokens.phtml', [
            'placeholders' => $this->placeholders,
            'components' => $this->components,
        ]);?>

    </div>
</section>
