<section class="section-header">
    <div class="container">

        <h1 class="section-header-title"><?=$this->escape($this->consultation['titl']);?></h1>
        <h2 class="section-header-subtitle"><?=$this->escape($this->consultation['titl_sub']);?></h2>

        <?=$this->consultationTabs($this->consultation['kid'], 'consultation');?>

    </div>
</section>
<section class="section-content">
    <div class="container">
        <div class="row">
            <div class="sidebar offset-bottom-large-sm-max">

                <?=$this->consultationNavigation($this->consultation, 'voting-permissions');?>

            </div>
            <div class="content">

                <a href="<?=$this->url(['action' => 'index']);?>" class="back"><?=$this->translate('Back to Voting Permissions');?></a>
                <h2>
                    <?=$this->translate('New Permission');?>
                </h2>

                <?php if ($this->usersWithoutRights > 0): ?>
                    <?=$this->form;?>
                <?php else: ?>
                    <p class="alert alert-info">
                        <?=$this->translate('There are no users without voting permissions.');?>
                        <a href="<?=$this->url(['controller' => 'user', 'action' => 'create']);?>">
                            <?=$this->translate('Create a new user');?>
                        </a>
                    </p>
                <?php endif; ?>
            </div>
        </div>
    </div>
</section>
