<section class="section-header">
    <div class="container">

        <h1 class="section-header-title"><?=$this->escape($this->consultation['titl']);?></h1>
        <h2 class="section-header-subtitle"><?=$this->escape($this->consultation['titl_sub']);?></h2>

        <?=$this->consultationTabs($this->consultation['kid'], 'consultation');?>

    </div>
</section>
<section class="section-content">
    <div class="container">
        <div class="row">
            <div class="sidebar offset-bottom-large-sm-max">

                <?=$this->consultationNavigation($this->consultation, 'voting-permissions');?>

            </div>
            <div class="content">

                <a href="<?=$this->url(['action' => 'index', 'uid' => null]);?>" class="back"><?=$this->translate('Back to Voting Permissions');?></a>
                <h2>
                    <?=$this->translate('Voting Permissions for');?>
                    <?=$this->escape($this->user['email']);?>
                </h2>
                <?=$this->form;?>

            </div>
        </div>
    </div>
</section>
