<section class="section-header has-tabs">
    <div class="container">

        <h1><?=$this->consultation['titl'];?></h1>
        <h2><?=$this->consultation['titl_sub'];?></h2>

        <?=$this->consultationTabs($this->consultation['kid'], 'consultation');?>

    </div>
</section>
<section class="section-content">
    <div class="container">
        <div class="row">
            <div class="col-md-3">

                <?=$this->consultationNavigation('voting-permissions');?>

            </div>
            <div class="col-md-9">

                <h2>Voting Permissions for <?=$this->user['email'];?></h2>
                <?=$this->form;?>
                <p>
                    or
                    <a href="<?=$this->url(array('action' => 'index', 'uid' => null));?>">Cancel</a>
                </p>

            </div>
        </div>
    </div>
</section>
