<section class="section-header">
    <div class="container">

        <?=$this->helpText('help-text-admin-consultation-voting-permissions');?>

        <h1 class="section-header-title"><?=$this->escape($this->consultation['titl']);?></h1>
        <h2 class="section-header-subtitle"><?=$this->escape($this->consultation['titl_sub']);?></h2>

        <?=$this->consultationTabs($this->consultation['kid'], 'consultation');?>

    </div>
</section>
<section class="section-content">
    <div class="container">
        <div class="row">
            <div class="sidebar offset-bottom-large-sm-max">

                <?=$this->consultationNavigation($this->consultation, 'voting-permissions');?>

            </div>
            <div class="content">

                <a class="btn btn-default cta" href="<?=$this->url(['action' => 'create-rights'])?>">
                    <span class="glyphicon glyphicon-plus-sign icon-shift-down offset-right" aria-hidden="true"></span>
                    <?=$this->translate('New Permission');?>
                </a>

                <?php if (!empty($this->votingRights)): ?>
                    <a
                        href="mailto:<?=$this->mailDefaultFrom;?>?bcc=<?=implode(';', array_filter(
                            array_map(function ($participant) {
                                return !empty($participant['email']) ? $participant['email'] : null;
                            }, $this->votingRights)
                        ));?>"
                        class="btn btn-default cta offset-right"
                    >
                        <span class="glyphicon glyphicon-pencil offset-right" aria-hidden="true"></span>
                        <?=$this->translate('Send an email to all');?>
                    </a>
                <?php endif;?>

                <h2><?=$this->translate('Voting Permissions');?></h2>

                <?php if ($this->countInserted): ?>
                    <p class="alert alert-info">
                        <span class="glyphicon glyphicon-info-sign icon-shift-down offset-right" aria-hidden="true"></span>
                        <strong><?=$this->countInserted;?></strong> <?=$this->translate('new users added recently.');?>
                    </p>
                <?php endif; ?>

                <?php if (!empty($this->votingRights)): ?>
                    <form method="<?=$this->listControlForm->getMethod();?>">
                        <?=$this->listControlForm->getElement($this->listControlForm->getCsrfTokenName());?>
                        <div class="table-responsive table-responsive-dropdowns">
                            <table class="table table-extra-condensed">
                                <thead>
                                    <tr>
                                        <th class="table-cell-id" data-toggle="sort" tabindex="0">#</th>
                                        <th class="sorting-asc" data-toggle="sort" tabindex="0"><?=$this->translate('User');?></th>
                                        <th data-toggle="sort" tabindex="0"><?=$this->translate('Voting Weight');?></th>
                                        <th data-toggle="sort" tabindex="0"><?=$this->translate('Access Code');?></th>
                                        <th data-toggle="sort" tabindex="0"><?=$this->translate('Accepted Size');?></th>
                                        <th data-toggle="sort" tabindex="0"><?=$this->translate('Stated Size');?></th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach ($this->votingRights as $user): ?>
                                        <tr>
                                            <td class="table-cell-id"><?=$this->escape($user['uid']);?></td>
                                            <td>
                                                <?php if ($user['name']): ?>
                                                    <?=$this->escape($user['name']);?>
                                                <?php elseif ($user['name_group']): ?>
                                                    <?=$this->escape($user['name_group']);?>
                                                <?php elseif ($user['name_pers']): ?>
                                                    <?=$this->escape($user['name_pers']);?>
                                                <?php else: ?>
                                                    <?=$this->escape(mb_substr($user['email'], 0, mb_stripos($user['email'], '@')));?>
                                                <?php endif; ?>
                                                <?php if ($user['invitation_sent_date'] !== null): ?>
                                                    <i class="glyphicon glyphicon-ok" style="color: green;" aria-hidden="true"></i>
                                                <?php endif; ?>
                                                <br />
                                                <a href="mailto:<?=$this->escape($user['email']);?>">
                                                    <?=$this->escape($user['email']);?>
                                                </a>
                                            </td>
                                            <td><?=$this->escape($user['vt_weight']);?></td>
                                            <td><?=$this->escape($user['vt_code']);?></td>
                                            <td><?=$this->escape($user['grp_siz']);?></td>
                                            <td><?=$this->escape($user['group_size_user'] ? $user['group_size_user'] : '-');?></td>
                                            <td class="table-cell-actions">
                                                <a
                                                    href="<?=$this->url(['controller' => 'input', 'action' => 'list-by-user', 'uid' => $user['uid']]);?>"
                                                    class="item-action"
                                                    title="<?=$this->translate('Show all contributions by this user');?>"
                                                >
                                                    <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                                                </a>
                                                <a
                                                    href="<?=$this->url(['action' => 'editrights', 'uid' => $user['uid']]);?>"
                                                    class="item-action"
                                                    title="<?=$this->translate('Edit permissions');?>"
                                                >
                                                    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                                                </a>
                                                <?php if (!empty($user['email'])): ?>
                                                    <div class="btn-group">
                                                        <button class="item-action" type="button" id="itemActions<?=$this->escape($user['uid']);?>" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                            <span class="glyphicon glyphicon-option-vertical" aria-hidden="true"></span>
                                                        </button>
                                                        <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="itemActions<?=$this->escape($user['uid']);?>">
                                                            <li>
                                                                <a
                                                                    href="<?=$this->url(['action' => 'sendinvitation', 'uid' => $user['uid'], 'mode' => 'preview']);?>"
                                                                    class="btn btn-dropdown"
                                                                >
                                                                    <span class="glyphicon glyphicon-envelope offset-right" aria-hidden="true"></span>
                                                                    <?=$this->translate('Preview and send invitation');?>
                                                                </a>
                                                            </li>
                                                            <?php if ($user['invitation_sent_date'] !== null): ?>
                                                                <li>
                                                                    <button
                                                                        value="<?=$this->escape($user['uid']);?>"
                                                                        name="instantSendUserId"
                                                                        class="btn btn-dropdown"
                                                                        data-toggle="confirm"
                                                                        data-confirm-message="<?=$this->translate('Do you really want to send invitation to this user again?');?>"
                                                                        data-confirm-yes="<?=$this->translate('Yes');?>"
                                                                        data-confirm-no="<?=$this->translate('No');?>"
                                                                    >
                                                                        <span class="glyphicon glyphicon-send offset-right" aria-hidden="true"></span>
                                                                        <?=sprintf($this->translate('Invitation has been sent at %s'), $this->formatDate($user['invitation_sent_date']));?>
                                                                    </button>
                                                                </li>
                                                            <?php else: ?>
                                                                <li>
                                                                    <button
                                                                        value="<?=$this->escape($user['uid']);?>"
                                                                        name="instantSendUserId"
                                                                        class="btn btn-dropdown"
                                                                        data-toggle="confirm"
                                                                        data-confirm-message="<?=$this->translate('Do you really want to send invitation to this user?');?>"
                                                                        data-confirm-yes="<?=$this->translate('Yes');?>"
                                                                        data-confirm-no="<?=$this->translate('No');?>"
                                                                    >
                                                                        <span class="glyphicon glyphicon-send offset-right" aria-hidden="true"></span>
                                                                        <?=$this->translate('Send invitation');?>
                                                                    </button>
                                                                </li>
                                                            <?php endif; ?>
                                                        </ul>
                                                    </div>

                                                <?php endif; ?>

                                            </td>
                                        </tr>
                                    <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                    </form>
                <?php else: ?>
                    <p class="alert alert-info">
                        <span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>
                        <?=$this->translate('There are no permissions to be set.');?>
                    </p>
                <?php endif; ?>

            </div>
        </div>
    </div>
</section>
