<section class="section-header has-tabs">
    <div class="container">

        <h1><?=$this->escape($this->consultation['titl']);?></h1>
        <h2><?=$this->escape($this->consultation['titl_sub']);?></h2>

        <?=$this->consultationTabs($this->consultation['kid'], 'consultation');?>

    </div>
</section>
<section class="section-content">
    <div class="container">
        <div class="row">
            <div class="sidebar">

                <?=$this->consultationNavigation($this->consultation, 'voting-permissions');?>

            </div>
            <div class="content">

                <h2><?=$this->translate('Voting Permissions');?></h2>

                <?php if ($this->countInserted): ?>
                    <p class="alert alert-info">
                        <span class="glyphicon glyphicon-info-sign"></span>
                        <span class="badge"><?=$this->countInserted;?></span> <?=$this->translate('new users added recently.');?>
                    </p>
                <?php endif; ?>

                <?php if (!empty($this->votingRights)): ?>
                    <table class="table">
                        <thead>
                            <tr>
                                <th class="table-cell-id" data-toggle="sort" tabindex="0">#</th>
                                <th class="sorting-asc" data-toggle="sort" tabindex="0">User</th>
                                <th data-toggle="sort" tabindex="0">Voting Weight</th>
                                <th data-toggle="sort" tabindex="0">Access Code</th>
                                <th data-toggle="sort" tabindex="0">Accepted Size</th>
                                <th data-toggle="sort" tabindex="0">Stated Size</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($this->votingRights as $item): ?>
                                <tr>
                                    <td class="table-cell-id"><?=$this->escape($item['uid']);?></td>
                                    <td>
                                        <a href="mailto:<?=$this->escape($item['email']);?>">
                                            <?=$this->escape($item['email']);?>
                                        </a>
                                    </td>
                                    <td><?=$this->escape($item['vt_weight']);?></td>
                                    <td><?=$this->escape($item['vt_code']);?></td>
                                    <td><?=$this->escape($item['grp_siz']);?></td>
                                    <td><?=$this->escape($item['group_size_user']);?></td>
                                    <td class="table-cell-actions">
                                        <a
                                            href="<?=$this->url(['controller' => 'input', 'action' => 'list-by-user', 'uid' => $item['uid']]);?>"
                                            class="item-action"
                                            title="<?=$this->translate('Show all contributions by this user');?>"
                                            >
                                            <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                                        </a>
                                        <a
                                            href="<?=$this->url(['action' => 'editrights', 'uid' => $item['uid']]);?>"
                                            class="item-action"
                                            title="<?=$this->translate('Edit permissions');?>"
                                            >
                                            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                                        </a>
                                    </td>
                                </tr>
                            <?php endforeach;?>
                        </tbody>
                    </table>
                <?php else: ?>
                    <p class="alert alert-info">
                        <span class="glyphicon glyphicon-info-sign"></span>
                        <?=$this->translate('There are no permissions to be set.');?>
                    </p>
                <?php endif; ?>

            </div>
        </div>
    </div>
</section>
