<section class="section-header">
    <div class="container">

        <?=$this->helpText('help-text-admin-consultation-voting-invitations');?>

        <h1 class="section-header-title"><?=$this->escape($this->consultation['titl']);?></h1>
        <h2 class="section-header-subtitle"><?=$this->escape($this->consultation['titl_sub']);?></h2>

        <?=$this->consultationTabs($this->consultation['kid'], 'consultation');?>

    </div>
</section>

<section class="section-content">
    <div class="container">
        <div class="row">
            <div class="sidebar offset-bottom-large-sm-max">

                <?=$this->consultationNavigation($this->consultation, 'voting-invitations');?>

            </div>
            <div class="content">

                <?php if (!empty($this->participants)): ?>
                    <p>
                        <a
                            href="mailto:<?=$this->mailDefaultFrom;?>?bcc=<?=implode(';', array_filter(
                                array_map(function ($participant) {
                                    return !empty($participant['email']) ? $participant['email'] : null;
                                }, $this->participants)
                            ));?>"
                            class="btn btn-default pull-right"
                        >
                            <span class="glyphicon glyphicon-pencil offset-right" aria-hidden="true"></span>
                            <?=$this->translate('Compose an email for all invited users');?>
                        </a>
                    </p>
                <?php endif;?>

                <h2><?=$this->translate('Voting Invitations');?></h2>

                <?php if (!empty($this->participants)): ?>
                    <?php $grp_siz_def = $this->groupSizes; ?>
                    <form method="<?=$this->listControlForm->getMethod();?>">
                        <?=$this->listControlForm->getElement($this->listControlForm->getCsrfTokenName());?>
                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th class="table-cell-id" data-toggle="sort" tabindex="0">#</th>
                                        <th data-toggle="sort" tabindex="0"><?=$this->translate('User Name');?></th>
                                        <th class="sorting-asc" data-toggle="sort" tabindex="0"><?=$this->translate('Email');?></th>
                                        <th><?=$this->translate('Permissions');?></th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach ($this->participants as $user): ?>
                                        <tr>
                                            <td class="table-cell-id table-cell-top"><?=$this->escape($user['uid']);?></td>
                                            <td class="table-cell-top">
                                                <?php if (!empty($user['name'])): ?>
                                                    <?=$this->escape($user['name']);?>
                                                <?php endif; ?>
                                            </td>
                                            <td class="table-cell-top">
                                                <?php if (!empty($user['email'])): ?>
                                                    <a href="mailto:<?=$this->escape($user['email']);?>">
                                                        <?=$this->escape($user['email']);?>
                                                    </a>
                                                <?php endif; ?>
                                            </td>
                                            <td class="table-cell-top">
                                                <?php if (isset($user['votingRights'])): ?>
                                                    <p>
                                                        <?=$this->translate('Voting weight');?>: <?=$user['votingRights']['vt_weight']; ?><br />
                                                        <?=$this->translate('Group size');?>: <?=$grp_siz_def[$user['votingRights']['grp_siz']]; ?>
                                                    </p>
                                                    <?php if ($grp_siz_def[$user['votingRights']['grp_siz']] != 1): ?>
                                                        <p>
                                                            <?=$this->translate('Partner');?>: <?=$this->escape($user['name_pers']);?><br/>
                                                            <?=$this->translate('Group name');?>: <?=$this->escape($user['name_group']);?><br/>
                                                            <?=$this->translate('Group size');?>: <?=$this->escape($user['group_size']);?>
                                                        </p>
                                                    <?php endif; ?>
                                                <?php endif; ?>
                                            </td>
                                            <td class="table-cell-actions table-cell-top">
                                                <?php if (!empty($user['email'])): ?>
                                                    <a
                                                        href="<?=$this->url(['action' => 'sendinvitation', 'uid' => $user['uid'], 'mode' => 'preview']);?>"
                                                        class="item-action"
                                                        title="<?=$this->translate('Preview and send invitation');?>"
                                                        >
                                                        <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>
                                                    </a>
                                                    <button
                                                        value="<?=$this->escape($user['uid']);?>"
                                                        name="instantSendUserId"
                                                        class="item-action"
                                                        data-toggle="confirm"
                                                        data-confirm-message="<?=$this->translate('Do you really want to send invitation to this user?');?>"
                                                        data-confirm-yes="<?=$this->translate('Yes');?>"
                                                        data-confirm-no="<?=$this->translate('No');?>"
                                                        title="<?=$this->translate('Send invitation');?>"
                                                    >
                                                        <span class="glyphicon glyphicon-send" aria-hidden="true"></span>
                                                    </button>
                                                <?php endif; ?>
                                                <a
                                                    href="<?=$this->url(['controller' => 'input', 'action' => 'list-by-user', 'uid' => $user['uid']]);?>"
                                                    class="item-action"
                                                    title="<?=$this->translate('Show all contributions by this user');?>"
                                                    >
                                                    <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                                                </a>
                                            </td>
                                        </tr>
                                    <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                    </form>
                <?php else: ?>
                    <p class="alert alert-info">
                        <span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>
                        <?=$this->translate('There are no participants to be invited.');?>
                    </p>
                <?php endif; ?>

            </div>
        </div>
    </div>
</section>
