<section class="section-header has-tabs">
    <div class="container">

        <h1><?=$this->consultation['titl'];?></h1>
        <h2><?=$this->consultation['titl_sub'];?></h2>

        <?=$this->consultationTabs($this->consultation['kid'], 'consultation');?>

    </div>
</section>
<section class="section-content">
    <div class="container">
        <div class="row">
            <div class="sidebar">

                <?=$this->consultationNavigation($this->consultation, 'voting-invitations');?>

            </div>
            <div class="content">

                <h2><?=$this->translate('Voting Invitations');?></h2>

                <?php $grp_siz_def = Zend_Registry::get('systemconfig')->group_size_def->toArray(); ?>

                <?php if (!empty($this->emailList)): ?>
                    <p>
                        <a href="mailto:<?=$this->mailDefaultFrom;?>?bcc=<?=$this->emailList;?>">
                            <?=$this->translate('Compose an email for all invited users');?>
                        </a>
                    </p>
                <?php endif; ?>

                <?php if (!empty($this->participants)): ?>
                    <form method="<?=$this->listControlForm->getMethod()?>">
                        <?=$this->listControlForm->getElement($this->listControlForm->getCsrfTokenName());?>
                        <table class="table">
                            <thead>
                                <tr>
                                    <th class="table-cell-id" data-toggle="sort" tabindex="0">#</th>
                                    <th data-toggle="sort" tabindex="0"><?=$this->translate('User Name');?></th>
                                    <th class="sorting-asc" data-toggle="sort" tabindex="0"><?=$this->translate('Email');?></th>
                                    <th><?=$this->translate('Permissions');?></th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach ($this->participants as $user): ?>
                                    <tr>
                                        <td class="table-cell-id table-cell-top"><?=$user['uid'];?></td>
                                        <td class="table-cell-top">
                                            <?php if (!empty($user['name'])): ?>
                                                <?=$this->escape($user['name']);?>
                                            <?php endif?>
                                        </td>
                                        <td class="table-cell-top">
                                            <?php if (!empty($user['email'])): ?>
                                                <a href="mailto:<?=$this->escape($user['email']);?>">
                                                    <?=$this->escape($user['email']);?>
                                                </a>
                                            <?php endif?>
                                        </td>
                                        <td class="table-cell-top">
                                            <?php if (isset($user['votingRights'])): ?>
                                                <p>
                                                    <?=$this->translate('Voting weight');?>: <?=$user['votingRights']['vt_weight']; ?><br />
                                                    <?=$this->translate('Group size');?>: <?=$grp_siz_def[$user['votingRights']['grp_siz']]; ?>
                                                </p>
                                                <?php if ($user['votingRights']['grp_siz'] != 1): ?>
                                                    <p>
                                                        <?=$this->translate('Partner');?>: <?=$user['name_pers']; ?><br/>
                                                        <?=$this->translate('Group name');?>: <?=$user['name_group']; ?><br/>
                                                        <?=$this->translate('Group size');?>: <?=$user['group_size']; ?>
                                                    </p>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                        </td>
                                        <td class="table-cell-actions table-cell-top">
                                            <?php if (!empty($user['email'])): ?>
                                                <a
                                                    href="<?=$this->url(['action' => 'sendinvitation', 'uid' => $user['uid'], 'mode' => 'preview']);?>"
                                                    class="item-action"
                                                    title="<?=$this->translate('Preview and send invitation');?>"
                                                    >
                                                    <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>
                                                </a>
                                                <button
                                                    value="<?=$user['uid'];?>"
                                                    name="instantSendUserId"
                                                    class="item-action"
                                                    data-toggle="confirm"
                                                    data-confirm-message="<?=$this->translate('Do you really want to send invitation to this user?');?>"
                                                    title="<?=$this->translate('Send invitation');?>"
                                                >
                                                    <span class="glyphicon glyphicon-send" aria-hidden="true"></span>
                                                </button>
                                            <?php endif; ?>
                                            <a
                                                href="<?=$this->url(['controller' => 'input', 'action' => 'list-by-user', 'uid' => $user['uid']]);?>"
                                                class="item-action"
                                                title="<?=$this->translate('Show all contributions by this user');?>"
                                                >
                                                <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                                            </a>
                                        </td>
                                    </tr>
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                    </form>
                <?php else: ?>
                    <p class="alert alert-info">
                        <span class="glyphicon glyphicon-info-sign"></span>
                        <?=$this->translate('There are no participants to be invited.');?>
                    </p>
                <?php endif; ?>

            </div>
        </div>
    </div>
</section>
