<?php
/**
 * Voting invitations
 */

$grp_siz_def = Zend_Registry::get('systemconfig')->group_size_def->toArray();
?>
<h1><?php echo $this->consultation['titl']; ?></h1>
<?php
echo $this->consultationNavigation('Votingeinladungen');
?>
<h2>Voting-Einladungen</h2>
<p>
    <a
        href="mailto:<?php echo Zend_Registry::get('projectConfig')->email->from->address; ?>?bcc=<?php echo $this->emailList; ?>"
    >
        &raquo; E-Mail an alle Teilnehmenden in externem Programm senden
    </a>
</p>

<?php foreach ($this->participants as $user): ?>
<div class="info">
  <p>
    <a href="<?php echo $this->url(array(
      'controller' => 'input',
      'action' => 'list',
      'uid' => $user['uid']
    )); ?>" title="Anklicken, um alle Beiträge dieses Users zu sehen">
    <?php if (!empty($user['name'])): ?>
    <?php echo $user['name'] . ' '; ?>
    <?php endif; ?>

    <?php if (!empty($user['email'])): ?>

      <?php echo $user['email'] . ' ' . $user['uid']; ?>
    </a>
  </p>
  <p>
    <a href="<?php echo $this->url(array(
      'action' => 'sendinvitation',
      'uid' => $user['uid'],
      'mode' => 'preview',
    )); ?>">Vorschau &amp; Senden</a>&emsp;<a href="<?php echo $this->url(array(
      'action' => 'sendinvitation',
      'uid' => $user['uid'],
      'mode' => 'instantsend',
    )); ?>">Direkt senden</a>
  </p>
  <?php if (isset($user['votingRights'])): ?>
  <p>Votinggewicht: <b><?php echo $user['votingRights']['vt_weight']; ?></b><br />
  Gruppengröße: <b><?php echo $grp_siz_def[$user['votingRights']['grp_siz']]; ?></b></p>
    <?php if ($user['votingRights']['grp_siz'] != 1): ?>
    <hr/>
    <p>
      Ansprechpartner: <b><?php echo $user['name_pers']; ?></b><br/>
      Gruppenname: <b><?php echo $user['name_group']; ?></b><br/>
      Gruppengröße: <b><?php echo $user['group_size']; ?></b>
    </p>
    <?php endif; ?>
  <?php endif; ?>

    <?php else: ?>

      Unbekannt <?php echo $user['uid']; ?>
    </a>
  </p>

    <?php endif; ?>
</div>
<?php endforeach; ?>
