<section class="section-header has-tabs">
    <div class="container">

        <h1><?=$this->escape($this->consultation['titl']);?></h1>
        <h2><?=$this->escape($this->consultation['titl_sub']);?></h2>

        <?=$this->consultationTabs($this->consultation['kid'], 'consultation');?>

    </div>
</section>
<section class="section-content">
    <div class="container">
        <div class="row">
            <div class="sidebar">

                <?=$this->consultationNavigation($this->consultation, 'voting-participants');?>

            </div>
            <div class="content">

                <a href="<?=$this->url(['action' => 'participants', 'uid' => null, 'sub_uid' => null]);?>" class="back"><?=$this->translate('Back to Voting Participants');?></a>
                <h2><?=$this->translate('Edit Voting Participant:');?> <?=$this->escape($this->user);?></h2>

                <p class="alert alert-warning">
                    <span class="glyphicon glyphicon-warning-sign" aria-hidden="true"></span>
                    <?=$this->translate('Please select a duplicate participant to be deleted. The data of selected participant will be transferred to currently edited participant. Eventually, the selected participant will be removed.');?>
                </p>

                <?=$this->form;?>

            </div>
        </div>
    </div>
</section>
