<section class="section-header">
    <div class="container">

        <h1 class="section-header-title"><?=$this->escape($this->consultation['titl']);?></h1>
        <h2 class="section-header-subtitle"><?=$this->escape($this->consultation['titl_sub']);?></h2>

        <?=$this->consultationTabs($this->consultation['kid'], 'consultation');?>

    </div>
</section>

<section class="section-content">
    <div class="container">
        <div class="row">
            <div class="sidebar offset-bottom-large-sm-max">

                <?=$this->consultationNavigation($this->consultation, 'voting-invitations');?>

            </div>
            <div class="content">

                <h2><?=$this->translate('Voting Invitations');?></h2>
                <?=$this->form;?>
                <?=$this->partial('_partials/mail-replacable-tokens.phtml', [
                    'placeholders' => $this->placeholders,
                    'components' => $this->components,
                ]);?>

            </div>
        </div>
    </div>
</section>
