<section class="section-header has-tabs">
    <div class="container">

        <h1><?=$this->consultation['titl'];?></h1>
        <h2><?=$this->consultation['titl_sub'];?></h2>

        <?=$this->consultationTabs($this->consultation['kid'], 'consultation');?>

    </div>
</section>
<section class="section-content">
    <div class="container">
        <div class="row">
            <div class="sidebar">

                <?=$this->consultationNavigation($this->consultation['kid'], 'voting-invitations');?>

            </div>
            <div class="content">

                <h2><?=$this->translate('Voting Invitations');?></h2>
                <?=$this->form;?>
                <p>
                    <?=$this->translate('or');?>
                    <a href="<?=$this->url(array('action' => 'invitations', 'uid' => null, 'mode' => null));?>">
                        <?=$this->translate('Cancel');?>
                    </a>
                </p>

            </div>
        </div>
    </div>
</section>
